DayzKode: P:/scripts/4_world/DayZ/plugins/pluginbase/plugindayzplayerdebug.c File Reference
plugindayzplayerdebug.c File Reference
Classes
class HumanCommandActionCallback
class PluginDayzPlayerDebugUserData
Functions
void Actions_DoCancel ()
void Actions_DoInternalCommand (int pCommandId)
void Actions_Start ()
void Actions_UpdateGlobals (DayZPlayer pPlayer)
void ActionsInit (int pType)
void CaptureFocus ()
void CommandHandler ()
void CreateModuleWidgets ()
void DbgShowBoneName (DayZPlayer pPlayer)
void DestroyModuleWidgets ()
int GetInt ()
int GetStanceMask ()
void Hide ()
bool IsActive ()
bool IsFullBody ()
bool IsWeaponChange (out string pNewWeapon, out int pHideSlot, out int pShowSlot)
override bool OnChange (Widget w, int x, int y, bool finished)
class PluginDayzPlayerDebugUserData OnClick (Widget w, int x, int y, int button)
buttons clicks
void PlayerSyncCreate ()
void PlayerSyncDelete ()
void PluginDayzPlayerDebug ()
void PluginDayzPlayerDebugUserData (int pUserData, bool pFullBody, int pStanceMask=-1)
void RegisterDebugItem (ItemBase item, PlayerBase player)
void ReleaseFocus ()
void Show ()
void ShowCard (int pCard)
void ShowWidgets (bool show)
void Tick ()
void ToggleDebugWindowEvent ()
void ToggleDebugWindowEventOld ()
void ToggleDebugWindowEventP ()
void ToggleDebugWindowSetMode (int pMode)
void UpdateCommandModifiers (DayZPlayer pPlayer)
void UpdateItemAccessor (DayZPlayer pPlayer)
void UpdatePlayerStatus (DayZPlayer pPlayer)
void ~PluginDayzPlayerDebug ()
Variables
TextWidget m_ActionEventV
ButtonWidget m_ActionsCancel
ButtonWidget m_ActionsEnd
ButtonWidget m_ActionsFinish
TextWidget m_ActionsGlobalStatus
ButtonWidget m_ActionsOTA
ButtonWidget m_ActionsOTL
TextListboxWidget m_ActionsSelector
ButtonWidget m_ActionsStart
TextWidget m_ActionStateV
ButtonWidget m_ActionTypeFLA
ButtonWidget m_ActionTypeFLG
ButtonWidget m_ActionTypeFOA
ButtonWidget m_ActionTypeFOG
ButtonWidget m_ActionTypeLA
ButtonWidget m_ActionTypeLG
ButtonWidget m_ActionTypeOA
ButtonWidget m_ActionTypeOG
protected bool m_bIsFullBody
Widget m_Card0
ButtonWidget m_Card0Button
Widget m_Card1
ButtonWidget m_Card1Button
Widget m_Card2
ButtonWidget m_Card2Button
Widget m_Card3
ButtonWidget m_Card3Button
bool m_CH_ActionCancel = false
int m_CH_ActionCommand = -1000
bool m_CH_ActionStart = false
ref PluginDayzPlayerDebug_Ctrl m_Controls
int m_CurrentMode = 0
bool m_HasFocus = false
bool m_HasServerWalk = false
bool m_IsActive = false
protected int m_iStanceMask
TextWidget m_ItemAccClass
TextWidget m_ItemAccInst
TextWidget m_ItemAccSClass
protected int m_iUserData
Widget m_MainWnd
ref PluginDayzPlayerDebug_OtherCmds m_OtherCmds
ButtonWidget m_PlayerServerWalk
EditBoxWidget m_PlayerStatusV
ButtonWidget m_PlayerSyncCreateShadow
ButtonWidget m_PlayerSyncDelete
Entity m_pPlayerShadow
PluginDayzPlayerDebug m_pPluginPlayerDebug
ref PluginDayzPlayerDebugUIHandler m_pUIHandler
class PluginDayzPlayerActionCallback extends HumanCommandActionCallback m_TickTimer
ref PluginDayzPlayerDebug_Weapons m_Weapons
Function Documentation
Actions_DoCancel()
void Actions_DoCancel ()
Definition at line 933 of file plugindayzplayerdebug.c.
    {
        DayZPlayer player = DayZPlayer.Cast( GetGame().GetPlayer() );
        if (!player)
        {
            return;
        }
        HumanCommandActionCallback clbk = player.GetCommand_Action();
        if (!clbk)
        {
            clbk = player.GetCommandModifier_Action();
            if (!clbk)
            {
                return;
            }
        }
        clbk.Cancel();
    }
References GetGame(), and GetPlayer().
Referenced by CommandHandler().
Actions_DoInternalCommand()
void Actions_DoInternalCommand (int pCommandId)
Definition at line 910 of file plugindayzplayerdebug.c.
    {
        DayZPlayer player = DayZPlayer.Cast( GetGame().GetPlayer() );
        if (!player)
        {
            return;
        }
        HumanCommandActionCallback clbk = player.GetCommand_Action();
        if (!clbk)
        {
            clbk = player.GetCommandModifier_Action();
            if (!clbk)
            {
                return;
            }
        }
        clbk.InternalCommand(pCommandId);
    }
References GetGame(), and GetPlayer().
Referenced by CommandHandler().
Actions_Start()
void Actions_Start ()
start action
Definition at line 872 of file plugindayzplayerdebug.c.
    {
        int     row = m_ActionsSelector.GetSelectedRow();
        if (row == -1)
        {
            return;
        }
        DayZPlayer player = DayZPlayer.Cast( GetGame().GetPlayer() );
        if (!player)
        {
            return;
        }
        PluginDayzPlayerDebugUserData   userData;
        m_ActionsSelector.GetItemData(row, 0, userData);
        PluginDayzPlayerActionCallback a;
        if (userData.IsFullBody())
        {
            a = PluginDayzPlayerActionCallback.Cast( player.StartCommand_Action(userData.GetInt(), PluginDayzPlayerActionCallback, userData.GetStanceMask()) );
        }
        else
        {
            a = PluginDayzPlayerActionCallback.Cast( player.AddCommandModifier_Action(userData.GetInt(), PluginDayzPlayerActionCallback) );
        }
        a.m_pStateWidget        = m_ActionStateV;
        a.m_pAnimEventWidget    = m_ActionEventV;
        Print(m_ActionStateV);
        m_ActionStateV.SetText("Crash Test");
    }
References GetGame(), PluginDayzPlayerDebugUserData::GetInt(), GetPlayer(), PluginDayzPlayerDebugUserData::GetStanceMask(), PluginDayzPlayerDebugUserData::IsFullBody(), m_ActionEventV, m_ActionsSelector, m_ActionStateV, and Print().
Referenced by CommandHandler().
Actions_UpdateGlobals()
void Actions_UpdateGlobals (DayZPlayer pPlayer)
Definition at line 956 of file plugindayzplayerdebug.c.
    {
        HumanCommandActionCallback clbk = pPlayer.GetCommandModifier_Action();
        if (!clbk)
        {
            m_ActionsGlobalStatus.SetText("No Action");
        }
        m_ActionsGlobalStatus.SetText(clbk.ToString());
    }
References m_ActionsGlobalStatus.
Referenced by UpdateCommandModifiers().
ActionsInit()
void ActionsInit (int pType)
------------------- ACTIONS -----------------------
looping
one time
fullbody looping
one time
------------------- GESTURES ----------------------
looping
one time
fullbody looping
fullbody one time
------------------- SUICIDE -----------------------
fullbody looping
Definition at line 572 of file plugindayzplayerdebug.c.
    {
        m_ActionsSelector.ClearItems();
        if (pType == 0)
        {
            m_ActionsSelector.AddItem("L DRINK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_DRINK, false), 0);
            m_ActionsSelector.AddItem("L EAT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_EAT, false), 0);
            m_ActionsSelector.AddItem("L EMPTY VESSEL", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_EMPTY_VESSEL, false), 0);
            m_ActionsSelector.AddItem("L CATCH RAIN", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_CATCHRAIN, false), 0);
            m_ActionsSelector.AddItem("L VIEW COMPASS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_VIEWCOMPASS, false), 0);
            m_ActionsSelector.AddItem("L ITEM TUNE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_ITEM_TUNE, false), 0);
            m_ActionsSelector.AddItem("L GIVE L ITEM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_GIVEL, false), 0);
            m_ActionsSelector.AddItem("L GIVE R ITEM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_GIVER, false), 0);
            m_ActionsSelector.AddItem("L SHAVE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_SHAVE, false), 0);
            m_ActionsSelector.AddItem("L FILL MAG", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_FILLMAG, false), 0);
            m_ActionsSelector.AddItem("L EMPTY MAG", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_EMPTYMAG, false), 0);
            m_ActionsSelector.AddItem("L OPEN ITEM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_OPENITEM, false), 0);
            m_ActionsSelector.AddItem("L TAKE TEMP SELF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_TAKETEMPSELF, false), 0);
            m_ActionsSelector.AddItem("L VIEW MAP", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_VIEWMAP, false), 0);
            m_ActionsSelector.AddItem("L RAISE ITEM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_RAISEITEM, false), 0);
            m_ActionsSelector.AddItem("L SEARCH INVENTORY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_SEARCHINVENTORY, false), 0);
            m_ActionsSelector.AddItem("L CRAFTING UPPDERBODY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_CRAFTING, false), 0);
            m_ActionsSelector.AddItem("L RESTRAINED STRUGGLE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_RESTRAINEDSTRUGGLE, false), 0);
            m_ActionsSelector.AddItem("L COVER HEAD SELF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_SELF, false), 0);
            m_ActionsSelector.AddItem("L COVER HEAD TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_TARGET, false), 0);
            m_ActionsSelector.AddItem("L SET ALARM CLOCK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_SET_ALARM, false), 0);
            m_ActionsSelector.AddItem("L ENGINE START", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_STARTENGINE, false), 0);
            m_ActionsSelector.AddItem("L TOOT HORN", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_TOOTHORN, false), 0);
            m_ActionsSelector.AddItem("O ENGINE STOP", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_STOPENGINE, false), 0);
            m_ActionsSelector.AddItem("O SHIFT GEAR", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_SHIFTGEAR, false), 0);
            m_ActionsSelector.AddItem("O TURN ON/OFF LIGHTS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_HEADLIGHT, false), 0);
            m_ActionsSelector.AddItem("O DRIVER OPEN DOOR", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_DRIVER_DOOR_OPEN, false), 0);
            m_ActionsSelector.AddItem("O DRIVER CLOSE DOOR", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_DRIVER_DOOR_CLOSE, false), 0);
            m_ActionsSelector.AddItem("O CODRIVER OPEN DOOR", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_CODRIVER_DOOROPEN, false), 0);
            m_ActionsSelector.AddItem("O CODRIVER CLOSE DOOR", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_CODRIVER_DOORCLOSE, false), 0);
        }
        if (pType == 1)
        {
            m_ActionsSelector.AddItem("O PICK UP HANDS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS, false), 0);
            m_ActionsSelector.AddItem("O PICK UP INVENTORY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_INVENTORY, false), 0);
            m_ActionsSelector.AddItem("O LICK BATTERY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_LICKBATTERY, false), 0);
            m_ActionsSelector.AddItem("O LIGHT FLARE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_LIGHTFLARE, false), 0);
            m_ActionsSelector.AddItem("O LITCHEM LIGHT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_LITCHEMLIGHT, false), 0);
            m_ActionsSelector.AddItem("O UNPIN GRENAGE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_UNPINGRENAGE, false), 0);
            m_ActionsSelector.AddItem("O OPEN DOOR FW", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW, false), 0);
            m_ActionsSelector.AddItem("O OPEN LID", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_OPENLID, false), 0);
            m_ActionsSelector.AddItem("O CLOSE LID", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_CLOSELID, false), 0);
            m_ActionsSelector.AddItem("O RADIO ON", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_ITEM_ON, false), 0);
            m_ActionsSelector.AddItem("O RADIO OFF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_ITEM_OFF, false), 0);
            m_ActionsSelector.AddItem("O BATON EXTEND", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_BATONEXTEND, false), 0);
            m_ActionsSelector.AddItem("O BATON RETRACT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_BATONRETRACT, false), 0);
            m_ActionsSelector.AddItem("O UNLOCK HANDCUFF TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_UNLOCKHANDCUFFTARGET, false), 0);
            m_ActionsSelector.AddItem("O FISHINGROD EXTEND", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_FISHINGRODEXTEND, false), 0);
            m_ActionsSelector.AddItem("O FISHINGROD RETRACT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_FISHINGRODRETRACT, false), 0);
            m_ActionsSelector.AddItem("O CLEAN HANDS BOTTLE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_CLEANHANDSBOTTLE, false), 0);
            m_ActionsSelector.AddItem("O OPEN ITEM ONCE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_OPENITEM_ONCE, false), 0);
            m_ActionsSelector.AddItem("O CLOSE ITEM ONCE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_CLOSEITEM_ONCE, false), 0);
            m_ActionsSelector.AddItem("O ATTACH SCOPE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_ATTACHSCOPE, false), 0);
            m_ActionsSelector.AddItem("O ATTACH BARREL", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_ATTACHBARREL, false), 0);
            m_ActionsSelector.AddItem("O EMPTY SEEDS PACK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_EMPTYSEEDSPACK, false), 0);
            m_ActionsSelector.AddItem("O INTERACT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_INTERACTONCE, false), 0);
            m_ActionsSelector.AddItem("O ATTACH ITEM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_ATTACHITEM, false), 0);
            m_ActionsSelector.AddItem("O STOP ALARM CLOCK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_STOP_ALARM, false), 0);
            m_ActionsSelector.AddItem("O PRESS TRIGGER", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_PRESS_TRIGGER, false), 0);
            m_ActionsSelector.AddItem("O DROP ITEM HANDS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_DROPITEM_HANDS, false), 0);
            m_ActionsSelector.AddItem("O DROP ITEM INVENTORY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONMOD_DROPITEM_INVENTORY, false), 0);
        }
        if (pType == 2)
        {
            m_ActionsSelector.AddItem("FB L DRINK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DRINK, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L EAT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_EAT, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L CATCH RAIN", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_CATCHRAIN, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L WALKIETALKIE TUNE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_ITEM_TUNE, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L GIVE L ITEM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_GIVEL, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L GIVE R ITEM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_GIVER, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L FILL MAG", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_FILLMAG, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L EMPTY MAG", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_EMPTYMAG, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L DRINK POND", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DRINKPOND, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L DRINK WELL", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DRINKWELL, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L FILL BOTTLE WELL", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_FILLBOTTLEWELL, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L FIRE ESTINGUISHER", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_FIREESTINGUISHER, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L FLAME REPAIR", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_FLAME_REPAIR, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L WRING CLOTH", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_WRING, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L FISHING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_FISHING, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L CPR", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_CPR, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L BANDAGE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_BANDAGE, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L CRAFTING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_CRAFTING, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L INTERACT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_INTERACT, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L FORCE FEED TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_FORCEFEED, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L BANDAGE TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_BANDAGETARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L SPRAY PLANT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_SPRAYPLANT, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L START FIRE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_STARTFIRE, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L ANIMAL SKINNING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_ANIMALSKINNING, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L WASH HANDS WELL", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_WASHHANDSWELL, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L WASH HANDS POND", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_WASHHANDSPOND, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L SALINE BLOODBAG TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_SALINEBLOODBAGTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L SALINE BLOOD BAG", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_SALINEBLOODBAG, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L STITCH UP SELF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_STITCHUPSELF, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L VOMIT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_VOMIT, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L UNRESTRAINT TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_UNRESTRAINTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L RESTRAIN TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_RESTRAINTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L CHECK PULSE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_CHECKPULSE, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L CLEAN WOUNDS TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_CLEANWOUNDSTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L COLLECT BLOOD SELF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_COLLECTBLOODSELF, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L EMPTY VESSEL", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_EMPTY_VESSEL, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L OPEN ITEM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_OPENITEM, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L HACK BUSH", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_HACKBUSH, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L HACK TREE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_HACKTREE, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L TAKE TEMP SELF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_TAKETEMPSELF, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L DIG HOLE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DIG, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L DIG UP CACHE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DIGUPCACHE, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L DIG MANIPULATE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DIGMANIPULATE, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L DEPLOY HEAVY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_HEAVY, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L DEPLOY 1HD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_1HD, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L DEPLOY 2HD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_2HD, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L BLOW FIREPLACE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_BLOWFIREPLACE, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L VIEW MAP", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_VIEWMAP, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L VIEW COMPASS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_VIEWCOMPASS, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L FILL BOTTLE POND", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_FILLBOTTLEPOND, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L PLACING HEAVY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_PLACING_HEAVY, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L PLACING 1HD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_PLACING_1HD, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L PLACING 2HD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_PLACING_2HD, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L CUT BARK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_CUTBARK, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L VIEW NOTE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_VIEWNOTE, true, DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L SEARCH INVENTORY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_SEARCHINVENTORY, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L LOOK OPTICS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_LOOKOPTICS, true, DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L MINE ROCK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_MINEROCK, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L RAISE ITEM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_RAISEITEM, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L RESTRAINED STRUGGLE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_RESTRAINEDSTRUGGLE, true, DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L RESTRAIN SELF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_RESTRAINSELF, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L ASSEMBLE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_ASSEMBLE, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L DISASSEMBLE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DISASSEMBLE, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L RAISE FLAG", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_RAISE_FLAG, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L LOWER FLAG", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_LOWER_FLAG, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L SET ALARM CLOCK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_SET_ALARM, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
        }
        if (pType == 3)
        {
            m_ActionsSelector.AddItem("FB O PICK UP HANDS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O PICK UP INVENTORY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_INVENTORY, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O LICK BATTERY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_LICKBATTERY, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O LIGHT FLARE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_LIGHTFLARE, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O LITCHEM LIGHT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_LITCHEMLIGHT, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O UNPIN GRENAGE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_UNPINGRENAGE, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O RADIO ON", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_ITEM_ON, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O RADIO OFF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_ITEM_OFF, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O HANDCUFF TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_HANDCUFFTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB O MORPHINE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_MORPHINE, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB O INJECTION", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_INJECTION, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB O INJECTION TARGET", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_INJECTIONTARGET, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB O DRINK SIP", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_DRINKSIP, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB O CLEAN HANDS BOTTLE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_CLEANHANDSBOTTLE, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O OPEN ITEM ONCE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_OPENITEM_ONCE, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O POKE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_POKE, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB O ATTACH SCOPE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_ATTACHSCOPE, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O ATTACH BARREL", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_ATTACHBARREL, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O RESTRAIN", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_RESTRAIN, true, DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB O PICK UP HEAVY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HEAVY, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB O STOP ALARM CLOCK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_STOP_ALARM, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O PRESS TRIGGER", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_ACTIONFB_PRESS_TRIGGER, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
        }
        if (pType == 4)
        {
            m_ActionsSelector.AddItem("L GREETING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_GREETING, false), 0);
            m_ActionsSelector.AddItem("L POINT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_POINT, false), 0);
            m_ActionsSelector.AddItem("L THUMB UP", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_THUMB, false), 0);
            m_ActionsSelector.AddItem("L THUMB DOWN", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_THUMB, false), 0);
            m_ActionsSelector.AddItem("L SILENCE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_SILENCE, false), 0);
            m_ActionsSelector.AddItem("L TAUNT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_TAUNT, false), 0);
            m_ActionsSelector.AddItem("L TIME OUT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_TIMEOUT, false), 0);
            m_ActionsSelector.AddItem("L HEART", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_HEART, false), 0);
            m_ActionsSelector.AddItem("L FACEPALM", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_FACEPALM, false), 0);
            m_ActionsSelector.AddItem("L WATCHING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_WATCHING, false), 0);
            m_ActionsSelector.AddItem("L HOLD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_HOLD, false), 0);
            m_ActionsSelector.AddItem("L LISTENING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_LISTENING, false), 0);
            m_ActionsSelector.AddItem("L POINT AT SELF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_POINTSELF, false), 0);
            m_ActionsSelector.AddItem("L LOOK AT ME", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_LOOKATME, false), 0);
            m_ActionsSelector.AddItem("L OKAY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_OKAY, false), 0);
            m_ActionsSelector.AddItem("L RPS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_RPS, false), 0);
        }
        if (pType == 5)
        {
            m_ActionsSelector.AddItem("O THROAT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_THROAT, false), 0);
            m_ActionsSelector.AddItem("O CLAP", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_CLAP, false), 0);
            m_ActionsSelector.AddItem("O DABBING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_DABBING, false), 0);
            m_ActionsSelector.AddItem("O MOVE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_MOVE, false), 0);
            m_ActionsSelector.AddItem("O DOWN", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_DOWN, false), 0);
            m_ActionsSelector.AddItem("O COME", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_COME, false), 0);
            m_ActionsSelector.AddItem("O TAUNT KISS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_TAUNTKISS, false), 0);
            m_ActionsSelector.AddItem("O TAUNT ELBOW", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_TAUNTELBOW, false), 0);
            m_ActionsSelector.AddItem("O TAUNT THINK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_TAUNTTHINK, false), 0);
            m_ActionsSelector.AddItem("O NOD HEAD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_NODHEAD, false), 0);
            m_ActionsSelector.AddItem("O SHAKE HEAD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_SHAKEHEAD, false), 0);
            m_ActionsSelector.AddItem("O SHRUG", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_SHRUG, false), 0);
            m_ActionsSelector.AddItem("O SURRENDER", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREMOD_SURRENDER, false), 0);
        }
        if (pType == 6)
        {
            m_ActionsSelector.AddItem("FB L GREETING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_GREETING, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L POINT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_POINT, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L THUMBUP", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_THUMB, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L THUMBDOWN", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_THUMB, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L SILENCE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_SILENCE, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L TAUNT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_TAUNT, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L TIMEOUT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_TIMEOUT, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L HEART", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_HEART, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L WATCHING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_WATCHING, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L HOLD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_HOLD, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L LISTENING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_LISTENING, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L POINTSELF", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_POINTSELF, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L LOOKATME", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_LOOKATME, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L OKAY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_OKAY, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L SALUTE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_SALUTE, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L CAMPFIRE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_CAMPFIRE, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L LYINGDOWN", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_LYINGDOWN, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L SOS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_SOS, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L SITA", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_SITA, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L SITB", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_SITB, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L DABBING", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_DABBING, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L SURRENDER", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_SURRENDER, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB L KNEEL", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_KNEEL, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("TRAILER WAKE UP", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_TRAILER_WAKE_UP, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("TRAILER DEAD BODY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_TRAILER_DEAD_BODY, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("TRAILER WALKIE TALKIE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_TRAILER_WALKIE_TALKIE, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("TRAILER WOUNDED", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_TRAILER_WOUNDED, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("TRAILER WALK AWAY", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_TRAILER_WALK_AWAY, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("TRAILER DEAD DEAD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_TRAILER_DEAD, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
        }
        if (pType == 7)
        {
            m_ActionsSelector.AddItem("FB O THROAT", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_THROAT, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O MOVE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_MOVE, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O DOWN", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_DOWN, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O COME", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_COME, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O TAUNT KISS", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_TAUNTKISS, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O TAUNT THINK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_TAUNTTHINK, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O DANCE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_DANCE, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB O NOD HEAD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_NODHEAD, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O SHAKE HEAD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_SHAKEHEAD, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O SHRUG", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_SHRUG, true, DayZPlayerConstants.STANCEMASK_PRONE), 0);
            m_ActionsSelector.AddItem("FB O SURRENDER", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_GESTUREFB_SURRENDER, true, DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE), 0);
        }
        if (pType == 6)
        {
            m_ActionsSelector.AddItem("FB L 1HD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_1HD, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L FIREAXE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_FIREAXE, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L PITCHFORK", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_PITCHFORK, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L PISTOL", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_PISTOL, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L RIFLE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_RIFLE, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L SWORD", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_SWORD, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L UNARMED", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_UNARMED, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L WOODAXE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_WOODAXE, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L SPEAR", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_SPEAR, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
            m_ActionsSelector.AddItem("FB L SICKLE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_SICKLE, true, DayZPlayerConstants.STANCEMASK_CROUCH), 0);
            m_ActionsSelector.AddItem("FB L HOE", new PluginDayzPlayerDebugUserData(DayZPlayerConstants.CMD_SUICIDEFB_HOE, true, DayZPlayerConstants.STANCEMASK_ERECT), 0);
        }
    }
References m_ActionsSelector.
Referenced by CreateModuleWidgets().
CaptureFocus()
void CaptureFocus ()
Definition at line 255 of file plugindayzplayerdebug.c.
    {
        if (!m_HasFocus)
        {
            GetGame().GetInput().ChangeGameFocus(1);
            GetGame().GetUIManager().ShowUICursor(true);
            m_HasFocus = true;
        }
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), m_HasFocus, and UIManager::ShowUICursor().
CommandHandler()
void CommandHandler ()
Definition at line 1160 of file plugindayzplayerdebug.c.
    {
        if (m_CH_ActionStart)
        {
            Actions_Start();
            m_CH_ActionStart    = false;
        }
        if (m_CH_ActionCommand != -1000)
        {
            Actions_DoInternalCommand(m_CH_ActionCommand);
            m_CH_ActionCommand = -1000;
        }
        if (m_CH_ActionCancel)
        {
            Actions_DoCancel();
            m_CH_ActionCancel = false;
        }
        if (m_Weapons)
        {
            m_Weapons.CommandHandler();
        }
        if (m_Controls)
        {
            m_Controls.CommandHandler();
        }
        if (m_OtherCmds)
        {
            m_OtherCmds.CommandHandler();
        }
    }
References Actions_DoCancel(), Actions_DoInternalCommand(), Actions_Start(), PluginDayzPlayerDebug_Ctrl::CommandHandler(), PluginDayzPlayerDebug_OtherCmds::CommandHandler(), PluginDayzPlayerDebug_Weapons::CommandHandler(), m_CH_ActionCancel, m_CH_ActionCommand, m_CH_ActionStart, m_Controls, m_OtherCmds, and m_Weapons.
CreateModuleWidgets()
void CreateModuleWidgets ()
Definition at line 340 of file plugindayzplayerdebug.c.
    {
        if (!m_pUIHandler)
        {
            m_pUIHandler = new PluginDayzPlayerDebugUIHandler();
            m_pUIHandler.m_pPluginPlayerDebug = this;
        }
        if (!m_MainWnd)
        {
            m_MainWnd = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_playerdebug.layout");
            m_MainWnd.SetHandler(m_pUIHandler);
            m_MainWnd.Show(false);
        }
        m_Card0 = m_MainWnd.FindAnyWidget("Card0");
        m_Card1 = m_MainWnd.FindAnyWidget("Card1");
        m_Card2 = m_MainWnd.FindAnyWidget("Card2");
        m_Card3 = m_MainWnd.FindAnyWidget("Card3");
        m_Card0Button   = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("Card0Button") );
        m_Card1Button   = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("Card1Button") );
        m_Card2Button   = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("Card2Button") );
        m_Card3Button   = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("Card3Button") );
        m_PlayerStatusV     = EditBoxWidget.Cast( m_MainWnd.FindAnyWidget("PlayerStatusV") );
        m_ActionsSelector   = TextListboxWidget.Cast( m_MainWnd.FindAnyWidget("ActionsSelector") );
        m_ActionsStart      = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsStart") );
        m_ActionsEnd        = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsEnd") );
        m_ActionsFinish     = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsFinish") );
        m_ActionsCancel     = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsCancel") );
        m_ActionsOTA            = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsOTA") );
        m_ActionsOTL            = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsOTL") );
        m_ActionStateV      = TextWidget.Cast( m_MainWnd.FindAnyWidget("ActionStateV") );
        m_ActionEventV      = TextWidget.Cast( m_MainWnd.FindAnyWidget("ActionEventV") );
        m_ActionsGlobalStatus   = TextWidget.Cast( m_MainWnd.FindAnyWidget("ActionGlobalStatus") );
        m_PlayerSyncCreateShadow    = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("PlayerSyncCreate") );
        m_PlayerSyncDelete          = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("PlayerSyncDelete") );
        m_PlayerServerWalk          = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("PlayerServerWalk") );
        m_ItemAccClass          = TextWidget.Cast( m_MainWnd.FindAnyWidget("ItemAccessClass") );
        m_ItemAccSClass         = TextWidget.Cast( m_MainWnd.FindAnyWidget("ItemAccessSClass") );
        m_ItemAccInst               = TextWidget.Cast( m_MainWnd.FindAnyWidget("ItemAccessInst") );
        m_ActionTypeLA          = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsGroupLA") );
        m_ActionTypeOA          = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsGroupOA") );
        m_ActionTypeFLA         = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsGroupFLA") );
        m_ActionTypeFOA         = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsGroupFOA") );
        m_ActionTypeLG          = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsGroupLG") );
        m_ActionTypeOG          = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsGroupOG") );
        m_ActionTypeFLG         = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsGroupFLG") );
        m_ActionTypeFOG         = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("ActionsGroupFOG") );
        ActionsInit(0);
        ShowCard(0);
        // m_DebugAgentListWidget = m_DebugRootWidget.FindAnyWidget("w_Agents");
        // m_DebugFloatsListWidget = m_DebugRootWidget.FindAnyWidget("w_Floats");
        // m_DebugStringsListWidget = m_DebugRootWidget.FindAnyWidget("w_Strings");
        // m_DebugFloatsProperListWidget = m_DebugRootWidget.FindAnyWidget("w_FloatsProper");
        // m_ItemPreviewWidget = m_DebugRootWidget.FindAnyWidget("w_ItemPreview");
        // m_ClassNameWidget = m_DebugRootWidget.FindAnyWidget("w_ClassName");
    }
References ActionsInit(), WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_ActionEventV, m_ActionsCancel, m_ActionsEnd, m_ActionsFinish, m_ActionsGlobalStatus, m_ActionsOTA, m_ActionsOTL, m_ActionsSelector, m_ActionsStart, m_ActionStateV, m_ActionTypeFLA, m_ActionTypeFLG, m_ActionTypeFOA, m_ActionTypeFOG, m_ActionTypeLA, m_ActionTypeLG, m_ActionTypeOA, m_ActionTypeOG, m_Card0, m_Card0Button, m_Card1, m_Card1Button, m_Card2, m_Card2Button, m_Card3, m_Card3Button, m_ItemAccClass, m_ItemAccInst, m_ItemAccSClass, m_MainWnd, m_PlayerServerWalk, m_PlayerStatusV, m_PlayerSyncCreateShadow, m_PlayerSyncDelete, m_pUIHandler, and PluginBase::ShowCard().
DbgShowBoneName()
void DbgShowBoneName (DayZPlayer pPlayer)
Definition at line 520 of file plugindayzplayerdebug.c.
    {
        int     boneIndex = pPlayer.GetBoneIndexByName("Head");
        // vector   pos         = pPlayer.GetBonePositionMS(boneIndex);
        vector  tm[4];
        pPlayer.GetBoneTransformMS(boneIndex, tm);
        string a = "Bone index:";
        a += boneIndex.ToString();
        a += ",";
        a += tm.ToString();
        Print(a);
    }
References Print(), vector::ToString(), and string::ToString().
DestroyModuleWidgets()
void DestroyModuleWidgets ()
Definition at line 406 of file plugindayzplayerdebug.c.
    {
        delete m_MainWnd;
    }
References PluginBase::m_MainWnd.
GetInt()
int OnClick::GetInt ()
Definition at line 48 of file plugindayzplayerdebug.c.
{
Referenced by PluginConfigHandler::GetBatchSpawnQuantity(), PluginConfigHandler::GetConfigClassesFlag(), PluginConfigHandler::GetEmoteFromSlot(), PluginConfigHandler::GetEmoteSlot1(), PluginConfigHandler::GetEmoteSlot10(), PluginConfigHandler::GetEmoteSlot11(), PluginConfigHandler::GetEmoteSlot2(), PluginConfigHandler::GetEmoteSlot3(), PluginConfigHandler::GetEmoteSlot4(), PluginConfigHandler::GetEmoteSlot5(), PluginConfigHandler::GetEmoteSlot6(), PluginConfigHandler::GetEmoteSlot7(), PluginConfigHandler::GetEmoteSlot8(), PluginConfigHandler::GetEmoteSlot9(), PluginConfigHandler::GetItemCategoryFlag(), PluginConfigHandler::GetSceneEditorRotationAngle(), and PluginConfigHandler::GetTabSelected().
GetStanceMask()
int OnClick::GetStanceMask ()
Definition at line 58 of file plugindayzplayerdebug.c.
{
    void    PluginDayzPlayerActionCallback()
Referenced by Can(), AnimatedActionBase::CreateAndSetupActionCallback(), OnFinish(), and SetupAction().
Hide()
void Hide ()
Definition at line 246 of file plugindayzplayerdebug.c.
    {
        ShowWidgets(false);
        m_IsActive = false;
        m_TickTimer = NULL;
    }
References m_IsActive, m_TickTimer, and PluginBase::ShowWidgets().
IsActive()
bool IsActive ()
Definition at line 219 of file plugindayzplayerdebug.c.
    {
        return m_IsActive;
    }
References PluginBase::m_IsActive.
IsFullBody()
bool OnClick::IsFullBody ()
Definition at line 53 of file plugindayzplayerdebug.c.
{
Referenced by Can(), AnimatedActionBase::CreateAndSetupActionCallback(), and ManBase::HeadingModel().
IsWeaponChange()
bool IsWeaponChange (out string pNewWeapon, out int pHideSlot, out int pShowSlot)
Definition at line 1146 of file plugindayzplayerdebug.c.
    {
        if (m_Weapons)
        {
            m_Weapons.IsWeaponChange(pNewWeapon, pHideSlot, pShowSlot);
        }
        return false;
    }
References PluginDayzPlayerDebug_Weapons::IsWeaponChange(), and m_Weapons.
OnChange()
override bool OnChange (Widget w, int x, int y, bool finished)
Definition at line 45 of file plugindayzplayerdebug.c.
    {
        super.OnChange(w, x, y, finished);
        return m_pPluginPlayerDebug.OnChange(w, x, y, finished);
    }
References x, and y.
OnClick()
class PluginDayzPlayerDebugUserData OnClick (Widget w, int x, int y, int button)
buttons clicks
send rcp
Definition at line 1 of file plugindayzplayerdebug.c.
    {
        super.OnClick(w, x, y, button);
        return m_pPluginPlayerDebug.OnClick(w, x, y, button);
    }
PlayerSyncCreate()
void PlayerSyncCreate ()
Definition at line 971 of file plugindayzplayerdebug.c.
    {
        PlayerSyncDelete();
        vector item_position =  GetGame().GetPlayer().GetPosition() + ( GetGame().GetPlayer().GetDirection() * 2.0);
        m_pPlayerShadow = Entity.Cast( GetGame().CreateObject("SurvivorM_Mirek", item_position, false, false) );
        DayZPlayer  pl = DayZPlayer.Cast( GetGame().GetPlayer() );
        pl.DebugSyncShadowSetup( DayZPlayer.Cast( m_pPlayerShadow ) );
    }
References CGame::CreateObject(), GetGame(), CGame::GetPlayer(), m_pPlayerShadow, and PlayerSyncDelete().
PlayerSyncDelete()
void PlayerSyncDelete ()
Definition at line 983 of file plugindayzplayerdebug.c.
    {
        if (m_pPlayerShadow)
        {
            GetGame().ObjectDelete(m_pPlayerShadow);
            m_pPlayerShadow = NULL;
        }
        DayZPlayer  pl = DayZPlayer.Cast( GetGame().GetPlayer() );
        if (pl)
        {
            pl.DebugSyncShadowSetup(NULL);
        }
    }
References GetGame(), GetPlayer(), m_pPlayerShadow, and CGame::ObjectDelete().
Referenced by PlayerSyncCreate(), and ~PluginDayzPlayerDebug().
PluginDayzPlayerDebug()
void PluginDayzPlayerDebug ()
Definition at line 189 of file plugindayzplayerdebug.c.
    {
        #ifndef NO_GUI
        CreateModuleWidgets();
        m_Weapons   = new PluginDayzPlayerDebug_Weapons(m_Card1);
        m_Controls  = new PluginDayzPlayerDebug_Ctrl(m_Card2);
        m_OtherCmds = new PluginDayzPlayerDebug_OtherCmds(m_Card3);
        #endif
    }
References PluginBase::CreateModuleWidgets(), m_Card1, m_Card2, m_Card3, m_Controls, m_OtherCmds, and m_Weapons.
Referenced by CommandHandlerDebug().
PluginDayzPlayerDebugUserData()
void OnClick::PluginDayzPlayerDebugUserData (int pUserData, bool pFullBody, int pStanceMask = -1)
Definition at line 40 of file plugindayzplayerdebug.c.
    {
        super.OnClick(w, x, y, button);
        return m_pPluginPlayerDebug.OnClick(w, x, y, button);
    }
    override bool OnChange(Widget w, int x, int y, bool finished)
References m_pPluginPlayerDebug, x, and y.
RegisterDebugItem()
void RegisterDebugItem (ItemBase item, PlayerBase player)
Definition at line 214 of file plugindayzplayerdebug.c.
    {
    }
ReleaseFocus()
void ReleaseFocus ()
Definition at line 266 of file plugindayzplayerdebug.c.
    {
        if (m_HasFocus)
        {
            GetGame().GetInput().ChangeGameFocus(-1);
            GetGame().GetUIManager().ShowUICursor(false);
            m_HasFocus = false;
        }
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), m_HasFocus, and UIManager::ShowUICursor().
Show()
void Show ()
Definition at line 233 of file plugindayzplayerdebug.c.
    {
        ShowWidgets(true);
        m_IsActive = true;
        if (!m_TickTimer)
        {
            m_TickTimer = new Timer();
            m_TickTimer.Run(0.1, this, "Tick", NULL, true);
        }
    }
References m_IsActive, m_TickTimer, and PluginBase::ShowWidgets().
ShowCard()
void ShowCard (int pCard)
Definition at line 412 of file plugindayzplayerdebug.c.
    {
        m_Card0.Show(pCard == 0);
        m_Card1.Show(pCard == 1);
        m_Card2.Show(pCard == 2);
        m_Card3.Show(pCard == 3);
    }
References m_Card0, m_Card1, m_Card2, and m_Card3.
ShowWidgets()
void ShowWidgets (bool show)
Definition at line 224 of file plugindayzplayerdebug.c.
    {
        if(m_MainWnd)
        {
            m_MainWnd.Show(show);
        }
    }
References m_MainWnd.
Referenced by OnRPC(), PluginItemDiagnostic(), and ToggleDebugWindowEvent().
Tick()
void Tick ()
Definition at line 426 of file plugindayzplayerdebug.c.
    {
        DayZPlayer player = DayZPlayer.Cast( GetGame().GetPlayer() );
        if (!player)
        {
            return;
        }
        // Print("PluginDayzPlayerDebug tick");
        UpdatePlayerStatus(player);
        // DbgShowBoneName(player);
        UpdateCommandModifiers(player);
        UpdateItemAccessor(player);
        m_Weapons.Tick();
    }
References GetGame(), GetPlayer(), m_Weapons, PluginDayzPlayerDebug_Weapons::Tick(), UpdateCommandModifiers(), UpdateItemAccessor(), and UpdatePlayerStatus().
ToggleDebugWindowEvent()
void ToggleDebugWindowEvent ()
Definition at line 279 of file plugindayzplayerdebug.c.
    {
        m_CurrentMode++;
        if (m_CurrentMode > 2)
        {
            m_CurrentMode = 0;
        }
        ToggleDebugWindowSetMode(m_CurrentMode);
    }
References m_CurrentMode, and PluginBase::ToggleDebugWindowSetMode().
ToggleDebugWindowEventOld()
void ToggleDebugWindowEventOld ()
act:0 foc:0 -> act:1 foc:0 act:1 foc:0 -> act:0 foc:0 act:1 foc:1 -> act:1 foc:0
Definition at line 292 of file plugindayzplayerdebug.c.
    {
        if(m_IsActive && !m_HasFocus)
        {
            Hide();
        }
        else
        {
            Show();
            ReleaseFocus();
        }
    }
References PluginBase::Hide(), m_HasFocus, m_IsActive, PluginBase::ReleaseFocus(), and PluginBase::Show().
ToggleDebugWindowEventP()
void ToggleDebugWindowEventP ()
act:0 foc:0 -> act:1 foc:1 act:1 foc:0 -> act:1 foc:1 act:1 foc:1 -> act:0 foc:0
Definition at line 311 of file plugindayzplayerdebug.c.
    {
        if (m_IsActive && m_HasFocus)
        {
            Hide();
            ReleaseFocus();
        }
        else
        {
            Show();
            CaptureFocus();
        }
    }
References PluginBase::CaptureFocus(), PluginBase::Hide(), m_HasFocus, m_IsActive, PluginBase::ReleaseFocus(), and PluginBase::Show().
ToggleDebugWindowSetMode()
void ToggleDebugWindowSetMode (int pMode)
Definition at line 330 of file plugindayzplayerdebug.c.
    {
        switch (pMode)
        {
        case 0:     Hide(); ReleaseFocus(); break;
        case 1:     Show(); ReleaseFocus(); break;
        case 2:     Show(); CaptureFocus(); break;
        }
    }
References PluginBase::CaptureFocus(), PluginBase::Hide(), PluginBase::ReleaseFocus(), and PluginBase::Show().
UpdateCommandModifiers()
void UpdateCommandModifiers (DayZPlayer pPlayer)
Definition at line 539 of file plugindayzplayerdebug.c.
    {
        Actions_UpdateGlobals(pPlayer);
        // int nMods = pPlayer.GetCommandModifierCount();
        // Print("Number of modifiers");
        // Print(nMods);
        /*
        for (int i = 0; i < nMods; i ++)
        {
            // int a = pPlayer.GetCommandModifierId(i);
            if (pPlayer.GetCommandModifierId(i) == DayZPlayerConstants.COMMANDID_MOD_ACTION)
            {
            }
            // Print(a);
        }
        */
        HumanCommandActionCallback clbk = pPlayer.GetCommandModifier_Action();
        if (clbk)
        {
            Print(clbk);
        };
    }
References Actions_UpdateGlobals(), and Print().
Referenced by Tick().
UpdateItemAccessor()
void UpdateItemAccessor (DayZPlayer pPlayer)
Definition at line 1003 of file plugindayzplayerdebug.c.
    {
        m_ItemAccClass.SetText(pPlayer.DebugGetItemClass());
        m_ItemAccSClass.SetText(pPlayer.DebugGetItemSuperClass());
        m_ItemAccInst.SetText(pPlayer.DebugGetItemAnimInstance());
    }
References m_ItemAccClass, m_ItemAccInst, and m_ItemAccSClass.
Referenced by Tick().
UpdatePlayerStatus()
void UpdatePlayerStatus (DayZPlayer pPlayer)
Definition at line 451 of file plugindayzplayerdebug.c.
    {
        ref HumanMovementState      state   = new HumanMovementState();
        pPlayer.GetMovementState(state);
        string a = "Cmd:";
        if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MOVE)
        {
            a += "MOVE:";
            a += " st:" + state.m_iStanceIdx.ToString() + ", mv:" + state.m_iMovement.ToString();
        }
        else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_ACTION)
        {
            a += "FB ACTION:";
            a += " st:" + state.m_iStanceIdx.ToString();
        }
        else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MELEE)
        {
            a += "MELEE:";
            a += " st:" + state.m_iStanceIdx.ToString();
        }
        else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MELEE2)
        {
            a += "MELEE2:";
            a += " st:" + state.m_iStanceIdx.ToString();
        }
        else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_FALL)
        {
            a += "FALL:";
            a += " st:" + state.m_iStanceIdx.ToString();
        }
        else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_DEATH)
        {
            a += "now DEAD:";
            a += " st:" + state.m_iStanceIdx.ToString();
        }
        else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_LADDER)
        {
            a += "LADDER:";
            a += " st:" + state.m_iStanceIdx.ToString();
        }
        else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_UNCONSCIOUS)
        {
            a += "Unconscious:";
            a += " st:" + state.m_iStanceIdx.ToString();
        }
        else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_SWIM)
        {
            a += "Swimming:";
            a += " st:" + state.m_iStanceIdx.ToString();
        }
        else if (state.m_CommandTypeId == DayZPlayerConstants.COMMANDID_CLIMB)
        {
            a += "Climbing:";
            a += " st:" + state.m_iStanceIdx.ToString();
        }
        else
        {
            a += "UNKNOWN";
        }
        m_PlayerStatusV.SetText(a);
    }
References m_PlayerStatusV, and string::ToString().
Referenced by Tick().
~PluginDayzPlayerDebug()
void ~PluginDayzPlayerDebug ()
Definition at line 200 of file plugindayzplayerdebug.c.
    {
        ReleaseFocus();
        PlayerSyncDelete();
        #ifndef NO_GUI
        m_Weapons = NULL;
        m_Controls = NULL;
        m_OtherCmds = NULL;
        DestroyModuleWidgets();
        #endif
    }
References PluginBase::DestroyModuleWidgets(), m_Controls, m_OtherCmds, m_Weapons, PlayerSyncDelete(), and PluginBase::ReleaseFocus().
Variable Documentation
m_ActionEventV
TextWidget m_ActionEventV
Definition at line 152 of file plugindayzplayerdebug.c.
Referenced by Actions_Start(), and CreateModuleWidgets().
m_ActionsCancel
ButtonWidget m_ActionsCancel
Definition at line 148 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionsEnd
ButtonWidget m_ActionsEnd
Definition at line 146 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionsFinish
ButtonWidget m_ActionsFinish
Definition at line 147 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionsGlobalStatus
TextWidget m_ActionsGlobalStatus
Definition at line 153 of file plugindayzplayerdebug.c.
Referenced by Actions_UpdateGlobals(), and CreateModuleWidgets().
m_ActionsOTA
ButtonWidget m_ActionsOTA
Definition at line 149 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionsOTL
ButtonWidget m_ActionsOTL
Definition at line 150 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionsSelector
TextListboxWidget m_ActionsSelector
Definition at line 144 of file plugindayzplayerdebug.c.
Referenced by Actions_Start(), ActionsInit(), and CreateModuleWidgets().
m_ActionsStart
ButtonWidget m_ActionsStart
Definition at line 145 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionStateV
TextWidget m_ActionStateV
Definition at line 151 of file plugindayzplayerdebug.c.
Referenced by Actions_Start(), and CreateModuleWidgets().
m_ActionTypeFLA
ButtonWidget m_ActionTypeFLA
Definition at line 165 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeFLG
ButtonWidget m_ActionTypeFLG
Definition at line 169 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeFOA
ButtonWidget m_ActionTypeFOA
Definition at line 166 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeFOG
ButtonWidget m_ActionTypeFOG
Definition at line 170 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeLA
ButtonWidget m_ActionTypeLA
Definition at line 163 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeLG
ButtonWidget m_ActionTypeLG
Definition at line 167 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeOA
ButtonWidget m_ActionTypeOA
Definition at line 164 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_ActionTypeOG
ButtonWidget m_ActionTypeOG
Definition at line 168 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_bIsFullBody
protected bool m_bIsFullBody
Definition at line 64 of file plugindayzplayerdebug.c.
m_Card0
Widget m_Card0
Definition at line 133 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets(), and ShowCard().
m_Card0Button
ButtonWidget m_Card0Button
Definition at line 137 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_Card1
Widget m_Card1
Definition at line 134 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets(), PluginDayzPlayerDebug(), and ShowCard().
m_Card1Button
ButtonWidget m_Card1Button
Definition at line 138 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_Card2
Widget m_Card2
Definition at line 135 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets(), PluginDayzPlayerDebug(), and ShowCard().
m_Card2Button
ButtonWidget m_Card2Button
Definition at line 139 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_Card3
Widget m_Card3
Definition at line 136 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets(), PluginDayzPlayerDebug(), and ShowCard().
m_Card3Button
ButtonWidget m_Card3Button
Definition at line 140 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_CH_ActionCancel
bool m_CH_ActionCancel = false
Definition at line 179 of file plugindayzplayerdebug.c.
Referenced by CommandHandler().
m_CH_ActionCommand
int m_CH_ActionCommand = -1000
Definition at line 178 of file plugindayzplayerdebug.c.
Referenced by CommandHandler().
m_CH_ActionStart
bool m_CH_ActionStart = false
Definition at line 177 of file plugindayzplayerdebug.c.
Referenced by CommandHandler().
m_Controls
ref PluginDayzPlayerDebug_Ctrl m_Controls
Definition at line 183 of file plugindayzplayerdebug.c.
Referenced by CommandHandler(), UIScriptedMenu::Init(), UIScriptedMenu::OnClick(), PluginDayzPlayerDebug(), and ~PluginDayzPlayerDebug().
m_CurrentMode
int m_CurrentMode = 0
Definition at line 276 of file plugindayzplayerdebug.c.
Referenced by PPERequester_GameplayBase::SetNVMode(), PPERequester_GameplayBase::SetUndergroundExposureCoef(), PluginBase::ToggleDebugWindowEvent(), and ToggleDebugWindowEvent().
m_HasFocus
bool m_HasFocus = false
Definition at line 129 of file plugindayzplayerdebug.c.
Referenced by PluginBase::CaptureFocus(), CaptureFocus(), PluginBase::OnClick(), PluginBase::ReleaseFocus(), ReleaseFocus(), ToggleDebugWindowEventOld(), and ToggleDebugWindowEventP().
m_HasServerWalk
bool m_HasServerWalk = false
Definition at line 130 of file plugindayzplayerdebug.c.
m_IsActive
bool m_IsActive = false
Definition at line 128 of file plugindayzplayerdebug.c.
m_iStanceMask
protected int m_iStanceMask
Definition at line 65 of file plugindayzplayerdebug.c.
m_ItemAccClass
TextWidget m_ItemAccClass
Definition at line 159 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets(), and UpdateItemAccessor().
m_ItemAccInst
TextWidget m_ItemAccInst
Definition at line 161 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets(), and UpdateItemAccessor().
m_ItemAccSClass
TextWidget m_ItemAccSClass
Definition at line 160 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets(), and UpdateItemAccessor().
m_iUserData
protected int m_iUserData
Definition at line 63 of file plugindayzplayerdebug.c.
m_MainWnd
Widget m_MainWnd
Definition at line 132 of file plugindayzplayerdebug.c.
Referenced by PluginBase::CreateModuleWidgets(), CreateModuleWidgets(), PluginBase::ShowWidgets(), and ShowWidgets().
m_OtherCmds
ref PluginDayzPlayerDebug_OtherCmds m_OtherCmds
Definition at line 184 of file plugindayzplayerdebug.c.
Referenced by CommandHandler(), PluginDayzPlayerDebug(), and ~PluginDayzPlayerDebug().
m_PlayerServerWalk
ButtonWidget m_PlayerServerWalk
Definition at line 157 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_PlayerStatusV
EditBoxWidget m_PlayerStatusV
Definition at line 143 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets(), and UpdatePlayerStatus().
m_PlayerSyncCreateShadow
ButtonWidget m_PlayerSyncCreateShadow
Definition at line 155 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_PlayerSyncDelete
ButtonWidget m_PlayerSyncDelete
Definition at line 156 of file plugindayzplayerdebug.c.
Referenced by CreateModuleWidgets().
m_pPlayerShadow
Entity m_pPlayerShadow
Definition at line 174 of file plugindayzplayerdebug.c.
Referenced by PlayerSyncCreate(), and PlayerSyncDelete().
m_pPluginPlayerDebug
PluginDayzPlayerDebug m_pPluginPlayerDebug
Definition at line 52 of file plugindayzplayerdebug.c.
Referenced by PluginDayzPlayerDebugUserData().
m_pUIHandler
ref PluginDayzPlayerDebugUIHandler m_pUIHandler
Definition at line 172 of file plugindayzplayerdebug.c.
Referenced by PluginBase::CreateModuleWidgets(), and CreateModuleWidgets().
m_TickTimer
class PluginDayzPlayerActionCallback extends HumanCommandActionCallback m_TickTimer
m_Weapons
ref PluginDayzPlayerDebug_Weapons m_Weapons
Definition at line 182 of file plugindayzplayerdebug.c.
Referenced by CommandHandler(), IsWeaponChange(), PluginDayzPlayerDebug(), Tick(), and ~PluginDayzPlayerDebug().