DayzKode: P:/scripts/4_world/DayZ/plugins/pluginbase/plugindayzcreatureaidebug.c File Reference
plugindayzcreatureaidebug.c File Reference
Classes
class DayZCreatureAnimScriptDebug
Typedefs
typedef Param4< float, string, int, string > DayZCreatureAnimScriptDebugAnimEventData
typedef Param1< string > DayZCreatureAnimScriptDebugAnimPredictionData
typedef Param1< string > DayZCreatureAnimScriptDebugAnimTagData
Functions
void ActivateCommand (int commandIdx, int userInt, float userFloat)
void CheckShowMode ()
void EnableAI (bool enable)
void Event_OnClick ()
string GetStrValue (int index)
string GetStrValueType (int index)
DayZCreatureAnimScriptDebugVarType GetVariableType (int index)
void GUIAction_ActivateCommand (int commandIdx, int userInt, float userFloat)
void GUIAction_EnableAI (bool enable)
void GUIAction_InitDebugObject (Object obj)
void GUIAction_ReleaseDebugObject ()
void GUIAction_SetValue (int index, string strVal)
void GUIAction_UpdateSimulationPrecision (int simLOD)
void Hide ()
void InitDebugObject (Object obj)
override void OnDestroy ()
void OnGUI (bool show)
void OnGUI_AIControlEdit ()
void OnGUI_AnimEvents ()
void OnGUI_BulkSet ()
void OnGUI_CommandsEdit ()
void OnGUI_Variables ()
void OnGUI_VariablesEdit ()
void OnGUITimer ()
override void OnInit ()
void OnRpc (PlayerBase player, int rpc_type, ParamsReadContext ctx)
override void OnUpdate (float delta_time)
void PluginDayZCreatureAIDebug ()
void ReleaseDebugObject ()
void SendSyncMessages ()
void SetDebugShowMode (int mode)
void SetValueBool (int index, bool value)
void SetValueFloat (int index, float value)
void SetValueInt (int index, int value)
void Show ()
void SyncActivateCommand (int commandIdx, int userInt, float userFloat)
void SyncEnableAI (bool enable)
void SyncInitDebugObject (Object obj)
void SyncReceiveActivateCommand (ParamsReadContext ctx)
void SyncReceiveDisableAI (ParamsReadContext ctx)
void SyncReceiveEnableAI (ParamsReadContext ctx)
void SyncReceiveInitDebugObject (ParamsReadContext ctx)
void SyncReceiveMessage (ParamsReadContext ctx)
void SyncReceiveReleaseDebugObject (ParamsReadContext ctx)
void SyncReceiveValueBool (ParamsReadContext ctx)
void SyncReceiveValueFloat (ParamsReadContext ctx)
void SyncReceiveValueInt (ParamsReadContext ctx)
void SyncReleaseDebugObject ()
void SyncSetValueBool (int index, bool value)
void SyncSetValueFloat (int index, float value)
void SyncSetValueInt (int index, int value)
void ~PluginDayZCreatureAIDebug ()
Variables
class DayZCreatureAnimScriptDebug ACTIVATE_COMMAND
class DayZCreatureAnimScriptDebug DISABLE_AI
class DayZCreatureAnimScriptDebug ENABLE_AI
class DayZCreatureAnimScriptDebug INIT_DEBUG_OBJECT
bool m_bAIEnabled = true
bool m_bBulkSet = false
bool m_bEditMode = false
bool m_bIsCaptureMode = false
bool m_bShowAnimEvents = false
DayZCreatureAI m_DebugEntity = NULL
ref DayZCreatureAnimScriptDebug m_EntityAnimDbg = NULL
class DayZCreatureAnimScriptDebug m_iDebugMenu = -1
bool m_IsActive = false
string m_sDebugEntityName = ""
ref array< bool > m_SetCommandCheckStates = new array<bool>
ref array< bool > m_SetVariableCheckStates = new array<bool>
bool m_ShowDbgUI = false
ref array< ref Param > m_SyncMessages = new array<ref Param>
ref Timer m_TickTimer
class DayZCreatureAnimScriptDebug RELEASE_DEBUG_OBJECT
class DayZCreatureAnimScriptDebug SET_VALUE_BOOL
class DayZCreatureAnimScriptDebug SET_VALUE_FLOAT
class DayZCreatureAnimScriptDebug SET_VALUE_INT
Typedef Documentation
DayZCreatureAnimScriptDebugAnimEventData
typedef Param4<float, string, int, string> DayZCreatureAnimScriptDebugAnimEventData
Definition at line 1 of file plugindayzcreatureaidebug.c.
DayZCreatureAnimScriptDebugAnimPredictionData
typedef Param1<string> DayZCreatureAnimScriptDebugAnimPredictionData
Definition at line 2 of file plugindayzcreatureaidebug.c.
DayZCreatureAnimScriptDebugAnimTagData
typedef Param1<string> DayZCreatureAnimScriptDebugAnimTagData
Definition at line 3 of file plugindayzcreatureaidebug.c.
Function Documentation
ActivateCommand()
void ActivateCommand (int commandIdx, int userInt, float userFloat)
Definition at line 243 of file plugindayzcreatureaidebug.c.
    {
        int commandId = m_EntityAnimDbg.GetCommandID(commandIdx);
        m_EntityAnimDbg.ActivateCommand(commandId, userInt, userFloat);
    }
References DayZCreatureAnimScriptDebug::ActivateCommand(), DayZCreatureAnimScriptDebug::GetCommandID(), and m_EntityAnimDbg.
Referenced by GUIAction_ActivateCommand(), and SyncReceiveActivateCommand().
CheckShowMode()
void CheckShowMode ()
Definition at line 117 of file plugindayzcreatureaidebug.c.
    {
        int actMenuValue = DiagMenu.GetValue(DayZCreatureAIConstants.DEBUG_SHOWDEBUGPLUGIN);
        if (actMenuValue != m_iDebugMenu)
        {
            SetDebugShowMode(actMenuValue);
            m_iDebugMenu = actMenuValue;
        }
    }
References DiagMenu::GetValue(), m_iDebugMenu, and SetDebugShowMode().
Referenced by OnUpdate().
EnableAI()
void EnableAI (bool enable)
Definition at line 249 of file plugindayzcreatureaidebug.c.
    {
        if (m_DebugEntity.IsInherited(DayZCreatureAI))
        {
            DayZCreatureAI creatureAI = m_DebugEntity;
            if (enable)
            {
                #ifdef DEVELOPER
                creatureAI.DebugRestoreAIControl();
                #endif
            }
            else
            {
                #ifdef DEVELOPER
                creatureAI.DebugDisableAIControl();
                #endif
            }
        }
    }
References m_DebugEntity.
Referenced by GUIAction_EnableAI(), SyncReceiveDisableAI(), and SyncReceiveEnableAI().
Event_OnClick()
void Event_OnClick ()
Definition at line 595 of file plugindayzcreatureaidebug.c.
    {
        if (m_IsActive == false)
            return;
        const float MAX_RAYCAST_RANGE = 1000;
        if (m_bIsCaptureMode)
        {
            vector dir = GetGame().GetPointerDirection();
            vector pos = GetGame().GetCurrentCameraPosition();
            // Raycast
            vector from = pos;
            vector to = pos + (dir * MAX_RAYCAST_RANGE);
            vector contact_pos;
            vector contact_dir;
            int contact_component;
            set<Object> objects = new set<Object>;
            if (DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component, objects, NULL, GetGame().GetPlayer()))
            {
                for ( int i = 0; i < objects.Count(); i++ )
                {
                    Object obj = objects.Get(i);
                    if (obj && obj.IsInherited(DayZCreature))
                    {
                        m_bIsCaptureMode = false;
                        GUIAction_InitDebugObject(obj);
                        return;
                    }
                }
            }
        }
    }
References CGame::GetCurrentCameraPosition(), GetGame(), GetPlayer(), CGame::GetPointerDirection(), GUIAction_InitDebugObject(), m_bIsCaptureMode, m_IsActive, and DayZPhysics::RaycastRV().
GetStrValue()
string GetStrValue (int index)
Definition at line 135 of file plugindayzcreatureaidebug.c.
    {
        string strVal;
        switch (m_EntityAnimDbg.GetVariableType(index))
        {
            case DayZCreatureAnimScriptDebugVarType.INT:
                int valInt = m_EntityAnimDbg.GetVariableInt(index);
                strVal = valInt.ToString();
                break;
            case DayZCreatureAnimScriptDebugVarType.FLOAT:
                float valFloat = m_EntityAnimDbg.GetVariableFloat(index);
                strVal = valFloat.ToString();
                break;
            case DayZCreatureAnimScriptDebugVarType.BOOL:
                bool valBool = m_EntityAnimDbg.GetVariableBool(index);
                if (valBool)
                {
                    strVal = "true";
                }
                else
                {
                    strVal = "false";
                }
                break;
            default:
                strVal = "unk";
        }
        return strVal;
    }
References DayZCreatureAnimScriptDebug::GetVariableBool(), DayZCreatureAnimScriptDebug::GetVariableFloat(), DayZCreatureAnimScriptDebug::GetVariableInt(), DayZCreatureAnimScriptDebug::GetVariableType(), m_EntityAnimDbg, float::ToString(), and string::ToString().
Referenced by OnGUI_Variables().
GetStrValueType()
string GetStrValueType (int index)
Definition at line 165 of file plugindayzcreatureaidebug.c.
    {
        string strValType;
        switch (m_EntityAnimDbg.GetVariableType(index))
        {
            case DayZCreatureAnimScriptDebugVarType.INT:
                strValType = "int";
                break;
            case DayZCreatureAnimScriptDebugVarType.FLOAT:
                strValType = "float";
                break;
            case DayZCreatureAnimScriptDebugVarType.BOOL:
                strValType = "bool";
                break;
            default:
                strValType = "unk";
        }
        return strValType;
    }
References DayZCreatureAnimScriptDebug::GetVariableType(), and m_EntityAnimDbg.
Referenced by OnGUI_VariablesEdit().
GetVariableType()
DayZCreatureAnimScriptDebugVarType GetVariableType (int index)
Definition at line 269 of file plugindayzcreatureaidebug.c.
    {
        return m_EntityAnimDbg.GetVariableType(index);
    }
References DayZCreatureAnimScriptDebug::GetVariableType(), and m_EntityAnimDbg.
Referenced by GUIAction_SetValue().
GUIAction_ActivateCommand()
void GUIAction_ActivateCommand (int commandIdx, int userInt, float userFloat)
Definition at line 719 of file plugindayzcreatureaidebug.c.
    {
        if (GetGame().IsMultiplayer())
        {
            SyncActivateCommand(commandIdx, userInt, userFloat);
        }
        else
        {
            ActivateCommand(commandIdx, userInt, userFloat);
        }
    }
References ActivateCommand(), GetGame(), and SyncActivateCommand().
Referenced by OnGUI_CommandsEdit().
GUIAction_EnableAI()
void GUIAction_EnableAI (bool enable)
Definition at line 732 of file plugindayzcreatureaidebug.c.
    {
        if (GetGame().IsMultiplayer())
        {
            SyncEnableAI(enable);
        }
        else
        {
            EnableAI(enable);
        }
    }
References EnableAI(), GetGame(), and SyncEnableAI().
Referenced by OnGUI_AIControlEdit().
GUIAction_InitDebugObject()
void GUIAction_InitDebugObject (Object obj)
GUI actions
Definition at line 634 of file plugindayzcreatureaidebug.c.
    {
        InitDebugObject(obj);
        if (GetGame().IsMultiplayer())
        {
            SyncInitDebugObject(obj);
        }
    }
References GetGame(), InitDebugObject(), and SyncInitDebugObject().
Referenced by Event_OnClick().
GUIAction_ReleaseDebugObject()
void GUIAction_ReleaseDebugObject ()
Definition at line 656 of file plugindayzcreatureaidebug.c.
    {
        ReleaseDebugObject();
        if (GetGame().IsMultiplayer())
        {
            SyncReleaseDebugObject();
        }
    }
References GetGame(), ReleaseDebugObject(), and SyncReleaseDebugObject().
Referenced by OnGUI().
GUIAction_SetValue()
void GUIAction_SetValue (int index, string strVal)
Definition at line 665 of file plugindayzcreatureaidebug.c.
    {
        switch (GetVariableType(index))
        {
            case DayZCreatureAnimScriptDebugVarType.INT:
                int intValue = strVal.ToInt();
                if (GetGame().IsMultiplayer())
                {
                    SyncSetValueInt(index, intValue);
                }
                else
                {
                    SetValueInt(index, intValue);
                }
                break;
            case DayZCreatureAnimScriptDebugVarType.FLOAT:
                float floatValue = strVal.ToFloat();
                if (GetGame().IsMultiplayer())
                {
                    SyncSetValueFloat(index, floatValue);
                }
                else
                {
                    SetValueFloat(index, floatValue);
                }
                break;
            case DayZCreatureAnimScriptDebugVarType.BOOL:
                bool boolValue;
                strVal.ToLower();
                if (strVal.Contains("true"))
                {
                    boolValue = true;
                }
                else if (strVal.Contains("false"))
                {
                    boolValue = false;
                }
                else
                {
                    boolValue = (bool)strVal.ToInt();
                }
                if (GetGame().IsMultiplayer())
                {
                    SyncSetValueBool(index, boolValue);
                }
                else
                {
                    SetValueBool(index, boolValue);
                }
                break;
        }
    }
References string::Contains(), GetGame(), GetVariableType(), CGame::IsMultiplayer(), SetValueBool(), SetValueFloat(), SetValueInt(), SyncSetValueBool(), SyncSetValueFloat(), SyncSetValueInt(), string::ToFloat(), string::ToInt(), and string::ToLower().
Referenced by OnGUI_VariablesEdit().
GUIAction_UpdateSimulationPrecision()
void GUIAction_UpdateSimulationPrecision (int simLOD)
Definition at line 651 of file plugindayzcreatureaidebug.c.
    {
        m_DebugEntity.UpdateSimulationPrecision(simLOD);
    }
References m_DebugEntity.
Referenced by OnGUI().
Hide()
void Hide ()
Definition at line 588 of file plugindayzcreatureaidebug.c.
    {
        m_IsActive = false;
        m_TickTimer = NULL;
        OnGUI(false);
    }
References m_IsActive, m_TickTimer, and OnGUI().
InitDebugObject()
void InitDebugObject (Object obj)
Definition at line 186 of file plugindayzcreatureaidebug.c.
    {
        m_EntityAnimDbg = new DayZCreatureAnimScriptDebug();
        m_EntityAnimDbg.SetCreature( DayZCreature.Cast( obj ) );
        m_DebugEntity = DayZCreatureAI.Cast( obj );
        m_sDebugEntityName = obj.GetType();
        int varCount = m_EntityAnimDbg.GetVariableCount();
        int cmdCount = m_EntityAnimDbg.GetCommandCount();
        int toAddCount = 0;
        if (m_SetVariableCheckStates.Count() < varCount)
        {
            toAddCount = varCount - m_SetVariableCheckStates.Count();
            for (int idxVar = 0; idxVar < toAddCount; idxVar++)
            {
                m_SetVariableCheckStates.Insert(false);
            }
        }
        if (m_SetCommandCheckStates.Count() < cmdCount)
        {
            toAddCount = cmdCount - m_SetCommandCheckStates.Count();
            for (int idxCmd = 0; idxCmd < toAddCount; idxCmd++)
            {
                m_SetCommandCheckStates.Insert(false);
            }
        }
    }
References DayZCreatureAnimScriptDebug::GetCommandCount(), DayZCreatureAnimScriptDebug::GetVariableCount(), m_DebugEntity, m_EntityAnimDbg, m_sDebugEntityName, m_SetCommandCheckStates, m_SetVariableCheckStates, and DayZCreatureAnimScriptDebug::SetCreature().
Referenced by GUIAction_InitDebugObject(), and SyncReceiveInitDebugObject().
OnDestroy()
override void OnDestroy ()
Definition at line 113 of file plugindayzcreatureaidebug.c.
    {
    }
OnGUI()
void OnGUI (bool show)
Definition at line 457 of file plugindayzcreatureaidebug.c.
    {
        const int windowPosX = 0;
        const int windowPosY = 300;
        const int mainPanelSizeX = 200;
        const int mainPanelSizeY = 1;
        const int margin = 10;
        DbgUI.BeginCleanupScope();
        DbgUI.Begin("CretureAI debug", windowPosX, windowPosY);
        if (show)
        {
            if (m_EntityAnimDbg == NULL)
            {
                if (m_bIsCaptureMode == true)
                {
                    DbgUI.Text("Capturing...");
                }
                else
                {
                    if (DbgUI.Button("Capture"))
                    {
                        m_bIsCaptureMode = true;
                    }
                }
                // Clear additional windows
                DbgUI.Begin("CreatureAI EditMenu");
                DbgUI.End();
                DbgUI.Begin("CreatureAI AnimEvents");
                DbgUI.End();
            }
            else
            {
                DbgUI.Panel("MinimumSize", mainPanelSizeX, mainPanelSizeY);
                DbgUI.Text(m_sDebugEntityName);
                DbgUI.SameLine();
                bool btnReleasePressed = DbgUI.Button("Release");
                DbgUI.Check("Edit", m_bEditMode);
                DbgUI.Check("ShowAnimEvents", m_bShowAnimEvents);
                #ifdef _DAYZ_CREATURE_DEBUG_SHADOW
                if (!GetGame().IsMultiplayer())
                {
                    DbgUI.SameLine();
                    if (DbgUI.Button("CreateShadow"))
                    {
                        GUIAction_CreateShadow();
                    }
                }
                #endif
                if (!GetGame().IsMultiplayer())
                {
                    const int simLODInputSize = 20;
                    int simLOD;
                    DbgUI.InputInt("SimLOD", simLOD, simLODInputSize);
                    DbgUI.SameLine();
                    if (DbgUI.Button("UpdateSimulationPrecision"))
                    {
                        GUIAction_UpdateSimulationPrecision(simLOD);
                    }
                }
                if (btnReleasePressed)
                {
                    GUIAction_ReleaseDebugObject();
                }
                else
                {
                    OnGUI_Variables();
                    DbgUI.Begin("CreatureAI EditMenu", windowPosX + mainPanelSizeX + margin, windowPosY);
                    if (m_bEditMode)
                    {
                        OnGUI_AIControlEdit();
                        OnGUI_BulkSet();
                        OnGUI_VariablesEdit();
                        DbgUI.Spacer(20);
                        OnGUI_CommandsEdit();
                    }
                    DbgUI.End();
                    DbgUI.Begin("CreatureAI AnimEvents", windowPosX + mainPanelSizeX + margin, windowPosY);
                    if (m_bShowAnimEvents)
                    {
                        OnGUI_AnimEvents();
                    }
                    DbgUI.End();
                }
            }
        }
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::Button(), DbgUI::Check(), DbgUI::End(), DbgUI::EndCleanupScope(), GetGame(), GUIAction_ReleaseDebugObject(), GUIAction_UpdateSimulationPrecision(), DbgUI::InputInt(), m_bEditMode, m_bIsCaptureMode, m_bShowAnimEvents, m_EntityAnimDbg, m_sDebugEntityName, mainPanelSizeX, mainPanelSizeY, margin, OnGUI_AIControlEdit(), OnGUI_AnimEvents(), OnGUI_BulkSet(), OnGUI_CommandsEdit(), OnGUI_Variables(), OnGUI_VariablesEdit(), DbgUI::Panel(), DbgUI::SameLine(), DbgUI::Spacer(), DbgUI::Text(), windowPosX, and windowPosY.
Referenced by Hide(), and OnGUITimer().
OnGUI_AIControlEdit()
void OnGUI_AIControlEdit ()
Definition at line 369 of file plugindayzcreatureaidebug.c.
    {
        bool buttonPressed = false;
        if (m_bAIEnabled)
        {
            buttonPressed = DbgUI.Button("Disable AI");
        }
        else
        {
            buttonPressed = DbgUI.Button("Enable AI");
        }
        if (buttonPressed)
        {
            m_bAIEnabled = !m_bAIEnabled;
            GUIAction_EnableAI(m_bAIEnabled);
        }
    }
References DbgUI::Button(), GUIAction_EnableAI(), and m_bAIEnabled.
Referenced by OnGUI().
OnGUI_AnimEvents()
void OnGUI_AnimEvents ()
Definition at line 399 of file plugindayzcreatureaidebug.c.
    {
        DbgUI.PushID_Str("AnimEvents");
        const int panelMinSizeX = 350;
        DbgUI.Panel("MinimumSize", panelMinSizeX, 1);
        string strTags;
        for (int tagIdx = 0; tagIdx < m_EntityAnimDbg.m_AnimTags.Count(); ++tagIdx)
        {
            if (tagIdx != 0)
                strTags += ", ";
            strTags += m_EntityAnimDbg.m_AnimTags[tagIdx].param1;
        }
        string strPredictions;
        for (int predIdx = 0; predIdx < m_EntityAnimDbg.m_AnimPredictions.Count(); ++predIdx)
        {
            if (predIdx != 0)
                strPredictions += ", ";
            strPredictions += m_EntityAnimDbg.m_AnimPredictions[predIdx].param1;
        }
        DbgUI.PushID_Str("AnimTagsDisplay");
        DbgUI.Text(strTags);
        DbgUI.PopID();
        DbgUI.PushID_Str("AnimPredictionsDisplay");
        DbgUI.Text(strPredictions);
        DbgUI.PopID();
        string strFilter;
        DbgUI.InputText("Filter", strFilter, panelMinSizeX);
        m_EntityAnimDbg.m_EventsFilter.Clear();
        strFilter.Split(" ", m_EntityAnimDbg.m_EventsFilter);
        DbgUI.Button("TakeMyFocus");
        const int evDisplayCount = 15;
        int evToDisplayCount = (int)Math.Min(m_EntityAnimDbg.m_AnimEvents.Count(), evDisplayCount);
        for (int evIdx = 0; evIdx < evToDisplayCount; ++evIdx)
        {
            DbgUI.PushID_Int(evIdx);
            if (m_EntityAnimDbg.m_AnimEvents[evIdx].param2.Length() > 0)
            {
                DbgUI.Text((m_EntityAnimDbg.m_AnimEvents[evIdx].param1 / 1000.0).ToString() + " - " + m_EntityAnimDbg.m_AnimEvents[evIdx].param2);
            }
            DbgUI.PopID();
        }
        DbgUI.PopID();
    }
References DbgUI::Button(), DbgUI::InputText(), int, DayZCreatureAnimScriptDebug::m_AnimEvents, DayZCreatureAnimScriptDebug::m_AnimPredictions, DayZCreatureAnimScriptDebug::m_AnimTags, m_EntityAnimDbg, DayZCreatureAnimScriptDebug::m_EventsFilter, Math::Min(), DbgUI::Panel(), DbgUI::PopID(), DbgUI::PushID_Int(), DbgUI::PushID_Str(), string::Split(), and DbgUI::Text().
Referenced by OnGUI().
OnGUI_BulkSet()
void OnGUI_BulkSet ()
Definition at line 389 of file plugindayzcreatureaidebug.c.
    {
        m_bBulkSet = false;
        if (DbgUI.Button("Bulk set"))
        {
            m_bBulkSet = true;
        }
    }
References DbgUI::Button(), and m_bBulkSet.
Referenced by OnGUI().
OnGUI_CommandsEdit()
void OnGUI_CommandsEdit ()
Definition at line 326 of file plugindayzcreatureaidebug.c.
    {
        const int INPUT_BOX_SIZE = 35;
        DbgUI.PushID_Str("CommandsEdit");
        int cmdCount = m_EntityAnimDbg.GetCommandCount();
        for (int i=0; i < cmdCount; i++)
        {
            DbgUI.BeginCleanupScope();
            DbgUI.PushID_Int(i);
            bool result;
            DbgUI.Check("", result);
            m_SetCommandCheckStates[i] = result;
            DbgUI.SameLine();
            bool setButtonPressed = DbgUI.Button("Set");
            DbgUI.SameLine();
            string strUserInt;
            DbgUI.InputText("int", strUserInt, INPUT_BOX_SIZE);
            DbgUI.SameLine();
            string strUserFloat;
            DbgUI.InputText("float", strUserFloat, INPUT_BOX_SIZE);
            DbgUI.SameLine();
            DbgUI.Text(m_EntityAnimDbg.GetCommandName(i) + "[" + m_EntityAnimDbg.GetCommandID(i) + "]");
            if (setButtonPressed || (m_bBulkSet && m_SetCommandCheckStates[i]))
            {
                GUIAction_ActivateCommand(i, strUserInt.ToInt(), strUserFloat.ToFloat());
            }
            DbgUI.PopID();
            DbgUI.EndCleanupScope();
        }
        DbgUI.PopID();
    }
References DbgUI::BeginCleanupScope(), DbgUI::Button(), DbgUI::Check(), DbgUI::EndCleanupScope(), DayZCreatureAnimScriptDebug::GetCommandCount(), DayZCreatureAnimScriptDebug::GetCommandID(), DayZCreatureAnimScriptDebug::GetCommandName(), GUIAction_ActivateCommand(), DbgUI::InputText(), m_bBulkSet, m_EntityAnimDbg, m_SetCommandCheckStates, DbgUI::PopID(), DbgUI::PushID_Int(), DbgUI::PushID_Str(), DbgUI::SameLine(), DbgUI::Text(), string::ToFloat(), and string::ToInt().
Referenced by OnGUI().
OnGUI_Variables()
void OnGUI_Variables ()
Definition at line 274 of file plugindayzcreatureaidebug.c.
    {
        int varCount = m_EntityAnimDbg.GetVariableCount();
        for (int i=0; i < varCount; i++)
        {
            DbgUI.BeginCleanupScope();
            DbgUI.Text(m_EntityAnimDbg.GetVariableName(i) + ": " + GetStrValue(i));
            DbgUI.EndCleanupScope();
        }
    }
References DbgUI::BeginCleanupScope(), DbgUI::EndCleanupScope(), GetStrValue(), DayZCreatureAnimScriptDebug::GetVariableCount(), DayZCreatureAnimScriptDebug::GetVariableName(), m_EntityAnimDbg, and DbgUI::Text().
Referenced by OnGUI().
OnGUI_VariablesEdit()
void OnGUI_VariablesEdit ()
Definition at line 285 of file plugindayzcreatureaidebug.c.
    {
        const int INPUT_BOX_SIZE = 35;
        DbgUI.PushID_Str("VariablesEdit");
        int varCount = m_EntityAnimDbg.GetVariableCount();
        for (int i=0; i < varCount; i++)
        {
            DbgUI.BeginCleanupScope();
            DbgUI.PushID_Int(i);
            bool result;
            DbgUI.Check("", result);
            m_SetVariableCheckStates[i] = result;
            DbgUI.SameLine();
            bool setButtonPressed = DbgUI.Button("Set");
            DbgUI.SameLine();
            string strUserVal;
            DbgUI.InputText(GetStrValueType(i), strUserVal, INPUT_BOX_SIZE);
            DbgUI.SameLine();
            DbgUI.Text(m_EntityAnimDbg.GetVariableName(i));
            if (setButtonPressed || (m_bBulkSet && m_SetVariableCheckStates[i]))
            {
                GUIAction_SetValue(i, strUserVal);
            }
            DbgUI.PopID();
            DbgUI.EndCleanupScope();
        }
        DbgUI.PopID();
    }
References DbgUI::BeginCleanupScope(), DbgUI::Button(), DbgUI::Check(), DbgUI::EndCleanupScope(), GetStrValueType(), DayZCreatureAnimScriptDebug::GetVariableCount(), DayZCreatureAnimScriptDebug::GetVariableName(), GUIAction_SetValue(), DbgUI::InputText(), m_bBulkSet, m_EntityAnimDbg, m_SetVariableCheckStates, DbgUI::PopID(), DbgUI::PushID_Int(), DbgUI::PushID_Str(), DbgUI::SameLine(), and DbgUI::Text().
Referenced by OnGUI().
OnGUITimer()
void OnGUITimer ()
Definition at line 555 of file plugindayzcreatureaidebug.c.
    {
        OnGUI(m_IsActive);
        if (GetGame().IsMultiplayer() && GetGame().IsClient())
        {
            SendSyncMessages();
        }
    }
References GetGame(), m_IsActive, OnGUI(), and SendSyncMessages().
OnInit()
override void OnInit ()
Definition at line 109 of file plugindayzcreatureaidebug.c.
    {
    }
OnRpc()
void OnRpc (PlayerBase player, int rpc_type, ParamsReadContext ctx)
Definition at line 762 of file plugindayzcreatureaidebug.c.
    {
        if (rpc_type == ERPCs.DEV_RPC_PLUGIN_DZCREATURE_DEBUG)
        {
            SyncReceiveMessage(ctx);
        }
    }
References SyncReceiveMessage().
OnUpdate()
override void OnUpdate (float delta_time)
Definition at line 127 of file plugindayzcreatureaidebug.c.
    {
        if (!GetGame().IsDedicatedServer())
        {
            CheckShowMode();
        }
    }
References CheckShowMode(), and GetGame().
PluginDayZCreatureAIDebug()
void PluginDayZCreatureAIDebug ()
Definition at line 101 of file plugindayzcreatureaidebug.c.
    {
    }
Referenced by PluginBase::OnRPCPluginDayzCreatureDebug().
ReleaseDebugObject()
void ReleaseDebugObject ()
Definition at line 218 of file plugindayzcreatureaidebug.c.
    {
        m_DebugEntity = NULL;
        m_EntityAnimDbg = NULL;
        m_sDebugEntityName = "";
        m_SetVariableCheckStates.Clear();
        m_SetCommandCheckStates.Clear();
    }
References m_DebugEntity, m_EntityAnimDbg, m_sDebugEntityName, m_SetCommandCheckStates, and m_SetVariableCheckStates.
Referenced by GUIAction_ReleaseDebugObject(), and SyncReceiveReleaseDebugObject().
SendSyncMessages()
void SendSyncMessages ()
sync
Definition at line 748 of file plugindayzcreatureaidebug.c.
    {
        int count = m_SyncMessages.Count();
        if (count > 0)
        {
            ref Param1<int> paramCount = new Param1<int>(count);
            m_SyncMessages.InsertAt(paramCount, 0);
            GetGame().GetPlayer().RPC(ERPCs.DEV_RPC_PLUGIN_DZCREATURE_DEBUG, m_SyncMessages, true);
            m_SyncMessages.Clear();
        }
    }
References GetGame(), CGame::GetPlayer(), and m_SyncMessages.
Referenced by OnGUITimer().
SetDebugShowMode()
void SetDebugShowMode (int mode)
Definition at line 565 of file plugindayzcreatureaidebug.c.
    {
        switch (mode)
        {
            case 0:
            {
                Hide();
            } break;
            case 1:
            {
                Show();
            } break;
        }
    }
References PluginBase::Hide(), and PluginBase::Show().
Referenced by CheckShowMode().
SetValueBool()
void SetValueBool (int index, bool value)
Definition at line 238 of file plugindayzcreatureaidebug.c.
    {
        m_EntityAnimDbg.SetVariableBool(index, value);
    }
References m_EntityAnimDbg, and DayZCreatureAnimScriptDebug::SetVariableBool().
Referenced by GUIAction_SetValue(), and SyncReceiveValueBool().
SetValueFloat()
void SetValueFloat (int index, float value)
Definition at line 233 of file plugindayzcreatureaidebug.c.
    {
        m_EntityAnimDbg.SetVariableFloat(index, value);
    }
References m_EntityAnimDbg, and DayZCreatureAnimScriptDebug::SetVariableFloat().
Referenced by GUIAction_SetValue(), and SyncReceiveValueFloat().
SetValueInt()
void SetValueInt (int index, int value)
Definition at line 228 of file plugindayzcreatureaidebug.c.
    {
        m_EntityAnimDbg.SetVariableInt(index, value);
    }
References m_EntityAnimDbg, and DayZCreatureAnimScriptDebug::SetVariableInt().
Referenced by GUIAction_SetValue(), and SyncReceiveValueInt().
Show()
void Show ()
Definition at line 580 of file plugindayzcreatureaidebug.c.
    {
        m_IsActive = true;
        m_TickTimer = new Timer();
        m_TickTimer.Run(0.1, this, "OnGUITimer", NULL, true);
    }
References m_IsActive, and m_TickTimer.
SyncActivateCommand()
void SyncActivateCommand (int commandIdx, int userInt, float userFloat)
Definition at line 901 of file plugindayzcreatureaidebug.c.
    {
        ref Param1<int> type = new Param1<int>(PluginDayZCreatureAIDebugSyncMessageType.ACTIVATE_COMMAND);
        ref Param3<int, int, float> command = new Param3<int, int, float>(commandIdx, userInt, userFloat);
        m_SyncMessages.Insert(type);
        m_SyncMessages.Insert(command);
    }
References m_SyncMessages.
Referenced by GUIAction_ActivateCommand().
SyncEnableAI()
void SyncEnableAI (bool enable)
Definition at line 920 of file plugindayzcreatureaidebug.c.
    {
        ref Param1<int> type = new Param1<int>(PluginDayZCreatureAIDebugSyncMessageType.COUNT);
        if (enable)
        {
            type.param1 = PluginDayZCreatureAIDebugSyncMessageType.ENABLE_AI;
        }
        else
        {
            type.param1 = PluginDayZCreatureAIDebugSyncMessageType.DISABLE_AI;
        }
        m_SyncMessages.Insert(type);
    }
References m_SyncMessages.
Referenced by GUIAction_EnableAI().
SyncInitDebugObject()
void SyncInitDebugObject (Object obj)
Definition at line 814 of file plugindayzcreatureaidebug.c.
    {
        ref Param1<int> type = new Param1<int>(PluginDayZCreatureAIDebugSyncMessageType.INIT_DEBUG_OBJECT);
        ref Param1<Object> object = new Param1<Object>(obj);
        m_SyncMessages.Insert(type);
        m_SyncMessages.Insert(object);
    }
References m_SyncMessages.
Referenced by GUIAction_InitDebugObject().
SyncReceiveActivateCommand()
void SyncReceiveActivateCommand (ParamsReadContext ctx)
Definition at line 910 of file plugindayzcreatureaidebug.c.
    {
        ref Param3<int, int, float> command = new Param3<int, int, float>(-1, 0, 0.0);
        if (ctx.Read(command))
        {
            ActivateCommand(command.param1, command.param2, command.param3);
        }
    }
References ActivateCommand(), and Serializer::Read().
Referenced by SyncReceiveMessage().
SyncReceiveDisableAI()
void SyncReceiveDisableAI (ParamsReadContext ctx)
Definition at line 940 of file plugindayzcreatureaidebug.c.
    {
        EnableAI(false);
    }
References EnableAI().
Referenced by SyncReceiveMessage().
SyncReceiveEnableAI()
void SyncReceiveEnableAI (ParamsReadContext ctx)
Definition at line 935 of file plugindayzcreatureaidebug.c.
    {
        EnableAI(true);
    }
References EnableAI().
Referenced by SyncReceiveMessage().
SyncReceiveInitDebugObject()
void SyncReceiveInitDebugObject (ParamsReadContext ctx)
Definition at line 823 of file plugindayzcreatureaidebug.c.
    {
        ref Param1<Object> object = new Param1<Object>(NULL);
        if (ctx.Read(object))
        {
            InitDebugObject(object.param1);
        }
    }
References InitDebugObject(), and Serializer::Read().
Referenced by SyncReceiveMessage().
SyncReceiveMessage()
void SyncReceiveMessage (ParamsReadContext ctx)
Definition at line 770 of file plugindayzcreatureaidebug.c.
    {
        ref Param1<int> count = new Param1<int>(0);
        if (ctx.Read(count))
        {
            ref Param1<int> type = new Param1<int>(PluginDayZCreatureAIDebugSyncMessageType.COUNT);
            for (int i=0; i < count.param1; ++i)
            {
                if (ctx.Read(type))
                {
                    switch (type.param1)
                    {
                        case PluginDayZCreatureAIDebugSyncMessageType.INIT_DEBUG_OBJECT:
                            SyncReceiveInitDebugObject(ctx);
                            break;
                        case PluginDayZCreatureAIDebugSyncMessageType.RELEASE_DEBUG_OBJECT:
                            SyncReceiveReleaseDebugObject(ctx);
                            break;
                        case PluginDayZCreatureAIDebugSyncMessageType.SET_VALUE_INT:
                            SyncReceiveValueInt(ctx);
                            break;
                        case PluginDayZCreatureAIDebugSyncMessageType.SET_VALUE_FLOAT:
                            SyncReceiveValueFloat(ctx);
                            break;
                        case PluginDayZCreatureAIDebugSyncMessageType.SET_VALUE_BOOL:
                            SyncReceiveValueBool(ctx);
                            break;
                        case PluginDayZCreatureAIDebugSyncMessageType.ACTIVATE_COMMAND:
                            SyncReceiveActivateCommand(ctx);
                            break;
                        case PluginDayZCreatureAIDebugSyncMessageType.ENABLE_AI:
                            SyncReceiveEnableAI(ctx);
                            break;
                        case PluginDayZCreatureAIDebugSyncMessageType.DISABLE_AI:
                            SyncReceiveDisableAI(ctx);
                            break;
                    }
                }
                type.param1 = PluginDayZCreatureAIDebugSyncMessageType.COUNT;
            }
        }
    }
References Serializer::Read(), SyncReceiveActivateCommand(), SyncReceiveDisableAI(), SyncReceiveEnableAI(), SyncReceiveInitDebugObject(), SyncReceiveReleaseDebugObject(), SyncReceiveValueBool(), SyncReceiveValueFloat(), and SyncReceiveValueInt().
Referenced by OnRpc().
SyncReceiveReleaseDebugObject()
void SyncReceiveReleaseDebugObject (ParamsReadContext ctx)
Definition at line 839 of file plugindayzcreatureaidebug.c.
    {
        ReleaseDebugObject();
    }
References ReleaseDebugObject().
Referenced by SyncReceiveMessage().
SyncReceiveValueBool()
void SyncReceiveValueBool (ParamsReadContext ctx)
Definition at line 891 of file plugindayzcreatureaidebug.c.
    {
        ref Param2<int, bool> paramValue = new Param2<int, bool>(-1, false);
        if (ctx.Read(paramValue))
        {
            SetValueBool(paramValue.param1, paramValue.param2);
        }
    }
References Serializer::Read(), and SetValueBool().
Referenced by SyncReceiveMessage().
SyncReceiveValueFloat()
void SyncReceiveValueFloat (ParamsReadContext ctx)
Definition at line 872 of file plugindayzcreatureaidebug.c.
    {
        ref Param2<int, float> paramValue = new Param2<int, float>(-1, 0.0);
        if (ctx.Read(paramValue))
        {
            SetValueFloat(paramValue.param1, paramValue.param2);
        }
    }
References Serializer::Read(), and SetValueFloat().
Referenced by SyncReceiveMessage().
SyncReceiveValueInt()
void SyncReceiveValueInt (ParamsReadContext ctx)
Definition at line 853 of file plugindayzcreatureaidebug.c.
    {
        ref Param2<int, int> paramValue = new Param2<int, int>(-1, 0);
        if (ctx.Read(paramValue))
        {
            SetValueInt(paramValue.param1, paramValue.param2);
        }
    }
References Serializer::Read(), and SetValueInt().
Referenced by SyncReceiveMessage().
SyncReleaseDebugObject()
void SyncReleaseDebugObject ()
Definition at line 832 of file plugindayzcreatureaidebug.c.
    {
        ref Param1<int> type = new Param1<int>(PluginDayZCreatureAIDebugSyncMessageType.RELEASE_DEBUG_OBJECT);
        m_SyncMessages.Insert(type);
    }
References m_SyncMessages.
Referenced by GUIAction_ReleaseDebugObject().
SyncSetValueBool()
void SyncSetValueBool (int index, bool value)
Definition at line 882 of file plugindayzcreatureaidebug.c.
    {
        ref Param1<int> type = new Param1<int>(PluginDayZCreatureAIDebugSyncMessageType.SET_VALUE_BOOL);
        ref Param2<int, bool> paramValue = new Param2<int, bool>(index, value);
        m_SyncMessages.Insert(type);
        m_SyncMessages.Insert(paramValue);
    }
References m_SyncMessages.
Referenced by GUIAction_SetValue().
SyncSetValueFloat()
void SyncSetValueFloat (int index, float value)
Definition at line 863 of file plugindayzcreatureaidebug.c.
    {
        ref Param1<int> type = new Param1<int>(PluginDayZCreatureAIDebugSyncMessageType.SET_VALUE_FLOAT);
        ref Param2<int, float> paramValue = new Param2<int, float>(index, value);
        m_SyncMessages.Insert(type);
        m_SyncMessages.Insert(paramValue);
    }
References m_SyncMessages.
Referenced by GUIAction_SetValue().
SyncSetValueInt()
void SyncSetValueInt (int index, int value)
Definition at line 844 of file plugindayzcreatureaidebug.c.
    {
        ref Param1<int> type = new Param1<int>(PluginDayZCreatureAIDebugSyncMessageType.SET_VALUE_INT);
        ref Param2<int, int> paramValue = new Param2<int, int>(index, value);
        m_SyncMessages.Insert(type);
        m_SyncMessages.Insert(paramValue);
    }
References m_SyncMessages.
Referenced by GUIAction_SetValue().
~PluginDayZCreatureAIDebug()
void ~PluginDayZCreatureAIDebug ()
Definition at line 105 of file plugindayzcreatureaidebug.c.
    {
    }
Variable Documentation
ACTIVATE_COMMAND
class DayZCreatureAnimScriptDebug ACTIVATE_COMMAND
DISABLE_AI
class DayZCreatureAnimScriptDebug DISABLE_AI
ENABLE_AI
class DayZCreatureAnimScriptDebug ENABLE_AI
INIT_DEBUG_OBJECT
class DayZCreatureAnimScriptDebug INIT_DEBUG_OBJECT
m_bAIEnabled
bool m_bAIEnabled = true
Definition at line 92 of file plugindayzcreatureaidebug.c.
Referenced by OnGUI_AIControlEdit().
m_bBulkSet
bool m_bBulkSet = false
Definition at line 95 of file plugindayzcreatureaidebug.c.
Referenced by OnGUI_BulkSet(), OnGUI_CommandsEdit(), and OnGUI_VariablesEdit().
m_bEditMode
bool m_bEditMode = false
Definition at line 91 of file plugindayzcreatureaidebug.c.
Referenced by OnGUI().
m_bIsCaptureMode
bool m_bIsCaptureMode = false
Definition at line 90 of file plugindayzcreatureaidebug.c.
Referenced by Event_OnClick(), and OnGUI().
m_bShowAnimEvents
bool m_bShowAnimEvents = false
Definition at line 93 of file plugindayzcreatureaidebug.c.
Referenced by OnGUI().
m_DebugEntity
DayZCreatureAI m_DebugEntity = NULL
Definition at line 82 of file plugindayzcreatureaidebug.c.
Referenced by EnableAI(), GUIAction_UpdateSimulationPrecision(), InitDebugObject(), and ReleaseDebugObject().
m_EntityAnimDbg
ref DayZCreatureAnimScriptDebug m_EntityAnimDbg = NULL
Definition at line 84 of file plugindayzcreatureaidebug.c.
Referenced by ActivateCommand(), GetStrValue(), GetStrValueType(), GetVariableType(), InitDebugObject(), OnGUI(), OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_Variables(), OnGUI_VariablesEdit(), ReleaseDebugObject(), SetValueBool(), SetValueFloat(), and SetValueInt().
m_iDebugMenu
class DayZCreatureAnimScriptDebug m_iDebugMenu = -1
Referenced by CheckShowMode().
m_IsActive
bool m_IsActive = false
Definition at line 87 of file plugindayzcreatureaidebug.c.
m_sDebugEntityName
string m_sDebugEntityName = ""
Definition at line 83 of file plugindayzcreatureaidebug.c.
Referenced by InitDebugObject(), OnGUI(), and ReleaseDebugObject().
m_SetCommandCheckStates
ref array<bool> m_SetCommandCheckStates = new array<bool>
Definition at line 97 of file plugindayzcreatureaidebug.c.
Referenced by InitDebugObject(), OnGUI_CommandsEdit(), and ReleaseDebugObject().
m_SetVariableCheckStates
ref array<bool> m_SetVariableCheckStates = new array<bool>
Definition at line 96 of file plugindayzcreatureaidebug.c.
Referenced by InitDebugObject(), OnGUI_VariablesEdit(), and ReleaseDebugObject().
m_ShowDbgUI
bool m_ShowDbgUI = false
Definition at line 88 of file plugindayzcreatureaidebug.c.
m_SyncMessages
ref array<ref Param> m_SyncMessages = new array<ref Param>
Definition at line 99 of file plugindayzcreatureaidebug.c.
Referenced by SendSyncMessages(), SyncActivateCommand(), SyncEnableAI(), SyncInitDebugObject(), SyncReleaseDebugObject(), SyncSetValueBool(), SyncSetValueFloat(), and SyncSetValueInt().
m_TickTimer
ref Timer m_TickTimer
Definition at line 86 of file plugindayzcreatureaidebug.c.
Referenced by Hide(), PluginBase::Hide(), PluginBase::OnDestroy(), PluginBase::OnInit(), Show(), and PluginBase::Show().
RELEASE_DEBUG_OBJECT
class DayZCreatureAnimScriptDebug RELEASE_DEBUG_OBJECT
SET_VALUE_BOOL
class DayZCreatureAnimScriptDebug SET_VALUE_BOOL
SET_VALUE_FLOAT
class DayZCreatureAnimScriptDebug SET_VALUE_FLOAT
SET_VALUE_INT
class DayZCreatureAnimScriptDebug SET_VALUE_INT