DayzKode: P:/scripts/4_world/DayZ/plugins/pluginbase/pluginpresencenotifier.c File Reference
pluginpresencenotifier.c File Reference
Classes
class PresenceNotifierNoiseEvents
Enumerations
enum EPresenceNotifierNoiseEventType { LAND_LIGHT , LAND_HEAVY }
Functions
void EnableDebug (bool pEnabled)
protected int GetBootsNoiseComponent ()
protected int GetExternalNoiseEventsComponent ()
DEPRECATED.
protected int GetMovementSpeedNoiseComponent ()
protected float GetMovementSpeedVisualCoef ()
Visibility.
protected float GetMovementStanceVisualCoef ()
int GetNoisePresence ()
returns actual noise presence of player
protected int GetSurfaceNoiseComponent ()
DEPRECATED.
float GetTimerLength ()
int GetValue ()
int GetVisualPresence ()
returns actual visibility presence of player
void Init (PlayerBase player)
void PluginPresenceNotifier ()
void PresenceNotifierNoiseEvent (float pValue, float pLength)
void ProcessEvent (EPresenceNotifierNoiseEventType pEventType)
processing of external one-time events (land, fire, etc.)
protected int ProcessNoiseComponents ()
protected int ProcessVisualComponents ()
protected void ShowCoefsDbg (bool pEnabled)
void ~PluginPresenceNotifier ()
Variables
const int LAND_NOISE_LVL1 = 2
land noise
const int LAND_NOISE_LVL2 = 3
protected PlayerBase m_pPlayer
protected ref PresenceNotifierNoiseEvents m_PresenceNotifierNoiseEvents
enum EPresenceNotifierNoiseEventType m_TimerLength
protected int m_Value
const int mainPanelSizeX = 200
const int mainPanelSizeY = 1
const int margin = 10
const int NOISE_LEVEL_MAX = 5
const int NOISE_LEVEL_MIN = 0
noise limits
const float SURFACE_LVL1_THRESHOLD = 0.5
const float SURFACE_LVL2_THRESHOLD = 1.0
const int SURFACE_NOISE_LVL0 = 0
noise component from surfaces
const int SURFACE_NOISE_LVL1 = 1
const int SURFACE_NOISE_LVL2 = 2
class PresenceNotifierNoiseEvents windowPosX = 0
dbgUI settings
const int windowPosY = 10
Enumeration Type Documentation
EPresenceNotifierNoiseEventType
enum EPresenceNotifierNoiseEventType
Enumerator
LAND_LIGHT
LAND_HEAVY
Definition at line 1 of file pluginpresencenotifier.c.
{
    LAND_LIGHT,
    LAND_HEAVY,
}
Function Documentation
EnableDebug()
void EnableDebug (bool pEnabled)
Definition at line 122 of file pluginpresencenotifier.c.
    {
        ShowCoefsDbg(pEnabled);
    }
References ShowCoefsDbg().
GetBootsNoiseComponent()
protected int GetBootsNoiseComponent ()
noise component of presence based on player's shoes DEPRECATED
GetExternalNoiseEventsComponent()
protected int GetExternalNoiseEventsComponent ()
DEPRECATED.
GetMovementSpeedNoiseComponent()
protected int GetMovementSpeedNoiseComponent ()
Noise related noise component of presence based on player's speed DEPRECATED
GetMovementSpeedVisualCoef()
protected float GetMovementSpeedVisualCoef ()
Visibility.
Definition at line 230 of file pluginpresencenotifier.c.
    {
        HumanMovementState hms  = new HumanMovementState();
        float speedCoef         = 1.0;
        m_pPlayer.GetMovementState(hms);
        //Print(hms.m_iMovement);
        switch (AITargetCallbacksPlayer.StanceToMovementIdxTranslation(hms))
        {
            case DayZPlayerConstants.MOVEMENTIDX_RUN:
                speedCoef = 0.66;
            break;
            case DayZPlayerConstants.MOVEMENTIDX_WALK:
                speedCoef = 0.33;
            break;
            case DayZPlayerConstants.MOVEMENTIDX_IDLE:
                speedCoef = 0;
            break;
        }
        return speedCoef;
    }
References m_pPlayer, and AITargetCallbacksPlayer::StanceToMovementIdxTranslation().
Referenced by ProcessVisualComponents(), and ShowCoefsDbg().
GetMovementStanceVisualCoef()
protected float GetMovementStanceVisualCoef ()
Definition at line 253 of file pluginpresencenotifier.c.
    {
        HumanMovementState hms  = new HumanMovementState();
        float stanceCoef        = 1.0;
        m_pPlayer.GetMovementState(hms);
        switch (hms.m_iStanceIdx)
        {
            case DayZPlayerConstants.STANCEIDX_CROUCH:
            case DayZPlayerConstants.STANCEIDX_RAISEDCROUCH:
                stanceCoef = 0.33;
            break;
            case DayZPlayerConstants.STANCEIDX_PRONE:
            case DayZPlayerConstants.STANCEIDX_RAISEDPRONE:
                stanceCoef = 0.11;
            break;
        }
        return stanceCoef;
    }
References HumanMovementState::m_iStanceIdx, and m_pPlayer.
Referenced by ProcessVisualComponents(), and ShowCoefsDbg().
GetNoisePresence()
int GetNoisePresence ()
returns actual noise presence of player
Definition at line 188 of file pluginpresencenotifier.c.
    {
        return ProcessNoiseComponents();
    }
References ProcessNoiseComponents().
Referenced by ShowCoefsDbg().
GetSurfaceNoiseComponent()
protected int GetSurfaceNoiseComponent ()
DEPRECATED.
GetTimerLength()
float GetTimerLength ()
Definition at line 18 of file pluginpresencenotifier.c.
    {
        return m_TimerLength;
    }
References m_TimerLength.
GetValue()
int GetValue ()
Definition at line 23 of file pluginpresencenotifier.c.
    {
        return m_Value;
    }
References m_Value.
GetVisualPresence()
int GetVisualPresence ()
returns actual visibility presence of player
Definition at line 194 of file pluginpresencenotifier.c.
    {
        return ProcessVisualComponents();
    }
References ProcessVisualComponents().
Referenced by ShowCoefsDbg().
Init()
void Init (PlayerBase player)
Definition at line 117 of file pluginpresencenotifier.c.
    {
        m_pPlayer = player;
    }
References m_pPlayer.
PluginPresenceNotifier()
void PluginPresenceNotifier ()
Definition at line 108 of file pluginpresencenotifier.c.
    {
        m_PresenceNotifierNoiseEvents = new PresenceNotifierNoiseEvents();
        m_PresenceNotifierNoiseEvents.RegisterEvent(EPresenceNotifierNoiseEventType.LAND_LIGHT, LAND_NOISE_LVL1, 0.25);
        m_PresenceNotifierNoiseEvents.RegisterEvent(EPresenceNotifierNoiseEventType.LAND_HEAVY, LAND_NOISE_LVL2, 0.25);
    }
References LAND_NOISE_LVL1, LAND_NOISE_LVL2, m_PresenceNotifierNoiseEvents, and PresenceNotifierNoiseEvents::RegisterEvent().
Referenced by ManBase::OnSelectPlayer().
PresenceNotifierNoiseEvent()
void PresenceNotifierNoiseEvent (float pValue, float pLength)
Definition at line 12 of file pluginpresencenotifier.c.
    {
        m_Value = pValue;
        m_TimerLength = pLength;
    }
References m_TimerLength, and m_Value.
Referenced by PresenceNotifierNoiseEvents::ProcessEvent(), and PresenceNotifierNoiseEvents::RegisterEvent().
ProcessEvent()
void ProcessEvent (EPresenceNotifierNoiseEventType pEventType)
processing of external one-time events (land, fire, etc.)
Definition at line 200 of file pluginpresencenotifier.c.
    {
        m_PresenceNotifierNoiseEvents.ProcessEvent(pEventType);
    }
References m_PresenceNotifierNoiseEvents, and PresenceNotifierNoiseEvents::ProcessEvent().
ProcessNoiseComponents()
protected int ProcessNoiseComponents ()
Definition at line 216 of file pluginpresencenotifier.c.
    {
        float noise = 0;
        if (m_pPlayer)
        {
            noise = NoiseAIEvaluate.GetNoiseMultiplier(m_pPlayer);
            noise = Math.Round(noise * NOISE_LEVEL_MAX);
        }
        return Math.Clamp(noise, NOISE_LEVEL_MIN, NOISE_LEVEL_MAX);
    }
References Math::Clamp(), NoiseAIEvaluate::GetNoiseMultiplier(), m_pPlayer, NOISE_LEVEL_MAX, NOISE_LEVEL_MIN, and Math::Round().
Referenced by GetNoisePresence().
ProcessVisualComponents()
protected int ProcessVisualComponents ()
Definition at line 205 of file pluginpresencenotifier.c.
    {
        float visualMean = 0;
        if (m_pPlayer)
        {
            visualMean = (m_pPlayer.GetVisibilityCoef() + GetMovementSpeedVisualCoef() + GetMovementStanceVisualCoef()) / 3;
        }
        return visualMean;
    }
References GetMovementSpeedVisualCoef(), GetMovementStanceVisualCoef(), and m_pPlayer.
Referenced by GetVisualPresence().
ShowCoefsDbg()
protected void ShowCoefsDbg (bool pEnabled)
HumanMovementState content
Definition at line 127 of file pluginpresencenotifier.c.
    {
        DbgUI.BeginCleanupScope();
        if (pEnabled && m_pPlayer)
        {
            HumanMovementState hms = new HumanMovementState();
            m_pPlayer.GetMovementState(hms);
            string visualAlertLevel;
            string noiseAlertLevel;
            DbgUI.Begin("Presence Notifier", windowPosX + 10, windowPosY);
            DbgUI.Panel("MinimumSize", mainPanelSizeX, mainPanelSizeY);
            DbgUI.Text("Visual: ");
            DbgUI.Text("Visibility: " + m_pPlayer.GetVisibilityCoef());
            DbgUI.Text("Speed: " + GetMovementSpeedVisualCoef());
            DbgUI.Text("Stance: " + GetMovementStanceVisualCoef());
            DbgUI.Spacer(10);
            DbgUI.Panel("-- Noises", mainPanelSizeX, 2);
            DbgUI.Text("Noises: ");
            DbgUI.Text("Speed:  " + NoiseAIEvaluate.GetNoiseMultiplierByPlayerSpeed(m_pPlayer));
            DbgUI.Text("Boots: " + NoiseAIEvaluate.GetNoiseMultiplierByShoes(m_pPlayer));
            DbgUI.Text("Surface: " + NoiseAIEvaluate.GetNoiseMultiplierBySurface(m_pPlayer) + " [ cfg: " + m_pPlayer.GetSurfaceNoise() + "]");
            DbgUI.Spacer(10);
            DbgUI.Panel("-- Result", mainPanelSizeX, 2);
            DbgUI.Text("Result: ");
            visualAlertLevel = "";
            for (int iv = 0; iv < GetVisualPresence(); iv++)
            {
                visualAlertLevel += "!";
            }
            DbgUI.Text("Visual level: " + GetVisualPresence() + " [" + visualAlertLevel + "]");
            noiseAlertLevel = "";
            for (int ia = 0; ia < GetNoisePresence(); ia++)
            {
                noiseAlertLevel += "!";
            }
            DbgUI.Text("Noise level: " + GetNoisePresence() + " [" + noiseAlertLevel + "]");
            DbgUI.End();
            DbgUI.Begin("HumanMovementState", windowPosX + 250, windowPosY);
            DbgUI.Panel("MinimumSize", mainPanelSizeX, mainPanelSizeY);
            DbgUI.Text("Command ID: " + hms.m_CommandTypeId);
            DbgUI.Text("Stance: " + hms.m_iStanceIdx);
            DbgUI.Text("Movement: " + hms.m_iMovement);
            DbgUI.End();
        }
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), DbgUI::EndCleanupScope(), GetMovementSpeedVisualCoef(), GetMovementStanceVisualCoef(), NoiseAIEvaluate::GetNoiseMultiplierByPlayerSpeed(), NoiseAIEvaluate::GetNoiseMultiplierByShoes(), NoiseAIEvaluate::GetNoiseMultiplierBySurface(), GetNoisePresence(), GetVisualPresence(), HumanMovementState::m_CommandTypeId, HumanMovementState::m_iMovement, HumanMovementState::m_iStanceIdx, m_pPlayer, mainPanelSizeX, mainPanelSizeY, DbgUI::Panel(), DbgUI::Spacer(), DbgUI::Text(), windowPosX, and windowPosY.
Referenced by EnableDebug().
~PluginPresenceNotifier()
void ~PluginPresenceNotifier ()
Definition at line 115 of file pluginpresencenotifier.c.
{}
Variable Documentation
LAND_NOISE_LVL1
const int LAND_NOISE_LVL1 = 2
land noise
Definition at line 99 of file pluginpresencenotifier.c.
Referenced by PluginPresenceNotifier().
LAND_NOISE_LVL2
const int LAND_NOISE_LVL2 = 3
Definition at line 100 of file pluginpresencenotifier.c.
Referenced by PluginPresenceNotifier().
m_pPlayer
protected PlayerBase m_pPlayer
Definition at line 104 of file pluginpresencenotifier.c.
m_PresenceNotifierNoiseEvents
protected ref PresenceNotifierNoiseEvents m_PresenceNotifierNoiseEvents
Definition at line 106 of file pluginpresencenotifier.c.
Referenced by PluginPresenceNotifier(), and ProcessEvent().
m_TimerLength
enum EPresenceNotifierNoiseEventType m_TimerLength
Referenced by GetTimerLength(), and PresenceNotifierNoiseEvent().
m_Value
protected int m_Value
Definition at line 10 of file pluginpresencenotifier.c.
mainPanelSizeX
const int mainPanelSizeX = 200
Definition at line 81 of file pluginpresencenotifier.c.
Referenced by OnGUI(), and ShowCoefsDbg().
mainPanelSizeY
const int mainPanelSizeY = 1
Definition at line 82 of file pluginpresencenotifier.c.
Referenced by OnGUI(), and ShowCoefsDbg().
margin
const int margin = 10
Definition at line 83 of file pluginpresencenotifier.c.
Referenced by OnGUI().
NOISE_LEVEL_MAX
const int NOISE_LEVEL_MAX = 5
Definition at line 88 of file pluginpresencenotifier.c.
Referenced by ProcessNoiseComponents().
NOISE_LEVEL_MIN
const int NOISE_LEVEL_MIN = 0
noise limits
Definition at line 87 of file pluginpresencenotifier.c.
Referenced by ProcessNoiseComponents().
SURFACE_LVL1_THRESHOLD
const float SURFACE_LVL1_THRESHOLD = 0.5
Definition at line 96 of file pluginpresencenotifier.c.
SURFACE_LVL2_THRESHOLD
const float SURFACE_LVL2_THRESHOLD = 1.0
Definition at line 95 of file pluginpresencenotifier.c.
SURFACE_NOISE_LVL0
const int SURFACE_NOISE_LVL0 = 0
noise component from surfaces
Definition at line 91 of file pluginpresencenotifier.c.
SURFACE_NOISE_LVL1
const int SURFACE_NOISE_LVL1 = 1
Definition at line 92 of file pluginpresencenotifier.c.
SURFACE_NOISE_LVL2
const int SURFACE_NOISE_LVL2 = 2
Definition at line 93 of file pluginpresencenotifier.c.
windowPosX
class PresenceNotifierNoiseEvents windowPosX = 0
dbgUI settings
Referenced by OnGUI(), and ShowCoefsDbg().
windowPosY
const int windowPosY = 10
Definition at line 80 of file pluginpresencenotifier.c.
Referenced by OnGUI(), and ShowCoefsDbg().