DayzKode: P:/scripts/4_world/DayZ/plugins/pluginbase/plugindeveloper/pluginremoteplayerdebugclient.c File Reference
pluginremoteplayerdebugclient.c File Reference
Enumerations
enum eRemoteDebugType { NONE , DAMAGE_ONLY , ALL }
Functions
void DebugDamage (PlayerBase player)
void EnableWidgets (bool enable)
void InitWidgets ()
void MergeDamage (array< ref RemotePlayerDamageDebug > delta)
override void OnInit ()
void OnRPC (ParamsReadContext ctx)
override void OnUpdate (float delta_time)
void RequestPlayerInfo (PlayerBase player, int type)
void UpdateDamageWidget (int index, PlayerBase player)
void UpdateDistanceWidget (int index, PlayerBase other_player)
void UpdateStatsWidget (int index, RemotePlayerStatDebug rpd)
void UpdateWidgetsStats ()
Variables
ref TextListboxWidget m_DamageListWidgets [MAX_SIMULTANIOUS_PLAYERS]
eRemoteDebugType m_DebugType
ref TextWidget m_DistanceWidget [MAX_SIMULTANIOUS_PLAYERS]
ref map< PlayerBase, ref RemotePlayerDamageDebug > m_PlayerDebugDamage = new map<PlayerBase,ref RemotePlayerDamageDebug>
ref array< ref RemotePlayerStatDebug > m_PlayerDebugStats = new array<ref RemotePlayerStatDebug>
ref Widget m_RootWidget [MAX_SIMULTANIOUS_PLAYERS]
ref Widget m_RootWidgetDamage [MAX_SIMULTANIOUS_PLAYERS]
ref TextListboxWidget m_StatListWidgets [MAX_SIMULTANIOUS_PLAYERS]
enum eRemoteDebugType MAX_SIMULTANIOUS_PLAYERS = 10
Enumeration Type Documentation
eRemoteDebugType
enum eRemoteDebugType
Enumerator
NONE
DAMAGE_ONLY
ALL
Definition at line 1 of file pluginremoteplayerdebugclient.c.
{
    NONE,
    DAMAGE_ONLY,
    ALL,
}
Function Documentation
DebugDamage()
void DebugDamage (PlayerBase player)
Definition at line 198 of file pluginremoteplayerdebugclient.c.
    {
        for (int i = 0; i < m_PlayerDebugStats.Count(); i++)
        {
            player = m_PlayerDebugStats.Get(i).GetPlayer();
            PrintString("player:" + player.ToString() );
            m_PlayerDebugStats.Get(i).Debug();
            PrintString("-------------------------------------");
        }
        for (i = 0; i < m_PlayerDebugDamage.Count(); i++)
        {
            PrintString("-------------------------------------");
            if( m_PlayerDebugDamage.GetElement(i) ) m_PlayerDebugDamage.GetElement(i).Debug();
            PrintString("-------------------------------------");
        }
        for (i = 0; i < m_PlayerDebugDamage.Count();i++)
        {
            PrintString("------------Debug Damage Start--------------");
            PlayerBase player2 = m_PlayerDebugDamage.GetKey(i);
            RemotePlayerDamageDebug obj = m_PlayerDebugDamage.Get(player2);
            obj.Debug();
            PrintString("-------------Debug Damage End-------------");
        }
    }
References RemotePlayerDamageDebug::Debug(), m_PlayerDebugDamage, m_PlayerDebugStats, and PrintString().
EnableWidgets()
void EnableWidgets (bool enable)
Definition at line 48 of file pluginremoteplayerdebugclient.c.
    {
        for (int i = 0; i < MAX_SIMULTANIOUS_PLAYERS; i++)
        {
            m_RootWidget[i].Show(enable);
            m_RootWidgetDamage[i].Show(enable);
        }
    }
References m_RootWidget, m_RootWidgetDamage, and MAX_SIMULTANIOUS_PLAYERS.
InitWidgets()
void InitWidgets ()
Definition at line 35 of file pluginremoteplayerdebugclient.c.
    {
        for (int i = 0; i < MAX_SIMULTANIOUS_PLAYERS; i++)
        {
            m_RootWidget[i] = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_debug_remoteinfo.layout");
            m_RootWidgetDamage[i] = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_debug_remoteinfo_damage.layout");
            m_DamageListWidgets[i] = TextListboxWidget.Cast(m_RootWidgetDamage[i].FindAnyWidget("TextListboxWidget1"));
            m_StatListWidgets[i] = TextListboxWidget.Cast(m_RootWidget[i].FindAnyWidget("TextListboxWidget0"));
            m_DistanceWidget[i] = TextWidget.Cast(m_RootWidget[i].FindAnyWidget("TextWidget0"));
        }
    }
References WorkspaceWidget::CreateWidgets(), FindAnyWidget(), GetGame(), CGame::GetWorkspace(), m_DamageListWidgets, m_DistanceWidget, m_RootWidget, m_RootWidgetDamage, m_StatListWidgets, and MAX_SIMULTANIOUS_PLAYERS.
MergeDamage()
void MergeDamage (array< ref RemotePlayerDamageDebug > delta)
Definition at line 166 of file pluginremoteplayerdebugclient.c.
    {
        for (int i = 0; i < delta.Count();i++)
        {
            RemotePlayerDamageDebug value_delta = delta.Get(i);
            PlayerBase player_delta = value_delta.GetPlayer();
            if ( m_PlayerDebugDamage.Contains(null) )
            {
                //cleans up garbage
                m_PlayerDebugDamage.Remove(null);
            }
            if ( m_PlayerDebugDamage.Contains(player_delta) )
            {
                RemotePlayerDamageDebug value_local = m_PlayerDebugDamage.Get(player_delta);
                array<ref DamageData> damage_list = new array<ref DamageData>;
                value_delta.GetReversed(damage_list);
                for (int x = 0; x < damage_list.Count(); x++)
                {
                    value_local.InsertDamageObject( damage_list.Get(x) );
                }
            }
            else
            {
                m_PlayerDebugDamage.Insert(player_delta, value_delta);
            }
        }
    }
References RemotePlayerDamageDebug::GetPlayer(), RemotePlayerDamageDebug::GetReversed(), RemotePlayerDamageDebug::InsertDamageObject(), m_PlayerDebugDamage, and x.
Referenced by OnRPC().
OnInit()
override void OnInit ()
Definition at line 21 of file pluginremoteplayerdebugclient.c.
    {
        #ifndef NO_GUI
        InitWidgets();
        #endif
    }
References PluginBase::InitWidgets().
OnRPC()
void OnRPC (ParamsReadContext ctx)
Definition at line 226 of file pluginremoteplayerdebugclient.c.
    {
        ctx.Read(m_PlayerDebugStats);
        array<ref RemotePlayerDamageDebug> player_damage = new array<ref RemotePlayerDamageDebug>;
        ctx.Read(player_damage);
        PlayerBase player;
        for (int x = 0; x < player_damage.Count(); x++)
        {
            RemotePlayerDamageDebug value = player_damage.Get(x);
            if (value)
            {
                player = value.GetPlayer();
                PrintString("debug damage: "+x.ToString() + "," + player.ToString());
                value.Debug();
                int xs = 1 + 1;
            }
        }
        if (player_damage.Count() > 0 ) MergeDamage(player_damage);
    }
References RemotePlayerDamageDebug::Debug(), RemotePlayerDamageDebug::GetPlayer(), m_PlayerDebugStats, MergeDamage(), PrintString(), Serializer::Read(), and x.
OnUpdate()
override void OnUpdate (float delta_time)
Definition at line 28 of file pluginremoteplayerdebugclient.c.
    {
        #ifndef NO_GUI
        if ( m_DebugType !=0 ) UpdateWidgetsStats();
        #endif
    }
References m_DebugType, and UpdateWidgetsStats().
RequestPlayerInfo()
void RequestPlayerInfo (PlayerBase player, int type)
Definition at line 148 of file pluginremoteplayerdebugclient.c.
    {
        if (type == 0)
        {
            EnableWidgets(false);
        }
        /*
        else
        {
            EnableWidgets(true);
        }
        */
        ScriptRPC rpc = new ScriptRPC();
        m_DebugType = type;
        rpc.Write(type);
        rpc.Send( player, ERPCs.DEV_REQUEST_PLAYER_DEBUG, true, player.GetIdentity() );
    }
References PluginBase::EnableWidgets(), m_DebugType, ScriptRPC::Send(), and Serializer::Write().
UpdateDamageWidget()
void UpdateDamageWidget (int index, PlayerBase player)
Definition at line 97 of file pluginremoteplayerdebugclient.c.
    {
        array<ref DamageData> damage_list = new array<ref DamageData>;
        if (m_PlayerDebugDamage.Contains(player))
        {
            RemotePlayerDamageDebug value = m_PlayerDebugDamage.Get(player);
            value.GetReversed(damage_list);
            m_DamageListWidgets[index].ClearItems();
            if (damage_list.Count() > 0)
            {
                m_DamageListWidgets[index].Show(true);
                for (int i = 0; i < damage_list.Count(); i++)
                {
                    float value_global = damage_list.Get(i).GetValueGlobal();
                    float value_blood = damage_list.Get(i).GetValueBlood();
                    float value_shock = damage_list.Get(i).GetValueShock();
                    m_DamageListWidgets[index].AddItem( value_global.ToString(),NULL,0,i );
                    m_DamageListWidgets[index].SetItem( i, value_blood.ToString(),NULL,1 );
                    m_DamageListWidgets[index].SetItem( i, value_shock.ToString(),NULL,2 );
                }
            }
            else
            {
                m_DamageListWidgets[index].Show(false);
            }
        }
    }
References RemotePlayerDamageDebug::GetReversed(), m_DamageListWidgets, m_PlayerDebugDamage, and float::ToString().
Referenced by UpdateWidgetsStats().
UpdateDistanceWidget()
void UpdateDistanceWidget (int index, PlayerBase other_player)
Definition at line 127 of file pluginremoteplayerdebugclient.c.
    {
        float distance = vector.Distance(GetGame().GetCurrentCameraPosition(), other_player.GetPosition());
        m_DistanceWidget[index].SetText(distance.ToString() +"m.");
    }
References vector::Distance(), GetGame(), m_DistanceWidget, and float::ToString().
Referenced by UpdateWidgetsStats().
UpdateStatsWidget()
void UpdateStatsWidget (int index, RemotePlayerStatDebug rpd)
Definition at line 133 of file pluginremoteplayerdebugclient.c.
    {
        array<string> names = new array<string>;
        array<string> values = new array<string>;
        rpd.SerializeNames(names, m_DebugType);
        rpd.SerializeValues(values,m_DebugType);
        m_StatListWidgets[index].ClearItems();
        for (int i = 0; i < names.Count(); i++)
        {
            m_StatListWidgets[index].AddItem( names.Get(i),NULL,0,i );
            m_StatListWidgets[index].SetItem( i, values.Get(i),NULL,1 );
        }
    }
References m_DebugType, and m_StatListWidgets.
Referenced by UpdateWidgetsStats().
UpdateWidgetsStats()
void UpdateWidgetsStats ()
Definition at line 57 of file pluginremoteplayerdebugclient.c.
    {
        int i = 0;
        for (; i < m_PlayerDebugStats.Count(); i++)
        {
            RemotePlayerStatDebug rpd = m_PlayerDebugStats.Get(i);
            PlayerBase player = rpd.GetPlayer();
            if (player)
            {
                vector pos = player.GetPosition();
                vector screen_pos_stats = GetGame().GetScreenPos(pos + "0 0 0");
                vector screen_pos_damage = GetGame().GetScreenPos(pos + "0 2 0");
                m_RootWidget[i].SetPos(screen_pos_stats[0],screen_pos_stats[1]);
                m_RootWidgetDamage[i].SetPos(screen_pos_damage[0],screen_pos_damage[1]);
                if (screen_pos_stats[2] > 0 && screen_pos_stats[0] > 0 && screen_pos_stats[1] > 0)
                {
                    m_RootWidget[i].Show(true);
                    m_RootWidgetDamage[i].Show(true);
                    UpdateStatsWidget(i,rpd);
                    UpdateDistanceWidget( i, player );
                    UpdateDamageWidget(i, player );
                }
                else
                {
                    m_RootWidget[i].Show(false);
                    m_RootWidgetDamage[i].Show(false);
                }
            }
        }
        for (; i < MAX_SIMULTANIOUS_PLAYERS; i++)
        {
            m_RootWidget[i].Show(false);
            m_RootWidgetDamage[i].Show(false);
        }
    }
References GetGame(), CGame::GetScreenPos(), m_PlayerDebugStats, m_RootWidget, m_RootWidgetDamage, MAX_SIMULTANIOUS_PLAYERS, RemotePlayerStatDebug(), UpdateDamageWidget(), UpdateDistanceWidget(), and UpdateStatsWidget().
Referenced by OnUpdate().
Variable Documentation
m_DamageListWidgets
ref TextListboxWidget m_DamageListWidgets[MAX_SIMULTANIOUS_PLAYERS]
Definition at line 17 of file pluginremoteplayerdebugclient.c.
Referenced by InitWidgets(), and UpdateDamageWidget().
m_DebugType
eRemoteDebugType m_DebugType
Definition at line 19 of file pluginremoteplayerdebugclient.c.
Referenced by OnUpdate(), RequestPlayerInfo(), and UpdateStatsWidget().
m_DistanceWidget
ref TextWidget m_DistanceWidget[MAX_SIMULTANIOUS_PLAYERS]
Definition at line 18 of file pluginremoteplayerdebugclient.c.
Referenced by InitializeWidgets(), InitWidgets(), OnUpdate(), and UpdateDistanceWidget().
m_PlayerDebugDamage
ref map<PlayerBase, ref RemotePlayerDamageDebug> m_PlayerDebugDamage = new map<PlayerBase,ref RemotePlayerDamageDebug>
Definition at line 12 of file pluginremoteplayerdebugclient.c.
Referenced by DebugDamage(), MergeDamage(), PluginBase::OnDamageEvent(), PluginBase::SendDebug(), and UpdateDamageWidget().
m_PlayerDebugStats
ref array<ref RemotePlayerStatDebug> m_PlayerDebugStats = new array<ref RemotePlayerStatDebug>
Definition at line 11 of file pluginremoteplayerdebugclient.c.
Referenced by DebugDamage(), PluginBase::GatherPlayerInfo(), OnRPC(), UIScriptedMenu::OnRPCEx(), PluginBase::SendDebug(), UIScriptedMenu::Update(), and UpdateWidgetsStats().
m_RootWidget
ref Widget m_RootWidget[MAX_SIMULTANIOUS_PLAYERS]
Definition at line 14 of file pluginremoteplayerdebugclient.c.
Referenced by AttachmentsWrapper::AttachmentsWrapper(), Container::CargoContainer(), CargoContainerRow::CargoContainerRow(), Container::ClosableContainer(), LayoutHolder::Container(), HandsPreview::CreateNewIcon(), HandsPreview::DeleteIcon(), EnableWidgets(), PluginBase::EnableWidgets(), ScriptedWidgetEventHandler::GetRootWidget(), HandsContainer::HandsContainer(), Icon::InitEx(), Icon::InitLock(), InitWidgets(), PluginBase::InitWidgets(), ScriptedWidgetEventHandler::IsVisible(), ScriptedWidgetEventHandler::LayoutHolder(), LeftArea::LeftArea(), ScriptedWidgetEventHandler::OnHide(), ScriptedWidgetEventHandler::OnShow(), PlayerContainer::PlayerContainer(), LeftArea::Refresh(), PlayerContainer::Refresh(), ScriptedWidgetEventHandler::Refresh(), RightArea::RightArea(), AttachmentCategoriesContainer::SetEntity(), Icon::SetTemperature(), LeftArea::UpdateInterval(), PluginBase::UpdateStatWidgets(), UpdateWidgetsStats(), VicinityContainer::VicinityContainer(), ZombieContainer::ZombieContainer(), and ScriptedWidgetEventHandler::~LayoutHolder().
m_RootWidgetDamage
ref Widget m_RootWidgetDamage[MAX_SIMULTANIOUS_PLAYERS]
Definition at line 15 of file pluginremoteplayerdebugclient.c.
Referenced by EnableWidgets(), InitWidgets(), and UpdateWidgetsStats().
m_StatListWidgets
ref TextListboxWidget m_StatListWidgets[MAX_SIMULTANIOUS_PLAYERS]
Definition at line 16 of file pluginremoteplayerdebugclient.c.
Referenced by InitWidgets(), PluginBase::InitWidgets(), UpdateStatsWidget(), and PluginBase::UpdateStatWidget().
MAX_SIMULTANIOUS_PLAYERS
enum eRemoteDebugType MAX_SIMULTANIOUS_PLAYERS = 10
Referenced by EnableWidgets(), InitWidgets(), and UpdateWidgetsStats().