DayzKode: P:/scripts/3_game/DayZ/particles/tests/pmtcreationandcleanup.c File Reference
pmtcreationandcleanup.c File Reference
Classes
class OwnershipTestDummyClass
Functions
TFResult CheckTestEvents ()
void PassCheckEvents (ParticleManager pm)
void PMTCreationAndCleanup ()
TFResult TestCCSB ()
TFResult TestCleanup (string f, int p1=0)
TFResult TestCreationSmallBlocking (int size, bool enableAsserts=true)
TFResult TestEvents ()
TFResult TestInvalidSize ()
TFResult TestMultiCreation (int instances)
TFResult TestOwnership ()
Variables
bool m_bTestEventsPassed = false
class OwnershipTestDummyClass m_EventTestManagerID
int m_OwnershipTestManagerID
Function Documentation
CheckTestEvents()
TFResult CheckTestEvents ()
Definition at line 94 of file pmtcreationandcleanup.c.
    {
        ParticleManager pm;
        if (GetManager(m_EventTestManagerID, pm))
        {
            if (pm)
            {
                if (pm.IsFinishedAllocating())
                {
                    return BTFR(Assert(m_bTestEventsPassed));
                }
            }
            else
            {
                return BTFR(Assert(false));
            }
        }
        else
        {
            return BTFR(Assert(false));
        }
        return NTFR(TFR.PENDING);
    }
References Assert(), BTFR(), PMTF::GetManager(), m_bTestEventsPassed, m_EventTestManagerID, NTFR(), and ParticleManager().
PassCheckEvents()
void PassCheckEvents (ParticleManager pm)
Definition at line 122 of file pmtcreationandcleanup.c.
    {
        Assert(pm.IsFinishedAllocating());
        m_bTestEventsPassed = true;
    }
References Assert(), and m_bTestEventsPassed.
Referenced by TestEvents().
PMTCreationAndCleanup()
void PMTCreationAndCleanup ()
Definition at line 16 of file pmtcreationandcleanup.c.
    {
        //AddInitTest("TestInvalidSize");
        AddInitTest("TestCCSB");
        AddInitTest("TestEvents");
        AddInitTest("TestOwnership");
    }
References AddInitTest().
TestCCSB()
TFResult TestCCSB ()
Definition at line 41 of file pmtcreationandcleanup.c.
    {
        return TestCleanup("TestMultiCreation", 3000);
    }
References TestCleanup().
TestCleanup()
TFResult TestCleanup (string f, int p1 = 0)
Definition at line 149 of file pmtcreationandcleanup.c.
    {
        int pmTotal = ParticleManager.GetStaticActiveCount();
        int psTotal = ParticleSource.GetStaticActiveCount();
        PrintActiveStats();
        TFResult res = CTFR();
        GetGame().GameScript.CallFunction(this, f, res, p1);
        int pmTotalPost = ParticleManager.GetStaticActiveCount();
        int psTotalPost = ParticleSource.GetStaticActiveCount();
        PrintActiveStats();
        bool success = Assert(pmTotal == pmTotalPost);
        success &= Assert(psTotal == psTotalPost);
        return res.And(BTFR(success));
    }
References Assert(), BTFR(), ScriptModule::CallFunction(), CTFR(), CGame::GameScript, GetGame(), ParticleSource::GetStaticActiveCount(), ParticleManager(), PMTF::PrintActiveStats(), and TFResult().
Referenced by TestCCSB().
TestCreationSmallBlocking()
TFResult TestCreationSmallBlocking (int size, bool enableAsserts = true)
Definition at line 131 of file pmtcreationandcleanup.c.
    {
        // Blocking, so that we can test AllocatedCount
        ParticleManager pm = CreatePMFixedBlocking(size);
        PrintPMStats(pm);
        bool success = true;
        if (enableAsserts)
        {
            success &= Assert(pm.GetPoolSize() == size);
            success &= Assert(pm.GetAllocatedCount() == size);
            success &= Assert(pm.GetEvents() != null);
        }
        return BTFR(success);
    }
References Assert(), BTFR(), PMTF::CreatePMFixedBlocking(), ParticleManager(), and PMTF::PrintPMStats().
Referenced by TestInvalidSize(), and TestMultiCreation().
TestEvents()
TFResult TestEvents ()
Definition at line 48 of file pmtcreationandcleanup.c.
    {
        ParticleManager pm = new ParticleManager(new ParticleManagerSettings(3000));
        bool success = !pm.IsFinishedAllocating(); // We need it to not be done in the same frame
        if (Assert(success))
        {
            pm.GetEvents().Event_OnAllocationEnd.Insert(PassCheckEvents);
            m_EventTestManagerID = InsertManager(pm);
            AddFrameTest("CheckTestEvents");
            return NTFR(TFR.SUCCESS);
        }
        return NTFR(TFR.FAIL);
    }
References AddFrameTest(), Assert(), PMTF::InsertManager(), m_EventTestManagerID, NTFR(), ParticleManager(), ParticleManagerSettings(), and PassCheckEvents().
TestInvalidSize()
TFResult TestInvalidSize ()
Definition at line 28 of file pmtcreationandcleanup.c.
    {
        Debug.ParticleLog("Expecting VME: Invalid size. (0)", this, "TestInvalidSize");
        TestCreationSmallBlocking(0, false);
        Debug.ParticleLog("Expecting VME: Invalid size. (-3)", this, "TestInvalidSize");
        TestCreationSmallBlocking(-3, false);
        return NTFR(TFR.SUCCESS); // No way to check if a VME popped or not...
    }
References NTFR(), Debug::ParticleLog(), and TestCreationSmallBlocking().
TestMultiCreation()
TFResult TestMultiCreation (int instances)
Definition at line 171 of file pmtcreationandcleanup.c.
    {
        TFResult res = CTFR();
        for (int i = 0; i < instances; ++i)
        {
            res.And(TestCreationSmallBlocking(1));
        }
        return res;
    }
References CTFR(), TestCreationSmallBlocking(), and TFResult().
TestOwnership()
TFResult TestOwnership ()
Definition at line 67 of file pmtcreationandcleanup.c.
    {
        ParticleManager pm = CreatePMFixedBlocking(1);
        bool success = pm.IsFinishedAllocating(); // We need it to be done in the same frame
        if (Assert(success))
        {
            m_OwnershipTestManagerID = InsertManager(pm);
            OwnershipTestDummyClass dummy = new OwnershipTestDummyClass();
            ParticleProperties pp = new ParticleProperties(GetGame().GetPlayer().GetPosition(), ParticlePropertiesFlags.NONE, null, vector.Zero, dummy);
            string particlePath = ParticleList.GetParticleFullPath(ParticleList.EXPLOSION_LANDMINE);
            bool result = Assert(pm.CreateParticleByPath(particlePath, pp) != null);
            Debug.ParticleLog("Expecting VME: All particles in pool are already used.", this, "TestOwnership");
            result &= Assert(pm.CreateParticleByPath(particlePath, pp) == null);
            delete dummy;
            result &= Assert(pm.CreateParticleByPath(particlePath, pp) != null);
            return BTFR(result);
        }
        return NTFR(TFR.FAIL);
    }
References Assert(), BTFR(), PMTF::CreatePMFixedBlocking(), ParticleList::EXPLOSION_LANDMINE, GetGame(), ParticleList::GetParticleFullPath(), GetPlayer(), GetPosition, PMTF::InsertManager(), m_OwnershipTestManagerID, NTFR(), Debug::ParticleLog(), ParticleManager(), and vector::Zero.
Variable Documentation
m_bTestEventsPassed
bool m_bTestEventsPassed = false
Definition at line 9 of file pmtcreationandcleanup.c.
Referenced by CheckTestEvents(), and PassCheckEvents().
m_EventTestManagerID
class OwnershipTestDummyClass m_EventTestManagerID
Referenced by CheckTestEvents(), and TestEvents().
m_OwnershipTestManagerID
int m_OwnershipTestManagerID
Definition at line 11 of file pmtcreationandcleanup.c.
Referenced by TestOwnership().