DayzKode: P:/scripts/3_game/DayZ/ppemanager/ppemanager.c File Reference
ppemanager.c File Reference
Classes
class PPEManagerStatic
Static component of PPE manager, used to hold the instance.
Functions
void ChangePPEMaterial (PostProcessPrioritiesCamera priority, PostProcessEffectType type, string path, bool scriptside_only)
Changes material file associated with the script material class. Will be used very rarely, mostly set in C++ anyway.
void Cleanup ()
protected void ClearMaterialUpdating ()
void DbgPrnt (string text)
bool GetExistingRequester (typename req, out PPERequesterBase ret)
Param GetPostProcessCurrentValues (int material, int parameter)
Returns current values as Param. See 'PPEConstants' file for various typedefs used.
Param GetPostProcessDefaultValues (int material, int parameter)
Returns default values as Param. See 'PPEConstants' file for various typedefs used.
protected void InitPPEManagerClassMap ()
Ordered by 'PostProcessEffectType' for easy access through the same enum; ID saved all the same.
void InsertUpdatedMaterial (int mat_id)
Marks material class as updated and values to be set in the course of update - 'ProcessApplyValueChanges'.
void PPEManager ()
protected void ProcessApplyValueChanges ()
protected void ProcessMaterialUpdates (float timeslice)
protected void ProcessRequesterUpdates (float timeslice)
protected void RegisterPPEClass (PPEClassBase material_class)
Registeres material class and creates data structure within.
protected void RemoveActiveRequestFromMaterials (PPERequesterBase req)
void RemoveMaterialUpdating (int material_id, int order=0)
Currently unused, requests remain in the hierarchy and are used when needed (slightly faster than constantly re-shuffilng the arrays)
protected void RequestsCleanup ()
Unused cleanup method, should it be ever needed.
void SendMaterialValueData (PPERequestParamDataBase data)
void SetMaterialParamUpdating (int material_id, int parameter_id, int order)
Queues material/parameter to update (once)
void SetRequestActive (PPERequesterBase request, bool active)
Marks requester as 'active'. Currently indistinguiishable from 'updating' requester, can potentially be used for intermittently updated requesters.
void SetRequestUpdating (PPERequesterBase request, bool active)
Marks requester as 'updating' and to be processed on manager update.
void StopAllEffects (int mask=0)
stops all effects of a certain kind
void Update (float timeslice)
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
Variables
class PPEManagerStatic CAMERA_ID = 0
protected ref array< ref PPERequesterBase > m_ExistingPostprocessRequests
protected bool m_ManagerInitialized
protected ref map< int, ref PPEClassBase > m_PPEClassMap
protected ref map< int, ref array< int > > m_PPEMaterialUpdateQueueMap
protected ref array< int > m_UpdatedMaterials
protected ref array< ref PPERequesterBase > m_UpdatingRequests
Function Documentation
ChangePPEMaterial()
void ChangePPEMaterial (PostProcessPrioritiesCamera priority, PostProcessEffectType type, string path, bool scriptside_only)
Changes material file associated with the script material class. Will be used very rarely, mostly set in C++ anyway.
Definition at line 341 of file ppemanager.c.
    {
        if (m_PPEClassMap.Contains(type))
        {
            PPEClassBase mat_class = m_PPEClassMap.Get(type);
            typename name = mat_class.Type();
            PPEClassBase postprocess_capsule = PPEClassBase.Cast(name.Spawn());
            postprocess_capsule.ChangeMaterialPathUsed(path);
            if (postprocess_capsule.GetMaterial() == 0x0)
            {
                Debug.Log("PPEManager | Invalid material path " + path + " used for " + name );
                return;
            }
            //m_PPEClassMap.Remove(type);
            m_PPEClassMap.Set(type,postprocess_capsule);
        }
        //can be sent script-side only to adapt to c++ options changes
        if (!scriptside_only)
            SetCameraPostProcessEffect(CAMERA_ID,priority,type,path);
    }
References CAMERA_ID, PPEClassBase::ChangeMaterialPathUsed(), PPEClassBase::GetMaterial(), Debug::Log(), m_PPEClassMap, name, path, and SetCameraPostProcessEffect().
Cleanup()
void Cleanup ()
Definition at line 70 of file ppemanager.c.
    {
        PPERequesterBank.Cleanup();
        if (m_ManagerInitialized)
        {
            m_PPEMaterialUpdateQueueMap.Clear();
            m_ExistingPostprocessRequests.Clear();
            m_UpdatingRequests.Clear();
            m_PPEClassMap.Clear();
        }
    }
References m_ExistingPostprocessRequests, m_ManagerInitialized, m_PPEClassMap, m_PPEMaterialUpdateQueueMap, and m_UpdatingRequests.
ClearMaterialUpdating()
protected void ClearMaterialUpdating ()
Definition at line 187 of file ppemanager.c.
    {
        m_PPEMaterialUpdateQueueMap.Clear();
    }
References m_PPEMaterialUpdateQueueMap.
Referenced by ProcessApplyValueChanges().
DbgPrnt()
void DbgPrnt (string text)
Definition at line 380 of file ppemanager.c.
    {
        //Debug.Log(""+text);
    }
GetExistingRequester()
bool GetExistingRequester (typename req , out PPERequesterBase ret)
Definition at line 230 of file ppemanager.c.
    {
        int idx = m_ExistingPostprocessRequests.Find(PPERequesterBank.GetRequester(req));
        if (idx > -1)
        {
            ret = m_ExistingPostprocessRequests.Get(idx);
            return true;
        }
        return false;
    }
References m_ExistingPostprocessRequests.
GetPostProcessCurrentValues()
Param GetPostProcessCurrentValues (int material, int parameter)
Returns current values as Param. See 'PPEConstants' file for various typedefs used.
Definition at line 332 of file ppemanager.c.
    {
        PPEClassBase mat_class = m_PPEClassMap.Get(material);
        return mat_class.GetParameterCommandData(parameter).GetCurrentValues();
    }
References PPEMatClassParameterCommandData::GetCurrentValues(), PPEClassBase::GetParameterCommandData(), and m_PPEClassMap.
GetPostProcessDefaultValues()
Param GetPostProcessDefaultValues (int material, int parameter)
Returns default values as Param. See 'PPEConstants' file for various typedefs used.
Definition at line 325 of file ppemanager.c.
    {
        PPEClassBase mat_class = m_PPEClassMap.Get(material);
        return mat_class.GetParameterCommandData(parameter).GetDefaultValues();
    }
References PPEMatClassParameterCommandData::GetDefaultValues(), PPEClassBase::GetParameterCommandData(), and m_PPEClassMap.
Init()
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
Definition at line 84 of file ppemanager.c.
    {
        //DbgPrnt("PPEDebug | PPEManager | m_ManagerInitialized: " + m_ManagerInitialized);
        if (!m_ManagerInitialized)
        {
            m_PPEMaterialUpdateQueueMap = new map<int, ref array<int>>;
            m_UpdatedMaterials = new array<int>;
            m_ExistingPostprocessRequests = new array<ref PPERequesterBase>;
            m_UpdatingRequests = new array<ref PPERequesterBase>;
            InitPPEManagerClassMap();
            GetGame().GetUpdateQueue(CALL_CATEGORY_GUI).Insert(this.Update); //can be safely and easily 'disabled' here
            m_ManagerInitialized = true;
        }
    }
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), InitPPEManagerClassMap(), ScriptInvoker::Insert(), m_ExistingPostprocessRequests, m_ManagerInitialized, m_PPEMaterialUpdateQueueMap, m_UpdatedMaterials, m_UpdatingRequests, and Update().
Referenced by ClockBase(), DayZPlayerImplementMeleeCombat(), DayZPlayerMeleeFightLogic_LightHeavy(), Environment::Environment(), FireworksBase(), Land_Underground_WaterReservoir(), Link< Class T >::Link(), LoginQueueBase::LoginQueueStatic(), LoginTimeBase::LoginTimeStatic(), ModifiersManager(), NotifiersManager(), ManBase::PlayerBase(), PlayerStats::PlayerStats(), PPEClassBase::PPEClassBase(), RemotePlayerStatDebug(), StaminaHandler(), UniversalTemperatureSourceDebug::UniversalTemperatureSource(), and DayZInfected::ZombieBase().
InitPPEManagerClassMap()
protected void InitPPEManagerClassMap ()
Ordered by 'PostProcessEffectType' for easy access through the same enum; ID saved all the same.
Definition at line 101 of file ppemanager.c.
    {
        if (m_PPEClassMap)
        {
            delete m_PPEClassMap;
        }
        m_PPEClassMap = new map<int, ref PPEClassBase>;
        RegisterPPEClass(new PPENone()); //dummy
        RegisterPPEClass(new PPEUnderWater());
        RegisterPPEClass(new PPESSAO());
        RegisterPPEClass(new PPEDepthOfField());
        RegisterPPEClass(new PPEHBAO());
        RegisterPPEClass(new PPERotBlur());
        RegisterPPEClass(new PPEGodRays());
        RegisterPPEClass(new PPERain());
        RegisterPPEClass(new PPEFilmGrain());
        RegisterPPEClass(new PPERadialBlur());
        RegisterPPEClass(new PPEChromAber());
        RegisterPPEClass(new PPEWetDistort());
        RegisterPPEClass(new PPEDynamicBlur());
        RegisterPPEClass(new PPEColorGrading());
        RegisterPPEClass(new PPEColors());
        RegisterPPEClass(new PPEGlow());
        RegisterPPEClass(new PPESMAA());
        RegisterPPEClass(new PPEFXAA());
        RegisterPPEClass(new PPEMedian());
        RegisterPPEClass(new PPESunMask());
        RegisterPPEClass(new PPEGaussFilter());
        RegisterPPEClass(new PPEExposureNative());
        RegisterPPEClass(new PPEEyeAccomodationNative());
        RegisterPPEClass(new PPEDOF());
        RegisterPPEClass(new PPELightIntensityParamsNative());
    }
References m_PPEClassMap, and RegisterPPEClass().
Referenced by Init().
InsertUpdatedMaterial()
void InsertUpdatedMaterial (int mat_id)
Marks material class as updated and values to be set in the course of update - 'ProcessApplyValueChanges'.
Definition at line 263 of file ppemanager.c.
    {
        if ( m_UpdatedMaterials.Find(mat_id) == -1 )
            m_UpdatedMaterials.Insert(mat_id);
    }
References m_UpdatedMaterials.
PPEManager()
void PPEManager ()
Definition at line 64 of file ppemanager.c.
    {
        m_ManagerInitialized = false;
        PPERequesterBank.Init();
    }
References m_ManagerInitialized.
Referenced by PPEManagerStatic::CreateManagerStatic().
ProcessApplyValueChanges()
protected void ProcessApplyValueChanges ()
Definition at line 299 of file ppemanager.c.
    {
        int material_id;
        for (int i = 0; i < m_UpdatedMaterials.Count(); i++)
        {
            material_id = m_UpdatedMaterials.Get(i);
            PPEClassBase mat_class = m_PPEClassMap.Get(material_id);
            mat_class.ApplyValueChanges();
        }
        m_UpdatedMaterials.Clear();
        ClearMaterialUpdating();
    }
References PPEClassBase::ApplyValueChanges(), ClearMaterialUpdating(), m_PPEClassMap, and m_UpdatedMaterials.
Referenced by Update().
ProcessMaterialUpdates()
protected void ProcessMaterialUpdates (float timeslice)
Definition at line 284 of file ppemanager.c.
    {
        for (int i = 0; i < m_PPEMaterialUpdateQueueMap.Count(); i++) //orders (levels?)
        {
            //DbgPrnt("PPEDebug | ProcessMaterialUpdates | GetKey " + i + ": " + m_PPEMaterialUpdateQueueMap.GetKey(i));
            //DbgPrnt("PPEDebug | ProcessMaterialUpdates | GetElement - count " + i + ": " + m_PPEMaterialUpdateQueueMap.GetElement(i).Count());
            for (int j = 0; j < m_PPEMaterialUpdateQueueMap.GetElement(i).Count(); j++)
            {
                PPEClassBase mat_class = m_PPEClassMap.Get(m_PPEMaterialUpdateQueueMap.GetElement(i).Get(j));
                mat_class.OnUpdate(timeslice,i);
            }
        }
    }
References Count, m_PPEClassMap, m_PPEMaterialUpdateQueueMap, and PPEClassBase::OnUpdate().
Referenced by Update().
ProcessRequesterUpdates()
protected void ProcessRequesterUpdates (float timeslice)
Definition at line 272 of file ppemanager.c.
    {
        PPERequesterBase req;
        for (int i = 0; i < m_UpdatingRequests.Count(); i++)
        {
            //DbgPrnt("PPEDebug | ProcessRequesterUpdates | m_UpdatingRequests[i]: " + m_UpdatingRequests[i]);
            req = m_UpdatingRequests.Get(i);
            if (req)
                req.OnUpdate(timeslice);
        }
    }
References m_UpdatingRequests, and PPERequesterBase::OnUpdate().
Referenced by Update().
RegisterPPEClass()
protected void RegisterPPEClass (PPEClassBase material_class)
Registeres material class and creates data structure within.
Definition at line 137 of file ppemanager.c.
    {
        m_PPEClassMap.Set(material_class.GetPostProcessEffectID(), material_class);
    }
References PPEClassBase::GetPostProcessEffectID(), and m_PPEClassMap.
Referenced by InitPPEManagerClassMap().
RemoveActiveRequestFromMaterials()
protected void RemoveActiveRequestFromMaterials (PPERequesterBase req)
/brief Originally designed to rip the requester data from all relevant mat/params, but that proved too costly and volatile. /note Still, it is here, use at your own peril.
Definition at line 245 of file ppemanager.c.
    {
        int count = req.GetActiveRequestStructure().Count();
        int mat_id;
        for (int i = 0; i < count; i++)
        {
            mat_id = req.GetActiveRequestStructure().GetKey(i);
            PPEClassBase mat_class = m_PPEClassMap.Get(mat_id);
            mat_class.RemoveRequest(req.GetRequesterIDX());
        }
    }
References PPERequesterBase::GetActiveRequestStructure(), PPERequesterBase::GetRequesterIDX(), m_PPEClassMap, and PPEClassBase::RemoveRequest().
RemoveMaterialUpdating()
void RemoveMaterialUpdating (int material_id, int order = 0)
Currently unused, requests remain in the hierarchy and are used when needed (slightly faster than constantly re-shuffilng the arrays)
Definition at line 176 of file ppemanager.c.
    {
        if ( m_PPEMaterialUpdateQueueMap.Contains(order) )
        {
            m_PPEMaterialUpdateQueueMap.Get(order).RemoveItem(material_id);
            if ( m_PPEMaterialUpdateQueueMap.Get(order).Count() == 0)
                m_PPEMaterialUpdateQueueMap.Remove(order);
        }
    }
References m_PPEMaterialUpdateQueueMap.
RequestsCleanup()
protected void RequestsCleanup ()
Unused cleanup method, should it be ever needed.
Definition at line 258 of file ppemanager.c.
    {
    }
Referenced by Update().
SendMaterialValueData()
void SendMaterialValueData (PPERequestParamDataBase data)
Definition at line 142 of file ppemanager.c.
    {
        //DbgPrnt("DataVerification | m_ColorTarget | SendMaterialValueData: " + PPERequestParamDataColor.Cast(data).m_ColorTarget[0] + "/" + PPERequestParamDataColor.Cast(data).m_ColorTarget[1] + "/" + PPERequestParamDataColor.Cast(data).m_ColorTarget[2] + "/" + PPERequestParamDataColor.Cast(data).m_ColorTarget[3]);
        PPEClassBase mat_class = m_PPEClassMap.Get(data.GetMaterialID());
        mat_class.InsertParamValueData(data);
        SetMaterialParamUpdating(data.GetMaterialID(),data.GetParameterID(),PPEConstants.DEPENDENCY_ORDER_BASE);
    }
References PPERequestParamDataBase::GetMaterialID(), PPERequestParamDataBase::GetParameterID(), PPEClassBase::InsertParamValueData(), m_PPEClassMap, and SetMaterialParamUpdating().
SetMaterialParamUpdating()
void SetMaterialParamUpdating (int material_id, int parameter_id, int order)
Queues material/parameter to update (once)
Definition at line 151 of file ppemanager.c.
    {
        if ( order > PPEConstants.DEPENDENCY_ORDER_HIGHEST )
        {
            //DbgPrnt("PPEDebug | PPEManager - SetMaterialParamUpdating | Order higher than max, ignoring! | mat/par/ord: " + material_id + "/" + parameter_id + "/" + order);
            return;
        }
        PPEClassBase mat_class = m_PPEClassMap.Get(material_id);
        //DbgPrnt("PPEDebug | PPEManager - SetMaterialParamUpdating | mat/par: " + material_id + "/" + parameter_id);
        //insert material into queue
        if ( !m_PPEMaterialUpdateQueueMap.Contains(order) )
            m_PPEMaterialUpdateQueueMap.Set(order,new array<int>);
        int found = m_PPEMaterialUpdateQueueMap.Get(order).Find(material_id);
        if ( found == -1 )
        {
            m_PPEMaterialUpdateQueueMap.Get(order).Insert(material_id);
        }
        mat_class.SetParameterUpdating(order,parameter_id);
    }
References m_PPEClassMap, m_PPEMaterialUpdateQueueMap, and PPEClassBase::SetParameterUpdating().
Referenced by SendMaterialValueData().
SetRequestActive()
void SetRequestActive (PPERequesterBase request, bool active)
Marks requester as 'active'. Currently indistinguiishable from 'updating' requester, can potentially be used for intermittently updated requesters.
Definition at line 193 of file ppemanager.c.
    {
        int found = m_ExistingPostprocessRequests.Find(request);
        if ( active && found == -1 )
        {
            m_ExistingPostprocessRequests.Insert(request);
        }
        else if ( !active && found > -1 ) //should always be found in this case, redundant?
        {
            //RemoveActiveRequestFromMaterials(request);
            m_ExistingPostprocessRequests.Remove(found);
        }
    }
References m_ExistingPostprocessRequests.
SetRequestUpdating()
void SetRequestUpdating (PPERequesterBase request, bool active)
Marks requester as 'updating' and to be processed on manager update.
Definition at line 209 of file ppemanager.c.
    {
        if (!m_UpdatingRequests)
        {
            Debug.Log("PPEManager | SetRequestUpdating | !m_UpdatingRequests");
            return;
        }
        int idx = m_UpdatingRequests.Find(request);
        if ( active && idx == -1 )
        {
            m_UpdatingRequests.Insert(request);
        }
        else if ( !active && idx > -1 )
        {
            m_UpdatingRequests.Remove(idx);
        }
    }
References Debug::Log(), and m_UpdatingRequests.
StopAllEffects()
void StopAllEffects (int mask = 0)
stops all effects of a certain kind
Definition at line 366 of file ppemanager.c.
    {
        if (m_ExistingPostprocessRequests)
        {
            foreach (PPERequesterBase requester : m_ExistingPostprocessRequests)
            {
                if (requester.GetCategoryMask() & mask)
                {
                    requester.Stop();
                }
            }
        }
    }
References m_ExistingPostprocessRequests.
Update()
void Update (float timeslice)
Definition at line 313 of file ppemanager.c.
    {
        if (!m_ManagerInitialized)
            return;
        ProcessRequesterUpdates(timeslice);
        ProcessMaterialUpdates(timeslice);
        ProcessApplyValueChanges();
        RequestsCleanup(); //unused
    }
References m_ManagerInitialized, ProcessApplyValueChanges(), ProcessMaterialUpdates(), ProcessRequesterUpdates(), and RequestsCleanup().
Variable Documentation
CAMERA_ID
class PPEManagerStatic CAMERA_ID = 0
/brief Postprocess manager, responsible for updates, receiving, and re-distributing requester data to their respective destinations. /par Basic post process flow outline: Getting a registered 'PPERequester' instance from the 'PPERequesterBank'
/par Launching the requester, either through an overriden 'Start' method, or custom method with some setters (both flag it as active and to be processed)
/par On render update, PPEManager: Handles queued requester changes, re-distributes individual commands to material structure
/par
Updates the material/parameter structure and calculates the blend values
/par
Sets the final values via native functions (only called once per changed parameter - optimization stonks)
/note Requester serves as a centralized platform for specific effec/group of effects. Although technically the direct commands to mat/param would be feasible, this allows for easier control of effect groups, /note and clearer command hierarchy (no value setters without clear parentage).
Referenced by ChangePPEMaterial().
m_ExistingPostprocessRequests
protected ref array<ref PPERequesterBase> m_ExistingPostprocessRequests
Definition at line 61 of file ppemanager.c.
Referenced by Cleanup(), GetExistingRequester(), Init(), SetRequestActive(), and StopAllEffects().
m_ManagerInitialized
protected bool m_ManagerInitialized
Definition at line 57 of file ppemanager.c.
Referenced by Cleanup(), Init(), PPEManager(), and Update().
m_PPEClassMap
protected ref map<int, ref PPEClassBase> m_PPEClassMap
Definition at line 58 of file ppemanager.c.
Referenced by ChangePPEMaterial(), Cleanup(), GetPostProcessCurrentValues(), GetPostProcessDefaultValues(), InitPPEManagerClassMap(), ProcessApplyValueChanges(), ProcessMaterialUpdates(), RegisterPPEClass(), RemoveActiveRequestFromMaterials(), SendMaterialValueData(), and SetMaterialParamUpdating().
m_PPEMaterialUpdateQueueMap
protected ref map<int, ref array<int> > m_PPEMaterialUpdateQueueMap
Definition at line 59 of file ppemanager.c.
Referenced by Cleanup(), ClearMaterialUpdating(), Init(), ProcessMaterialUpdates(), RemoveMaterialUpdating(), and SetMaterialParamUpdating().
m_UpdatedMaterials
protected ref array<int> m_UpdatedMaterials
Definition at line 60 of file ppemanager.c.
Referenced by Init(), InsertUpdatedMaterial(), and ProcessApplyValueChanges().
m_UpdatingRequests
protected ref array<ref PPERequesterBase> m_UpdatingRequests
Definition at line 62 of file ppemanager.c.
Referenced by Cleanup(), Init(), ProcessRequesterUpdates(), and SetRequestUpdating().