DayzKode: P:/scripts/3_game/DayZ/ppemanager/materials/matparameters/ppematclassparameterfloat.c File Reference
ppematclassparameterfloat.c File Reference
Classes
class PPEMatClassParameterCommandData
Functions
override int GetParameterVarType ()
override void InitCuttent ()
override void InitDefaults ()
void PPEMatClassParameterFloat (int mat_idx, int parameter_idx, PPEClassBase parent)
class PPEMatClassParameterFloat extends PPEMatClassParameterCommandData PPEMatClassParameterFloatSaturation (int mat_idx, int parameter_idx, PPEClassBase parent)
void PrepareLayerInfo (int layer, float value, int operator)
override void SetParameterValueDefault (inout Param p_total)
No active requests for the mat. parameter value change, sets the value to DEFAULT (zero?)
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
Variables
protected PPETemplateDefFloat m_Float
protected ref map< int, ref array< float, int > > m_LayerInfo
protected float m_ValueDefault
protected float m_ValueMax
protected float m_ValueMin
Function Documentation
GetParameterVarType()
override int PPEMatClassParameterFloatSaturation::GetParameterVarType ()
Definition at line 271 of file ppematclassparameterfloat.c.
InitCuttent()
override void PPEMatClassParameterFloatSaturation::InitCuttent ()
Definition at line 266 of file ppematclassparameterfloat.c.
InitDefaults()
override void PPEMatClassParameterFloatSaturation::InitDefaults ()
Definition at line 257 of file ppematclassparameterfloat.c.
PPEMatClassParameterFloat()
void PPEMatClassParameterFloatSaturation::PPEMatClassParameterFloat (int mat_idx, int parameter_idx, PPEClassBase parent)
Definition at line 252 of file ppematclassparameterfloat.c.
Referenced by PPEClassBase::RegisterParameterScalarFloat(), and PPEClassBase::RegisterParameterScalarFloatEx().
PPEMatClassParameterFloatSaturation()
class PPEMatClassParameterFloat extends PPEMatClassParameterCommandData PPEMatClassParameterFloatSaturation (int mat_idx, int parameter_idx, PPEClassBase parent)
Definition at line 1 of file ppematclassparameterfloat.c.
    {
        m_Dependencies = new map<int,ref array<int>>;
        m_Dependencies.Set(PostProcessEffectType.Glow,{PPEGlow.PARAM_COLORIZATIONCOLOR, PPEGlow.PARAM_OVERLAYCOLOR});
    }
Referenced by PPEColors::RegisterMaterialParameters(), and PPEGlow::RegisterMaterialParameters().
PrepareLayerInfo()
void PPEMatClassParameterFloatSaturation::PrepareLayerInfo (int layer, float value, int operator)
Definition at line 469 of file ppematclassparameterfloat.c.
SetParameterValueDefault()
override void PPEMatClassParameterFloatSaturation::SetParameterValueDefault (inout Param p_total)
No active requests for the mat. parameter value change, sets the value to DEFAULT (zero?)
Definition at line 476 of file ppematclassparameterfloat.c.
Update()
override void PPEMatClassParameterFloatSaturation::Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
Definition at line 276 of file ppematclassparameterfloat.c.
Variable Documentation
m_Float
protected PPETemplateDefFloat m_Float
Definition at line 247 of file ppematclassparameterfloat.c.
Referenced by PPEMatClassParameterCommandData::InitDefaults().
m_LayerInfo
protected ref map<int,ref array<float,int> > m_LayerInfo
Definition at line 245 of file ppematclassparameterfloat.c.
m_ValueDefault
protected float m_ValueDefault
Definition at line 248 of file ppematclassparameterfloat.c.
Referenced by PPEMatClassParameterCommandData::InitCuttent(), PPEMatClassParameterCommandData::InitDefaults(), and PPEMatClassParameterCommandData::Update().
m_ValueMax
protected float m_ValueMax
Definition at line 250 of file ppematclassparameterfloat.c.
Referenced by PPEMatClassParameterCommandData::InitDefaults(), and PPEMatClassParameterCommandData::Update().
m_ValueMin
protected float m_ValueMin
Definition at line 249 of file ppematclassparameterfloat.c.
Referenced by PPEMatClassParameterCommandData::InitDefaults(), and PPEMatClassParameterCommandData::Update().