DayzKode: P:/scripts/3_game/DayZ/ppemanager/requesters/pperequestplatformsbase.c File Reference
pperequestplatformsbase.c File Reference
Classes
class PPERequesterBase
Functions
protected void ClearRequesterData ()
void DbgPrnt (string text)
map< int, ref map< int, ref PPERequestParamDataBase > > GetActiveRequestStructure ()
class PPERequesterBase GetCategoryMask ()
mask for mass-handling methods like 'StopAllEffects'
PPERequestParamDataBase GetRequestData (int mat_id, int param_idx, int type)
returns request data for specific parameter, or creates one if one does not exist in this request yet (singletons)
int GetRequesterIDX ()
Returns requester index.
bool IsRequesterRunning ()
protected void OnStart (Param par=null)
protected void OnStop (Param par=null)
automatically resets all material parameters of this requester to defaults
void OnUpdate (float delta)
void PPERequesterBase (int requester_IDX)
protected PPERequestParamDataBase PrepareData (int mat_id, int param_idx, int type)
protected void QueueValuesSend ()
Sets this requester to update in the manager.
protected float RelativizeValue (float value, int var_type, int mat_id, int param_id, bool relative)
converts all values used to relative values (if not relative already)
protected void SendCurrentValueData (PPERequestParamDataBase data)
protected void SetDefaultValuesAll ()
Sets all requested values to default, ignoring them in further calculations.
void SetRequesterIDX (int idx)
automatically assigned by PPERequesterBank
void SetRequesterUpdating (bool state)
Has to be set for the requester to be handled.
protected void SetTargetValueBool (int mat_id, int param_idx, bool val, int priority_layer, int operator=PPOperators.SET)
protected void SetTargetValueBoolDefault (int mat_id, int param_idx)
protected void SetTargetValueColor (int mat_id, int param_idx, ref array< float > val, int priority_layer, int operator=PPOperators.ADD_RELATIVE)
protected void SetTargetValueColorDefault (int mat_id, int param_idx)
protected void SetTargetValueFloat (int mat_id, int param_idx, bool relative, float val, int priority_layer, int operator=PPOperators.ADD_RELATIVE)
protected void SetTargetValueFloatDefault (int mat_id, int param_idx)
protected void SetTargetValueInt (int mat_id, int param_idx, bool relative, int val, int priority_layer, int operator=PPOperators.SET)
protected void SetTargetValueIntDefault (int mat_id, int param_idx)
void Start (Param par=null)
void Stop (Param par=null)
Variables
protected int m_IDX
protected bool m_IsRunning
protected ref map< int, ref map< int, ref PPERequestParamDataBase > > m_RequestDataStructure
protected bool m_Valid = false
protected bool m_ValuesSent
Function Documentation
ClearRequesterData()
protected void GetCategoryMask::ClearRequesterData ()
Definition at line 757 of file pperequestplatformsbase.c.
DbgPrnt()
void GetCategoryMask::DbgPrnt (string text)
Definition at line 857 of file pperequestplatformsbase.c.
GetActiveRequestStructure()
map< int, ref map< int, ref PPERequestParamDataBase > > GetCategoryMask::GetActiveRequestStructure ()
Definition at line 752 of file pperequestplatformsbase.c.
GetCategoryMask()
int GetCategoryMask ()
mask for mass-handling methods like 'StopAllEffects'
Definition at line 1 of file pperequestplatformsbase.c.
    {
        return PPERequesterCategory.GAMEPLAY_EFFECTS;
    }
GetRequestData()
PPERequestParamDataBase GetCategoryMask::GetRequestData (int mat_id, int param_idx, int type)
returns request data for specific parameter, or creates one if one does not exist in this request yet (singletons)
Definition at line 694 of file pperequestplatformsbase.c.
GetRequesterIDX()
int GetCategoryMask::GetRequesterIDX ()
Returns requester index.
Definition at line 498 of file pperequestplatformsbase.c.
IsRequesterRunning()
bool GetCategoryMask::IsRequesterRunning ()
Definition at line 486 of file pperequestplatformsbase.c.
OnStart()
override protected void OnStart (Param par = null)
Definition at line 787 of file pperequestplatformsbase.c.
Referenced by Start().
OnStop()
protected void GetCategoryMask::OnStop (Param par = null)
automatically resets all material parameters of this requester to defaults
Definition at line 793 of file pperequestplatformsbase.c.
OnUpdate()
void GetCategoryMask::OnUpdate (float delta)
Definition at line 769 of file pperequestplatformsbase.c.
PPERequesterBase()
void GetCategoryMask::PPERequesterBase (int requester_IDX)
Definition at line 445 of file pperequestplatformsbase.c.
    {
        return PPERequesterCategory.MENU_EFFECTS;
    }
}
PrepareData()
protected PPERequestParamDataBase GetCategoryMask::PrepareData (int mat_id, int param_idx, int type)
Definition at line 727 of file pperequestplatformsbase.c.
QueueValuesSend()
protected void GetCategoryMask::QueueValuesSend ()
Sets this requester to update in the manager.
Definition at line 686 of file pperequestplatformsbase.c.
RelativizeValue()
protected float GetCategoryMask::RelativizeValue (float value, int var_type, int mat_id, int param_id, bool relative)
converts all values used to relative values (if not relative already)
Definition at line 801 of file pperequestplatformsbase.c.
SendCurrentValueData()
protected void GetCategoryMask::SendCurrentValueData (PPERequestParamDataBase data)
Definition at line 762 of file pperequestplatformsbase.c.
SetDefaultValuesAll()
protected void GetCategoryMask::SetDefaultValuesAll ()
Sets all requested values to default, ignoring them in further calculations.
Definition at line 821 of file pperequestplatformsbase.c.
SetRequesterIDX()
void GetCategoryMask::SetRequesterIDX (int idx)
automatically assigned by PPERequesterBank
Definition at line 492 of file pperequestplatformsbase.c.
SetRequesterUpdating()
void GetCategoryMask::SetRequesterUpdating (bool state)
Has to be set for the requester to be handled.
Definition at line 456 of file pperequestplatformsbase.c.
SetTargetValueBool()
protected void GetCategoryMask::SetTargetValueBool (int mat_id, int param_idx, bool val, int priority_layer, int operator = PPOperators.SET)
Definition at line 511 of file pperequestplatformsbase.c.
Referenced by PPERequester_GameplayBase::SetValuesIronsights().
SetTargetValueBoolDefault()
protected void GetCategoryMask::SetTargetValueBoolDefault (int mat_id, int param_idx)
Definition at line 533 of file pperequestplatformsbase.c.
Referenced by PPERequester_GameplayBase::SetValuesOptics().
SetTargetValueColor()
protected void GetCategoryMask::SetTargetValueColor (int mat_id, int param_idx, ref array< float > val, int priority_layer, int operator = PPOperators.ADD_RELATIVE)
Definition at line 630 of file pperequestplatformsbase.c.
Referenced by PPERequester_GameplayBase::OnStart(), PPERequester_GameplayBase::OnUpdate(), PPERequester_GameplayBase::SetFlashbangIntensity(), PPERequester_GameplayBase::SetHitIntensity(), PPERequester_GameplayBase::SetNVMode(), and PPERequester_MenuBase::SetVignetteIntensity().
SetTargetValueColorDefault()
protected void GetCategoryMask::SetTargetValueColorDefault (int mat_id, int param_idx)
Definition at line 654 of file pperequestplatformsbase.c.
SetTargetValueFloat()
protected void GetCategoryMask::SetTargetValueFloat (int mat_id, int param_idx, bool relative, float val, int priority_layer, int operator = PPOperators.ADD_RELATIVE)
Definition at line 588 of file pperequestplatformsbase.c.
Referenced by PPERequester_GameplayBase::OnStart(), PPERequester_MenuBase::OnStart(), PPERequester_GameplayBase::OnUpdate(), PPERequester_GameplayBase::SetBloodLossLevel(), PPERequester_MenuBase::SetBlurIntensity(), PPERequester_GameplayBase::SetEyeAccommodation(), PPERequester_GameplayBase::SetFeverIntensity(), PPERequester_GameplayBase::SetFlashbangIntensity(), PPERequester_GameplayBase::SetHitIntensity(), PPERequester_GameplayBase::SetNVMode(), PPERequester_GameplayBase::SetRadialBlur(), PPERequester_GameplayBase::SetValuesIronsights(), PPERequester_GameplayBase::SetValuesOptics(), and PPERequester_MenuBase::SetVignetteIntensity().
SetTargetValueFloatDefault()
protected void GetCategoryMask::SetTargetValueFloatDefault (int mat_id, int param_idx)
Definition at line 611 of file pperequestplatformsbase.c.
Referenced by PPERequester_GameplayBase::SetNVMode(), and PPERequester_GameplayBase::SetValuesIronsights().
SetTargetValueInt()
protected void GetCategoryMask::SetTargetValueInt (int mat_id, int param_idx, bool relative, int val, int priority_layer, int operator = PPOperators.SET)
Definition at line 550 of file pperequestplatformsbase.c.
SetTargetValueIntDefault()
protected void GetCategoryMask::SetTargetValueIntDefault (int mat_id, int param_idx)
Definition at line 571 of file pperequestplatformsbase.c.
Start()
void GetCategoryMask::Start (Param par = null)
Definition at line 471 of file pperequestplatformsbase.c.
Stop()
void GetCategoryMask::Stop (Param par = null)
Definition at line 477 of file pperequestplatformsbase.c.
Variable Documentation
m_IDX
protected int m_IDX
Definition at line 439 of file pperequestplatformsbase.c.
m_IsRunning
protected bool m_IsRunning
Definition at line 437 of file pperequestplatformsbase.c.
Referenced by PPERequester_GameplayBase::OnStart(), PPERequester_GameplayBase::OnUpdate(), PPERequester_GameplayBase::SetUndergroundExposureCoef(), Managed::StartRunningDrops(), Managed::StopIndicator(), and Managed::Update().
m_RequestDataStructure
protected ref map<int,ref map<int,ref PPERequestParamDataBase> > m_RequestDataStructure
Definition at line 443 of file pperequestplatformsbase.c.
m_Valid
protected bool m_Valid = false
Definition at line 441 of file pperequestplatformsbase.c.
m_ValuesSent
protected bool m_ValuesSent
Definition at line 438 of file pperequestplatformsbase.c.