DayzKode: P:/scripts/1_core/DayZ/proto/proto.c File Reference
proto.c File Reference
Classes
class AnimEvent
class Link< Class T >
class Material
class PacketInputAdapter
class SoundEvent
class vobject
Typedefs
typedef int[] vobject
Functions
proto native int GetFPS ()
proto native void MakeScreenshot (string name)
proto native IEntitySource ToEntitySource ()
class vobject WriteBool (bool value)
proto native void WriteFloat (float value)
proto native void WriteFloatAsByte (float value, float min, float max)
proto native void WriteFloatAsHalf (float value, float min, float max)
proto native void WriteInt (int value)
proto native void WriteIntAsByte (int value)
proto native void WriteIntAsHalf (int value)
proto native void WriteIntAsUByte (int value)
proto native void WriteIntAsUHalf (int value)
proto native void WriteMatrixAsQuaternionVector (vector mat[4])
proto native void WriteString (string value)
proto native void WriteVector (vector value)
SkyDome API
proto native int InitSky (string presetName)
proto native int LerpSkyPreset (string presetName1, string presetName2, float dayTime, float stormy1, float stormy2, float lerpVal)
proto native int LerpSkyPreset3 (string presetName1, string presetName2, string presetName3, float dayTime, float stormy1, float stormy2, float stormy3, float w1, float w2, float w3)
proto native int LoadSkyPresets (string presetsFile)
proto native void SetNightLayerRotMatrix (vector mat[3])
proto native void SetRealStarAutoUpdate (bool update)
proto native bool SetSkyPlanet (int index, float azimuthDeg, float zenithDeg)
proto native bool SetSkyPlanetSize (int index, float angleDeg)
proto native int SetSkyPreset (string presetName, float stormy, float dayTime)
proto native void SetSkyUserPlanets (bool enabled)
proto native void SetStarsObserverPosition (float latitudeDeg, float longitudeDeg)
proto native void SetStarsObserverTime (int year, int month, int day, int hour, int minute, float sec, int offsetSec)
proto native void SetStarsRotMatrix (vector mat[3])
Variables
class PacketInputAdapter WriteBool
Materials API
int ARGB (int a, int r, int g, int b)
int ARGBF (float fa, float fr, float fg, float fb)
Converts <0.0, 1.0> ARGB into color.
int AWHITE (int a)
int LerpARGB (int c1, int c2)
typedef int[] Material
int VectortoRGBA (vector vec, float h)
Typedef Documentation
Material
typedef int [] Material
Definition at line 265 of file proto.c.
vobject
typedef int [] vobject
Definition at line 46 of file proto.c.
Function Documentation
ARGB()
int ARGB (int a, int r, int g, int b)
Definition at line 322 of file proto.c.
{
    a = a << 24;
    r = r << 16;
    g = g << 8;
    return a | r | g | b;
}
Referenced by AddModifier(), BleedingIndicatorDropData::AdjustColorSaturation(), ARGBF(), CalculateEyeAccoTarget(), UIScriptedMenu::ColorDisable(), ScriptedWidgetEventHandler::ColorDisabled(), OptionSelectorBase::ColorDisabledConsole(), ScriptedWidgetEventHandler::ColorDisabledConsole(), UIScriptedMenu::ColorHighlight(), ScriptedWidgetEventHandler::ColorHighlight(), OptionSelectorBase::ColorHighlight(), ColorHighlight(), ServerBrowserTab::ColorHighlight(), ScriptedWidgetEventHandler::ColorHighlightConsole(), UIScriptedMenu::ColorNormal(), ScriptedWidgetEventHandler::ColorNormal(), OptionSelectorBase::ColorNormal(), ColorNormal(), ServerBrowserTab::ColorNormal(), OptionSelectorBase::ColorNormalConsole(), ScriptedWidgetEventHandler::ColorNormalConsole(), OptionSelectorBase::ColorOption(), UIScriptedMenu::ColorRed(), ScriptedWidgetEventHandler::ColorRed(), UIScriptedMenu::ColorRunButton(), UIScriptedMenu::ColorWhite(), ScriptedWidgetEventHandler::ColorWhite(), HandsPreview::CreateNewIcon(), ScriptedWidgetEventHandler::Darken(), Transport::DebugFreeAreaAtDoor(), EntityAI::DebugFreeAreaAtDoor(), HandsPreview::DeleteIcon(), ScriptedWidgetEventHandler::DeselectTabControl(), Hud::DisplayTendencyNormal(), Hud::DisplayTendencyTemp(), Icon::FullScreen(), GetTemperatureColor(), Hud::InitBadgesAndNotifiers(), ScriptedWidgetEventHandler::Lighten(), UIScriptedMenu::OnChange(), InventoryGridController::OnItemDraggingOver(), ScriptedWidgetEventHandler::OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), OnWidgetScriptInit(), ScriptedWidgetEventHandler::Preview(), ScriptedWidgetEventHandler::Select(), ScriptedWidgetEventHandler::SelectTabControl(), Hud::Update(), ScriptedWidgetEventHandler::UpdateColors(), and UIScriptedMenu::UpdateQuickbarItemCard().
ARGBF()
int ARGBF (float fa, float fr, float fg, float fb)
Converts <0.0, 1.0> ARGB into color.
Definition at line 332 of file proto.c.
{
    return ARGB((float)(fa * 255.0), (float)(fr * 255.0), (float)(fg * 255.0), (float)(fb * 255.0));
}
References ARGB().
Referenced by GameplayEffectWidgets_base::CalculateBreathEffect(), ScriptedWidgetEventHandler::Deselect(), Icon::DestroyWhiteBackground(), DrawConnectingLines(), UIScriptedMenu::DrawConnectingLines(), SlotsIcon::OnIconDrop(), ScriptedWidgetEventHandler::OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), ScriptedWidgetEventHandler::Select(), ClosableHeader::SetActive(), Header::SetActive(), ScriptedWidgetEventHandler::SetBattleye(), ScriptedWidgetEventHandler::SetPing(), ServerBrowserTab::SetSort(), ScriptedWidgetEventHandler::Unselect(), HoverEffect::Update(), and MainMenuButtonEffect::Update().
AWHITE()
int AWHITE (int a)
Definition at line 338 of file proto.c.
{
    return a << 24 | 0xffffff;
}
GetFPS()
proto native int GetFPS ()
Returns actual fps (average in last 10 frames)
InitSky()
proto native int InitSky (string presetName)
initialize sky with preset, must be called to set the global planets setting
Parameters
presetName name of preset to be set (one of presets from file loaded using LoadSkyPresets)
LerpARGB()
int LerpARGB (int c1, int c2)
Definition at line 344 of file proto.c.
{
    int cb1, cb2;
    const int cmask = 0x00ff00ff;
    cb1 = c1 >> 8 & cmask;
    cb2 = c2 >> 8 & cmask;
    cb1 = cb1 + cb2 >> 1;
    c1 = c1 & cmask;
    c2 = c2 & cmask;
    c1 = c1 + c2 >> 1;
    return cb1 << 8 | c1;
}
LerpSkyPreset()
proto native int LerpSkyPreset (string presetName1, string presetName2, float dayTime, float stormy1, float stormy2, float lerpVal)
lerp two sky presets and set the result using day time
Parameters
presetName1 name of preset1 to be set (one of presets from file loaded using LoadSkyPresets)
presetName2 name of preset2 to be set (one of presets from file loaded using LoadSkyPresets)
dayTime day of time <0, 1>
stormy1 stormy parameter for preset1 <0, 1>
stormy2 stormy parameter for preset2 <0, 1>
lerpVal lerp value between two presets
LerpSkyPreset3()
proto native int LerpSkyPreset3 (string presetName1, string presetName2, string presetName3, float dayTime, float stormy1, float stormy2, float stormy3, float w1, float w2, float w3)
lerp three sky presets using barycentric coordinates and set the result using day time
Parameters
presetName1 name of preset1 to be set (one of presets from file loaded using LoadSkyPresets)
presetName2 name of preset2 to be set (one of presets from file loaded using LoadSkyPresets)
presetName2 name of preset3 to be set (one of presets from file loaded using LoadSkyPresets)
dayTime day of time <0, 1>
stormy1 stormy parameter for preset1 <0, 1>
stormy2 stormy parameter for preset2 <0, 1>
stormy3 stormy parameter for preset3 <0, 1>
w1 weight for preset1
w2 weight for preset2
w3 weight for preset3
LoadSkyPresets()
proto native int LoadSkyPresets (string presetsFile)
load all sky presets from xml file
Parameters
presetFile name of XML file with presets
MakeScreenshot()
proto native void MakeScreenshot (string name)
makes screenshot and stores it in to a DDS format file if the name begins with '$' the screenshot in stored in the fullpath according to the name parameter otherwise the screenshot is stored in "$profile:ScreenShotes/DATE TIME-NAME.dds" where DATE, TIME AND NAME are replaced by actual values
Parameters
name name of the screenshot
SetNightLayerRotMatrix()
proto native void SetNightLayerRotMatrix (vector mat[3])
night sky layer rotation matrix
Parameters
mat rotation matrix
SetRealStarAutoUpdate()
proto native void SetRealStarAutoUpdate (bool update)
update of stars
Parameters
update true = automatic stars update, false = update is on user by SetStarsRotMatrix
SetSkyPlanet()
proto native bool SetSkyPlanet (int index, float azimuthDeg, float zenithDeg)
set planet position
Parameters
index index of planet, 0 = sun usually
azimuthDeg azimuth position in degrees
zenithDeg zenith position in degrees
SetSkyPlanetSize()
proto native bool SetSkyPlanetSize (int index, float angleDeg)
set planet size in degrees
Parameters
index index of planet, 0 = sun usually
angleDeg angle size in degrees
SetSkyPreset()
proto native int SetSkyPreset (string presetName, float stormy, float dayTime)
set sky preset to day time and stormy parameter
Parameters
presetName name of preset to be set (one of presets from file loaded using LoadSkyPresets)
stormy stormy parameter <0, 1>
dayTime day of time <0, 1>
SetSkyUserPlanets()
proto native void SetSkyUserPlanets (bool enabled)
user can set planets to its own positions on skydome using SetSkyPresetPlanet function, if disabled, the planets are positioned automatically using sky preset setting
Parameters
enabled enable/disable
SetStarsObserverPosition()
proto native void SetStarsObserverPosition (float latitudeDeg, float longitudeDeg)
set observer position
Parameters
latitudeDeg latitude in degrees
longitudeDeg longitude in degrees
SetStarsObserverTime()
proto native void SetStarsObserverTime (int year, int month, int day, int hour, int minute, float sec, int offsetSec)
set UTC time for real time stars
Parameters
year
month
day
hour
minute
sec
offsetSec to take into account time difference between Greenwich and local time (position dependency, summer/winter time)
SetStarsRotMatrix()
proto native void SetStarsRotMatrix (vector mat[3])
stars rotation matrix, is different from night rotation matrix because we don't know the time when night layers was captured
Parameters
mat rotation matrix
ToEntitySource()
proto native IEntitySource WriteBool::ToEntitySource ()
VectortoRGBA()
int VectortoRGBA (vector vec, float h)
Definition at line 298 of file proto.c.
{
float x,y,z;
int r,g,b,a,rgba;
    x = vec[0];
    y = vec[1];
    z = vec[2];
    x = x * 127.0 + 128.0;
    y = y * 127.0 + 128.0;
    z = z * 127.0 + 128.0;
    h = h * 255.0;
    a = (int)h << 24;
    r = (int)x << 16;
    g = (int)y << 8;
    b = z;
    return r | g | b | a;
}
References int, x, and y.
WriteBool()
class vobject WriteBool (bool value)
WriteFloat()
proto native void WriteFloat (float value)
WriteFloatAsByte()
proto native void WriteFloatAsByte (float value, float min, float max)
WriteFloatAsHalf()
proto native void WriteFloatAsHalf (float value, float min, float max)
WriteInt()
proto native void WriteInt (int value)
WriteIntAsByte()
proto native void WriteIntAsByte (int value)
WriteIntAsHalf()
proto native void WriteIntAsHalf (int value)
WriteIntAsUByte()
proto native void WriteIntAsUByte (int value)
WriteIntAsUHalf()
proto native void WriteIntAsUHalf (int value)
WriteMatrixAsQuaternionVector()
proto native void WriteMatrixAsQuaternionVector (vector mat[4])
WriteString()
proto native void WriteString (string value)
WriteVector()
proto native void WriteVector (vector value)
Variable Documentation
WriteBool
class PacketInputAdapter WriteBool