DayzKode: P:/scripts/4_world/DayZ/classes/quickbarbase.c File Reference
quickbarbase.c File Reference
Classes
class QuickBarItem
Functions
protected void _RemoveEntity (int index)
protected void _SetEntity (EntityAI entity, int index, bool force=false)
protected void _SetEntityShortcut (EntityAI entity, int index, bool force=false)
bool CanAddAsShortcut (EntityAI entity)
protected void CancelContinuousUse (int index)
int FindEntityIndex (EntityAI entity)
EntityAI GetEntity (int index)
int GetNonEmptyCount ()
int GetSize ()
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
void OnSetEntityNoSync (EntityAI entity, int index, bool force=false)
void OnSetEntityRequest (ParamsReadContext ctx)
Reaction on SetEntityShortcut from client.
void OnSetEntityRPC (ParamsReadContext ctx)
Reaction on Rpc from server for set inicial state for quickbar.
void QuickBarBase (PlayerBase player)
void SetEntityShortcut (EntityAI entity, int index, bool force=false)
void SetShotcutEnable (int index, bool value)
void SetSize (int newSize)
void UpdateShotcutVisibility (int index)
void updateSlotsCount ()
void ~QuickBarBase ()
Variables
protected PlayerBase _player
class QuickBarItem m_aQuickbarEnts [MAX_QUICKBAR_SLOTS_COUNT]
protected int m_slotsCount
const int MAX_QUICKBAR_SLOTS_COUNT = 10
Function Documentation
_RemoveEntity()
protected void _RemoveEntity (int index)
Definition at line 242 of file quickbarbase.c.
    {
        if ( index >= 0 && index < MAX_QUICKBAR_SLOTS_COUNT )
        {
            CancelContinuousUse(index);
            m_aQuickbarEnts[index].m_entity = NULL;
            m_aQuickbarEnts[index].m_enabled = false;
            if (_player.m_Hud)
                _player.m_Hud.RefreshQuickbar(true);
        }
    }
References _player, CancelContinuousUse(), m_aQuickbarEnts, QuickBarItem::m_enabled, QuickBarItem::m_entity, and MAX_QUICKBAR_SLOTS_COUNT.
Referenced by _SetEntityShortcut().
_SetEntity()
protected void _SetEntity (EntityAI entity, int index, bool force = false)
Definition at line 256 of file quickbarbase.c.
    {
        if ( index >= 0 && index < MAX_QUICKBAR_SLOTS_COUNT )
        {
            if ( CanAddAsShortcut(entity) )
            {
                m_aQuickbarEnts[index].m_entity = entity;
                m_aQuickbarEnts[index].m_enabled = true;
            }
            else
            {
                CancelContinuousUse(index);
                m_aQuickbarEnts[index].m_enabled = false;
            }
            if (_player.m_Hud)
                _player.m_Hud.RefreshQuickbar(true);
        }
    }
References _player, CanAddAsShortcut(), CancelContinuousUse(), m_aQuickbarEnts, QuickBarItem::m_enabled, QuickBarItem::m_entity, and MAX_QUICKBAR_SLOTS_COUNT.
Referenced by _SetEntityShortcut().
_SetEntityShortcut()
protected void _SetEntityShortcut (EntityAI entity, int index, bool force = false)
Definition at line 209 of file quickbarbase.c.
    {
        //TODO Check, if is in inventory
        //if(entity.GetLoca)
        if ( entity == NULL )
        {
            _RemoveEntity(index);
            return;
        }
        int i = FindEntityIndex(entity);
        if ( i != -1 )
            _RemoveEntity(i);
        _RemoveEntity(index);
        _SetEntity( entity, index, force);
    }
References _RemoveEntity(), _SetEntity(), and FindEntityIndex().
Referenced by OnSetEntityNoSync(), OnSetEntityRequest(), OnSetEntityRPC(), and SetEntityShortcut().
CanAddAsShortcut()
bool CanAddAsShortcut (EntityAI entity)
Definition at line 137 of file quickbarbase.c.
    {
        InventoryLocation loc = new InventoryLocation;
        entity.GetInventory().GetCurrentInventoryLocation(loc);
        EntityAI parent = loc.GetParent();
        return (entity && entity.GetHierarchyRootPlayer() == _player && parent.CanAssignAttachmentsToQuickbar() && entity.CanAssignToQuickbar());
    }
References _player, and InventoryLocation::GetParent().
Referenced by _SetEntity(), SetShotcutEnable(), and UpdateShotcutVisibility().
CancelContinuousUse()
protected void CancelContinuousUse (int index)
Definition at line 281 of file quickbarbase.c.
    {
        if (_player.m_QuickBarHold)
        {
            HumanInputController hic = _player.GetInputController();
            if (hic && hic.IsQuickBarSlot() == index + 1)
                _player.OnQuickBarContinuousUseEnd(index + 1);
        }
    }
References _player, and HumanInputController::IsQuickBarSlot().
Referenced by _RemoveEntity(), _SetEntity(), SetShotcutEnable(), and UpdateShotcutVisibility().
FindEntityIndex()
int FindEntityIndex (EntityAI entity)
Definition at line 95 of file quickbarbase.c.
    {
        for (int i = 0; i < MAX_QUICKBAR_SLOTS_COUNT; i++)
        {
            if (m_aQuickbarEnts[i].m_entity == entity)
                return i;
        }
        return -1;
    }
References m_aQuickbarEnts, and MAX_QUICKBAR_SLOTS_COUNT.
Referenced by _SetEntityShortcut().
GetEntity()
EntityAI GetEntity (int index)
Definition at line 78 of file quickbarbase.c.
    {
        if (index < 0 || index >= m_slotsCount)
            return NULL;
        if (m_aQuickbarEnts[index].m_enabled)
            return m_aQuickbarEnts[index].m_entity;
        return NULL;
    }
References m_aQuickbarEnts, QuickBarItem::m_entity, and m_slotsCount.
GetNonEmptyCount()
int GetNonEmptyCount ()
Definition at line 66 of file quickbarbase.c.
    {
        int count = 0;
        for ( int i = 0; i < m_slotsCount; i++ )
        {
            if (m_aQuickbarEnts[i].m_enabled)
                count++;
        }
        return count;
    }
References m_aQuickbarEnts, and m_slotsCount.
GetSize()
int GetSize ()
Definition at line 90 of file quickbarbase.c.
    {
        return m_slotsCount;
    }
References m_slotsCount.
OnInputUserDataProcess()
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
Definition at line 106 of file quickbarbase.c.
    {
        if ( userDataType == INPUT_UDT_QUICKABARSHORTCUT)
        {
            OnSetEntityRequest(ctx);
            return true;
        }
        return false;
    }
References INPUT_UDT_QUICKABARSHORTCUT, and OnSetEntityRequest().
OnSetEntityNoSync()
void OnSetEntityNoSync (EntityAI entity, int index, bool force = false)
Definition at line 175 of file quickbarbase.c.
    {
        _SetEntityShortcut(entity, index, force);
    }
References _SetEntityShortcut().
OnSetEntityRequest()
void OnSetEntityRequest (ParamsReadContext ctx)
Reaction on SetEntityShortcut from client.
Definition at line 192 of file quickbarbase.c.
    {
        EntityAI eai = null;
        if (!ctx.Read(eai))
            return;
        int index = -1;
        if (!ctx.Read(index))
            return;
        bool force = false;
        if (!ctx.Read(force))
            return
        _SetEntityShortcut(eai, index, force);
    }
References _SetEntityShortcut(), and Serializer::Read().
Referenced by OnInputUserDataProcess().
OnSetEntityRPC()
void OnSetEntityRPC (ParamsReadContext ctx)
Reaction on Rpc from server for set inicial state for quickbar.
Definition at line 181 of file quickbarbase.c.
    {
        Param2<Entity,int> param;
        if (!ctx.Read(param))
            return;
        EntityAI entity1 = EntityAI.Cast(param.param1);
        _SetEntityShortcut(entity1, param.param2, false);
    }
References _SetEntityShortcut(), and Serializer::Read().
QuickBarBase()
void QuickBarBase (PlayerBase player)
Definition at line 21 of file quickbarbase.c.
    {
        for (int i = 0; i < MAX_QUICKBAR_SLOTS_COUNT; i++)
        {
            m_aQuickbarEnts[i] = new QuickBarItem;
            m_aQuickbarEnts[i].m_enabled = false;
            m_aQuickbarEnts[i].m_entity = NULL;
        }
        _player = player;
        m_slotsCount = 0;
    }
References _player, m_aQuickbarEnts, QuickBarItem::m_enabled, QuickBarItem::m_entity, m_slotsCount, and MAX_QUICKBAR_SLOTS_COUNT.
Referenced by ManBase::Init().
SetEntityShortcut()
void SetEntityShortcut (EntityAI entity, int index, bool force = false)
Definition at line 146 of file quickbarbase.c.
    {
        //Client
        if (GetGame().IsClient())
        {
            if (ScriptInputUserData.CanStoreInputUserData())
            {
                ScriptInputUserData ctx = new ScriptInputUserData;
                ctx.Write(INPUT_UDT_QUICKABARSHORTCUT);
                ctx.Write(entity);
                ctx.Write(index);
                ctx.Write(force);
                ctx.Send();
                _SetEntityShortcut(entity, index, force);
            }
        }
        //Server
        else if (GetGame().IsMultiplayer() && GetGame().IsServer())
        {
            DayZPlayerSyncJunctures.SendQuickbarSetShortcut(_player, entity, index, force);
        }
        else
        {
            // Single player
            _SetEntityShortcut(entity,index,force);
        }
    }
References _player, _SetEntityShortcut(), ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_QUICKABARSHORTCUT, ScriptInputUserData::Send(), DayZPlayerSyncJunctures::SendQuickbarSetShortcut(), and Serializer::Write().
SetShotcutEnable()
void SetShotcutEnable (int index, bool value)
Definition at line 127 of file quickbarbase.c.
    {
        m_aQuickbarEnts[index].m_enabled = value && CanAddAsShortcut(m_aQuickbarEnts[index].m_entity);
        if (!m_aQuickbarEnts[index].m_enabled)
            CancelContinuousUse(index);
        if (_player.m_Hud)
            _player.m_Hud.RefreshQuickbar(true);
    }
References _player, CanAddAsShortcut(), CancelContinuousUse(), m_aQuickbarEnts, and QuickBarItem::m_enabled.
SetSize()
void SetSize (int newSize)
Definition at line 34 of file quickbarbase.c.
    {
        int i = m_slotsCount;
        if ( newSize == m_slotsCount )
            return;
        if (newSize > MAX_QUICKBAR_SLOTS_COUNT)
            newSize = MAX_QUICKBAR_SLOTS_COUNT;
        if ( newSize > i )
        {
            for (; i < newSize; i++)
            {
                EntityAI entity = m_aQuickbarEnts[i].m_entity;
                if ( entity != NULL && entity.GetHierarchyRootPlayer() == _player )
                {
                    m_aQuickbarEnts[i].m_enabled = true;
                }
            }
        }
        else
        {
            for (i--; i >= newSize; i--)
                m_aQuickbarEnts[i].m_enabled = false;
        }
        m_slotsCount = newSize;
        if (_player.m_Hud)
            _player.m_Hud.RefreshQuickbar(true);
    }
References _player, m_aQuickbarEnts, QuickBarItem::m_enabled, QuickBarItem::m_entity, m_slotsCount, and MAX_QUICKBAR_SLOTS_COUNT.
UpdateShotcutVisibility()
void UpdateShotcutVisibility (int index)
Definition at line 117 of file quickbarbase.c.
    {
        m_aQuickbarEnts[index].m_enabled = CanAddAsShortcut(m_aQuickbarEnts[index].m_entity);
        if (!m_aQuickbarEnts[index].m_enabled)
            CancelContinuousUse(index);
        if (_player.m_Hud)
            _player.m_Hud.RefreshQuickbar(true);
    }
References _player, CanAddAsShortcut(), CancelContinuousUse(), m_aQuickbarEnts, and QuickBarItem::m_enabled.
updateSlotsCount()
void updateSlotsCount ()
Definition at line 228 of file quickbarbase.c.
    {
        int slotsCount = _player.GetQuickBarBonus();
        int attCount  = _player.GetInventory().AttachmentCount();
        for ( int i = 0; i < attCount; ++i)
        {
            slotsCount += _player.GetInventory().GetAttachmentFromIndex(i).GetQuickBarBonus();
        }
        //max slots is 10
        SetSize(Math.Min(slotsCount, 10));
    }
References _player, Math::Min(), and SetSize().
~QuickBarBase()
void ~QuickBarBase ()
Definition at line 276 of file quickbarbase.c.
    {
    }
Variable Documentation
_player
protected PlayerBase _player
Definition at line 18 of file quickbarbase.c.
Referenced by _RemoveEntity(), _SetEntity(), CanAddAsShortcut(), CancelContinuousUse(), ManBase::OnRPC(), QuickBarBase(), UIScriptedMenu::RunEnscript(), SetEntityShortcut(), SetShotcutEnable(), SetSize(), UpdateShotcutVisibility(), and updateSlotsCount().
m_aQuickbarEnts
class QuickBarItem m_aQuickbarEnts[MAX_QUICKBAR_SLOTS_COUNT]
Referenced by _RemoveEntity(), _SetEntity(), FindEntityIndex(), GetEntity(), GetNonEmptyCount(), QuickBarBase(), SetShotcutEnable(), SetSize(), and UpdateShotcutVisibility().
m_slotsCount
protected int m_slotsCount
Definition at line 19 of file quickbarbase.c.
Referenced by GetEntity(), GetNonEmptyCount(), GetSize(), QuickBarBase(), and SetSize().
MAX_QUICKBAR_SLOTS_COUNT
const int MAX_QUICKBAR_SLOTS_COUNT = 10
Definition at line 1 of file quickbarbase.c.
Referenced by _RemoveEntity(), _SetEntity(), FindEntityIndex(), QuickBarBase(), and SetSize().