DayzKode: P:/scripts/3_game/DayZ/gui/effects/radialmenu.c File Reference
radialmenu.c File Reference
Enumerations
enum RadialMenuControlType { MOUSE , CONTROLLER }
Functions
void ActivateControllerTimeout (bool state)
protected float GetAngleInDegrees (float rad_angle)
static RadialMenu GetInstance ()
protected int GetItemCardsCount ()
protected float GetMouseDistance ()
protected float GetMousePointerAngle ()
protected Widget GetObjectByDegAngle (float deg_angle)
protected void GetParentCenter (out float center_x, out float center_y)
protected float GetParentMinSize ()
protected float GetRadius ()
protected void HideRadialSelector ()
bool IsUsingController ()
bool IsUsingMouse ()
bool IsWidgetInitialized ()
float NormalizeInvertAngle (float angle)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
void OnWidgetScriptInit (Widget w)
void RadialMenu ()
void Refresh (bool hide_selector=true)
void RegisterClass (UIScriptedMenu class_name)
void SetControlType (RadialMenuControlType type)
void SetExecuteDistOffset (float execute_dist_offset)
void SetItemCardRadiusOffset (float item_card_radius_offset)
void SetOffsetFromTop (float offset_from_top)
void SetRadiusOffset (float radius_offset)
void SetWidgetInitialized (bool state)
void SetWidgetProperties (string delimiter_layout)
protected void ShowRadialSelector (Widget selected_item)
void UpdataControllerInput ()
protected void Update ()
void ~RadialMenu ()
Variables
protected const float CONTROLLER_DESELECT_TIMEOUT = 1000
protected const float CONTROLLER_TILT_TRESHOLD_EXECUTE = 1.0
protected const float CONTROLLER_TILT_TRESHOLD_SELECT = 0.8
int last_time = -1
protected float m_AngleRadOffset
protected float m_ControllerAngle
protected float m_ControllerTilt
protected int m_ControllerTimout
protected RadialMenuControlType m_ControlType
protected string m_DelimiterLayout
protected float m_ExecuteDistanceOffset
static ref RadialMenu m_Instance
protected bool m_IsControllerTimoutEnabled = true
protected float m_ItemCardRadiusOffset
protected Widget m_ItemCardsContainer
protected float m_OffsetFromTop
enum RadialMenuControlType m_Parent
protected ref map< Widget, float > m_RadialItemCards
protected Widget m_RadialSelector
protected int m_RadialSelectorDisabledColor
protected ImageWidget m_RadialSelectorImage
protected int m_RadialSelectorOriginalColor
protected ImageWidget m_RadialSelectorPointerImage
protected float m_RadiusOffset
ref UIScriptedMenu m_RegisteredClass
protected Widget m_SelectedObject
protected ref Timer m_UpdateTimer
protected bool m_WidgetInitialized
protected const float MOUSE_SAFE_ZONE_RADIUS = 120
static const string RADIAL_DELIMITER_CONTAINER = "RadialDelimiterContainer"
static const string RADIAL_ITEM_CARD_CONTAINER = "RadialItemCardContainer"
static const string RADIAL_SELECTOR = "RadialSelector"
static const string RADIAL_SELECTOR_IMAGE = "SelectorImage"
static const string RADIAL_SELECTOR_POINTER = "SelectorPointer"
Enumeration Type Documentation
RadialMenuControlType
enum RadialMenuControlType
Enumerator
MOUSE
CONTROLLER
Definition at line 1 of file radialmenu.c.
{
    MOUSE,
    CONTROLLER
}
Function Documentation
ActivateControllerTimeout()
void ActivateControllerTimeout (bool state)
Definition at line 209 of file radialmenu.c.
    {
        m_IsControllerTimoutEnabled = state;
    }
References m_IsControllerTimoutEnabled.
GetAngleInDegrees()
protected float GetAngleInDegrees (float rad_angle)
Definition at line 492 of file radialmenu.c.
    {
        float rad_deg = rad_angle * Math.RAD2DEG;
        int angle_mp = rad_deg / 360;
        if ( rad_deg < 0 )
        {
            rad_deg = rad_deg - ( 360 * angle_mp );
            rad_deg += 360;
        }
        return rad_deg;
    }
References Math::RAD2DEG.
Referenced by GetObjectByDegAngle(), Refresh(), ShowRadialSelector(), and Update().
GetInstance()
static RadialMenu GetInstance () static
Definition at line 112 of file radialmenu.c.
    {
        return m_Instance;
    }
References m_Instance.
GetItemCardsCount()
protected int GetItemCardsCount ()
Definition at line 351 of file radialmenu.c.
    {
        Widget child = m_ItemCardsContainer.GetChildren();
        int count = 0;
        while ( child )
        {
            ++count;
            child = child.GetSibling();
        }
        return count;
    }
References m_ItemCardsContainer.
Referenced by Refresh().
GetMouseDistance()
protected float GetMouseDistance ()
Definition at line 476 of file radialmenu.c.
    {
        int mouse_x;
        int mouse_y;
        GetGame().GetMousePos( mouse_x, mouse_y );
        float center_x;
        float center_y;
        GetParentCenter( center_x, center_y );
        float distance = vector.Distance( Vector( mouse_x, mouse_y, 0 ), Vector( center_x, center_y, 0 ) );
        return distance;
    }
References vector::Distance(), GetGame(), GetParentCenter(), and Vector().
Referenced by Update().
GetMousePointerAngle()
protected float GetMousePointerAngle ()
Definition at line 458 of file radialmenu.c.
    {
        int mouse_x;
        int mouse_y;
        GetGame().GetMousePos( mouse_x, mouse_y );
        float center_x;
        float center_y;
        GetParentCenter( center_x, center_y );
        float tan_x = mouse_x - center_x;
        float tan_y = mouse_y - center_y;
        float angle = Math.Atan2( tan_y, tan_x );
        return angle;
    }
References Math::Atan2(), GetGame(), and GetParentCenter().
Referenced by Update().
GetObjectByDegAngle()
protected Widget GetObjectByDegAngle (float deg_angle)
Definition at line 415 of file radialmenu.c.
    {
        for ( int i = 0; i < m_RadialItemCards.Count(); ++i )
        {
            Widget w = m_RadialItemCards.GetKey( i );
            float w_angle = GetAngleInDegrees( m_RadialItemCards.Get( w ) );
            float offset = GetAngleInDegrees( m_AngleRadOffset ) / 2;
            float min_angle = w_angle - offset;
            float max_angle = w_angle + offset;
            if ( min_angle < 0 ) min_angle += 360;  //clamp 0-360
            if ( max_angle > 360 ) max_angle -= 360;
            if ( min_angle > max_angle )        //angle radius is in the cycling point 360->
            {
                if ( min_angle <= deg_angle )   //is cursor position also before this point
                {
                    if ( deg_angle > max_angle )
                    {
                        return w;
                    }
                }
                else                            //is cursor position after this point
                {
                    if ( deg_angle < max_angle )
                    {
                        return w;
                    }
                }
            }
            else
            {
                if ( deg_angle >= min_angle && deg_angle < max_angle )  //min, max angles are within 0-360 radius
                {
                    return w;
                }
            }
        }
        return NULL;
    }
References GetAngleInDegrees(), m_AngleRadOffset, and m_RadialItemCards.
Referenced by Update().
GetParentCenter()
protected void GetParentCenter (out float center_x, out float center_y)
Definition at line 380 of file radialmenu.c.
    {
        if ( m_Parent )
        {
            float wx;
            float wy;
            m_Parent.GetScreenPos( wx, wy );
            float ww;
            float wh;
            m_Parent.GetScreenSize( ww, wh );
            center_x = wx + ww / 2; //center
            center_y = wy + wh / 2;
        }
    }
References m_Parent.
Referenced by GetMouseDistance(), and GetMousePointerAngle().
GetParentMinSize()
protected float GetParentMinSize ()
Definition at line 397 of file radialmenu.c.
    {
        if ( m_Parent )
        {
            float size_x;
            float size_y;
            m_Parent.GetScreenSize( size_x, size_y );
            return Math.Min( size_x, size_y );
        }
        return 0;
    }
References m_Parent, and Math::Min().
Referenced by GetRadius().
GetRadius()
protected float GetRadius ()
Definition at line 366 of file radialmenu.c.
    {
        float radius = Math.AbsFloat( GetParentMinSize() * 0.5 );
        //PARAM --radius--
        if ( m_RadiusOffset > 0 )
        {
            return radius * m_RadiusOffset;
        }
        //----------------
        return radius;
    }
References Math::AbsFloat(), GetParentMinSize(), and m_RadiusOffset.
Referenced by Refresh(), and AreaDamageTriggerBase::SetExtents().
HideRadialSelector()
protected void HideRadialSelector ()
Definition at line 340 of file radialmenu.c.
    {
        if ( m_RadialSelector )
        {
            m_RadialSelector.Show( false );
        }
    }
References m_RadialSelector.
Referenced by Refresh(), and Update().
IsUsingController()
bool IsUsingController ()
Definition at line 153 of file radialmenu.c.
    {
        if ( m_ControlType == RadialMenuControlType.CONTROLLER )
        {
            return true;
        }
        return false;
    }
References m_ControlType.
Referenced by Update().
IsUsingMouse()
bool IsUsingMouse ()
Definition at line 143 of file radialmenu.c.
    {
        if ( m_ControlType == RadialMenuControlType.MOUSE )
        {
            return true;
        }
        return false;
    }
References m_ControlType.
Referenced by Update().
IsWidgetInitialized()
bool IsWidgetInitialized ()
Definition at line 168 of file radialmenu.c.
    {
        return m_WidgetInitialized;
    }
References m_WidgetInitialized.
NormalizeInvertAngle()
float NormalizeInvertAngle (float angle)
Definition at line 623 of file radialmenu.c.
    {
        float new_angle = 360 - angle;
        int angle_mp = new_angle / 360;
        new_angle = new_angle - ( 360 * angle_mp );
        return new_angle;
    }
Referenced by UpdataControllerInput().
OnMouseButtonUp()
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
Definition at line 664 of file radialmenu.c.
    {
        if (button == MouseState.LEFT && m_SelectedObject/* && w == m_SelectedObject*/)
        {
            //Execute
            GetGame().GameScript.CallFunction( m_RegisteredClass, "OnMousePressLeft", NULL, m_SelectedObject );
            return true;
        }
        if (button == MouseState.RIGHT)
        {
            //Back one level
            GetGame().GameScript.CallFunction( m_RegisteredClass, "OnMousePressRight", NULL, NULL );
            return true;
        }
        return false;
    }
References ScriptModule::CallFunction(), CGame::GameScript, GetGame(), m_RegisteredClass, and m_SelectedObject.
OnWidgetScriptInit()
void OnWidgetScriptInit (Widget w)
Definition at line 118 of file radialmenu.c.
    {
        m_ItemCardsContainer = w.FindAnyWidget( RADIAL_ITEM_CARD_CONTAINER );
        m_RadialSelector = w.FindAnyWidget( RADIAL_SELECTOR );
        m_RadialSelectorImage = ImageWidget.Cast( m_RadialSelector.FindAnyWidget( RADIAL_SELECTOR_IMAGE ) );
        m_RadialSelectorPointerImage = ImageWidget.Cast( m_RadialSelector.FindAnyWidget( RADIAL_SELECTOR_POINTER ) );
        m_RadialSelectorOriginalColor = m_RadialSelectorImage.GetColor();
        m_RadialSelectorDisabledColor = ARGB(255,150,150,150);
        //parent
        m_Parent = w;
        m_Parent.SetHandler( this );
    }
References ARGB(), m_ItemCardsContainer, m_Parent, m_RadialSelector, m_RadialSelectorDisabledColor, m_RadialSelectorImage, m_RadialSelectorOriginalColor, m_RadialSelectorPointerImage, RADIAL_ITEM_CARD_CONTAINER, RADIAL_SELECTOR, RADIAL_SELECTOR_IMAGE, and RADIAL_SELECTOR_POINTER.
RadialMenu()
void RadialMenu ()
Definition at line 83 of file radialmenu.c.
    {
        m_Instance = this;
        //set default control type
#ifdef PLATFORM_CONSOLE
        Input inp = GetGame().GetInput();
        if (inp && inp.IsEnabledMouseAndKeyboardEvenOnServer())
        {
            m_ControlType = RadialMenuControlType.MOUSE;
        }
        else
        {
            m_ControlType = RadialMenuControlType.CONTROLLER;
        }
#endif
#ifdef PLATFORM_WINDOWS
        m_ControlType = RadialMenuControlType.MOUSE;
#endif
        //radial cards
        m_RadialItemCards = new map<Widget, float>;
        m_UpdateTimer = new Timer();
        m_UpdateTimer.Run( 0.01, this, "Update", NULL, true );
    }
References GetGame(), CGame::GetInput(), Input::IsEnabledMouseAndKeyboardEvenOnServer(), m_ControlType, m_Instance, m_RadialItemCards, and m_UpdateTimer.
Referenced by UIScriptedMenu::CreateContent(), UIScriptedMenu::CreateGestureContent(), UIScriptedMenu::Init(), UIScriptedMenu::OnController(), and UIScriptedMenu::OnMouseEnter().
Refresh()
void Refresh (bool hide_selector = true)
Definition at line 223 of file radialmenu.c.
    {
        int item_cards_count = GetItemCardsCount();
        if ( item_cards_count > 0 ) m_AngleRadOffset = 2 * Math.PI / item_cards_count;
        float angle_rad = -Math.PI / 2;
        //--PARAM top offset--
        if ( m_OffsetFromTop != 0 )
        {
            angle_rad = angle_rad + m_OffsetFromTop;
        }
        //--------------------
        //delete all delimiters
        Widget delimiters_panel = m_Parent.FindAnyWidget( RADIAL_DELIMITER_CONTAINER );
        if ( delimiters_panel )
        {
            Widget del_child = delimiters_panel.GetChildren();
            while ( del_child )
            {
                Widget child_to_destroy1 = del_child;
                del_child = del_child.GetSibling();
                delete child_to_destroy1;
            }
        }
        //Position item cards, crate radial delimiters
        Widget item_cards_panel = m_Parent.FindAnyWidget( RADIAL_ITEM_CARD_CONTAINER );
        Widget item_card = item_cards_panel.GetChildren();
        //get radius
        float original_r = GetRadius();
        float item_cards_r = original_r;
        //--PARAM top offset--....
        if ( m_ItemCardRadiusOffset != 0 )
        {
            item_cards_r = item_cards_r * m_ItemCardRadiusOffset;
            if ( item_cards_r < 0 ) item_cards_r = 0;               //min radius is 0
        }
        m_RadialItemCards.Clear();
        for ( int i = 0; i < item_cards_count; ++i )
        {
            //position item cards
            if ( item_card )
            {
                //creates circle from simple widget items
                float pos_x = item_cards_r * Math.Cos( angle_rad );
                float pos_y = item_cards_r * Math.Sin( angle_rad );
                pos_x = pos_x / original_r;
                pos_y = pos_y / original_r;
                item_card.SetPos( pos_x, pos_y );
                //store item card
                m_RadialItemCards.Insert( item_card, angle_rad );
                //get next child
                item_card = item_card.GetSibling();
            }
            //-------------------------
            //create delimiter
            if ( item_cards_count > 1 && delimiters_panel && m_DelimiterLayout )
            {
                Widget delimiter_widget = GetGame().GetWorkspace().CreateWidgets( m_DelimiterLayout, delimiters_panel );
                float delim_angle_rad = angle_rad + ( m_AngleRadOffset / 2 );
                delimiter_widget.SetPos( 0, 0 );
                delimiter_widget.SetRotation( 0, 0, GetAngleInDegrees( delim_angle_rad ) + 90 );
            }
            //calculate next angle
            angle_rad += m_AngleRadOffset;
        }
        //hide selector on refresh
        if ( hide_selector )
        {
            HideRadialSelector();
        }
    }
References Math::Cos(), WorkspaceWidget::CreateWidgets(), GetAngleInDegrees(), GetGame(), GetItemCardsCount(), GetRadius(), CGame::GetWorkspace(), HideRadialSelector(), m_AngleRadOffset, m_DelimiterLayout, m_ItemCardRadiusOffset, m_OffsetFromTop, m_Parent, m_RadialItemCards, Math::PI, RADIAL_DELIMITER_CONTAINER, RADIAL_ITEM_CARD_CONTAINER, and Math::Sin().
RegisterClass()
void RegisterClass (UIScriptedMenu class_name)
Definition at line 176 of file radialmenu.c.
    {
        m_RegisteredClass = class_name;
        if (m_UpdateTimer && !m_UpdateTimer.IsRunning())
            m_UpdateTimer.Run( 0.01, this, "Update", NULL, true );
    }
References class_name, m_RegisteredClass, and m_UpdateTimer.
SetControlType()
void SetControlType (RadialMenuControlType type)
Definition at line 134 of file radialmenu.c.
    {
        if ( m_ControlType != type )
        {
            m_ControlType = type;
            GetGame().GameScript.CallFunction( m_RegisteredClass, "OnControlsChanged", NULL, type );
        }
    }
References ScriptModule::CallFunction(), CGame::GameScript, GetGame(), m_ControlType, and m_RegisteredClass.
SetExecuteDistOffset()
void SetExecuteDistOffset (float execute_dist_offset)
Definition at line 191 of file radialmenu.c.
    {
        m_ExecuteDistanceOffset = execute_dist_offset;
    }
References m_ExecuteDistanceOffset.
SetItemCardRadiusOffset()
void SetItemCardRadiusOffset (float item_card_radius_offset)
Definition at line 203 of file radialmenu.c.
    {
        m_ItemCardRadiusOffset = item_card_radius_offset;
    }
References m_ItemCardRadiusOffset.
SetOffsetFromTop()
void SetOffsetFromTop (float offset_from_top)
Definition at line 197 of file radialmenu.c.
    {
        m_OffsetFromTop = offset_from_top;
    }
References m_OffsetFromTop.
SetRadiusOffset()
void SetRadiusOffset (float radius_offset)
Definition at line 185 of file radialmenu.c.
    {
        m_RadiusOffset = radius_offset;
    }
References m_RadiusOffset.
SetWidgetInitialized()
void SetWidgetInitialized (bool state)
Definition at line 163 of file radialmenu.c.
    {
        m_WidgetInitialized = state;
    }
References m_WidgetInitialized.
SetWidgetProperties()
void SetWidgetProperties (string delimiter_layout)
Definition at line 214 of file radialmenu.c.
    {
        m_DelimiterLayout = delimiter_layout;
    }
References m_DelimiterLayout.
ShowRadialSelector()
protected void ShowRadialSelector (Widget selected_item)
Definition at line 309 of file radialmenu.c.
    {
        if ( m_RadialSelector && selected_item )
        {
            int item_count = m_RadialItemCards.Count();
            if ( item_count > 1 )
            {
                int angle_deg = GetAngleInDegrees( m_RadialItemCards.Get( selected_item ) );
                m_RadialSelector.SetRotation( 0, 0, angle_deg + 90 );           //rotate widget according to its desired rotation
                //set radial selector size
                float progress = ( 1 / item_count ) * 2;
                m_RadialSelectorImage.SetMaskProgress( progress );
                m_RadialSelector.Show( true );
                bool grey_selector = selected_item.GetFlags() & WidgetFlags.DISABLED;
                if (!grey_selector)
                {
                    m_RadialSelectorImage.SetColor(m_RadialSelectorDisabledColor);
                    m_RadialSelectorPointerImage.SetColor(m_RadialSelectorDisabledColor);
                }
                else
                {
                    m_RadialSelectorImage.SetColor(m_RadialSelectorOriginalColor);
                    m_RadialSelectorPointerImage.SetColor(m_RadialSelectorOriginalColor);
                }
            }
        }
    }
References GetAngleInDegrees(), m_RadialItemCards, m_RadialSelector, m_RadialSelectorDisabledColor, m_RadialSelectorImage, m_RadialSelectorOriginalColor, and m_RadialSelectorPointerImage.
Referenced by Update().
UpdataControllerInput()
void UpdataControllerInput ()
Definition at line 636 of file radialmenu.c.
    {
        Input input = GetGame().GetInput();
        //Controller radial
        float angle;
        float tilt;
        input.GetGamepadThumbDirection( GamepadButton.THUMB_RIGHT, angle, tilt );
        angle = NormalizeInvertAngle( angle * Math.RAD2DEG );
        m_ControllerAngle = angle;
        m_ControllerTilt = tilt;
        m_ControllerTimout  = 0;            //reset controller timeout
        //Controller buttons
        //Select (A,cross)
        if ( input.LocalPress( "UAUISelect", false ) )
        {
            GetGame().GameScript.CallFunction( m_RegisteredClass, "OnControllerPressSelect", NULL, m_SelectedObject );
        }
        //Back (B,circle)
        if ( input.LocalPress( "UAUIBack", false ) )
        {
            GetGame().GameScript.CallFunction( m_RegisteredClass, "OnControllerPressBack", NULL, m_SelectedObject );
        }
    }
References ScriptModule::CallFunction(), CGame::GameScript, GetGame(), Input::GetGamepadThumbDirection(), CGame::GetInput(), Input::LocalPress(), m_ControllerAngle, m_ControllerTilt, m_ControllerTimout, m_RegisteredClass, m_SelectedObject, NormalizeInvertAngle(), and Math::RAD2DEG.
Referenced by Update().
~RadialMenu()
void ~RadialMenu ()
Definition at line 108 of file radialmenu.c.
    {
    }
Variable Documentation
CONTROLLER_DESELECT_TIMEOUT
protected const float CONTROLLER_DESELECT_TIMEOUT = 1000
Definition at line 38 of file radialmenu.c.
Referenced by Update().
CONTROLLER_TILT_TRESHOLD_EXECUTE
protected const float CONTROLLER_TILT_TRESHOLD_EXECUTE = 1.0
Definition at line 40 of file radialmenu.c.
CONTROLLER_TILT_TRESHOLD_SELECT
protected const float CONTROLLER_TILT_TRESHOLD_SELECT = 0.8
Definition at line 39 of file radialmenu.c.
Referenced by Update().
last_time
int last_time = -1
Definition at line 511 of file radialmenu.c.
Referenced by Update().
m_AngleRadOffset
protected float m_AngleRadOffset
Definition at line 19 of file radialmenu.c.
Referenced by GetObjectByDegAngle(), and Refresh().
m_ControllerAngle
protected float m_ControllerAngle
Definition at line 32 of file radialmenu.c.
Referenced by Controller(), UpdataControllerInput(), and Update().
m_ControllerTilt
protected float m_ControllerTilt
Definition at line 33 of file radialmenu.c.
Referenced by Controller(), UpdataControllerInput(), and Update().
m_ControllerTimout
protected int m_ControllerTimout
Definition at line 36 of file radialmenu.c.
Referenced by UpdataControllerInput(), and Update().
m_ControlType
protected RadialMenuControlType m_ControlType
Definition at line 30 of file radialmenu.c.
Referenced by IsUsingController(), IsUsingMouse(), RadialMenu(), and SetControlType().
m_DelimiterLayout
protected string m_DelimiterLayout
Definition at line 51 of file radialmenu.c.
Referenced by Refresh(), and SetWidgetProperties().
m_ExecuteDistanceOffset
protected float m_ExecuteDistanceOffset
Definition at line 48 of file radialmenu.c.
Referenced by SetExecuteDistOffset().
m_Instance
ref RadialMenu m_Instance static
Definition at line 54 of file radialmenu.c.
Referenced by UIScriptedMenu::CameraToolsMenu(), GetInstance(), PluginBase::GetInstance(), array::GetTestEx(), Inventory(), MoveAttachmentDown(), MoveAttachmentUp(), PluginBase::OnInit(), UIScriptedMenu::PlayAnimOnActor(), RadialMenu(), array::Run(), and array::TFCaller().
m_IsControllerTimoutEnabled
protected bool m_IsControllerTimoutEnabled = true
Definition at line 37 of file radialmenu.c.
Referenced by ActivateControllerTimeout(), and Update().
m_ItemCardRadiusOffset
protected float m_ItemCardRadiusOffset
Definition at line 50 of file radialmenu.c.
Referenced by Refresh(), and SetItemCardRadiusOffset().
m_ItemCardsContainer
protected Widget m_ItemCardsContainer
Definition at line 10 of file radialmenu.c.
Referenced by GetItemCardsCount(), and OnWidgetScriptInit().
m_OffsetFromTop
protected float m_OffsetFromTop
Definition at line 49 of file radialmenu.c.
Referenced by Refresh(), and SetOffsetFromTop().
m_Parent
enum RadialMenuControlType m_Parent
m_RadialItemCards
protected ref map<Widget, float> m_RadialItemCards
Definition at line 17 of file radialmenu.c.
Referenced by GetObjectByDegAngle(), RadialMenu(), Refresh(), and ShowRadialSelector().
m_RadialSelector
protected Widget m_RadialSelector
Definition at line 11 of file radialmenu.c.
Referenced by HideRadialSelector(), OnWidgetScriptInit(), and ShowRadialSelector().
m_RadialSelectorDisabledColor
protected int m_RadialSelectorDisabledColor
Definition at line 15 of file radialmenu.c.
Referenced by OnWidgetScriptInit(), and ShowRadialSelector().
m_RadialSelectorImage
protected ImageWidget m_RadialSelectorImage
Definition at line 12 of file radialmenu.c.
Referenced by OnWidgetScriptInit(), and ShowRadialSelector().
m_RadialSelectorOriginalColor
protected int m_RadialSelectorOriginalColor
Definition at line 14 of file radialmenu.c.
Referenced by OnWidgetScriptInit(), and ShowRadialSelector().
m_RadialSelectorPointerImage
protected ImageWidget m_RadialSelectorPointerImage
Definition at line 13 of file radialmenu.c.
Referenced by OnWidgetScriptInit(), and ShowRadialSelector().
m_RadiusOffset
protected float m_RadiusOffset
Definition at line 47 of file radialmenu.c.
Referenced by GetRadius(), and SetRadiusOffset().
m_RegisteredClass
ref UIScriptedMenu m_RegisteredClass
Definition at line 53 of file radialmenu.c.
Referenced by OnMouseButtonUp(), RegisterClass(), SetControlType(), UpdataControllerInput(), and Update().
m_SelectedObject
protected Widget m_SelectedObject
Definition at line 16 of file radialmenu.c.
Referenced by PluginBase::DeselectObject(), PluginBase::GetSelectedSceneObject(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnDoubleClick(), UIScriptedMenu::OnItemSelected(), UIScriptedMenu::OnKeyDown(), OnMouseButtonUp(), PluginBase::SelectObject(), UIScriptedMenu::SelectPreset(), UIScriptedMenu::SetObject(), UpdataControllerInput(), and Update().
m_UpdateTimer
protected ref Timer m_UpdateTimer
Definition at line 20 of file radialmenu.c.
Referenced by PluginBase::EnableUpdate(), PluginBase::OnInit(), TrapBase::OnServerSteppedOn(), OnServerSteppedOn(), TrapBase::OnSteppedOn(), OnSteppedOn(), OnSteppedOut(), TrapBase::OnSteppedOut(), PlayerSoundEventHandler(), RadialMenu(), RegisterClass(), TrapBase(), and Update().
m_WidgetInitialized
protected bool m_WidgetInitialized
Definition at line 43 of file radialmenu.c.
Referenced by IsWidgetInitialized(), SetWidgetInitialized(), and Update().
MOUSE_SAFE_ZONE_RADIUS
protected const float MOUSE_SAFE_ZONE_RADIUS = 120
Definition at line 44 of file radialmenu.c.
Referenced by Update().
RADIAL_DELIMITER_CONTAINER
const string RADIAL_DELIMITER_CONTAINER = "RadialDelimiterContainer" static
Definition at line 26 of file radialmenu.c.
Referenced by Refresh().
RADIAL_ITEM_CARD_CONTAINER
const string RADIAL_ITEM_CARD_CONTAINER = "RadialItemCardContainer" static
Definition at line 27 of file radialmenu.c.
Referenced by OnWidgetScriptInit(), and Refresh().
RADIAL_SELECTOR
const string RADIAL_SELECTOR = "RadialSelector" static
Definition at line 23 of file radialmenu.c.
Referenced by OnWidgetScriptInit().
RADIAL_SELECTOR_IMAGE
const string RADIAL_SELECTOR_IMAGE = "SelectorImage" static
Definition at line 24 of file radialmenu.c.
Referenced by OnWidgetScriptInit().
RADIAL_SELECTOR_POINTER
const string RADIAL_SELECTOR_POINTER = "SelectorPointer" static
Definition at line 25 of file radialmenu.c.
Referenced by OnWidgetScriptInit().