DayzKode: P:/scripts/5_mission/DayZ/gui/radialquickbarmenu.c File Reference
radialquickbarmenu.c File Reference
Classes
class UIScriptedMenu
Enumerations
enum RadialQuickbarCategory { DEFAULT , SPECIALIZED_LIGHTS }
Functions
int GetCategorySwitchID ()
int GetId ()
EntityAI GetItem ()
int GetItemCategory ()
string GetItemName ()
Widget GetRadialItemCard ()
bool IsLightSourceExtra ()
bool IsNVGExtra ()
void RadialQuickbarItem (int id, EntityAI item, string item_name, int category=RadialQuickbarCategory.DEFAULT, int category_switch=-1)
void SetItem (EntityAI item)
void SetRadialItemCard (Widget widget)
Variables
protected int m_Category
protected int m_CategorySwitchID
protected int m_Id
enum RadialQuickbarCategory m_IsLightSourceExtra
protected bool m_IsNVG
protected EntityAI m_Item
protected string m_ItemName
protected Widget m_RadialMenuItemCard
protected Widget m_RadialMenuSelector
Enumeration Type Documentation
RadialQuickbarCategory
enum RadialQuickbarCategory
Enumerator
DEFAULT
SPECIALIZED_LIGHTS
Definition at line 1 of file radialquickbarmenu.c.
{
    DEFAULT,
    SPECIALIZED_LIGHTS
}
Function Documentation
GetCategorySwitchID()
int GetCategorySwitchID ()
Definition at line 67 of file radialquickbarmenu.c.
    {
        return m_CategorySwitchID;
    }
References m_CategorySwitchID.
GetId()
int GetId ()
Definition at line 57 of file radialquickbarmenu.c.
    {
        return m_Id;
    }
References m_Id.
GetItem()
EntityAI GetItem ()
Definition at line 37 of file radialquickbarmenu.c.
    {
        return m_Item;
    }
References m_Item.
Referenced by HandEventBase::CanPerformEvent(), InventoryItem::DamageItemInCargo(), ItemBase::GetStashedItem(), and ScriptedWidgetEventHandler::SetItemColor().
GetItemCategory()
int GetItemCategory ()
Definition at line 62 of file radialquickbarmenu.c.
    {
        return m_Category;
    }
References m_Category.
GetItemName()
string GetItemName ()
Definition at line 82 of file radialquickbarmenu.c.
    {
        return m_ItemName;
    }
References m_ItemName.
GetRadialItemCard()
Widget GetRadialItemCard ()
Definition at line 72 of file radialquickbarmenu.c.
    {
        return m_RadialMenuItemCard;
    }
References m_RadialMenuItemCard.
IsLightSourceExtra()
bool IsLightSourceExtra ()
Definition at line 47 of file radialquickbarmenu.c.
    {
        return m_IsLightSourceExtra;
    }
References m_IsLightSourceExtra.
IsNVGExtra()
bool IsNVGExtra ()
Definition at line 52 of file radialquickbarmenu.c.
    {
        return m_IsNVG;
    }
References m_IsNVG.
RadialQuickbarItem()
void RadialQuickbarItem (int id, EntityAI item, string item_name, int category = RadialQuickbarCategory.DEFAULT, int category_switch = -1)
Definition at line 21 of file radialquickbarmenu.c.
    {
        m_Id                = id;
        m_Item              = item;
        m_ItemName          = item_name;
        m_Category          = category;
        m_CategorySwitchID  = category_switch;
        //
        if (ItemBase.Cast(m_Item))
        {
            m_IsNVG = ItemBase.Cast(m_Item).IsNVG();
            m_IsLightSourceExtra = ItemBase.Cast(m_Item).IsLightSource();
        }
    }
References m_Category, m_CategorySwitchID, m_Id, m_IsLightSourceExtra, m_IsNVG, m_Item, and m_ItemName.
Referenced by UIScriptedMenu::CheckForLightsAndNVG(), UIScriptedMenu::CreateContent(), UIScriptedMenu::GetItems(), UIScriptedMenu::MarkSelected(), UIScriptedMenu::PrimaryAction(), UIScriptedMenu::RefreshQuickbar(), and UIScriptedMenu::SecondaryAction().
SetItem()
void SetItem (EntityAI item)
Definition at line 42 of file radialquickbarmenu.c.
    {
        m_Item = item;
    }
References m_Item.
SetRadialItemCard()
void SetRadialItemCard (Widget widget)
Definition at line 77 of file radialquickbarmenu.c.
    {
        m_RadialMenuItemCard = widget;
    }
References m_RadialMenuItemCard.
Variable Documentation
m_Category
protected int m_Category
Definition at line 12 of file radialquickbarmenu.c.
m_CategorySwitchID
protected int m_CategorySwitchID
Definition at line 13 of file radialquickbarmenu.c.
Referenced by GetCategorySwitchID(), and RadialQuickbarItem().
m_Id
protected int m_Id
Definition at line 11 of file radialquickbarmenu.c.
m_IsLightSourceExtra
enum RadialQuickbarCategory m_IsLightSourceExtra
Referenced by IsLightSourceExtra(), and RadialQuickbarItem().
m_IsNVG
protected bool m_IsNVG
Definition at line 10 of file radialquickbarmenu.c.
Referenced by IsNVGExtra(), and RadialQuickbarItem().
m_Item
protected EntityAI m_Item
Definition at line 14 of file radialquickbarmenu.c.
m_ItemName
protected string m_ItemName
Definition at line 15 of file radialquickbarmenu.c.
m_RadialMenuItemCard
protected Widget m_RadialMenuItemCard
Definition at line 19 of file radialquickbarmenu.c.
m_RadialMenuSelector
protected Widget m_RadialMenuSelector
Definition at line 18 of file radialquickbarmenu.c.