DayzKode: P:/scripts/4_world/DayZ/entities/grenade_base/rdg2smokegrenade_colorbase.c File Reference
rdg2smokegrenade_colorbase.c File Reference
Classes
class RDG2SmokeGrenade_ColorBase
class SmokeGrenadeBase
Functions
void RDG2SmokeGrenade_Black ()
class RDG2SmokeGrenade_Black extends RDG2SmokeGrenade_ColorBase RDG2SmokeGrenade_White ()
Function Documentation
RDG2SmokeGrenade_Black()
void RDG2SmokeGrenade_White::RDG2SmokeGrenade_Black ()
Definition at line 33 of file rdg2smokegrenade_colorbase.c.
    {
        SetParticleSmokeStart(ParticleList.GRENADE_RDG2_WHITE_START);
        SetParticleSmokeLoop(ParticleList.GRENADE_RDG2_WHITE_LOOP);
        SetParticleSmokeEnd(ParticleList.GRENADE_RDG2_WHITE_END);
    }
}
References ParticleList::GRENADE_RDG2_WHITE_END, ParticleList::GRENADE_RDG2_WHITE_LOOP, ParticleList::GRENADE_RDG2_WHITE_START, SetParticleSmokeEnd(), SetParticleSmokeLoop(), and SetParticleSmokeStart().
RDG2SmokeGrenade_White()
class RDG2SmokeGrenade_Black extends RDG2SmokeGrenade_ColorBase RDG2SmokeGrenade_White ()
Definition at line 20 of file rdg2smokegrenade_colorbase.c.
    {
        SetParticleSmokeStart(ParticleList.GRENADE_RDG2_WHITE_START);
        SetParticleSmokeLoop(ParticleList.GRENADE_RDG2_WHITE_LOOP);
        SetParticleSmokeEnd(ParticleList.GRENADE_RDG2_WHITE_END);
    }