DayzKode: P:/scripts/4_world/DayZ/entities/explosivesbase/remotedetonator.c File Reference
remotedetonator.c File Reference
Classes
class RemoteDetonatorTrigger
Enumerations
enum ERemoteDetonatorLEDState { OFF = 0 , LIT }
Functions
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EEKilled (Object killer)
EntityAI GetControlledDevice ()
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
Remotely controlled devices helpers.
bool IsConnected ()
bool IsKit ()
override void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
override void OnAnimationPhaseStarted (string animSource, float phase)
override void OnCEUpdate ()
override void OnVariablesSynchronized ()
override void OnWasDetached (EntityAI parent, int slot_id)
override void PairRemote (notnull EntityAI trigger)
RemoteDetonatorTrigger RemoteDetonator RemoteDetonatorReceiver ()
void RemoteDetonatorTrigger ()
override void SetActions ()
void SetControlledDevice (EntityAI pDevice)
static RemoteDetonatorTrigger SpawnInPlayerHands (notnull EntityAI pEntity)
override void UnpairRemote ()
void UpdateLED (ERemoteDetonatorLEDState pState, bool pForced=false)
Variables
protected const string ANIM_PHASE_TRIGGER = "trigger"
const string COLOR_LED_LIT = "#(argb,8,8,3)color(1,0,0,1.0,co)"
enum ERemoteDetonatorLEDState COLOR_LED_OFF = "#(argb,8,8,3)color(0,0,0,1.0,co)"
protected ERemoteDetonatorLEDState m_LastLEDState
protected bool m_LED
protected ref RemotelyActivatedItemBehaviour m_RAIB
const string SELECTION_NAME_LED = "LED"
Enumeration Type Documentation
ERemoteDetonatorLEDState
enum ERemoteDetonatorLEDState
Enumerator
OFF
LIT
Definition at line 1 of file remotedetonator.c.
{
    OFF = 0,
    LIT,
}
Function Documentation
EEItemLocationChanged()
override void RemoteDetonatorReceiver::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
Definition at line 252 of file remotedetonator.c.
EEKilled()
override void EEKilled (Object killer)
Definition at line 233 of file remotedetonator.c.
    {
        super.EEKilled(killer);
        UpdateLED(ERemoteDetonatorLEDState.OFF, true);
    }
References UpdateLED().
GetControlledDevice()
EntityAI RemoteDetonatorReceiver::GetControlledDevice ()
Definition at line 320 of file remotedetonator.c.
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour RemoteDetonatorReceiver::GetRemotelyActivatedItemBehaviour ()
Remotely controlled devices helpers.
Definition at line 262 of file remotedetonator.c.
IsConnected()
bool RemoteDetonatorReceiver::IsConnected ()
Definition at line 315 of file remotedetonator.c.
IsKit()
override bool IsKit ()
Definition at line 15 of file remotedetonator.c.
    {
        return true;
    }
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
Definition at line 295 of file remotedetonator.c.
OnAnimationPhaseStarted()
override void RemoteDetonatorReceiver::OnAnimationPhaseStarted (string animSource, float phase)
Definition at line 353 of file remotedetonator.c.
OnCEUpdate()
override void RemoteDetonatorReceiver::OnCEUpdate ()
Definition at line 267 of file remotedetonator.c.
OnVariablesSynchronized()
override void RemoteDetonatorReceiver::OnVariablesSynchronized ()
Definition at line 240 of file remotedetonator.c.
    {
        super.SetActions();
        RemoveAction(ActionAttachExplosivesTrigger);
        RemoveAction(ActionDisarmExplosiveWithRemoteDetonatorUnpaired);
    }
}
References ActionAttachExplosivesTrigger(), ActionDisarmExplosiveWithRemoteDetonatorUnpaired(), and RemoveAction().
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id)
Definition at line 228 of file remotedetonator.c.
    {
        UpdateLED(ERemoteDetonatorLEDState.OFF);
    }
References UpdateLED().
PairRemote()
override void RemoteDetonatorReceiver::PairRemote (notnull EntityAI trigger)
Definition at line 284 of file remotedetonator.c.
RemoteDetonatorReceiver()
RemoteDetonatorTrigger RemoteDetonator RemoteDetonatorReceiver ()
Definition at line 37 of file remotedetonator.c.
    {
        UpdateLED(ERemoteDetonatorLEDState.OFF, true);
    }
References ActionAttachExplosivesTrigger(), ActionDisarmExplosiveWithRemoteDetonatorUnpaired(), and AddAction().
Referenced by ActionCondition(), ImprovisedExplosive::UpdateLED(), and Plastic_Explosive::UpdateLED().
RemoteDetonatorTrigger()
void RemoteDetonatorReceiver::RemoteDetonatorTrigger ()
Definition at line 224 of file remotedetonator.c.
    {
        return false;
    }
    override void OnWasDetached(EntityAI parent, int slot_id)
    {
        UpdateLED(ERemoteDetonatorLEDState.OFF);
    }
    override void EEKilled(Object killer)
SetActions()
override void SetActions ()
Definition at line 37 of file remotedetonator.c.
    {
        super.SetActions();
        AddAction(ActionAttachExplosivesTrigger);
        AddAction(ActionDisarmExplosiveWithRemoteDetonatorUnpaired);
    }
SetControlledDevice()
void RemoteDetonatorReceiver::SetControlledDevice (EntityAI pDevice)
Definition at line 310 of file remotedetonator.c.
SpawnInPlayerHands()
static RemoteDetonatorTrigger RemoteDetonatorReceiver::SpawnInPlayerHands (notnull EntityAI pEntity) static
item replaced, use different IK
Definition at line 325 of file remotedetonator.c.
UnpairRemote()
override void RemoteDetonatorReceiver::UnpairRemote ()
Definition at line 289 of file remotedetonator.c.
UpdateLED()
void UpdateLED (ERemoteDetonatorLEDState pState, bool pForced = false)
Definition at line 20 of file remotedetonator.c.
    {
        int selectionIdx = GetHiddenSelectionIndex(SELECTION_NAME_LED);
        switch (pState)
        {
        case ERemoteDetonatorLEDState.LIT:
            SetObjectTexture(selectionIdx, COLOR_LED_LIT);
        break;
        default:
            SetObjectTexture(selectionIdx, COLOR_LED_OFF);
        }
        m_LastLEDState = pState;
        SetSynchDirty();
    }
References COLOR_LED_LIT, COLOR_LED_OFF, m_LastLEDState, and SELECTION_NAME_LED.
Referenced by RemoteDetonatorTrigger::OnAnimationPhaseStarted(), RemoteDetonatorTrigger::OnCEUpdate(), RemoteDetonatorTrigger::OnVariablesSynchronized(), RemoteDetonatorTrigger::RemoteDetonatorTrigger(), and RemoteDetonatorTrigger::UnpairRemote().
Variable Documentation
ANIM_PHASE_TRIGGER
protected const string ANIM_PHASE_TRIGGER = "trigger"
Definition at line 219 of file remotedetonator.c.
COLOR_LED_LIT
const string COLOR_LED_LIT = "#(argb,8,8,3)color(1,0,0,1.0,co)"
Definition at line 10 of file remotedetonator.c.
Referenced by UpdateLED().
COLOR_LED_OFF
enum ERemoteDetonatorLEDState COLOR_LED_OFF = "#(argb,8,8,3)color(0,0,0,1.0,co)"
m_LastLEDState
protected ERemoteDetonatorLEDState m_LastLEDState
Definition at line 13 of file remotedetonator.c.
Referenced by RemoteDetonatorTrigger::OnVariablesSynchronized(), RemoteDetonatorTrigger::RemoteDetonatorTrigger(), and UpdateLED().
m_LED
protected bool m_LED
Definition at line 221 of file remotedetonator.c.
m_RAIB
protected ref RemotelyActivatedItemBehaviour m_RAIB
Definition at line 222 of file remotedetonator.c.
SELECTION_NAME_LED
const string SELECTION_NAME_LED = "LED"
Definition at line 11 of file remotedetonator.c.
Referenced by UpdateLED().