DayzKode: P:/scripts/4_world/DayZ/classes/remoteplayerdebug/remoteplayerstatdebug.c File Reference
remoteplayerstatdebug.c File Reference
Enumerations
enum eRemoteStatType { NONE , DAMAGE_SYSTEM = 1 , PLAYER_STATS = 2 , OTHER = 4 }
Functions
void Debug ()
PlayerBase GetPlayer ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void InjectDamageSystemValues ()
void RemotePlayerStatDebug (PlayerBase player)
void SerializeNames (array< string > names, eRemoteDebugType type)
void SerializeValues (array< string > values, eRemoteDebugType type)
void UpdatePlayerStatsValues ()
Variables
string m_Name
enum eRemoteStatType m_Player
vector m_Pos
ref array< ref StatDebugObject > m_Stats = new array<ref StatDebugObject>
Enumeration Type Documentation
eRemoteStatType
enum eRemoteStatType
Enumerator
NONE
DAMAGE_SYSTEM
PLAYER_STATS
OTHER
Definition at line 1 of file remoteplayerstatdebug.c.
{
    NONE,
    DAMAGE_SYSTEM = 1,
    PLAYER_STATS = 2,
    OTHER = 4,
}
Function Documentation
Debug()
void Debug ()
Definition at line 88 of file remoteplayerstatdebug.c.
    {
        for(int i = 0; i < m_Stats.Count(); i++)
        {
            m_Stats.Get(i).Debug();
        }
    }
References m_Stats.
GetPlayer()
PlayerBase GetPlayer ()
Definition at line 31 of file remoteplayerstatdebug.c.
    {
        return m_Player;
    }
References m_Player.
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
Definition at line 23 of file remoteplayerstatdebug.c.
    {
        UpdatePlayerStatsValues();
        InjectDamageSystemValues();
        m_Pos = m_Player.GetWorldPosition();
        m_Name = m_Player.GetIdentity().GetName();
    }
References InjectDamageSystemValues(), m_Name, m_Player, m_Pos, and UpdatePlayerStatsValues().
InjectDamageSystemValues()
void InjectDamageSystemValues ()
Definition at line 41 of file remoteplayerstatdebug.c.
    {
        m_Stats.Insert( new StatDebugObject("Health", m_Player.GetHealth("",""), eRemoteStatType.DAMAGE_SYSTEM) );
        m_Stats.Insert( new StatDebugObject("Blood", m_Player.GetHealth("","Blood"), eRemoteStatType.DAMAGE_SYSTEM) );
        m_Stats.Insert( new StatDebugObject("Shock", m_Player.GetHealth("","Shock"), eRemoteStatType.DAMAGE_SYSTEM) );
    }
References m_Player, and m_Stats.
Referenced by Init().
RemotePlayerStatDebug()
void RemotePlayerStatDebug (PlayerBase player)
Definition at line 16 of file remoteplayerstatdebug.c.
    {
        m_Player = player;
        Init();
    }
References Init(), and m_Player.
Referenced by PluginBase::GatherPlayerInfo(), UIScriptedMenu::Update(), and UpdateWidgetsStats().
SerializeNames()
void SerializeNames (array< string > names, eRemoteDebugType type)
Definition at line 48 of file remoteplayerstatdebug.c.
    {
        for(int i = 0; i < m_Stats.Count(); i++)
        {
            if( type ==  eRemoteDebugType.ALL )
            {
                names.Insert(m_Stats.Get(i).GetName());
            }
            else if( type ==  eRemoteDebugType.DAMAGE_ONLY )
            {
                StatDebugObject obj = m_Stats.Get(i);
                eRemoteStatType debug_type = obj.GetType();
                if(debug_type == eRemoteStatType.DAMAGE_SYSTEM)
                {
                    names.Insert(m_Stats.Get(i).GetName());
                }
            }
        }
    }
References StatDebugObject::GetType(), and m_Stats.
SerializeValues()
void SerializeValues (array< string > values, eRemoteDebugType type)
Definition at line 68 of file remoteplayerstatdebug.c.
    {
        for(int i = 0; i < m_Stats.Count(); i++)
        {
            if( type ==  eRemoteDebugType.ALL )
            {
                values.Insert(m_Stats.Get(i).GetValue());
            }
            else if( type ==  eRemoteDebugType.DAMAGE_ONLY )
            {
                StatDebugObject obj = m_Stats.Get(i);
                eRemoteStatType debug_type = obj.GetType();
                if(debug_type == eRemoteStatType.DAMAGE_SYSTEM)
                {
                    values.Insert(m_Stats.Get(i).GetValue());
                }
            }
        }
    }
References StatDebugObject::GetType(), and m_Stats.
UpdatePlayerStatsValues()
void UpdatePlayerStatsValues ()
Definition at line 36 of file remoteplayerstatdebug.c.
    {
        m_Player.GetPlayerStats().GetDebugInfo(m_Stats, 0);
    }
References m_Player, and m_Stats.
Referenced by Init().
Variable Documentation
m_Name
string m_Name
Definition at line 14 of file remoteplayerstatdebug.c.
m_Player
enum eRemoteStatType m_Player
m_Pos
vector m_Pos
Definition at line 15 of file remoteplayerstatdebug.c.
Referenced by Init().
m_Stats
ref array<ref StatDebugObject> m_Stats = new array<ref StatDebugObject>
Definition at line 13 of file remoteplayerstatdebug.c.
Referenced by Debug(), UIScriptedMenu::Init(), InjectDamageSystemValues(), UIScriptedMenu::OnChangeCharacter(), SerializeNames(), SerializeValues(), and UpdatePlayerStatsValues().