DayzKode: P:/scripts/3_game/DayZ/entities/scriptedentity.c File Reference
scriptedentity.c File Reference
Enumerations
enum TriggerShape
Functions
proto native TriggerShape GetTriggerShape ()
Get the current TriggerShape.
override bool IsInventoryVisible ()
enum TriggerShape SetClippingInfo (vector mins, vector maxs, float radius)
Sets collision properties for object.
proto native void SetCollisionBox (vector mins, vector maxs)
Sets collision box for object.
proto native void SetCollisionCylinder (float radius, float height)
Sets collision cylinder for object.
proto native void SetCollisionSphere (float radius)
Sets collision sphere for object.
proto native void SetTriggerShape (TriggerShape shape)
Set the TriggerShape to be used, default is TriggerShape.BOX.
Variables
BOX
CYLINDER
SPHERE
Enumeration Type Documentation
TriggerShape
enum TriggerShape
Definition at line 1 of file scriptedentity.c.
{
    BOX,
    SPHERE,
    CYLINDER,
}
Function Documentation
GetTriggerShape()
proto native TriggerShape GetTriggerShape ()
Get the current TriggerShape.
IsInventoryVisible()
override bool IsInventoryVisible ()
Definition at line 62 of file scriptedentity.c.
    {
        return false;
    }
SetClippingInfo()
enum TriggerShape SetClippingInfo (vector mins, vector maxs, float radius)
Sets collision properties for object.
Parameters
mins vector Min values of box
maxs vector Max values of box
radius float Radius of bounding sphere
Note
This function is obsolete, use rather SetCollisionBox()
SetCollisionBox()
proto native void SetCollisionBox (vector mins, vector maxs)
Sets collision box for object.
Parameters
mins vector Min values of box
maxs vector Max values of box
Note
Automatically sets TriggerShape.BOX
usage :
vector mins = "-1 -1 -1";
vector maxs = "1 1 1";
SetCollisionBox(mins, maxs);
Referenced by Trigger::SetExtents().
SetCollisionCylinder()
proto native void SetCollisionCylinder (float radius, float height)
Sets collision cylinder for object.
Parameters
radius float Radius of cylinder
height float Height of cylinder
Note
Automatically sets TriggerShape.CYLINDER
usage :
SetCollisionCylinder(3, 6);
Referenced by CylinderTrigger::EOnInit().
SetCollisionSphere()
proto native void SetCollisionSphere (float radius)
Sets collision sphere for object.
Parameters
radius float Radius of cylinder
Note
Automatically sets TriggerShape.SPHERE
usage :
SetCollisionSphere(3);
Referenced by SphereTrigger::EOnInit().
SetTriggerShape()
proto native void SetTriggerShape (TriggerShape shape)
Set the TriggerShape to be used, default is TriggerShape.BOX.
Variable Documentation
BOX
@ BOX
Definition at line 0 of file scriptedentity.c.
CYLINDER
@ CYLINDER
Definition at line 2 of file scriptedentity.c.
SPHERE
@ SPHERE
Definition at line 1 of file scriptedentity.c.