DayzKode: P:/scripts/4_world/DayZ/entities/grenade_base/smokegrenadebase.c File Reference
smokegrenadebase.c File Reference
Enumerations
enum ESmokeGrenadeState { NO_SMOKE , LOOP = 2 , END = 3 , COUNT = 4 }
Functions
override bool CanPutInCargo (EntityAI parent)
protected void DestroySmokeGrenade ()
override void EEDelete (EntityAI parent)
ESmokeGrenadeState GetSmokeGrenadeState ()
override void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
override void OnActivateFinished ()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
override void OnVariablesSynchronized ()
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
protected void PlaySmokeParticle ()
protected void RefreshParticlesAndSounds ()
override void SetActions ()
void SetParticleSmokeCurrent (int particle)
void SetParticleSmokeEnd (int particle)
void SetParticleSmokeLoop (int particle)
void SetParticleSmokeStart (int particle)
void SetSmokeGrenadeState (ESmokeGrenadeState state)
void SetSoundSmokeEnd (string sound)
void SetSoundSmokeLoop (string sound)
void SetSoundSmokeStart (string sound)
void SmokeGrenadeBase ()
protected void SoundSmokeEnd ()
protected void SoundSmokeLoop ()
protected void SoundSmokeStart ()
protected void SoundSmokeStop ()
override void Unpin ()
void ~SmokeGrenadeBase ()
Variables
protected ESmokeGrenadeState m_LastSmokeGrenadeState
ref NoiseParams m_NoisePar
Noise.
protected Particle m_ParticleSmoke
particle
protected int m_ParticleSmokeCurrentId
protected int m_ParticleSmokeEndId
protected int m_ParticleSmokeLoopId
protected vector m_ParticleSmokePosition
protected int m_ParticleSmokeStartId
protected ESmokeGrenadeState m_SmokeGrenadeState
protected EffectSound m_SoundSmoke
sounds
protected string m_SoundSmokeEndId
protected string m_SoundSmokeLoopId
protected string m_SoundSmokeStartId
protected ref Timer m_TimerDefer
protected ref Timer m_TimerSmokeEnd
protected ref Timer m_TimerSmokeLoop
enum ESmokeGrenadeState m_TimerSmokeStart
Enumeration Type Documentation
ESmokeGrenadeState
enum ESmokeGrenadeState
Enumerator
NO_SMOKE
LOOP
END
COUNT
Definition at line 1 of file smokegrenadebase.c.
{
    NO_SMOKE    = 0
    START       = 1,
    LOOP        = 2,
    END         = 3,
    COUNT       = 4
}
Function Documentation
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent)
Definition at line 216 of file smokegrenadebase.c.
    {
        return !GetCompEM().IsWorking();
    }
DestroySmokeGrenade()
protected void DestroySmokeGrenade ()
Definition at line 100 of file smokegrenadebase.c.
    {
        SetSmokeGrenadeState(ESmokeGrenadeState.NO_SMOKE);
        if ( GetGame().IsServer() )
        {
            SetHealth("", "", 0);
        }
    }
References GetGame(), SetHealth(), and SetSmokeGrenadeState().
EEDelete()
override void EEDelete (EntityAI parent)
Definition at line 247 of file smokegrenadebase.c.
    {
        super.EEDelete(parent);
        SoundSmokeStop();
        DestroyParticle(m_ParticleSmoke);
    }
References DestroyParticle(), m_ParticleSmoke, and SoundSmokeStop().
GetSmokeGrenadeState()
ESmokeGrenadeState GetSmokeGrenadeState ()
Definition at line 242 of file smokegrenadebase.c.
    {
        return m_SmokeGrenadeState;
    }
References m_SmokeGrenadeState.
Referenced by RefreshParticlesAndSounds().
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
Definition at line 221 of file smokegrenadebase.c.
    {
        GetCompEM().SwitchOn();
    }
OnActivateFinished()
override void OnActivateFinished ()
Definition at line 166 of file smokegrenadebase.c.
    {
        if ( GetCompEM() && GetCompEM().CanWork() )
        {
            GetCompEM().SwitchOn();
        }
    }
OnExplosionEffects()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
Definition at line 240 of file smokegrenadebase.c.
{}
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 233 of file smokegrenadebase.c.
    {
        super.OnVariablesSynchronized();
        RefreshParticlesAndSounds();
    }
References RefreshParticlesAndSounds().
OnWork()
override void OnWork (float consumed_energy)
Definition at line 195 of file smokegrenadebase.c.
    {
        if ( GetGame().IsServer() )
        {
            NoiseSystem noise = GetGame().GetNoiseSystem();
            if ( noise )
            {
                noise.AddNoisePos( this, GetPosition(), m_NoisePar);
            }
        }
    }
References NoiseSystem::AddNoisePos(), GetGame(), CGame::GetNoiseSystem(), GetPosition, and m_NoisePar.
OnWorkStart()
override void OnWorkStart ()
Definition at line 175 of file smokegrenadebase.c.
    {
        SetSmokeGrenadeState(ESmokeGrenadeState.START);
        if ( GetGame().IsServer() )
        {
            m_NoisePar = new NoiseParams();
            m_NoisePar.LoadFromPath("cfgVehicles " + GetType() + " NoiseSmokeGrenade");
            NoiseSystem noise = GetGame().GetNoiseSystem();
            if ( noise )
            {
                noise.AddNoisePos( this, GetPosition(), m_NoisePar );
            }
        }
        Param1<ESmokeGrenadeState> par = new Param1<ESmokeGrenadeState>(ESmokeGrenadeState.LOOP);
        m_TimerSmokeLoop.Run(5.0, this, "SetSmokeGrenadeState", par);
    }
References NoiseSystem::AddNoisePos(), GetGame(), CGame::GetNoiseSystem(), GetPosition, GetType(), m_NoisePar, m_TimerSmokeLoop, NoiseParams(), and SetSmokeGrenadeState().
OnWorkStop()
override void OnWorkStop ()
defer timer
Definition at line 208 of file smokegrenadebase.c.
    {
        SetSmokeGrenadeState(ESmokeGrenadeState.END);
        m_TimerDefer.Run(5.0, this, "DestroySmokeGrenade");
    }
References m_TimerDefer, and SetSmokeGrenadeState().
PlaySmokeParticle()
protected void PlaySmokeParticle ()
Definition at line 74 of file smokegrenadebase.c.
    {
        m_ParticleSmoke = ParticleManager.GetInstance().PlayOnObject(m_ParticleSmokeCurrentId, this, m_ParticlePosition, vector.Zero, true);
    }
References m_ParticlePosition, m_ParticleSmoke, m_ParticleSmokeCurrentId, ParticleManager(), and vector::Zero.
Referenced by RefreshParticlesAndSounds().
RefreshParticlesAndSounds()
protected void RefreshParticlesAndSounds ()
Definition at line 110 of file smokegrenadebase.c.
    {
        ESmokeGrenadeState state = GetSmokeGrenadeState();
        if ( m_LastSmokeGrenadeState != state )
        {
            if ( state == ESmokeGrenadeState.START )
            {
                //Print("RefreshAudioVisual:: START");
                SoundSmokeEnd();
                SoundSmokeStart();
                DestroyParticle(m_ParticleSmoke);
                SetParticleSmokeCurrent(m_ParticleSmokeStartId);
                PlaySmokeParticle();
            }
            else if ( state == ESmokeGrenadeState.LOOP )
            {
                //Print("RefreshAudioVisual:: LOOP");
                SoundSmokeStop();
                SoundSmokeLoop();
                DestroyParticle(m_ParticleSmoke);
                SetParticleSmokeCurrent(m_ParticleSmokeLoopId);
                PlaySmokeParticle();
            }
            else if ( state == ESmokeGrenadeState.END )
            {
                //Print("RefreshAudioVisual:: END");
                SoundSmokeStop();
                SoundSmokeEnd();
                DestroyParticle(m_ParticleSmoke);
                SetParticleSmokeCurrent(m_ParticleSmokeEndId);
                PlaySmokeParticle();
            }
            else if ( state == ESmokeGrenadeState.NO_SMOKE )
            {
                //Print("RefreshAudioVisual:: NO_SMOKE");
                SoundSmokeStop();
                DestroyParticle(m_ParticleSmoke);
            }
            m_LastSmokeGrenadeState = state;
        }
    }
References DestroyParticle(), GetSmokeGrenadeState(), m_LastSmokeGrenadeState, m_ParticleSmoke, m_ParticleSmokeEndId, m_ParticleSmokeLoopId, m_ParticleSmokeStartId, PlaySmokeParticle(), SetParticleSmokeCurrent(), SoundSmokeEnd(), SoundSmokeLoop(), SoundSmokeStart(), and SoundSmokeStop().
Referenced by OnVariablesSynchronized().
SetActions()
override void SetActions ()
Definition at line 226 of file smokegrenadebase.c.
    {
        super.SetActions();
        RemoveAction(ActionPin);
    }
References RemoveAction().
SetParticleSmokeCurrent()
void SetParticleSmokeCurrent (int particle)
Definition at line 39 of file smokegrenadebase.c.
    {
        m_ParticleSmokeCurrentId = particle;
    }
References m_ParticleSmokeCurrentId.
Referenced by RefreshParticlesAndSounds().
SetParticleSmokeEnd()
void SetParticleSmokeEnd (int particle)
Definition at line 54 of file smokegrenadebase.c.
    {
        m_ParticleSmokeEndId = particle;
    }
References m_ParticleSmokeEndId.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_White(), M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow(), M18SmokeGrenade_Yellow(), OnWorkStop(), RDG2SmokeGrenade_ColorBase::RDG2SmokeGrenade_Black(), RDG2SmokeGrenade_Black(), and SmokeGrenadeBase().
SetParticleSmokeLoop()
void SetParticleSmokeLoop (int particle)
Definition at line 49 of file smokegrenadebase.c.
    {
        m_ParticleSmokeLoopId = particle;
    }
References m_ParticleSmokeLoopId.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_White(), M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow(), M18SmokeGrenade_Yellow(), OnWorkStop(), RDG2SmokeGrenade_ColorBase::RDG2SmokeGrenade_Black(), RDG2SmokeGrenade_Black(), and SmokeGrenadeBase().
SetParticleSmokeStart()
void SetParticleSmokeStart (int particle)
Definition at line 44 of file smokegrenadebase.c.
    {
        m_ParticleSmokeStartId = particle;
    }
References m_ParticleSmokeStartId.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_White(), M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow(), M18SmokeGrenade_Yellow(), OnWorkStop(), RDG2SmokeGrenade_ColorBase::RDG2SmokeGrenade_Black(), RDG2SmokeGrenade_Black(), and SmokeGrenadeBase().
SetSmokeGrenadeState()
void SetSmokeGrenadeState (ESmokeGrenadeState state)
Definition at line 255 of file smokegrenadebase.c.
    {
        //Print("Setting SGS to: " + typename.EnumToString(ESmokeGrenadeState, state));
        if ( GetGame().IsServer() )
        {
            if ( m_SmokeGrenadeState != state )
            {
                m_SmokeGrenadeState = state;
                //synchronize
                SetSynchDirty();
            }
        }
    }
References GetGame(), and m_SmokeGrenadeState.
Referenced by DestroySmokeGrenade(), OnWorkStart(), and OnWorkStop().
SetSoundSmokeEnd()
void SetSoundSmokeEnd (string sound)
Definition at line 69 of file smokegrenadebase.c.
    {
        m_SoundSmokeEndId = sound;
    }
References m_SoundSmokeEndId.
Referenced by SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
SetSoundSmokeLoop()
void SetSoundSmokeLoop (string sound)
Definition at line 64 of file smokegrenadebase.c.
    {
        m_SoundSmokeLoopId = sound;
    }
References m_SoundSmokeLoopId.
Referenced by SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
SetSoundSmokeStart()
void SetSoundSmokeStart (string sound)
Definition at line 59 of file smokegrenadebase.c.
    {
        m_SoundSmokeStartId = sound;
    }
References m_SoundSmokeStartId.
Referenced by SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
SmokeGrenadeBase()
void SmokeGrenadeBase ()
no effect on base
no effect on base
no effect on base
Definition at line 271 of file smokegrenadebase.c.
    {
        m_SmokeGrenadeState = ESmokeGrenadeState.NO_SMOKE;
        m_TimerSmokeLoop = new Timer;
        m_TimerDefer = new Timer;
        SetAmmoType("");
        SetPinnable(false);
        SetGrenadeType(EGrenadeType.CHEMICAL);
        SetParticleSmokeStart(ParticleList.INVALID);
        SetParticleSmokeLoop(ParticleList.INVALID);
        SetParticleSmokeEnd(ParticleList.INVALID);
        RegisterNetSyncVariableInt("m_SmokeGrenadeState", ESmokeGrenadeState.NO_SMOKE, ESmokeGrenadeState.COUNT);
    }
References ParticleList::INVALID, m_SmokeGrenadeState, m_TimerDefer, m_TimerSmokeLoop, SetAmmoType(), SetParticleSmokeEnd(), SetParticleSmokeLoop(), and SetParticleSmokeStart().
SoundSmokeEnd()
protected void SoundSmokeEnd ()
Definition at line 89 of file smokegrenadebase.c.
    {
        PlaySoundSetLoop(m_SoundSmoke, m_SoundSmokeEndId, 1.0, 1.0);
    }
References m_SoundSmoke, m_SoundSmokeEndId, and PlaySoundSetLoop().
Referenced by RefreshParticlesAndSounds().
SoundSmokeLoop()
protected void SoundSmokeLoop ()
Definition at line 84 of file smokegrenadebase.c.
    {
        PlaySoundSetLoop(m_SoundSmoke, m_SoundSmokeLoopId, 0.3, 1.0);
    }
References m_SoundSmoke, m_SoundSmokeLoopId, and PlaySoundSetLoop().
Referenced by RefreshParticlesAndSounds().
SoundSmokeStart()
protected void SoundSmokeStart ()
Definition at line 79 of file smokegrenadebase.c.
    {
        PlaySoundSetLoop(m_SoundSmoke, m_SoundSmokeStartId, 0.3, 1.0);
    }
References m_SoundSmoke, m_SoundSmokeStartId, and PlaySoundSetLoop().
Referenced by RefreshParticlesAndSounds().
SoundSmokeStop()
protected void SoundSmokeStop ()
Definition at line 95 of file smokegrenadebase.c.
    {
        StopSoundSet(m_SoundSmoke);
    }
References m_SoundSmoke, and StopSoundSet().
Referenced by EEDelete(), and RefreshParticlesAndSounds().
Unpin()
override void Unpin ()
Definition at line 158 of file smokegrenadebase.c.
    {
        super.Unpin();
        Activate();
    }
References Activate().
~SmokeGrenadeBase()
void ~SmokeGrenadeBase ()
Variable Documentation
m_LastSmokeGrenadeState
protected ESmokeGrenadeState m_LastSmokeGrenadeState
Definition at line 20 of file smokegrenadebase.c.
Referenced by RefreshParticlesAndSounds().
m_NoisePar
ref NoiseParams m_NoisePar
Noise.
Definition at line 37 of file smokegrenadebase.c.
m_ParticleSmoke
protected Particle m_ParticleSmoke
particle
Definition at line 23 of file smokegrenadebase.c.
Referenced by BuildingSuper::EEDelete(), EEDelete(), BuildingSuper::EEInit(), PlaySmokeParticle(), and RefreshParticlesAndSounds().
m_ParticleSmokeCurrentId
protected int m_ParticleSmokeCurrentId
Definition at line 24 of file smokegrenadebase.c.
Referenced by PlaySmokeParticle(), and SetParticleSmokeCurrent().
m_ParticleSmokeEndId
protected int m_ParticleSmokeEndId
Definition at line 27 of file smokegrenadebase.c.
Referenced by RefreshParticlesAndSounds(), and SetParticleSmokeEnd().
m_ParticleSmokeLoopId
protected int m_ParticleSmokeLoopId
Definition at line 26 of file smokegrenadebase.c.
Referenced by RefreshParticlesAndSounds(), and SetParticleSmokeLoop().
m_ParticleSmokePosition
protected vector m_ParticleSmokePosition
Definition at line 28 of file smokegrenadebase.c.
m_ParticleSmokeStartId
protected int m_ParticleSmokeStartId
Definition at line 25 of file smokegrenadebase.c.
Referenced by RefreshParticlesAndSounds(), and SetParticleSmokeStart().
m_SmokeGrenadeState
protected ESmokeGrenadeState m_SmokeGrenadeState
Definition at line 19 of file smokegrenadebase.c.
Referenced by GetSmokeGrenadeState(), SetSmokeGrenadeState(), and SmokeGrenadeBase().
m_SoundSmoke
protected EffectSound m_SoundSmoke
sounds
Definition at line 31 of file smokegrenadebase.c.
Referenced by SoundSmokeEnd(), SoundSmokeLoop(), SoundSmokeStart(), and SoundSmokeStop().
m_SoundSmokeEndId
protected string m_SoundSmokeEndId
Definition at line 34 of file smokegrenadebase.c.
Referenced by SetSoundSmokeEnd(), and SoundSmokeEnd().
m_SoundSmokeLoopId
protected string m_SoundSmokeLoopId
Definition at line 33 of file smokegrenadebase.c.
Referenced by SetSoundSmokeLoop(), and SoundSmokeLoop().
m_SoundSmokeStartId
protected string m_SoundSmokeStartId
Definition at line 32 of file smokegrenadebase.c.
Referenced by SetSoundSmokeStart(), and SoundSmokeStart().
m_TimerDefer
protected ref Timer m_TimerDefer
Definition at line 17 of file smokegrenadebase.c.
Referenced by OnWorkStop(), and SmokeGrenadeBase().
m_TimerSmokeEnd
protected ref Timer m_TimerSmokeEnd
Definition at line 15 of file smokegrenadebase.c.
m_TimerSmokeLoop
protected ref Timer m_TimerSmokeLoop
Definition at line 14 of file smokegrenadebase.c.
Referenced by OnWorkStart(), and SmokeGrenadeBase().
m_TimerSmokeStart
enum ESmokeGrenadeState m_TimerSmokeStart