DayzKode: P:/scripts/4_world/DayZ/classes/playersymptoms/smptanimmeta.c File Reference
smptanimmeta.c File Reference
Classes
class SmptAnimMetaADD
class SmptAnimMetaBase
Enumerations
enum eAnimFinishType { SUCCESS , FAILURE }
Functions
void AnimFinished (eAnimFinishType type)
void Init (ParamsReadContext ctx, SymptomManager manager, PlayerBase player)
bool IsDestroyReqested ()
bool IsPlaying ()
protected EAnimPlayState Play ()
EAnimPlayState PlayRequest ()
void SmptAnimMetaBase ()
void Update (HumanMovementState movement_state)
Variables
int m_AnimID
class SmptAnimMetaFB extends SmptAnimMetaBase m_CalledAnimStart
bool m_Canceled
bool m_DestroyRequested
enum eAnimFinishType m_IsPlaying
SymptomManager m_Manager
PlayerBase m_Player
int m_SymptomType
Enumeration Type Documentation
eAnimFinishType
enum eAnimFinishType
Enumerator
SUCCESS
FAILURE
Definition at line 1 of file smptanimmeta.c.
{
    SUCCESS,
    FAILURE,
}
Function Documentation
AnimFinished()
void AnimFinished (eAnimFinishType type)
Definition at line 37 of file smptanimmeta.c.
    {
        m_DestroyRequested = true;
        SymptomBase Symptom = m_Manager.GetCurrentPrimaryActiveSymptom();
        if( type == eAnimFinishType.FAILURE)//   <--------------- FAILED
        {
            if( m_Player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer())
            {
                if( Symptom )
                {
                    Symptom.AnimationPlayFailed();
                }
            }
        }
        else if( type == eAnimFinishType.SUCCESS)//   <--------------- SUCCESS
        {
            if( m_Player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer())
            {
                if( Symptom )
                {
                    Symptom.AnimationFinish();
                }
            }
        }
    }
References SymptomBase::AnimationFinish(), SymptomBase::AnimationPlayFailed(), SymptomManager::GetCurrentPrimaryActiveSymptom(), GetGame(), m_DestroyRequested, m_Manager, and m_Player.
Init()
override void Init (ParamsReadContext ctx, SymptomManager manager, PlayerBase player)
Definition at line 21 of file smptanimmeta.c.
    {
        m_Manager = manager;
        m_Player = player;
    }
References m_Manager, and m_Player.
IsDestroyReqested()
bool IsDestroyReqested ()
Definition at line 32 of file smptanimmeta.c.
    {
        return m_DestroyRequested;
    }
References m_DestroyRequested.
IsPlaying()
bool IsPlaying ()
Definition at line 27 of file smptanimmeta.c.
    {
        return m_IsPlaying;
    }
References m_IsPlaying.
Play()
override EAnimPlayState Play ()
Definition at line 143 of file smptanimmeta.c.
    {
        HumanCommandActionCallback callback = m_Player.GetCommand_Action();
        if (!callback)
        {
            callback = m_Player.GetCommandModifier_Action();
        }
        if( !callback )
        {
            HumanCommandWeapons hcw = m_Player.GetCommandModifier_Weapons();
            if (hcw && !hcw.IsActionFinished())
                return EAnimPlayState.FAILED;
            HumanCommandAdditives ad = m_Player.GetCommandModifier_Additives();
            if(ad)
            {
                //Print("------------------ Playing -----------------");
                ad.StartModifier(m_AnimID);
                m_IsPlaying = true;
                return EAnimPlayState.OK;
            }
        }
        return EAnimPlayState.FAILED;
    }
References HumanCommandAdditives(), HumanCommandWeapons::IsActionFinished(), m_AnimID, m_IsPlaying, and m_Player.
Referenced by UIScriptedMenu::OnClick(), and UIScriptedMenu::OnKeyPress().
PlayRequest()
EAnimPlayState PlayRequest ()
Definition at line 64 of file smptanimmeta.c.
    {
        EAnimPlayState played = Play();
        if(played == EAnimPlayState.FAILED)
        {
            m_Manager.OnAnimationFinished(eAnimFinishType.FAILURE);
        }
        return played;
    }
References m_Manager, SymptomManager::OnAnimationFinished(), and SmptAnimMetaBase::Play().
SmptAnimMetaBase()
void SmptAnimMetaBase ()
Definition at line 17 of file smptanimmeta.c.
    {
    }
Update()
override void Update (HumanMovementState movement_state)
Definition at line 169 of file smptanimmeta.c.
    {
        if( m_IsPlaying )
        {
            HumanCommandAdditives ad = m_Player.GetCommandModifier_Additives();
            if(!ad || !ad.IsModifierActive())
            {
                //Print("------------------ Not Playing -----------------");
                m_Manager.OnAnimationFinished();
            }
            else
            {
                if(!m_CalledAnimStart)
                {
                    m_Manager.OnAnimationStarted();
                    m_CalledAnimStart = true;
                }
            }
        }
    }
References HumanCommandAdditives(), m_CalledAnimStart, m_IsPlaying, m_Manager, m_Player, SymptomManager::OnAnimationFinished(), and SymptomManager::OnAnimationStarted().
Variable Documentation
m_AnimID
int m_AnimID
Definition at line 12 of file smptanimmeta.c.
Referenced by SmptAnimMetaBase::Init(), SmptAnimMetaBase::Play(), and Play().
m_CalledAnimStart
class SmptAnimMetaFB extends SmptAnimMetaBase m_CalledAnimStart
Referenced by Update().
m_Canceled
bool m_Canceled
Definition at line 15 of file smptanimmeta.c.
Referenced by EndActionComponent(), and SmptAnimMetaBase::Play().
m_DestroyRequested
bool m_DestroyRequested
Definition at line 14 of file smptanimmeta.c.
Referenced by AnimFinished(), and IsDestroyReqested().
m_IsPlaying
enum eAnimFinishType m_IsPlaying
Referenced by IsPlaying(), Play(), and Update().
m_Manager
SymptomManager m_Manager
Definition at line 10 of file smptanimmeta.c.
Referenced by AnimFinished(), Init(), PlayRequest(), and Update().
m_Player
PlayerBase m_Player
Definition at line 11 of file smptanimmeta.c.
Referenced by AnimFinished(), Init(), Play(), and Update().
m_SymptomType
int m_SymptomType
Definition at line 13 of file smptanimmeta.c.
Referenced by SymptomBase::OnInit().