DayzKode: P:/scripts/4_world/DayZ/classes/softskillsmanager.c File Reference
softskillsmanager.c File Reference
Classes
class SoftSkillsManager
Functions
SoftSkillsManager GetActiveSoftSkillManager ()
void OnUpdate ()
void SoftSkillManagerDebug (SoftSkillsManager softskill_manager)
void ~SoftSkillManagerDebug ()
Variables
TextWidget ComponentBonusAfter
TextWidget ComponentBonusBefore
TextWidget CoolDown
TextWidget GeneralBonusAfter
TextWidget GeneralBonusBefore
TextWidget IsCoolDown
ref Widget m_PanelSoftSkills
class SoftSkillsManager m_SoftSkillManager
TextWidget SpecialtyChange
TextWidget SpecialtyTotal
Function Documentation
GetActiveSoftSkillManager()
SoftSkillsManager GetActiveSoftSkillManager ()
Definition at line 612 of file softskillsmanager.c.
    {
        return m_SoftSkillManager;
    }
References m_SoftSkillManager.
Referenced by OnUpdate().
SoftSkillManagerDebug()
void SoftSkillManagerDebug (SoftSkillsManager softskill_manager)
Definition at line 575 of file softskillsmanager.c.
    {
        m_SoftSkillManager = softskill_manager;
        m_PanelSoftSkills = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_hud_debug_softskills.layout");
        GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Insert(this.OnUpdate);
        Class.CastTo(SpecialtyTotal,  m_PanelSoftSkills.FindWidget("SpecialtyTotal"));
        Class.CastTo(SpecialtyChange,  m_PanelSoftSkills.FindWidget("SpecialtyChange"));
        Class.CastTo(ComponentBonusBefore,  m_PanelSoftSkills.FindWidget("ComponentBonusBefore"));
        Class.CastTo(ComponentBonusAfter,  m_PanelSoftSkills.FindWidget("ComponentBonusAfter"));
        Class.CastTo(GeneralBonusBefore,  m_PanelSoftSkills.FindWidget("GeneralBonusBefore"));
        Class.CastTo(GeneralBonusAfter,  m_PanelSoftSkills.FindWidget("GeneralBonusAfter"));
        Class.CastTo(CoolDown,  m_PanelSoftSkills.FindWidget("CoolDown"));
        Class.CastTo(IsCoolDown,  m_PanelSoftSkills.FindWidget("IsCoolDown"));
        m_PanelSoftSkills.Show( true );
        SpecialtyTotal.Show( true );
        SpecialtyChange.Show( true );
        ComponentBonusBefore.Show( true );
        ComponentBonusAfter.Show( true );
        GeneralBonusBefore.Show( true );
        GeneralBonusAfter.Show( true );
        CoolDown.Show( true );
        IsCoolDown.Show( true );
    }
References CALL_CATEGORY_SYSTEM, Class::CastTo(), ComponentBonusAfter, ComponentBonusBefore, CoolDown, WorkspaceWidget::CreateWidgets(), GeneralBonusAfter, GeneralBonusBefore, GetGame(), CGame::GetUpdateQueue(), CGame::GetWorkspace(), ScriptInvoker::Insert(), IsCoolDown, m_PanelSoftSkills, m_SoftSkillManager, OnUpdate(), SpecialtyChange, and SpecialtyTotal.
Referenced by SoftSkillsManager::CreateDebugWindow().
~SoftSkillManagerDebug()
void ~SoftSkillManagerDebug ()
Definition at line 602 of file softskillsmanager.c.
    {
        if ( GetGame() )
        {
            GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Remove(this.OnUpdate);
        }
        delete m_PanelSoftSkills;
    }
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), m_PanelSoftSkills, OnUpdate(), and ScriptInvoker::Remove().
Variable Documentation
ComponentBonusAfter
TextWidget ComponentBonusAfter
Definition at line 569 of file softskillsmanager.c.
Referenced by OnUpdate(), and SoftSkillManagerDebug().
ComponentBonusBefore
TextWidget ComponentBonusBefore
Definition at line 568 of file softskillsmanager.c.
Referenced by OnUpdate(), and SoftSkillManagerDebug().
CoolDown
TextWidget CoolDown
Definition at line 572 of file softskillsmanager.c.
Referenced by OnUpdate(), and SoftSkillManagerDebug().
GeneralBonusAfter
TextWidget GeneralBonusAfter
Definition at line 571 of file softskillsmanager.c.
Referenced by OnUpdate(), and SoftSkillManagerDebug().
GeneralBonusBefore
TextWidget GeneralBonusBefore
Definition at line 570 of file softskillsmanager.c.
Referenced by OnUpdate(), and SoftSkillManagerDebug().
IsCoolDown
TextWidget IsCoolDown
Definition at line 573 of file softskillsmanager.c.
Referenced by OnUpdate(), and SoftSkillManagerDebug().
m_PanelSoftSkills
ref Widget m_PanelSoftSkills
Definition at line 565 of file softskillsmanager.c.
Referenced by SoftSkillManagerDebug(), and ~SoftSkillManagerDebug().
m_SoftSkillManager
class SoftSkillsManager m_SoftSkillManager
Referenced by GetActiveSoftSkillManager(), and SoftSkillManagerDebug().
SpecialtyChange
TextWidget SpecialtyChange
Definition at line 567 of file softskillsmanager.c.
Referenced by OnUpdate(), and SoftSkillManagerDebug().
SpecialtyTotal
TextWidget SpecialtyTotal
Definition at line 566 of file softskillsmanager.c.
Referenced by OnUpdate(), and SoftSkillManagerDebug().