DayzKode: P:/scripts/3_game/DayZ/sound.c File Reference
sound.c File Reference
Classes
class AbstractWave
class SoundObjectBuilder
class SoundParams
Enumerations
enum WaveKind
Functions
enum WaveKind AbstractSoundScene ()
SoundObject BuildSoundObject ()
proto native SoundObject BuildSoundObject (SoundObjectBuilder soundObjectbuilder)
proto native float GetAudioLevel ()
proto native float GetMusicVolume ()
proto native vector GetPosition ()
Retrieve position.
proto native float GetRadioVolume ()
proto native float GetSilenceThreshold ()
proto native float GetSoundVolume ()
proto native float GetSpeechExVolume ()
proto native float GetVOIPVolume ()
proto native void Initialize (SoundParams soundParams)
proto native AbstractWave Play2D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
proto native AbstractWave Play3D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
proto native void SetKind (WaveKind kind)
proto native void SetMusicVolume (float vol, float time)
proto native void SetOcclusionObstruction (float occlusion, float obstruction)
proto native void SetPosition (vector position)
Set the world position of the Effect.
proto native void SetRadioVolume (float vol, float time)
proto native void SetSoundVolume (float vol, float time)
proto native void SetSpeechExVolume (float vol, float time)
proto native void SetVariable (string name, float value)
proto native void SetVOIPVolume (float vol, float time)
class SoundObjectBuilder SoundObject (SoundParams soundParams)
void SoundObjectBuilder (SoundParams soundParams)
proto native void UpdateEnvSoundControllers (vector position)
private void ~AbstractSoundScene ()
Variables
ref ScriptInvoker Event_OnSoundWaveEnded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveHeaderLoaded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveLoaded = new ScriptInvoker()
class SoundParams Event_OnSoundWaveStarted = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveStopped = new ScriptInvoker()
WAVEATTALWAYS
WAVEEFFECT
WAVEEFFECTEX
WAVEENVIRONMENT
WAVEENVIRONMENTEX
WAVEMUSIC
WAVESPEECH
WAVESPEECHEX
WAVEUI
WAVEWEAPONS
WAVEWEAPONSEX
Enumeration Type Documentation
WaveKind
enum WaveKind
Definition at line 1 of file sound.c.
{
    WAVEEFFECT,
    WAVEEFFECTEX,
    WAVESPEECH,
    WAVEMUSIC,
    WAVESPEECHEX,
    WAVEENVIRONMENT,
    WAVEENVIRONMENTEX,
    WAVEWEAPONS,
    WAVEWEAPONSEX,
    WAVEATTALWAYS,
    WAVEUI
}
Function Documentation
AbstractSoundScene()
enum WaveKind AbstractSoundScene ()
Definition at line 1 of file sound.c.
{}
BuildSoundObject() [1/2]
SoundObject SoundObject::BuildSoundObject ()
Definition at line 2 of file sound.c.
{
    WAVEEFFECT,
    WAVEEFFECTEX,
    WAVESPEECH,
References WAVEEFFECT, WAVEEFFECTEX, WAVEMUSIC, and WAVESPEECH.
BuildSoundObject() [2/2]
proto native SoundObject BuildSoundObject (SoundObjectBuilder soundObjectbuilder)
GetAudioLevel()
proto native float GetAudioLevel ()
Referenced by ScriptedWidgetEventHandler::UpdateAudioLevel().
GetMusicVolume()
proto native float GetMusicVolume ()
GetPosition()
proto native vector GetPosition ()
Retrieve position.
Retrieve position.
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
vector The world position of the Effect
Definition at line 44 of file undergroundarealoader.c.
    {
        return Vector(Position[0],Position[1],Position[2]);
    }
References m_AreaPosition, and m_Position.
Referenced by FireplaceBase::AfterStoreLoad(), UIScriptedMenu::CameraToolsMenu(), DayZInfected::ChaseAttackLogic(), CheckAllowUpdate(), CommandHandler(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), CreateLight(), Grenade_Base::CreateLight(), ItemBase::CreateRope(), CreateTrigger(), VicinityItemManager::DebugActorsSphereDraw(), VicinityItemManager::DebugObjectsSphereDraw(), KitBase::DisassembleKit(), ItemBase::DoMeasurement(), UIScriptedMenu::DrawItems(), ManBase::DropItem(), ContaminatedArea_Dynamic::EEInit(), House::EEInit(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), FlammableBase::EEItemDetached(), Ammo_40mm_Explosive::EEKilled(), ContaminatedArea_Dynamic::EEOnCECreate(), Inventory_Base::EmptySeedPack(), DynamicArea_Flare::EOnFrame(), DayZSpectator::EOnFrame(), FireplaceBase::EOnTouch(), EOnTouch(), DayZInfected::EvaluateCrawlTransitionAnimation(), EvaluateDamageHitAnimation(), EvaluateDeathAnimation(), Hit_MeatBones::Event_OnStarted(), Explode(), ExplosionEffects(), ExplosivesBase(), DayZInfected::FightAttackLogic(), DayZInfected::FightLogic(), GenerateCarHornAINoise(), DayZInfected::GetAttackPitch(), GetCeilingHeight(), GetCenter(), GetClosestCarWheel(), GetClosestDoor(), GetEmptyingEndSoundset(), GetEmptyingLoopSoundset(), ItemBase::GetKitSpawnPosition(), BaseBuildingBase::GetKitSpawnPosition(), GetSurfaceNoise(), EntityLightSource::HandleDancingShadows(), HandleDoorsSound(), HandleInputData(), BaseBuildingBase::HandleRefreshers(), HandleView(), Heating(), BaseBuildingBase::InsertRefresherPosition(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), ManBase::IsFacingTarget(), BaseBuildingBase::IsPlayerInside(), TentBase::IsPlayerInside(), RemoteDetonatorTrigger::OnActivatedByItem(), CarScript::OnAnimationPhaseStarted(), OnCEUpdate(), RemoteDetonatorTrigger::OnCEUpdate(), BaseBuildingBase::OnCEUpdate(), UIScriptedMenu::OnClick(), ManBase::OnConnect(), Grenade_ChemGas::OnDamageDestroyed(), RifleSingleShot_Base::OnDebugSpawn(), KitBase::OnDebugSpawn(), OnDebugSpawn(), FireworksLauncher::OnEventServer(), Grenade_ChemGas::OnExplode(), OnExplodeClient(), Weapon::OnFireModeChange(), FireworksLauncher::OnFuseIgnitedClient(), PluginBase::OnGUITimer(), FireplaceBase::OnIgnitedThis(), GardenBase::OnPlacementComplete(), KitBase::OnPlacementComplete(), InventoryItem::OnRPC(), OnRPC(), OnStepEvent(), OnSteppedOn(), GardenBase::OnStoreLoad(), ItemBase::OnStoreLoad(), UIScriptedMenu::OnTabSeleted(), AlarmClock_ColorBase::OnUpdate(), KitchenTimer::OnUpdate(), BotStateBase::OnUpdate(), OnWork(), OnWorkStart(), ItemBase::ParticleTest(), BaseBuildingBase::PerformRoofCheckForBase(), ItemBase::PlaceOnGround(), InventoryItem::PlayAttachSound(), InventoryItem::PlayDeployFinishSound(), ItemBase::PlayDeployLoopSound(), Inventory_Base::PlayDeployLoopSound(), PlayDeployLoopSound(), InventoryItem::PlayDeploySound(), PlayDisarmingLoopSound(), EntityAI::PlayImpactSound(), InventoryItem::PlayPlaceSound(), PlayRepackingLoopSound(), Clothing::PlayRepackingLoopSound(), DayZCreature::PlaySound(), EntityAI::PlaySound(), PlaySound(), PlaySoundActivate(), TrapBase::PlaySoundBiteEmpty(), TrapBase::PlaySoundBiteLeg(), PlaySoundEx(), TrapBase::PlaySoundOpen(), PlayVFX(), DayZCreature::ProcessSoundEvent(), ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), RefreshFireplaceVisuals(), ItemBase::RemovePlant(), BaseBuildingBase::RemoveRefresherPosition(), House::RequestSoundEvent(), ManBase::SaySoundSet(), ManBase::SetContaminatedEffectEx(), SetParticlePosition(), BaseBuildingBase::SetRefresherActive(), Barrel_ColorBase::SoundBarrelClosePlay(), FireplaceBase::SoundBarrelClosePlay(), Barrel_ColorBase::SoundBarrelOpenPlay(), FireplaceBase::SoundBarrelOpenPlay(), EffectSound::SoundLoadEx(), EffectSound::SoundPlayEx(), ItemBase::SoundTentClosePlay(), ItemBase::SoundTentCloseWindowPlay(), ItemBase::SoundTentOpenPlay(), ItemBase::SoundTentOpenWindowPlay(), ItemBase::SpawnCatch(), TrapSpawnBase::SpawnCatch(), ManBase::SpawnEntityOnGroundOnCursorDir(), TentBase::SpawnKit(), PluginBase::SpawnNewInfectedEntity(), CrashBase::SpawnRandomDeers(), UndergroundTriggerCarrierBase::SpawnTrigger(), FlammableBase::StandUp(), EffectParticle::Start(), StartActivate(), Particle::StopParticle(), TestOwnership(), EntityLightSource::TryShadowOptimization(), FlammableBase::TryTransformIntoStick(), AreaDamageTriggerBase::UpdateInsiders(), ManBase::UpdatePlayerMeasures(), and ScriptedWidgetEventHandler::UpdatePos().
GetRadioVolume()
proto native float GetRadioVolume ()
GetSilenceThreshold()
proto native float GetSilenceThreshold ()
GetSoundVolume()
proto native float GetSoundVolume ()
GetSpeechExVolume()
proto native float GetSpeechExVolume ()
GetVOIPVolume()
proto native float GetVOIPVolume ()
Initialize()
proto native void Initialize (SoundParams soundParams)
Play2D()
proto native AbstractWave Play2D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
Play3D()
proto native AbstractWave Play3D (SoundObject soundObject, SoundObjectBuilder soundBuilder)
SetKind()
proto native void SetKind (WaveKind kind)
SetMusicVolume()
proto native void SetMusicVolume (float vol, float time)
SetOcclusionObstruction()
proto native void SetOcclusionObstruction (float occlusion, float obstruction)
SetRadioVolume()
proto native void SetRadioVolume (float vol, float time)
SetSoundVolume()
proto native void SetSoundVolume (float vol, float time)
SetSpeechExVolume()
proto native void SetSpeechExVolume (float vol, float time)
SetVariable()
proto native void SoundObject::SetVariable (string name, float value)
SetVOIPVolume()
proto native void SetVOIPVolume (float vol, float time)
SoundObject()
class SoundObjectBuilder SoundObject (SoundParams soundParams)
Referenced by HandleView(), OnStepEvent(), EntityAI::PlayImpactSound(), MissionBase::PlayMusic(), ProcessAttachmentEvent(), DayZCreature::ProcessSoundEvent(), ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), ProcessVoiceEvent(), DayZInfected::ProcessVoiceFX(), and ProcessWeaponEvent().
SoundObjectBuilder()
void SoundObject::SoundObjectBuilder (SoundParams soundParams)
UpdateEnvSoundControllers()
proto native void SoundObject::UpdateEnvSoundControllers (vector position)
~AbstractSoundScene()
private void ~AbstractSoundScene ()
Definition at line 19 of file sound.c.
{}
Variable Documentation
Event_OnSoundWaveEnded
ref ScriptInvoker Event_OnSoundWaveEnded = new ScriptInvoker()
Definition at line 87 of file sound.c.
Event_OnSoundWaveHeaderLoaded
ref ScriptInvoker Event_OnSoundWaveHeaderLoaded = new ScriptInvoker()
Definition at line 86 of file sound.c.
Event_OnSoundWaveLoaded
ref ScriptInvoker Event_OnSoundWaveLoaded = new ScriptInvoker()
Definition at line 85 of file sound.c.
Event_OnSoundWaveStarted
class SoundParams Event_OnSoundWaveStarted = new ScriptInvoker()
Event_OnSoundWaveStopped
ref ScriptInvoker Event_OnSoundWaveStopped = new ScriptInvoker()
Definition at line 84 of file sound.c.
WAVEATTALWAYS
WAVEATTALWAYS
Definition at line 28 of file sound.c.
WAVEEFFECT
WAVEEFFECT
Definition at line 19 of file sound.c.
Referenced by BuildSoundObject().
WAVEEFFECTEX
WAVEEFFECTEX
Definition at line 20 of file sound.c.
Referenced by BuildSoundObject().
WAVEENVIRONMENT
WAVEENVIRONMENT
Definition at line 24 of file sound.c.
WAVEENVIRONMENTEX
WAVEENVIRONMENTEX
Definition at line 25 of file sound.c.
WAVEMUSIC
WAVEMUSIC
Definition at line 22 of file sound.c.
Referenced by BuildSoundObject().
WAVESPEECH
WAVESPEECH
Definition at line 21 of file sound.c.
Referenced by BuildSoundObject().
WAVESPEECHEX
WAVESPEECHEX
Definition at line 23 of file sound.c.
WAVEUI
WAVEUI
Definition at line 29 of file sound.c.
WAVEWEAPONS
WAVEWEAPONS
Definition at line 26 of file sound.c.
WAVEWEAPONSEX
WAVEWEAPONSEX
Definition at line 27 of file sound.c.