DayzKode: P:/scripts/4_world/DayZ/classes/soundevents/playersoundevents/events/staminaevents.c File Reference
staminaevents.c File Reference
Classes
class PlayerSoundEventBase
class StaminaLowFilterBase
class StaminaSoundEventBase
Functions
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override void OnPlay (PlayerBase player)
void StaminaDownHeavy ()
class StaminaSoundEventBase extends PlayerSoundEventBase StaminaDownLight ()
class StaminaNormalDummy extends StaminaSoundEventBase StaminaLowFilterBase ()
class StaminaLowFilterUpper extends StaminaLowFilterBase StaminaLowFilterMid ()
void StaminaLowFilterUpper ()
void StaminaNormalDummy ()
void StaminaSoundEventBase ()
class StaminaUpLight extends StaminaSoundEventBase StaminaUpEnd ()
class StaminaDownHeavy extends StaminaSoundEventBase StaminaUpHeavy ()
void StaminaUpLight ()
Variables
const int MAX_VOLUME = 4
Function Documentation
HasPriorityOverCurrent()
override bool StaminaDownLight::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Definition at line 56 of file staminaevents.c.
{
    void StaminaDownHeavy()
    {
        m_ID = EPlayerSoundEventID.STAMINA_DOWN_HEAVY;
OnPlay()
override void StaminaDownLight::OnPlay (PlayerBase player)
!! beware of the ifdef above , most likely you want to put your code above it, otherwise it might not get executed !!!
Definition at line 61 of file staminaevents.c.
{
    void StaminaUpHeavy()
    {
        m_ID = EPlayerSoundEventID.STAMINA_UP_HEAVY;
        m_SoundVoiceAnimEventClassID = 3;
    }
}
class StaminaUpLight extends StaminaSoundEventBase
{
    void StaminaUpLight()
    {
        m_ID = EPlayerSoundEventID.STAMINA_UP_LIGHT;
        m_SoundVoiceAnimEventClassID = 4;
    }
}
class StaminaUpEnd extends StaminaSoundEventBase
{
    void StaminaUpEnd()
    {
        m_ID = EPlayerSoundEventID.STAMINA_UP_END;
        m_SoundVoiceAnimEventClassID = 26;
    }
StaminaDownHeavy()
void StaminaUpHeavy::StaminaDownHeavy ()
Definition at line 67 of file staminaevents.c.
    {
        m_ID = EPlayerSoundEventID.STAMINA_UP_HEAVY;
        m_SoundVoiceAnimEventClassID = 3;
    }
}
References m_ID, and m_SoundVoiceAnimEventClassID.
Referenced by PlayerSoundEventHandler().
StaminaDownLight()
class StaminaSoundEventBase extends PlayerSoundEventBase StaminaDownLight ()
Definition at line 1 of file staminaevents.c.
    {
        m_ID = EPlayerSoundEventID.STAMINA_DOWN_LIGHT;
        m_SoundVoiceAnimEventClassID = 1;
    }
Referenced by PlayerSoundEventHandler().
StaminaLowFilterBase()
class StaminaNormalDummy extends StaminaSoundEventBase StaminaLowFilterBase ()
Definition at line 96 of file staminaevents.c.
    {
        m_ProcessPlaybackEvent = true;
    }
StaminaLowFilterMid()
class StaminaLowFilterUpper extends StaminaLowFilterBase StaminaLowFilterMid ()
Definition at line 118 of file staminaevents.c.
    {
        m_ID = EPlayerSoundEventID.STAMINA_LOW_FILTER_MID;
        m_SoundVoiceAnimEventClassID = 32;
    }
Referenced by PlayerSoundEventHandler().
StaminaLowFilterUpper()
void StaminaLowFilterMid::StaminaLowFilterUpper ()
Definition at line 130 of file staminaevents.c.
    {
        m_ID = EPlayerSoundEventID.STAMINA_LOW_FILTER_MID;
        m_SoundVoiceAnimEventClassID = 32;
    }
}
References m_ID, and m_SoundVoiceAnimEventClassID.
Referenced by PlayerSoundEventHandler().
StaminaNormalDummy()
void StaminaLowFilterBase::StaminaNormalDummy ()
Definition at line 113 of file staminaevents.c.
    {
        m_ProcessPlaybackEvent = true;
    }
}
class StaminaLowFilterUpper extends StaminaLowFilterBase
{
    void StaminaLowFilterUpper()
References m_ProcessPlaybackEvent.
Referenced by PlayerSoundEventHandler().
StaminaSoundEventBase()
void StaminaDownLight::StaminaSoundEventBase ()
Definition at line 50 of file staminaevents.c.
{
StaminaUpEnd()
class StaminaUpLight extends StaminaSoundEventBase StaminaUpEnd ()
Definition at line 73 of file staminaevents.c.
    {
        m_ID = EPlayerSoundEventID.STAMINA_UP_END;
        m_SoundVoiceAnimEventClassID = 26;
    }
Referenced by PlayerSoundEventHandler().
StaminaUpHeavy()
class StaminaDownHeavy extends StaminaSoundEventBase StaminaUpHeavy ()
Definition at line 55 of file staminaevents.c.
    {
        m_ID = EPlayerSoundEventID.STAMINA_UP_HEAVY;
        m_SoundVoiceAnimEventClassID = 3;
    }
Referenced by PlayerSoundEventHandler().
StaminaUpLight()
void StaminaUpEnd::StaminaUpLight ()
Definition at line 85 of file staminaevents.c.
    {
        m_ID = EPlayerSoundEventID.STAMINA_UP_END;
        m_SoundVoiceAnimEventClassID = 26;
    }
References m_ID, and m_SoundVoiceAnimEventClassID.
Referenced by PlayerSoundEventHandler().
Variable Documentation
MAX_VOLUME
const int MAX_VOLUME = 4
Definition at line 49 of file staminaevents.c.
Referenced by PlayerSoundEventBase::OnPlay().