DayzKode: P:/scripts/4_world/DayZ/classes/staminahandler.c File Reference
staminahandler.c File Reference
Classes
class StaminaConsumers
class StaminaModifiers
Enumerations
enum EStaminaMultiplierTypes
Functions
void ActivateDepletionModifier (EStaminaMultiplierTypes type)
void ActivateRecoveryModifier (EStaminaMultiplierTypes type)
void AddRunTime (float val)
protected void ApplyExhaustion ()
protected float CalcStaminaGainBonus ()
Calulates stamina regain bonus coef based on current stamina cap and level.
protected void CheckStaminaState ()
check if the stamina is completely depleted
void DeactivateDepletionModifier (EStaminaMultiplierTypes type)
void DeactivateRecoveryModifier (EStaminaMultiplierTypes type)
void DepleteStamina (EStaminaModifiers modifier, float dT=-1)
float GetActivationThreshold ()
float GetCooldown ()
Timer GetCooldownTimer (int modifier)
float GetDepletionMultiplier ()
float GetDrainThreshold ()
float GetDuration ()
float GetDurationAdjusted ()
float GetMaxValue ()
float GetMinValue ()
float GetRecoveryMultiplier ()
float GetRunTime ()
float GetStamina ()
float GetStaminaCap ()
float GetStaminaMax ()
float GetStaminaNormalized ()
float GetStartTime ()
bool GetState ()
returns one of STATE_...
float GetSyncedStamina ()
float GetSyncedStaminaNormalized ()
int GetType ()
bool HasEnoughStaminaFor (EStaminaConsumers consumer)
bool HasEnoughStaminaFor (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap)
bool HasEnoughStaminaToStart (EStaminaConsumers consumer)
bool HasEnoughStaminaToStart (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap)
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
bool IsInUse ()
void OnRPC (float stamina, float stamina_cap, bool cooldown)
deprecated use, StaminaHandler uses SyncJunctures now
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
called from PlayerBase - syncs stamina values on server with client AND sets the value to match on server and client both (m_StaminaSynced guarantees identical values)
protected void ReadAdditionalStaminaInfo (ParamsReadContext pCtx)
Order of read parameters must match the order of writing above.
void RecalculateDepletionMultiplier ()
void RecalculateRecoveryMultiplier ()
void RegisterConsumer (EStaminaConsumers consumer, float threshold, float depletion_threshold=-1)
protected void RegisterStaminaConsumers ()
protected void RegisterStaminaModifiers ()
protected void ResetCooldown (int modifier=-1)
void ResetRunTime ()
void SetActivationThreshold (float threshold)
protected void SetCooldown (float time, int modifier=-1)
set cooldown timer between each consume of stamina
void SetCooldown (float val)
void SetDepletionMultiplier (float val)
void SetDrainThreshold (float threshold)
void SetInUse (bool val)
void SetMaxValue (float val)
void SetMinValue (float val)
void SetRecoveryMultiplier (float val)
void SetRunTimeTick (float val)
void SetStamina (float stamina_value)
void SetStartTime (float val)
void SetState (bool state)
void StaminaConsumer (float threshold, float threshold2, bool state)
void StaminaConsumers ()
void StaminaHandler (PlayerBase player)
void StaminaModifier (int type, float min, float max, float cooldown, float startTime=0, float duration=0)
protected void StaminaProcessor_Ladder (HumanMovementState pHumanMovementState)
protected void StaminaProcessor_Move (HumanMovementState pHumanMovementState)
protected void StaminaProcessor_Swimming (HumanMovementState pHumanMovementState)
protected void SyncAdditionalStaminaInfo (Param par)
Method to sync more info for stamina manager. Template parameter means it is very extendable for further use.
protected void SyncStamina (float stamina, float stamina_cap, bool cooldown)
stamina sync - server part
void Update (float deltaT, int pCurrentCommandID)
Variables
DROWNING
EPINEPHRINE
FATIGUE
m_ActivationThreshold
ref set< EStaminaMultiplierTypes > m_ActiveDepletionModifiers
ref set< EStaminaMultiplierTypes > m_ActiveRecoveryModifiers
float m_Cooldown
protected bool m_Debug
float m_Duration
m_InUse = false
protected bool m_IsInCooldown
float m_MaxValue
float m_MinValue
protected PlayerBase m_Player
class StaminaModifiers m_PlayerLoad
float m_ProgressTime
ref map< EStaminaMultiplierTypes, float > m_RegisteredDepletionModifiers
ref map< EStaminaMultiplierTypes, float > m_RegisteredRecoveryModifiers
protected float m_Stamina
protected float m_StaminaCap
protected ref map< EStaminaConsumers, ref StaminaConsumer > m_StaminaConsumers
protected float m_StaminaDelta
protected bool m_StaminaDepleted
DEPRECATED.
protected float m_StaminaDepletion
protected float m_StaminaDepletionMultiplier
protected ref StaminaModifiers m_StaminaModifiers
protected ref Param3< float, float, bool > m_StaminaParams
protected float m_StaminaRecoveryMultiplier
protected float m_StaminaSynced
float m_StartTime
protected float m_DrainThreshold protected bool m_State
float m_Tick
protected float m_Time
protected ref map< int, ref Timer > m_TimerMap
int m_Type
MASK = 1
Enumeration Type Documentation
EStaminaMultiplierTypes
enum EStaminaMultiplierTypes
Definition at line 1 of file staminahandler.c.
{
    MASK = 1,
    FATIGUE,
    EPINEPHRINE,
    DROWNING,
}
Function Documentation
ActivateDepletionModifier()
void ActivateDepletionModifier (EStaminaMultiplierTypes type)
Definition at line 317 of file staminahandler.c.
    {
        if (m_RegisteredDepletionModifiers.Contains(type))
        {
            m_ActiveDepletionModifiers.Insert(type);
            RecalculateDepletionMultiplier();
        }
        else
        {
            Error("attempting to activate unregistered depletion modifier");
        }
    }
References Error(), m_ActiveDepletionModifiers, m_RegisteredDepletionModifiers, and RecalculateDepletionMultiplier().
ActivateRecoveryModifier()
void ActivateRecoveryModifier (EStaminaMultiplierTypes type)
Definition at line 353 of file staminahandler.c.
    {
        if (m_RegisteredRecoveryModifiers.Contains(type))
        {
            m_ActiveRecoveryModifiers.Insert(type);
            RecalculateRecoveryMultiplier();
        }
        else
        {
            Error("attempting to activate unregistered recovery modifier");
        }
    }
References Error(), m_ActiveRecoveryModifiers, m_RegisteredRecoveryModifiers, and RecalculateRecoveryMultiplier().
AddRunTime()
void AddRunTime (float val)
Definition at line 173 of file staminahandler.c.
{ m_ProgressTime += val; }
References m_ProgressTime.
ApplyExhaustion()
protected void ApplyExhaustion ()
sets exhaustion look of player based on stamina level
Definition at line 713 of file staminahandler.c.
    {
        HumanCommandAdditives ad = m_Player.GetCommandModifier_Additives();
        float exhaustion_value = 1;
        if (m_StaminaCap != 0)
        {
            exhaustion_value = 1 - ((m_Stamina / (m_StaminaCap * 0.01)) * 0.01);
        }
        exhaustion_value = Math.Min(1, exhaustion_value);
        if (ad)
        {
            // do not apply exhaustion on local client if player is in ADS/Optics (camera shakes)
            if (m_Player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT && (m_Player.IsInOptics() || m_Player.IsInIronsights()))
            {
                ad.SetExhaustion(0, true);
            }
            else
            {
                ad.SetExhaustion(exhaustion_value, true);
            }
        }
    }
References HumanCommandAdditives(), m_Player, m_Stamina, m_StaminaCap, and Math::Min().
Referenced by Update().
CalcStaminaGainBonus()
protected float CalcStaminaGainBonus ()
Calulates stamina regain bonus coef based on current stamina cap and level.
Definition at line 702 of file staminahandler.c.
    {
        if (m_StaminaDepletion > 0)
            return 0;
        if (m_Stamina > 25)
            return Math.Min((m_Stamina/10),GameConstants.STAMINA_GAIN_BONUS_CAP); // exp version
        else
            return GameConstants.STAMINA_GAIN_BONUS_CAP; // linear version
    }
References m_Stamina, m_StaminaDepletion, Math::Min(), and GameConstants::STAMINA_GAIN_BONUS_CAP.
Referenced by StaminaProcessor_Ladder(), StaminaProcessor_Move(), and StaminaProcessor_Swimming().
CheckStaminaState()
protected void CheckStaminaState ()
check if the stamina is completely depleted
in case of complete depletion - start a cooldown timer before the regeneration cycle start
Definition at line 740 of file staminahandler.c.
    {
        if (m_Stamina <= 0)
        {
            m_StaminaDepleted = true;
            if (!m_IsInCooldown)
            {
                // set this only once
                SetCooldown(GameConstants.STAMINA_REGEN_COOLDOWN_EXHAUSTION);
            }
        }
        else
        {
            m_StaminaDepleted = false;
        }
    }
References m_IsInCooldown, m_Stamina, m_StaminaDepleted, SetCooldown(), and GameConstants::STAMINA_REGEN_COOLDOWN_EXHAUSTION.
Referenced by Update().
DeactivateDepletionModifier()
void DeactivateDepletionModifier (EStaminaMultiplierTypes type)
Definition at line 330 of file staminahandler.c.
    {
        int index = m_ActiveDepletionModifiers.Find(type);
        if (index != -1)
        {
            m_ActiveDepletionModifiers.Remove(index);
            RecalculateDepletionMultiplier();
        }
    }
References m_ActiveDepletionModifiers, and RecalculateDepletionMultiplier().
DeactivateRecoveryModifier()
void DeactivateRecoveryModifier (EStaminaMultiplierTypes type)
Definition at line 367 of file staminahandler.c.
    {
        int index = m_ActiveRecoveryModifiers.Find(type);
        if (index != -1)
        {
            m_ActiveRecoveryModifiers.Remove(index);
            RecalculateRecoveryMultiplier();
        }
    }
References m_ActiveRecoveryModifiers, and RecalculateRecoveryMultiplier().
DepleteStamina()
void DepleteStamina (EStaminaModifiers modifier, float dT = -1)
run cooldown right after depletion
Definition at line 876 of file staminahandler.c.
    {
        #ifdef DEVELOPER
        if (!m_StaminaEnabled || DiagMenu.GetBool(DiagMenuIDs.DM_CHEATS_STAMINA_DISABLE))
        {
            return;
        }
        #endif
        float val = 0.0;
        float current_time = m_Player.GetSimulationTimeStamp();
        float time;
        StaminaModifier sm = m_StaminaModifiers.GetModifierData(modifier);
        // select by modifier type and drain stamina
        switch (sm.GetType())
        {
            case m_StaminaModifiers.FIXED:
                if (dT == -1)
                {
                    dT = 1;
                }
                m_StaminaDepletion = m_StaminaDepletion + sm.GetMaxValue() * dT;
            break;
            case m_StaminaModifiers.RANDOMIZED:
                val = Math.RandomFloat(sm.GetMinValue(), sm.GetMaxValue());
                m_StaminaDepletion = m_StaminaDepletion + val;
            break;
            case m_StaminaModifiers.LINEAR:
                if (!sm.IsInUse())
                {
                    sm.SetStartTime(current_time + ( (PlayerSwayConstants.SWAY_TIME_IN + PlayerSwayConstants.SWAY_TIME_STABLE) / dT ) );
                    sm.SetRunTimeTick(dT);
                    sm.SetInUse(true);
                }
                time = Math.Clamp( ((current_time - sm.GetStartTime()) / sm.GetDurationAdjusted()), 0, 1 );
                val = Math.Lerp(sm.GetMinValue(), sm.GetMaxValue(), time);
                m_StaminaDepletion = m_StaminaDepletion + val;
            break;
            case m_StaminaModifiers.EXPONENTIAL:
                if (!sm.IsInUse())
                {
                    sm.SetStartTime(current_time + ( (PlayerSwayConstants.SWAY_TIME_IN + PlayerSwayConstants.SWAY_TIME_STABLE) / dT ) );
                    sm.SetRunTimeTick(dT);
                    sm.SetInUse(true);
                }
                time = Math.Clamp( ((current_time - sm.GetStartTime()) / sm.GetDurationAdjusted()), 0, 1 );
                float exp;
                if (sm.GetMinValue() < 1)
                {
                    exp = 1 - Math.Lerp(0, sm.GetMaxValue(), time);
                }
                else
                {
                    exp = Math.Lerp(0, sm.GetMaxValue(), time);
                }
                val = Math.Pow(sm.GetMinValue(),exp);
                m_StaminaDepletion = m_StaminaDepletion + val;
            break;
        }
        SetCooldown(sm.GetCooldown(),modifier);
        m_StaminaDepletion = Math.Clamp(m_StaminaDepletion, 0, CfgGameplayHandler.GetStaminaMax());
        m_StaminaDepletion = m_StaminaDepletion * m_StaminaDepletionMultiplier;
    }
References Math::Clamp(), StaminaModifiers::EXPONENTIAL, StaminaModifiers::FIXED, DiagMenu::GetBool(), StaminaModifiers::GetModifierData(), CfgGameplayHandler::GetStaminaMax(), Math::Lerp(), StaminaModifiers::LINEAR, m_Player, m_StaminaDepletion, m_StaminaDepletionMultiplier, m_StaminaModifiers, Math::Pow(), Math::RandomFloat(), StaminaModifiers::RANDOMIZED, SetCooldown(), and StaminaModifier().
Referenced by ManBase::OnRollStart(), and ManBase::ProcessHoldBreath().
GetActivationThreshold()
float GetActivationThreshold ()
Definition at line 32 of file staminahandler.c.
{ return m_ActivationThreshold; }
References m_ActivationThreshold.
GetCooldown()
float GetCooldown ()
Definition at line 160 of file staminahandler.c.
{ return m_Cooldown; }
References m_Cooldown.
GetCooldownTimer()
Timer GetCooldownTimer (int modifier)
Definition at line 797 of file staminahandler.c.
    {
    }
GetDepletionMultiplier()
float GetDepletionMultiplier ()
Definition at line 866 of file staminahandler.c.
    {
        return m_StaminaDepletionMultiplier;
    }
References m_StaminaDepletionMultiplier.
GetDrainThreshold()
float GetDrainThreshold ()
Definition at line 35 of file staminahandler.c.
{ return m_DrainThreshold; }
GetDuration()
float GetDuration ()
Definition at line 166 of file staminahandler.c.
{ return m_Duration; }
References m_Duration.
GetDurationAdjusted()
float GetDurationAdjusted ()
Definition at line 167 of file staminahandler.c.
{ return m_Duration / m_Tick; }
References m_Duration, and m_Tick.
GetMaxValue()
float GetMaxValue ()
Definition at line 157 of file staminahandler.c.
{ return m_MaxValue; }
References m_MaxValue.
GetMinValue()
float GetMinValue ()
Definition at line 154 of file staminahandler.c.
{ return m_MinValue; }
References m_MinValue.
GetRecoveryMultiplier()
float GetRecoveryMultiplier ()
Definition at line 871 of file staminahandler.c.
    {
        return m_StaminaRecoveryMultiplier;
    }
References m_StaminaRecoveryMultiplier.
GetRunTime()
float GetRunTime ()
Definition at line 172 of file staminahandler.c.
{ return m_ProgressTime; }
References m_ProgressTime.
GetStamina()
float GetStamina ()
Definition at line 819 of file staminahandler.c.
    {
        return m_Stamina;
    }
References m_Stamina.
GetStaminaCap()
float GetStaminaCap ()
Definition at line 839 of file staminahandler.c.
    {
        return m_StaminaCap;
    }
References m_StaminaCap.
GetStaminaMax()
float GetStaminaMax ()
Definition at line 844 of file staminahandler.c.
    {
        return CfgGameplayHandler.GetStaminaMax();
    }
References CfgGameplayHandler::GetStaminaMax().
Referenced by GetStaminaNormalized(), and GetSyncedStaminaNormalized().
GetStaminaNormalized()
float GetStaminaNormalized ()
Definition at line 824 of file staminahandler.c.
    {
        return m_Stamina / GetStaminaMax();
    }
References GetStaminaMax(), and m_Stamina.
Referenced by ManBase::ProcessDrowning().
GetStartTime()
float GetStartTime ()
Definition at line 163 of file staminahandler.c.
{ return m_StartTime; }
References m_StartTime.
GetState()
bool GetState ()
returns one of STATE_...
returns the state of climb (enum value of ClimbStates);
Definition at line 29 of file staminahandler.c.
{ return m_State; }
GetSyncedStamina()
float GetSyncedStamina ()
Definition at line 829 of file staminahandler.c.
    {
        return m_StaminaSynced;
    }
References m_StaminaSynced.
Referenced by GetSyncedStaminaNormalized().
GetSyncedStaminaNormalized()
float GetSyncedStaminaNormalized ()
Definition at line 834 of file staminahandler.c.
    {
        return GetSyncedStamina() / GetStaminaMax();
    }
References GetStaminaMax(), and GetSyncedStamina().
GetType()
int GetType ()
Definition at line 152 of file staminahandler.c.
{ return m_Type; }
References m_Type.
HasEnoughStaminaFor() [1/2]
bool HasEnoughStaminaFor (EStaminaConsumers consumer)
Definition at line 803 of file staminahandler.c.
    {
        return m_StaminaConsumers.HasEnoughStaminaFor(consumer, m_Stamina, m_StaminaDepleted, m_StaminaCap);
    }
References m_Stamina, m_StaminaCap, m_StaminaConsumers, and m_StaminaDepleted.
HasEnoughStaminaFor() [2/2]
bool Stamina::HasEnoughStaminaFor (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap)
Definition at line 63 of file staminahandler.c.
    {
        if ( m_StaminaConsumers && m_StaminaConsumers.Contains(consumer) )
        {
            StaminaConsumer sc = m_StaminaConsumers.Get(consumer);
            if ( consumer != EStaminaConsumers.SPRINT )
            {
                if ( (isDepleted || (curStamina < sc.GetDrainThreshold()/* && curStamina < cap*/)) )
                {
                    sc.SetState(false);
                    return false;
                }
            }
            else
            {
                if( !isDepleted )
                {
                    if ( sc.GetState() )
                    {
                        sc.SetState(true);
                        return true;
                    }
                }
                else
                {
                    sc.SetState(false);
                    return false;
                }
            }
            if ( curStamina > sc.GetDrainThreshold() || curStamina == cap ) //Sometimes player can't go up to drain threshold
            {
                sc.SetState(true);
                return true;
            }
        }
        return false;
    }
HasEnoughStaminaToStart() [1/2]
bool HasEnoughStaminaToStart (EStaminaConsumers consumer)
Definition at line 808 of file staminahandler.c.
    {
        return m_StaminaConsumers.HasEnoughStaminaToStart(consumer, m_Stamina, m_StaminaDepleted, m_StaminaCap);
    }
References m_Stamina, m_StaminaCap, m_StaminaConsumers, and m_StaminaDepleted.
HasEnoughStaminaToStart() [2/2]
bool Stamina::HasEnoughStaminaToStart (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap)
Definition at line 104 of file staminahandler.c.
    {
        if ( m_StaminaConsumers && m_StaminaConsumers.Contains(consumer) )
        {
            StaminaConsumer sc = m_StaminaConsumers.Get(consumer);
            if( (isDepleted || (curStamina < sc.GetActivationThreshold() && curStamina < cap)) )
            {
                sc.SetState(false);
                return false;
            }
            else
            {
                sc.SetState(true);
                return true;
            }
        }
        return false;
    }
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
Definition at line 303 of file staminahandler.c.
    {
        //----------------- depletion --------------------
        m_RegisteredDepletionModifiers.Insert(EStaminaMultiplierTypes.MASK, MaskMdfr.STAMINA_DEPLETION_MODIFIER);
        m_RegisteredDepletionModifiers.Insert(EStaminaMultiplierTypes.FATIGUE, FatigueMdfr.STAMINA_DEPLETION_MULTIPLIER);
        m_RegisteredDepletionModifiers.Insert(EStaminaMultiplierTypes.EPINEPHRINE, EpinephrineMdfr.STAMINA_DEPLETION_MULTIPLIER);
        //----------------- recovery --------------------
        m_RegisteredRecoveryModifiers.Insert(EStaminaMultiplierTypes.MASK, MaskMdfr.STAMINA_RECOVERY_MODIFIER);
        m_RegisteredRecoveryModifiers.Insert(EStaminaMultiplierTypes.FATIGUE, FatigueMdfr.STAMINA_RECOVERY_MULTIPLIER);
        m_RegisteredRecoveryModifiers.Insert(EStaminaMultiplierTypes.DROWNING, DrowningMdfr.STAMINA_RECOVERY_MULTIPLIER);
    }
References m_RegisteredDepletionModifiers, m_RegisteredRecoveryModifiers, MaskMdfr::STAMINA_DEPLETION_MODIFIER, FatigueMdfr::STAMINA_DEPLETION_MULTIPLIER, EpinephrineMdfr::STAMINA_DEPLETION_MULTIPLIER, MaskMdfr::STAMINA_RECOVERY_MODIFIER, FatigueMdfr::STAMINA_RECOVERY_MULTIPLIER, and DrowningMdfr::STAMINA_RECOVERY_MULTIPLIER.
IsInUse()
bool IsInUse ()
Definition at line 169 of file staminahandler.c.
{ return m_InUse; }
References m_InUse.
OnRPC()
void OnRPC (float stamina, float stamina_cap, bool cooldown)
deprecated use, StaminaHandler uses SyncJunctures now
Definition at line 485 of file staminahandler.c.
    {
    }
OnSyncJuncture()
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
called from PlayerBase - syncs stamina values on server with client AND sets the value to match on server and client both (m_StaminaSynced guarantees identical values)
Definition at line 490 of file staminahandler.c.
    {
        switch ( pJunctureID )
        {
        case DayZPlayerSyncJunctures.SJ_STAMINA:
            float stamina;
            float stamina_cap;
            bool cooldown;
            if (!pCtx.Read(stamina) || !pCtx.Read(stamina_cap) || !pCtx.Read(cooldown))
            {
                return;
            }
            m_Stamina = stamina; //?
            m_StaminaSynced = stamina;
            if (m_Player.GetInstanceType() != DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
            {
                return;
            }
            if ( stamina_cap != m_StaminaCap )
            {
                m_StaminaCap = stamina_cap;
            }
            m_IsInCooldown = cooldown;
            m_Player.SetStamina(m_Stamina, m_StaminaCap);
        break;
        case DayZPlayerSyncJunctures.SJ_STAMINA_MISC:
            ReadAdditionalStaminaInfo(pCtx);
        break;
        }
    }
References m_IsInCooldown, m_Player, m_Stamina, m_StaminaCap, m_StaminaSynced, Serializer::Read(), ReadAdditionalStaminaInfo(), DayZPlayerSyncJunctures::SJ_STAMINA, and DayZPlayerSyncJunctures::SJ_STAMINA_MISC.
ReadAdditionalStaminaInfo()
protected void ReadAdditionalStaminaInfo (ParamsReadContext pCtx)
Order of read parameters must match the order of writing above.
Definition at line 657 of file staminahandler.c.
    {
        float mult_dep;
        float mult_rec;
        if (!pCtx.Read(mult_dep) || !pCtx.Read(mult_rec))
        {
            return;
        }
        m_StaminaDepletionMultiplier = mult_dep;
        m_StaminaRecoveryMultiplier = mult_rec;
    }
References m_StaminaDepletionMultiplier, m_StaminaRecoveryMultiplier, and Serializer::Read().
Referenced by OnSyncJuncture().
RecalculateDepletionMultiplier()
void RecalculateDepletionMultiplier ()
Definition at line 340 of file staminahandler.c.
    {
        float value = 1;
        foreach (int multiplier: m_ActiveDepletionModifiers)
        {
            value *= m_RegisteredDepletionModifiers.Get(multiplier);
        }
        if (value != m_StaminaDepletionMultiplier)
            SetDepletionMultiplier(value);
    }
References m_ActiveDepletionModifiers, m_RegisteredDepletionModifiers, m_StaminaDepletionMultiplier, and SetDepletionMultiplier().
Referenced by ActivateDepletionModifier(), and DeactivateDepletionModifier().
RecalculateRecoveryMultiplier()
void RecalculateRecoveryMultiplier ()
Definition at line 377 of file staminahandler.c.
    {
        float value = 1;
        foreach (int multiplier: m_ActiveRecoveryModifiers)
        {
            value *= m_RegisteredRecoveryModifiers.Get(multiplier);
        }
        if (value != m_StaminaRecoveryMultiplier)
        {
            SetRecoveryMultiplier(value);
        }
    }
References m_ActiveRecoveryModifiers, m_RegisteredRecoveryModifiers, m_StaminaRecoveryMultiplier, and SetRecoveryMultiplier().
Referenced by ActivateRecoveryModifier(), and DeactivateRecoveryModifier().
RegisterConsumer()
void Stamina::RegisterConsumer (EStaminaConsumers consumer, float threshold, float depletion_threshold = -1)
init of StaminaConsumer - threshold, state
Definition at line 48 of file staminahandler.c.
    {
        if (depletion_threshold == -1)
        {
            depletion_threshold = threshold;
        }
        if ( !m_StaminaConsumers.Contains(consumer) )
        {
            StaminaConsumer sc = new StaminaConsumer(threshold, depletion_threshold, true);
            m_StaminaConsumers.Set(consumer, sc);
        }
    }
RegisterStaminaConsumers()
protected void RegisterStaminaConsumers ()
stamina consumers registration
Definition at line 670 of file staminahandler.c.
    {
        m_StaminaConsumers = new StaminaConsumers;
        m_StaminaConsumers.RegisterConsumer(EStaminaConsumers.HOLD_BREATH, GameConstants.STAMINA_HOLD_BREATH_THRESHOLD_ACTIVATE,GameConstants.STAMINA_HOLD_BREATH_THRESHOLD_DRAIN);
        m_StaminaConsumers.RegisterConsumer(EStaminaConsumers.SPRINT, CfgGameplayHandler.GetStaminaMinCap() + 15);
        m_StaminaConsumers.RegisterConsumer(EStaminaConsumers.JUMP, GameConstants.STAMINA_JUMP_THRESHOLD);
        m_StaminaConsumers.RegisterConsumer(EStaminaConsumers.VAULT, GameConstants.STAMINA_VAULT_THRESHOLD);
        m_StaminaConsumers.RegisterConsumer(EStaminaConsumers.CLIMB, GameConstants.STAMINA_CLIMB_THRESHOLD);
        m_StaminaConsumers.RegisterConsumer(EStaminaConsumers.MELEE_HEAVY, GameConstants.STAMINA_MELEE_HEAVY_THRESHOLD);
        m_StaminaConsumers.RegisterConsumer(EStaminaConsumers.MELEE_EVADE, GameConstants.STAMINA_MELEE_EVADE_THRESHOLD);
        m_StaminaConsumers.RegisterConsumer(EStaminaConsumers.ROLL, GameConstants.STAMINA_ROLL_THRESHOLD);
        m_StaminaConsumers.RegisterConsumer(EStaminaConsumers.DROWN,0);
    }
References CfgGameplayHandler::GetStaminaMinCap(), m_StaminaConsumers, GameConstants::STAMINA_CLIMB_THRESHOLD, GameConstants::STAMINA_HOLD_BREATH_THRESHOLD_ACTIVATE, GameConstants::STAMINA_HOLD_BREATH_THRESHOLD_DRAIN, GameConstants::STAMINA_JUMP_THRESHOLD, GameConstants::STAMINA_MELEE_EVADE_THRESHOLD, GameConstants::STAMINA_MELEE_HEAVY_THRESHOLD, GameConstants::STAMINA_ROLL_THRESHOLD, and GameConstants::STAMINA_VAULT_THRESHOLD.
Referenced by StaminaHandler().
RegisterStaminaModifiers()
protected void RegisterStaminaModifiers ()
stamina modifiers registration
Definition at line 685 of file staminahandler.c.
    {
        m_StaminaModifiers = new StaminaModifiers;
        m_StaminaModifiers.RegisterExponential(EStaminaModifiers.HOLD_BREATH, GameConstants.STAMINA_DRAIN_HOLD_BREATH_START, GameConstants.STAMINA_DRAIN_HOLD_BREATH_EXPONENT,0,GameConstants.STAMINA_DRAIN_HOLD_BREATH_DURATION);
        m_StaminaModifiers.RegisterFixed(EStaminaModifiers.DROWN, 10);
        m_StaminaModifiers.RegisterFixed(EStaminaModifiers.JUMP, GameConstants.STAMINA_DRAIN_JUMP);
        m_StaminaModifiers.RegisterFixed(EStaminaModifiers.VAULT, GameConstants.STAMINA_DRAIN_VAULT);
        m_StaminaModifiers.RegisterFixed(EStaminaModifiers.CLIMB, GameConstants.STAMINA_DRAIN_CLIMB);
        m_StaminaModifiers.RegisterFixed(EStaminaModifiers.MELEE_LIGHT, GameConstants.STAMINA_DRAIN_MELEE_LIGHT);
        m_StaminaModifiers.RegisterFixed(EStaminaModifiers.MELEE_HEAVY, GameConstants.STAMINA_DRAIN_MELEE_HEAVY);
        m_StaminaModifiers.RegisterFixed(EStaminaModifiers.OVERALL_DRAIN, CfgGameplayHandler.GetStaminaMax(), 5.0);
        m_StaminaModifiers.RegisterRandomized(EStaminaModifiers.MELEE_EVADE, 3, GameConstants.STAMINA_DRAIN_MELEE_EVADE);
        m_StaminaModifiers.RegisterFixed(EStaminaModifiers.ROLL, GameConstants.STAMINA_DRAIN_ROLL);
    }
References CfgGameplayHandler::GetStaminaMax(), m_StaminaModifiers, StaminaModifiers::RegisterExponential(), StaminaModifiers::RegisterFixed(), StaminaModifiers::RegisterRandomized(), GameConstants::STAMINA_DRAIN_CLIMB, GameConstants::STAMINA_DRAIN_HOLD_BREATH_DURATION, GameConstants::STAMINA_DRAIN_HOLD_BREATH_EXPONENT, GameConstants::STAMINA_DRAIN_HOLD_BREATH_START, GameConstants::STAMINA_DRAIN_JUMP, GameConstants::STAMINA_DRAIN_MELEE_EVADE, GameConstants::STAMINA_DRAIN_MELEE_HEAVY, GameConstants::STAMINA_DRAIN_MELEE_LIGHT, GameConstants::STAMINA_DRAIN_ROLL, and GameConstants::STAMINA_DRAIN_VAULT.
Referenced by StaminaHandler().
ResetCooldown()
protected void ResetCooldown (int modifier = -1)
Definition at line 783 of file staminahandler.c.
    {
        StaminaModifier sm = m_StaminaModifiers.GetModifierData(modifier);
        if (sm)
        {
            //Print(modifier);
            //Error("Error: No StaminaModifier found! | StaminaHandler | ResetCooldown");
            sm.SetStartTime(-1);
            sm.ResetRunTime();
            sm.SetInUse(false);
        }
        m_IsInCooldown = false;
    }
References StaminaModifiers::GetModifierData(), m_IsInCooldown, m_StaminaModifiers, and StaminaModifier().
Referenced by SetCooldown().
ResetRunTime()
void ResetRunTime ()
Definition at line 175 of file staminahandler.c.
{ m_ProgressTime = 0 }
References m_ProgressTime.
SetActivationThreshold()
void SetActivationThreshold (float threshold)
Definition at line 33 of file staminahandler.c.
{ m_ActivationThreshold = threshold; }
References m_ActivationThreshold.
SetCooldown() [1/2]
protected void SetCooldown (float time, int modifier = -1)
set cooldown timer between each consume of stamina
Definition at line 759 of file staminahandler.c.
    {
        if ( m_StaminaDepleted || m_Stamina <= 0.0 )
        {
            ResetCooldown(modifier);
            return;
        }
        m_IsInCooldown = true;
        Timer timer;
        if (m_TimerMap.Find(modifier, timer) && timer.IsRunning())
        {
            timer.Stop();
        }
        else
        {
            timer = new ref Timer;
            m_TimerMap.Set(modifier,timer);
        }
        timer.Run(time, this, "ResetCooldown",  new Param1<int>( modifier ));
        //Print(m_TimerMap.Count());
    }
References m_IsInCooldown, m_Stamina, m_StaminaDepleted, m_TimerMap, and ResetCooldown().
SetCooldown() [2/2]
void SetCooldown (float val)
Definition at line 161 of file staminahandler.c.
{ m_Cooldown = val; }
References m_Cooldown.
Referenced by CheckStaminaState(), DepleteStamina(), HandleFightLogic(), StaminaProcessor_Ladder(), StaminaProcessor_Move(), and StaminaProcessor_Swimming().
SetDepletionMultiplier()
void SetDepletionMultiplier (float val)
Definition at line 850 of file staminahandler.c.
    {
        if (m_StaminaDepletionMultiplier < 0)
            m_StaminaDepletionMultiplier = 0;
        m_StaminaDepletionMultiplier = val;
        SyncAdditionalStaminaInfo(new Param2<float,float>(m_StaminaDepletionMultiplier,m_StaminaRecoveryMultiplier));
    }
References m_StaminaDepletionMultiplier, m_StaminaRecoveryMultiplier, and SyncAdditionalStaminaInfo().
Referenced by RecalculateDepletionMultiplier().
SetDrainThreshold()
void SetDrainThreshold (float threshold)
Definition at line 36 of file staminahandler.c.
{ m_DrainThreshold = threshold; }
SetInUse()
void SetInUse (bool val)
Definition at line 170 of file staminahandler.c.
{ m_InUse = val; }
References m_InUse.
SetMaxValue()
void SetMaxValue (float val)
Definition at line 158 of file staminahandler.c.
{ m_MaxValue = val; }
References m_MaxValue.
SetMinValue()
void SetMinValue (float val)
Definition at line 155 of file staminahandler.c.
{ m_MinValue = val; }
References m_MinValue.
SetRecoveryMultiplier()
void SetRecoveryMultiplier (float val)
Definition at line 858 of file staminahandler.c.
    {
        if (m_StaminaRecoveryMultiplier < 0)
            m_StaminaRecoveryMultiplier = 0;
        m_StaminaRecoveryMultiplier = val;
        SyncAdditionalStaminaInfo(new Param2<float,float>(m_StaminaDepletionMultiplier,m_StaminaRecoveryMultiplier));
    }
References m_StaminaDepletionMultiplier, m_StaminaRecoveryMultiplier, and SyncAdditionalStaminaInfo().
Referenced by RecalculateRecoveryMultiplier().
SetRunTimeTick()
void SetRunTimeTick (float val)
Definition at line 174 of file staminahandler.c.
{ m_Tick = val; }
References m_Tick.
SetStamina()
void SetStamina (float stamina_value)
Definition at line 813 of file staminahandler.c.
    {
        m_Stamina = Math.Clamp(stamina_value, 0, CfgGameplayHandler.GetStaminaMax());
        SyncStamina(m_Stamina, m_StaminaCap, m_IsInCooldown);
    }
References Math::Clamp(), CfgGameplayHandler::GetStaminaMax(), m_IsInCooldown, m_Stamina, m_StaminaCap, and SyncStamina().
Referenced by Update().
SetStartTime()
void SetStartTime (float val)
Definition at line 164 of file staminahandler.c.
{ m_StartTime = val; }
References m_StartTime.
SetState()
void SetState (bool state)
Definition at line 30 of file staminahandler.c.
{ m_State = state; }
References m_State.
Referenced by FireworksLauncher::OnEventServer(), FireworksLauncher::OnFuseIgnitedServer(), OnInventoryEnter(), OnPlacementCancelled(), FireworksLauncher::OnPlacementComplete(), OnPlacementComplete(), OnSteppedOn(), AlarmClock_ColorBase::OnStoreLoad(), FireworksLauncher::OnStoreLoad(), KitchenTimer::OnStoreLoad(), OnStoreLoad(), SetupTrapPlayer(), and StartDeactivate().
StaminaConsumer()
void StaminaConsumer (float threshold, float threshold2, bool state)
Definition at line 22 of file staminahandler.c.
    {
        m_ActivationThreshold = threshold; //can be activated if above this threshold
        m_DrainThreshold = threshold2; //can continually drain until it reaches this threshold
        m_State = state;
    }
References m_ActivationThreshold, and m_State.
Referenced by StaminaConsumers::HasEnoughStaminaFor(), StaminaConsumers::HasEnoughStaminaToStart(), and StaminaConsumers::RegisterConsumer().
StaminaConsumers()
void Stamina::StaminaConsumers ()
Definition at line 43 of file staminahandler.c.
    {
        m_StaminaConsumers = new map<EStaminaConsumers, ref StaminaConsumer>;
    }
StaminaHandler()
void StaminaHandler (PlayerBase player)
Definition at line 269 of file staminahandler.c.
    {
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_StaminaParams = new Param3<float,float,bool>(0,0, false);
        }
        m_State                         = new HumanMovementState();
        m_Player                        = player;
        m_Stamina                       = CfgGameplayHandler.GetStaminaMax();
        m_StaminaCap                    = CfgGameplayHandler.GetStaminaMax();
        m_StaminaDepletion              = 0;
        m_StaminaDepletionMultiplier    = 1;
        m_StaminaRecoveryMultiplier     = 1;
        m_Time                          = 0;
        m_StaminaDepleted               = false;
        m_IsInCooldown                  = false;
        RegisterStaminaConsumers();
        RegisterStaminaModifiers();
        m_TimerMap = new map<int,ref Timer>;
        //----------------- depletion --------------------
        m_RegisteredDepletionModifiers = new map<EStaminaMultiplierTypes, float>;
        m_ActiveDepletionModifiers = new set<EStaminaMultiplierTypes>;
        //----------------- recovery --------------------
        m_RegisteredRecoveryModifiers = new map<EStaminaMultiplierTypes, float>;
        m_ActiveRecoveryModifiers = new set<EStaminaMultiplierTypes>;
        Init();
    }
References GetGame(), CfgGameplayHandler::GetStaminaMax(), Init(), m_ActiveDepletionModifiers, m_ActiveRecoveryModifiers, m_IsInCooldown, m_Player, m_RegisteredDepletionModifiers, m_RegisteredRecoveryModifiers, m_Stamina, m_StaminaCap, m_StaminaDepleted, m_StaminaDepletion, m_StaminaDepletionMultiplier, m_StaminaParams, m_StaminaRecoveryMultiplier, m_State, m_Time, m_TimerMap, RegisterStaminaConsumers(), and RegisterStaminaModifiers().
Referenced by ManBase::Init().
StaminaModifier()
void StaminaModifier (int type, float min, float max, float cooldown, float startTime = 0, float duration = 0)
Definition at line 141 of file staminahandler.c.
    {
        m_Type = type;
        m_MinValue = min;
        m_MaxValue = max;
        m_Cooldown = cooldown;
        m_StartTime = startTime;
        m_Duration = duration;
        m_Tick = 1;
    }
References m_Cooldown, m_Duration, m_MaxValue, m_MinValue, m_StartTime, m_Tick, and m_Type.
Referenced by DepleteStamina(), StaminaModifiers::RegisterExponential(), StaminaModifiers::RegisterFixed(), StaminaModifiers::RegisterLinear(), StaminaModifiers::RegisterRandomized(), and ResetCooldown().
StaminaProcessor_Ladder()
protected void StaminaProcessor_Ladder (HumanMovementState pHumanMovementState)
Definition at line 582 of file staminahandler.c.
    {
        switch (pHumanMovementState.m_iMovement)
        {
        case 2: //climb up (fast)
            m_StaminaDelta = -GameConstants.STAMINA_DRAIN_LADDER_FAST_PER_SEC;
            SetCooldown(GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION);
            break;
        break;
        case 1: //climb up (slow)
            if (!m_IsInCooldown)
            {
                m_StaminaDelta = (GameConstants.STAMINA_GAIN_LADDER_PER_SEC + CalcStaminaGainBonus());
            }
        break;
        default:
            if (!m_IsInCooldown)
            {
                m_StaminaDelta = GameConstants.STAMINA_GAIN_IDLE_PER_SEC + CalcStaminaGainBonus();
            }
        break;
        }
    }
References CalcStaminaGainBonus(), HumanMovementState::m_iMovement, m_IsInCooldown, m_StaminaDelta, SetCooldown(), GameConstants::STAMINA_DRAIN_LADDER_FAST_PER_SEC, GameConstants::STAMINA_GAIN_IDLE_PER_SEC, GameConstants::STAMINA_GAIN_LADDER_PER_SEC, and GameConstants::STAMINA_REGEN_COOLDOWN_DEPLETION.
Referenced by Update().
StaminaProcessor_Move()
protected void StaminaProcessor_Move (HumanMovementState pHumanMovementState)
Definition at line 527 of file staminahandler.c.
    {
        switch (pHumanMovementState.m_iMovement)
        {
        case DayZPlayerConstants.MOVEMENTIDX_SPRINT: //sprint
            if (pHumanMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_ERECT)
            {
                m_StaminaDelta = -GameConstants.STAMINA_DRAIN_STANDING_SPRINT_PER_SEC * CfgGameplayHandler.GetSprintStaminaModifierErc();
                SetCooldown(GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION);
                break;
            }
            else if ( pHumanMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH)
            {
                m_StaminaDelta = -GameConstants.STAMINA_DRAIN_CROUCHED_SPRINT_PER_SEC * CfgGameplayHandler.GetSprintStaminaModifierCro();
                SetCooldown(GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION);
                break;
            }
            m_StaminaDelta = GameConstants.STAMINA_GAIN_JOG_PER_SEC;
        break;
        case DayZPlayerConstants.MOVEMENTIDX_RUN: //jog
            if (!m_IsInCooldown)
            {
                m_StaminaDelta = (GameConstants.STAMINA_GAIN_JOG_PER_SEC + CalcStaminaGainBonus());
            }
        break;
        case DayZPlayerConstants.MOVEMENTIDX_WALK: //walk
            if (!m_IsInCooldown)
            {
                m_StaminaDelta = (GameConstants.STAMINA_GAIN_WALK_PER_SEC + CalcStaminaGainBonus());
            }
        break;
        case DayZPlayerConstants.MOVEMENTIDX_IDLE: //idle
            if (m_Player.IsRolling())
            {
                m_StaminaDelta = GameConstants.STAMINA_GAIN_ROLL_PER_SEC;
                break;
            }
            if (!m_IsInCooldown)
            {
                m_StaminaDelta = (GameConstants.STAMINA_GAIN_IDLE_PER_SEC + CalcStaminaGainBonus());
            }
        break;
        default:
            if (!m_IsInCooldown)
            {
                m_StaminaDelta = GameConstants.STAMINA_GAIN_IDLE_PER_SEC;
            }
        break;
        }
    }
References CalcStaminaGainBonus(), CfgGameplayHandler::GetSprintStaminaModifierCro(), CfgGameplayHandler::GetSprintStaminaModifierErc(), HumanMovementState::m_iMovement, m_IsInCooldown, HumanMovementState::m_iStanceIdx, m_Player, m_StaminaDelta, SetCooldown(), GameConstants::STAMINA_DRAIN_CROUCHED_SPRINT_PER_SEC, GameConstants::STAMINA_DRAIN_STANDING_SPRINT_PER_SEC, GameConstants::STAMINA_GAIN_IDLE_PER_SEC, GameConstants::STAMINA_GAIN_JOG_PER_SEC, GameConstants::STAMINA_GAIN_ROLL_PER_SEC, GameConstants::STAMINA_GAIN_WALK_PER_SEC, and GameConstants::STAMINA_REGEN_COOLDOWN_DEPLETION.
Referenced by Update().
StaminaProcessor_Swimming()
protected void StaminaProcessor_Swimming (HumanMovementState pHumanMovementState)
Definition at line 608 of file staminahandler.c.
    {
        switch (pHumanMovementState.m_iMovement)
        {
        case 3: //swim fast
            m_StaminaDelta = -GameConstants.STAMINA_DRAIN_SWIM_FAST_PER_SEC;
            SetCooldown(GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION);
            break;
        break;
        case 2: //swim slow
            if (!m_IsInCooldown)
            {
                m_StaminaDelta = (GameConstants.STAMINA_GAIN_SWIM_PER_SEC + CalcStaminaGainBonus());
            }
        break;
        default:
            if (!m_IsInCooldown)
            {
                m_StaminaDelta = GameConstants.STAMINA_GAIN_IDLE_PER_SEC + CalcStaminaGainBonus();
            }
        break;
        }
    }
References CalcStaminaGainBonus(), HumanMovementState::m_iMovement, m_IsInCooldown, m_StaminaDelta, SetCooldown(), GameConstants::STAMINA_DRAIN_SWIM_FAST_PER_SEC, GameConstants::STAMINA_GAIN_IDLE_PER_SEC, GameConstants::STAMINA_GAIN_SWIM_PER_SEC, and GameConstants::STAMINA_REGEN_COOLDOWN_DEPLETION.
Referenced by Update().
SyncAdditionalStaminaInfo()
protected void SyncAdditionalStaminaInfo (Param par)
Method to sync more info for stamina manager. Template parameter means it is very extendable for further use.
Definition at line 646 of file staminahandler.c.
    {
        Param2<float,float> p = Param2<float,float>.Cast(par);
        ScriptJunctureData pCtx = new ScriptJunctureData;
        pCtx.Write(p.param1);
        pCtx.Write(p.param2);
        m_Player.SendSyncJuncture(DayZPlayerSyncJunctures.SJ_STAMINA_MISC,pCtx);
    }
References m_Player, DayZPlayerSyncJunctures::SJ_STAMINA_MISC, and Serializer::Write().
Referenced by SetDepletionMultiplier(), and SetRecoveryMultiplier().
SyncStamina()
protected void SyncStamina (float stamina, float stamina_cap, bool cooldown)
stamina sync - server part
Definition at line 635 of file staminahandler.c.
    {
        m_Player.GetStatStamina().Set(m_Stamina);
        ScriptJunctureData pCtx = new ScriptJunctureData;
        pCtx.Write(m_Stamina);
        pCtx.Write(m_StaminaCap);
        pCtx.Write(m_IsInCooldown);
        m_Player.SendSyncJuncture(DayZPlayerSyncJunctures.SJ_STAMINA,pCtx);
    }
References m_IsInCooldown, m_Player, m_Stamina, m_StaminaCap, DayZPlayerSyncJunctures::SJ_STAMINA, and Serializer::Write().
Referenced by SetStamina().
Update()
void Update (float deltaT, int pCurrentCommandID)
gets the actual players load
StaminaCap calculation starts when PlayerLoad exceeds STAMINA_WEIGHT_LIMIT_THRESHOLD
processed on event
processed on event
processed on event
Definition at line 392 of file staminahandler.c.
    {
        #ifdef DEVELOPER
        if (!m_StaminaEnabled || DiagMenu.GetBool(DiagMenuIDs.DM_CHEATS_STAMINA_DISABLE))
        {
            return;
        }
        #endif
        if (m_Player)
        {
            // Calculates actual max stamina based on player's load
            if (GetGame().IsServer() || !GetGame().IsMultiplayer())
            {
                m_PlayerLoad = m_Player.GetPlayerLoad();
                if (m_PlayerLoad >= CfgGameplayHandler.GetStaminaWeightLimitThreshold())
                {
                    m_StaminaCap =  Math.Max((CfgGameplayHandler.GetStaminaMax() - (((m_PlayerLoad - CfgGameplayHandler.GetStaminaWeightLimitThreshold())/GameConstants.STAMINA_KG_TO_GRAMS) * CfgGameplayHandler.GetStaminaKgToStaminaPercentPenalty())),CfgGameplayHandler.GetStaminaMinCap());
                }
                else
                {
                    m_StaminaCap = CfgGameplayHandler.GetStaminaMax();
                }
            }
            // Calculates stamina gain/loss based on movement and load
            m_Player.GetMovementState(m_State);
            switch (pCurrentCommandID)
            {
            case DayZPlayerConstants.COMMANDID_MOVE:
                StaminaProcessor_Move(m_State);
                break;
            case DayZPlayerConstants.COMMANDID_LADDER:
                StaminaProcessor_Ladder(m_State);
                break;
            case DayZPlayerConstants.COMMANDID_SWIM:
                StaminaProcessor_Swimming(m_State);
                break;
            case DayZPlayerConstants.COMMANDID_FALL:
            case DayZPlayerConstants.COMMANDID_MELEE2:
            case DayZPlayerConstants.COMMANDID_CLIMB:
                break;
            default:
                if (!m_IsInCooldown)
                {
                    m_StaminaDelta = GameConstants.STAMINA_GAIN_IDLE_PER_SEC;
                }
                break;
            }
            //Sets current stamina & stores + syncs data with client
            float temp = m_StaminaDelta * deltaT;
            if (temp < 0)
            {
                temp *= m_StaminaDepletionMultiplier;
            }
            else
            {
                temp *= m_StaminaRecoveryMultiplier;
            }
            m_Stamina = Math.Max(0, Math.Min((m_Stamina + temp), m_StaminaCap));
            m_Stamina = m_Stamina - m_StaminaDepletion;
            if (GetGame().IsServer() || !GetGame().IsMultiplayer())
            {
                m_Player.GetStatStamina().Set(m_Stamina);
                m_Time += deltaT;
                if (m_Time >= GameConstants.STAMINA_SYNC_RATE)
                {
                    m_Time = 0;
                    SetStamina(m_Stamina);
                }
            }
            #ifndef SERVER
            m_Player.SetStamina(m_StaminaSynced, m_StaminaCap);
            #endif
            ApplyExhaustion();
            CheckStaminaState();
            m_StaminaDelta = 0;
            m_StaminaDepletion = 0; // resets depletion modifier
        }
    }
References ApplyExhaustion(), CheckStaminaState(), DiagMenu::GetBool(), GetGame(), CfgGameplayHandler::GetStaminaKgToStaminaPercentPenalty(), CfgGameplayHandler::GetStaminaMax(), CfgGameplayHandler::GetStaminaMinCap(), CfgGameplayHandler::GetStaminaWeightLimitThreshold(), m_IsInCooldown, m_Player, m_PlayerLoad, m_Stamina, m_StaminaCap, m_StaminaDelta, m_StaminaDepletion, m_StaminaDepletionMultiplier, m_StaminaRecoveryMultiplier, m_StaminaSynced, m_State, m_Time, Math::Max(), Math::Min(), SetStamina(), GameConstants::STAMINA_GAIN_IDLE_PER_SEC, GameConstants::STAMINA_KG_TO_GRAMS, GameConstants::STAMINA_SYNC_RATE, StaminaProcessor_Ladder(), StaminaProcessor_Move(), and StaminaProcessor_Swimming().
Variable Documentation
DROWNING
@ DROWNING
Definition at line 6 of file staminahandler.c.
EPINEPHRINE
EPINEPHRINE
Definition at line 5 of file staminahandler.c.
FATIGUE
FATIGUE
Definition at line 4 of file staminahandler.c.
m_ActivationThreshold
m_ActivationThreshold
Referenced by GetActivationThreshold(), SetActivationThreshold(), and StaminaConsumer().
m_ActiveDepletionModifiers
ref set<EStaminaMultiplierTypes> m_ActiveDepletionModifiers
Definition at line 255 of file staminahandler.c.
Referenced by ActivateDepletionModifier(), DeactivateDepletionModifier(), RecalculateDepletionMultiplier(), and StaminaHandler().
m_ActiveRecoveryModifiers
ref set<EStaminaMultiplierTypes> m_ActiveRecoveryModifiers
Definition at line 258 of file staminahandler.c.
Referenced by ActivateRecoveryModifier(), DeactivateRecoveryModifier(), RecalculateRecoveryMultiplier(), and StaminaHandler().
m_Cooldown
float m_Cooldown
Definition at line 139 of file staminahandler.c.
Referenced by GetCooldown(), SetCooldown(), and StaminaModifier().
m_Debug
protected bool m_Debug
Definition at line 250 of file staminahandler.c.
Referenced by ActionTargets::FilterObstructedObjectsEx(), ScriptedWidgetEventHandler::ProjectedCrosshair(), and ScriptedWidgetEventHandler::Update().
m_Duration
float m_Duration
Definition at line 139 of file staminahandler.c.
m_InUse
m_InUse = false
Referenced by IsInUse(), and SetInUse().
m_IsInCooldown
protected bool m_IsInCooldown
Definition at line 260 of file staminahandler.c.
Referenced by CheckStaminaState(), OnSyncJuncture(), ResetCooldown(), SetCooldown(), SetStamina(), StaminaHandler(), StaminaProcessor_Ladder(), StaminaProcessor_Move(), StaminaProcessor_Swimming(), SyncStamina(), and Update().
m_MaxValue
float m_MaxValue
Definition at line 139 of file staminahandler.c.
Referenced by GetMaxValue(), OptionSelectorBase::GetValue(), OptionSelectorBase::NormalizeInput(), OptionSelectorSliderSetup::OptionSelectorLevelMarker(), OptionSelectorSliderSetup::OptionSelectorSlider(), PlayerStatBase::PlayerStat(), PlayerStatBase::Set(), SetMaxValue(), and StaminaModifier().
m_MinValue
float m_MinValue
Definition at line 139 of file staminahandler.c.
Referenced by GetMinValue(), OptionSelectorBase::GetValue(), OptionSelectorBase::NormalizeInput(), OptionSelectorSliderSetup::OptionSelectorLevelMarker(), OptionSelectorSliderSetup::OptionSelectorSlider(), PlayerStatBase::PlayerStat(), PlayerStatBase::Set(), SetMinValue(), and StaminaModifier().
m_Player
protected PlayerBase m_Player
Definition at line 248 of file staminahandler.c.
m_PlayerLoad
class StaminaModifiers m_PlayerLoad
Referenced by Update().
m_ProgressTime
float m_ProgressTime
Definition at line 139 of file staminahandler.c.
Referenced by AddRunTime(), GetRunTime(), and ResetRunTime().
m_RegisteredDepletionModifiers
ref map<EStaminaMultiplierTypes, float> m_RegisteredDepletionModifiers
Definition at line 254 of file staminahandler.c.
Referenced by ActivateDepletionModifier(), Init(), RecalculateDepletionMultiplier(), and StaminaHandler().
m_RegisteredRecoveryModifiers
ref map<EStaminaMultiplierTypes, float> m_RegisteredRecoveryModifiers
Definition at line 257 of file staminahandler.c.
Referenced by ActivateRecoveryModifier(), Init(), RecalculateRecoveryMultiplier(), and StaminaHandler().
m_Stamina
protected float m_Stamina
Definition at line 239 of file staminahandler.c.
Referenced by ApplyExhaustion(), CalcStaminaGainBonus(), CheckStaminaState(), GetStamina(), GetStaminaNormalized(), HasEnoughStaminaFor(), HasEnoughStaminaToStart(), Hud::Init(), OnSyncJuncture(), SetCooldown(), SetStamina(), Hud::SetStamina(), Hud::SetStaminaBarVisibility(), StaminaHandler(), SyncStamina(), and Update().
m_StaminaCap
protected float m_StaminaCap
Definition at line 241 of file staminahandler.c.
Referenced by ApplyExhaustion(), GetStaminaCap(), HasEnoughStaminaFor(), HasEnoughStaminaToStart(), OnSyncJuncture(), SetStamina(), StaminaHandler(), SyncStamina(), and Update().
m_StaminaConsumers
protected ref StaminaConsumers m_StaminaConsumers
Definition at line 41 of file staminahandler.c.
Referenced by HasEnoughStaminaFor(), HasEnoughStaminaToStart(), and RegisterStaminaConsumers().
m_StaminaDelta
protected float m_StaminaDelta
Definition at line 238 of file staminahandler.c.
Referenced by StaminaProcessor_Ladder(), StaminaProcessor_Move(), StaminaProcessor_Swimming(), and Update().
m_StaminaDepleted
protected bool m_StaminaDepleted
DEPRECATED.
Definition at line 251 of file staminahandler.c.
Referenced by CheckStaminaState(), HasEnoughStaminaFor(), HasEnoughStaminaToStart(), SetCooldown(), and StaminaHandler().
m_StaminaDepletion
protected float m_StaminaDepletion
Definition at line 242 of file staminahandler.c.
Referenced by CalcStaminaGainBonus(), DepleteStamina(), StaminaHandler(), and Update().
m_StaminaDepletionMultiplier
protected float m_StaminaDepletionMultiplier
Definition at line 243 of file staminahandler.c.
Referenced by DepleteStamina(), GetDepletionMultiplier(), ReadAdditionalStaminaInfo(), RecalculateDepletionMultiplier(), SetDepletionMultiplier(), SetRecoveryMultiplier(), StaminaHandler(), and Update().
m_StaminaModifiers
protected ref StaminaModifiers m_StaminaModifiers
Definition at line 263 of file staminahandler.c.
Referenced by DepleteStamina(), RegisterStaminaModifiers(), and ResetCooldown().
m_StaminaParams
protected ref Param3<float,float,bool> m_StaminaParams
Definition at line 246 of file staminahandler.c.
Referenced by StaminaHandler().
m_StaminaRecoveryMultiplier
protected float m_StaminaRecoveryMultiplier
Definition at line 244 of file staminahandler.c.
Referenced by GetRecoveryMultiplier(), ReadAdditionalStaminaInfo(), RecalculateRecoveryMultiplier(), SetDepletionMultiplier(), SetRecoveryMultiplier(), StaminaHandler(), and Update().
m_StaminaSynced
protected float m_StaminaSynced
Definition at line 240 of file staminahandler.c.
Referenced by GetSyncedStamina(), OnSyncJuncture(), and Update().
m_StartTime
float m_StartTime
Definition at line 139 of file staminahandler.c.
Referenced by GetStartTime(), SetStartTime(), and StaminaModifier().
m_State
protected ref HumanMovementState m_State
Definition at line 20 of file staminahandler.c.
Referenced by HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Abort(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindFirstCompletionTransition(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindFirstUnguardedTransition(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::GetCurrentState(), AlarmClock_ColorBase::GetDebugText(), KitchenTimer::GetDebugText(), GetState(), ItemBase::GetState(), Inventory_Base::HescoBox(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::Internal_ValidateAndRepair(), IsAlarmOn(), IsRinging(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::IsRunning(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadAndSetCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnFailThresholdBreached(), FireworksLauncher::OnIndexChangedClient(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreLoad(), FireworksLauncher::OnStoreLoad(), ItemBase::OnStoreLoad(), AlarmClock_ColorBase::OnStoreSave(), FireworksLauncher::OnStoreSave(), KitchenTimer::OnStoreSave(), Inventory_Base::OnStoreSave(), ItemBase::OnStoreSave(), OnStoreSave(), OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), ItemBase::Pack(), ItemBase::Pitch(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortTransition(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::RandomizeFSMStateEx(), ItemBase::RefreshPhysics(), SetState(), Inventory_Base::SetState(), StaminaConsumer(), StaminaHandler(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate(), ItemBase::ToggleAnimation(), Update(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Update(), and HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ValidateAndRepairHelper().
m_Tick
float m_Tick
Definition at line 139 of file staminahandler.c.
Referenced by GetDurationAdjusted(), BleedingSourcesManagerBase::OnTick(), SetRunTimeTick(), and StaminaModifier().
m_Time
protected float m_Time
Definition at line 245 of file staminahandler.c.
Referenced by CarScript(), EOnPostSimulate(), SymptomBase::OnUpdateClient(), UIScriptedMenu::Play(), StaminaHandler(), Update(), and UIScriptedMenu::Update().
m_TimerMap
protected ref map<int,ref Timer> m_TimerMap
Definition at line 253 of file staminahandler.c.
Referenced by SetCooldown(), and StaminaHandler().
m_Type
int m_Type
Definition at line 138 of file staminahandler.c.
MASK
MASK = 1
Definition at line 3 of file staminahandler.c.