DayzKode: P:/scripts/4_world/DayZ/classes/modules/syncedvalue.c File Reference
syncedvalue.c File Reference
Classes
class SyncedValue
class SyncedValueModifier
Functions
int GetID ()
string GetName ()
Gets the name which is set for the ParticleManager, default is "ParticleSourceManager".
float GetValue ()
float GetValue2 ()
void SyncedValueAgent (string name, string value, int id)
void SyncedValueLevel (string name, float value, float value2)
Variables
int m_ID
class SyncedValue m_Name
float m_Value
float m_Value2
Function Documentation
GetID()
int GetID ()
Definition at line 127 of file syncedvalue.c.
    {
        return m_ID;
    }
References m_ID.
GetValue()
string GetValue ()
Definition at line 55 of file syncedvalue.c.
    {
        return m_Value;
    }
References m_Value.
Referenced by OptionSelectorBase::OnChange(), and OptionSelectorBase::SetValue().
GetValue2()
float GetValue2 ()
Definition at line 60 of file syncedvalue.c.
    {
        return m_Value2;
    }
References m_Value2.
SyncedValueAgent()
void SyncedValueAgent (string name, string value, int id)
Definition at line 110 of file syncedvalue.c.
    {
        m_Name = name;
        m_Value = value;
        m_ID = id;
    }
References m_ID, m_Name, m_Value, and name.
Referenced by PluginBase::OnRPCAgents().
SyncedValueLevel()
void SyncedValueLevel (string name, float value, float value2)
Definition at line 43 of file syncedvalue.c.
    {
        m_Name = name;
        m_Value = value;
        m_Value2 = value2;
    }
References m_Name, m_Value, m_Value2, and name.
Referenced by PluginBase::OnRPCLevels().
Variable Documentation
m_ID
int m_ID
Definition at line 108 of file syncedvalue.c.
m_Name
class SyncedValueModifier m_Name
m_Value
string m_Value
Definition at line 40 of file syncedvalue.c.
m_Value2
float m_Value2
Definition at line 41 of file syncedvalue.c.
Referenced by GetValue2(), and SyncedValueLevel().