DayzKode: P:/scripts/4_world/DayZ/entities/itembase/torch.c File Reference
torch.c File Reference
Classes
class FlammableBase
class TorchLambda
Functions
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
Variables
static float m_BurnTimePerFullFuelDose
static float m_BurnTimePerFullLard
FlammableBase m_BurnTimePerRag
static float m_MaxConsumableFuelQuantity
static float m_MaxConsumableLardQuantity
static int m_StartFadeOutOfLightAtQuantity = 3
static float m_WaterEvaporationByFireIntensity = 0.001
Function Documentation
Init()
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
pre-init arrays
Definition at line 911 of file torch.c.
    {
        super.Init();
        //for legacy reasons
        m_BurnTimePerRag = m_BurnTimePerRagEx;
        m_BurnTimePerFullLard = m_BurnTimePerFullLardEx;
        m_BurnTimePerFullFuelDose = m_BurnTimePerFullFuelDoseEx;
        m_MaxConsumableLardQuantity = m_MaxConsumableLardQuantityEx;
        m_MaxConsumableFuelQuantity = m_MaxConsumableFuelQuantityEx;
    }
References m_BurnTimePerFullFuelDose, FlammableBase::m_BurnTimePerFullFuelDoseEx, m_BurnTimePerFullLard, FlammableBase::m_BurnTimePerFullLardEx, m_BurnTimePerRag, FlammableBase::m_BurnTimePerRagEx, m_MaxConsumableFuelQuantity, FlammableBase::m_MaxConsumableFuelQuantityEx, m_MaxConsumableLardQuantity, and FlammableBase::m_MaxConsumableLardQuantityEx.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 948 of file torch.c.
    {
        if (!super.OnStoreLoad(ctx, version))
        {
            return false;
        }
        if (version >= 129)
        {
            if (!ctx.Read( m_ConsumeRagFlipFlop ))
            {
                return false;
            }
            if (!ctx.Read( m_RagsUpgradedCount ))
            {
                return false;
            }
        }
        UpdateCheckForReceivingUpgrade();
        return true;
    }
References Serializer::Read(), and FlammableBase::UpdateCheckForReceivingUpgrade().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
Definition at line 940 of file torch.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write(m_ConsumeRagFlipFlop);
        ctx.Write(m_RagsUpgradedCount);
    }
References Serializer::Write().
OnWasAttached()
override void OnWasAttached (EntityAI parent, int slot_id)
Definition at line 924 of file torch.c.
    {
        super.OnWasAttached(parent, slot_id);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
            LockRags(true);
    }
References GetGame(), and FlammableBase::LockRags().
OnWasDetached()
override void OnWasDetached (EntityAI parent, int slot_id)
Definition at line 932 of file torch.c.
    {
        super.OnWasDetached(parent, slot_id);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
            LockRags(false);
    }
References GetGame(), and FlammableBase::LockRags().
Variable Documentation
m_BurnTimePerFullFuelDose
float m_BurnTimePerFullFuelDose static
Definition at line 904 of file torch.c.
Referenced by Init().
m_BurnTimePerFullLard
float m_BurnTimePerFullLard static
Definition at line 903 of file torch.c.
Referenced by Init().
m_BurnTimePerRag
FlammableBase m_BurnTimePerRag
Referenced by Init().
m_MaxConsumableFuelQuantity
float m_MaxConsumableFuelQuantity static
Definition at line 906 of file torch.c.
Referenced by Init().
m_MaxConsumableLardQuantity
float m_MaxConsumableLardQuantity static
Definition at line 905 of file torch.c.
Referenced by Init().
m_StartFadeOutOfLightAtQuantity
int m_StartFadeOutOfLightAtQuantity = 3 static
Definition at line 908 of file torch.c.
m_WaterEvaporationByFireIntensity
float m_WaterEvaporationByFireIntensity = 0.001 static
Definition at line 907 of file torch.c.