DayzKode: P:/scripts/4_world/DayZ/entities/itembase/trapbase/trap_tripwire.c File Reference
trap_tripwire.c File Reference
Classes
class TripwireTrapDeployed
Enumerations
enum eWireMaterial { WIRE = 0 , BARBED_WIRE = 1 , ROPE = 2 }
Functions
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override void CreateTrigger ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EEKilled (Object killer)
void FoldTripWire ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
int GetState ()
returns one of STATE_...
int GetWireType ()
override bool IsDeployable ()
override bool IsTakeable ()
override void OnInventoryEnter (Man player)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnPlacementCancelled (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnSteppedOn (EntityAI victim)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
override void RefreshState ()
override void SetActions ()
override void SetInactive (bool stop_timer=true)
void SetState (int state_ID)
override void SetupTrapPlayer (PlayerBase player, bool set_position=true)
void SetWireType (int wireType)
override void StartDeactivate (PlayerBase player)
void TripwireTrap ()
void UpdateProxySelections ()
Variables
static const int DEPLOYED = 2
enum eWireMaterial FOLDED = 3
protected bool m_ResultOfAdvancedPlacing
int m_State = FOLDED
protected vector m_TriggerOrientation
protected vector m_TriggerPosition
private int m_WireMaterial
static const int TRIGGERED = 1
Enumeration Type Documentation
eWireMaterial
enum eWireMaterial
Enumerator
WIRE
BARBED_WIRE
ROPE
Definition at line 2 of file trap_tripwire.c.
{
    WIRE        = 0,
    BARBED_WIRE = 1,
    ROPE        = 2
}
Function Documentation
CanDisplayAttachmentSlot()
override bool CanDisplayAttachmentSlot (int slot_id)
Definition at line 211 of file trap_tripwire.c.
    {
        if ( GetState() != DEPLOYED )
            return false;
        return super.CanDisplayAttachmentSlot( slot_id );
    }
References DEPLOYED, and GetState().
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
Definition at line 202 of file trap_tripwire.c.
    {
        if ( GetState() != DEPLOYED )
            return false;
        return super.CanReceiveAttachment( attachment, slotId );
    }
References DEPLOYED, and GetState().
CreateTrigger()
override void CreateTrigger ()
Definition at line 70 of file trap_tripwire.c.
    {
        m_TrapTrigger = TripWireTrigger.Cast(GetGame().CreateObjectEx("TripWireTrigger", GetPosition(), SPAWN_FLAGS));
        vector mins = "-0.75 0.3 -0.01";
        vector maxs = "0.75 0.32 0.01";
        m_TrapTrigger.SetOrientation(GetOrientation());
        m_TrapTrigger.SetExtents(mins, maxs);
        m_TrapTrigger.SetParentObject(this);
    }
References GetGame(), GetOrientation(), GetPosition, m_TrapTrigger, Trigger::SetExtents(), TrapTrigger::SetParentObject(), and SPAWN_FLAGS.
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name)
Definition at line 219 of file trap_tripwire.c.
    {
        super.EEItemAttached(item, slot_name);
        SetTakeable(false);
    }
References SetTakeable().
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name)
Definition at line 226 of file trap_tripwire.c.
    {
        super.EEItemDetached(item, slot_name);
        SetTakeable(false);
    }
References SetTakeable().
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
Definition at line 118 of file trap_tripwire.c.
    {
        super.EEItemLocationChanged(oldLoc, newLoc);
        if (m_ResultOfAdvancedPlacing)
        {
            if (oldLoc.GetType() == InventoryLocationType.GROUND && newLoc.GetType() == InventoryLocationType.GROUND)
            {
                SetActive();
                m_TrapTrigger.SetPosition(m_TriggerPosition);
                m_TrapTrigger.SetOrientation(m_TriggerOrientation);
            }
            m_ResultOfAdvancedPlacing = false;
        }
    }
References m_ResultOfAdvancedPlacing, m_TrapTrigger, m_TriggerOrientation, m_TriggerPosition, and SetActive().
EEKilled()
override void EEKilled (Object killer)
Definition at line 233 of file trap_tripwire.c.
    {
        if (m_TrapTrigger)
        {
            StartDeactivate(null);
        }
        super.EEKilled(killer);
    }
References m_TrapTrigger, and StartDeactivate().
FoldTripWire()
void FoldTripWire ()
Definition at line 244 of file trap_tripwire.c.
    {
        if ( m_AnimationPhaseGrounded != "" )
        {
            SetAnimationPhase( m_AnimationPhaseSet, 1 );
            if ( m_AnimationPhaseTriggered != m_AnimationPhaseGrounded )
            {
                SetAnimationPhase( m_AnimationPhaseTriggered, 1 );
            }
            SetAnimationPhase( m_AnimationPhaseGrounded, 0 );
        }
    }
References m_AnimationPhaseGrounded, m_AnimationPhaseSet, and m_AnimationPhaseTriggered.
Referenced by RefreshState().
GetDeploySoundset()
override string GetDeploySoundset ()
Definition at line 358 of file trap_tripwire.c.
    {
        return "tripwire_deploy_SoundSet";
    }
GetLoopDeploySoundset()
override string GetLoopDeploySoundset ()
Definition at line 363 of file trap_tripwire.c.
    {
        return "tripwiretrap_deploy_SoundSet";
    }
GetState()
int GetState ()
returns one of STATE_...
returns the state of climb (enum value of ClimbStates);
Definition at line 161 of file trap_tripwire.c.
    {
        return m_State;
    }
References m_State.
Referenced by ItemBase::CanAttach(), ItemBase::CanBeManipulated(), ItemBase::CanBePacked(), ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), CanDisplayAttachmentSlot(), FireworksLauncher::CanPutInCargo(), FireworksLauncher::CanPutIntoHands(), CanReceiveAttachment(), ItemBase::EEHealthLevelChanged(), GetStateString(), ItemBase::GetViewIndex(), ItemBase::HandleOpeningsPhysics(), FireworksLauncher::IsIgnited(), IsTakeable(), FireworksLauncher::OnPlacementComplete(), RefreshState(), ItemBase::UpdatePhysics(), UpdateProxySelections(), and ItemBase::UpdateVisuals().
GetWireType()
int GetWireType ()
Definition at line 171 of file trap_tripwire.c.
    {
        return m_WireMaterial;
    }
References m_WireMaterial.
IsDeployable()
override bool IsDeployable ()
Definition at line 347 of file trap_tripwire.c.
    {
        return true;
    }
IsTakeable()
override bool IsTakeable ()
Definition at line 353 of file trap_tripwire.c.
    {
        return !IsRuined() && (GetState() != DEPLOYED || (GetInventory().AttachmentCount() == 0 && GetState() == DEPLOYED));
    }
References DEPLOYED, GetState(), and IsRuined().
OnInventoryEnter()
override void OnInventoryEnter (Man player)
Definition at line 259 of file trap_tripwire.c.
    {
        SetState( FOLDED );
    }
References FOLDED, and SetState().
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
Definition at line 107 of file trap_tripwire.c.
    {
        super.OnItemLocationChanged(old_owner, new_owner);
        PlayerBase player = PlayerBase.Cast( new_owner );
        if (player)
        {
            StartDeactivate(player);
        }
    }
References StartDeactivate().
OnPlacementCancelled()
override void OnPlacementCancelled (Man player)
Definition at line 338 of file trap_tripwire.c.
    {
        super.OnPlacementCancelled(player);
        SetState(FOLDED);
        m_ResultOfAdvancedPlacing = false;
    }
References FOLDED, m_ResultOfAdvancedPlacing, and SetState().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0")
Definition at line 323 of file trap_tripwire.c.
    {
        super.OnPlacementComplete(player, position, orientation);
        SetIsPlaceSound(true);
        if (GetGame().IsServer())
        {
            SetState(DEPLOYED);
            m_TriggerPosition           = position;
            m_TriggerOrientation        = orientation;
            m_ResultOfAdvancedPlacing   = true;
        }
    }
References DEPLOYED, GetGame(), m_ResultOfAdvancedPlacing, m_TriggerOrientation, m_TriggerPosition, SetIsPlaceSound(), and SetState().
OnSteppedOn()
override void OnSteppedOn (EntityAI victim)
Definition at line 80 of file trap_tripwire.c.
    {
        if (!victim)
        {
            return;
        }
        if (!victim.GetAllowDamage())
        {
            return;
        }
        // We must deal some damage, here 5 shock as melee damage in order to trigger hit animation
        if (GetGame().IsServer())
        {
            victim.ProcessDirectDamage(DT_CLOSE_COMBAT, this, "", "TripWireHit", "0 0 0", 1);
            SetState(TRIGGERED);
            SetInactive(false);
        }
        // We play the trap trigger sound
        #ifndef SERVER
        EffectSound sound = SEffectManager.PlaySound("TripwireTrap_Trigger_SoundSet", GetPosition());
        sound.SetAutodestroy(true);
        #endif
    }
References GetGame(), GetPosition, SEffectManager::PlaySound(), EffectSound::SetAutodestroy(), SetInactive(), SetState(), and TRIGGERED.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 55 of file trap_tripwire.c.
    {
        if ( !super.OnStoreLoad(ctx, version) )
            return false;
        int state = FOLDED;
        if ( !ctx.Read( state ) )
            state = FOLDED;
        SetState( state );
        RefreshState();
        return true;
    }
References FOLDED, Serializer::Read(), RefreshState(), and SetState().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
Definition at line 47 of file trap_tripwire.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write( m_State );
    }
References m_State, and Serializer::Write().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 37 of file trap_tripwire.c.
    {
        super.OnVariablesSynchronized();
        if ( IsPlaceSound() )
        {
            PlayPlaceSound();
        }
    }
References IsPlaceSound(), and PlayPlaceSound().
RefreshState()
override void RefreshState ()
Definition at line 177 of file trap_tripwire.c.
    {
        super.RefreshState();
        if (GetState() == FOLDED)
        {
            FoldTripWire();
        }
    }
References FOLDED, FoldTripWire(), and GetState().
SetActions()
override void SetActions ()
Definition at line 368 of file trap_tripwire.c.
    {
        super.SetActions();
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionDeployObject);
    }
References ActionDeployObject(), and AddAction().
SetInactive()
override void SetInactive (bool stop_timer = true)
Definition at line 135 of file trap_tripwire.c.
    {
        super.SetInactive(stop_timer);
        // de-attach attachments after "activating them"
        for (int att = 0; att < GetInventory().AttachmentCount(); att++)
        {
            ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(att));
            if (attachment)
            {
                if (attachment.IsLockedInSlot())
                {
                    attachment.UnlockFromParent();
                }
                attachment.OnActivatedByItem(this);
                GetInventory().DropEntity(InventoryMode.SERVER, this, attachment);
            }
        }
    }
SetState()
void SetState (int state_ID)
Definition at line 156 of file trap_tripwire.c.
    {
        m_State = state_ID;
    }
References m_State.
SetupTrapPlayer()
override void SetupTrapPlayer (PlayerBase player, bool set_position = true)
Definition at line 187 of file trap_tripwire.c.
    {
        super.SetupTrapPlayer( player, set_position );
        SetState(DEPLOYED);
    }
References DEPLOYED, and SetState().
SetWireType()
void SetWireType (int wireType)
Definition at line 166 of file trap_tripwire.c.
    {
        m_WireMaterial = wireType;
    }
References m_WireMaterial.
StartDeactivate()
override void StartDeactivate (PlayerBase player)
Definition at line 193 of file trap_tripwire.c.
    {
        super.StartDeactivate(player);
        DeleteTrigger();
        SetState(FOLDED);
    }
References DeleteTrigger(), FOLDED, and SetState().
Referenced by EEKilled(), and OnItemLocationChanged().
TripwireTrap()
void TripwireTrap ()
Definition at line 23 of file trap_tripwire.c.
    {
        m_DamagePlayers = 0;            //How much damage player gets when caught
        m_InitWaitTime = 0;             //After this time after deployment, the trap is activated
        m_DefectRate = 15;
        m_NeedActivation = false;
        m_AnimationPhaseGrounded = "inventory";
        m_AnimationPhaseSet = "placing";
        m_AnimationPhaseTriggered = "triggered";
        m_InfoActivationTime = string.Format("#STR_TripwireTrap0%1#STR_TripwireTrap1", m_InitWaitTime.ToString());  // nefunguje dynamicke vyrazy mimo funkcii
        RegisterNetSyncVariableInt("m_State");
    }
References string::Format(), m_AnimationPhaseGrounded, m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DamagePlayers, m_DefectRate, m_InfoActivationTime, m_InitWaitTime, and m_NeedActivation.
Referenced by RecipeBase::Do(), and Roadflare::OnActivatedByItem().
UpdateProxySelections()
void UpdateProxySelections ()
Definition at line 380 of file trap_tripwire.c.
    {
        if ( GetInventory().AttachmentCount() > 0)
        {
            ItemBase attachment = ItemBase.Cast( GetInventory().GetAttachmentFromIndex(0) );
            if ( attachment )
            {
                // Hide all proxies
                for (int i = 1; i <= 3; i++)
                {
                    HideSelection("s" + i + "_charge");
                }
                // Now show the one we need to see
                string proxy_to_show = string.Format("s%1_charge", GetState() );
                //Print(proxy_to_show);
                ShowSelection( proxy_to_show );
            }
        }
    }
References AttachmentCount(), GetAttachmentFromIndex(), and GetState().
Variable Documentation
DEPLOYED
const int DEPLOYED = 2 static
Definition at line 13 of file trap_tripwire.c.
Referenced by CanDisplayAttachmentSlot(), CanReceiveAttachment(), IsTakeable(), OnPlacementComplete(), and SetupTrapPlayer().
FOLDED
enum eWireMaterial FOLDED = 3
Referenced by Inventory_Base::CanBeManipulated(), Inventory_Base::Fold(), Inventory_Base::HescoBox(), OnInventoryEnter(), OnPlacementCancelled(), OnStoreLoad(), RefreshState(), and StartDeactivate().
m_ResultOfAdvancedPlacing
protected bool m_ResultOfAdvancedPlacing
Definition at line 19 of file trap_tripwire.c.
Referenced by EEItemLocationChanged(), OnPlacementCancelled(), and OnPlacementComplete().
m_State
int m_State = FOLDED
Definition at line 16 of file trap_tripwire.c.
m_TriggerOrientation
protected vector m_TriggerOrientation
Definition at line 21 of file trap_tripwire.c.
Referenced by EEItemLocationChanged(), and OnPlacementComplete().
m_TriggerPosition
protected vector m_TriggerPosition
Definition at line 20 of file trap_tripwire.c.
Referenced by EEItemLocationChanged(), and OnPlacementComplete().
m_WireMaterial
private int m_WireMaterial
Definition at line 17 of file trap_tripwire.c.
Referenced by GetWireType(), and SetWireType().
TRIGGERED
const int TRIGGERED = 1 static
Definition at line 14 of file trap_tripwire.c.
Referenced by OnSteppedOn().