DayzKode: P:/scripts/4_world/DayZ/entities/itembase/trapbase.c File Reference
trapbase.c File Reference
Enumerations
enum SoundTypeTrap { ACTIVATING = 5 }
Functions
void AddDefect ()
bool CanBeClapped ()
DEPRECATED Set if trap can be disarmed using ActionClapBearTrapWithThisItem.
bool CanBeDisarmed ()
override bool CanBePlaced (Man player, vector position)
override string CanBePlacedFailMessage (Man player, vector position)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanRemoveFromHands (EntityAI parent)
void CreateTrigger ()
protected void DamageClothing (PlayerBase player)
void DeleteTrigger ()
void Disarm ()
override void EEDelete (EntityAI parent)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
protected EntityAI GetClosestCarWheel (EntityAI victim)
bool GetDisarmed ()
DEPRECATED.
bool IsActivable ()
bool IsActive ()
bool IsInactive ()
bool IsPlaceable ()
bool IsPlaceableAtPosition (vector position)
override bool IsTakeable ()
void OnActivate ()
HumanCommandScript fully scriptable command.
void OnDisarm ()
also called from RPC on client
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
void OnSteppedOn (EntityAI victim)
void OnSteppedOut (EntityAI victim)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
void OnUpdate (EntityAI victim)
override void OnVariablesSynchronized ()
this event is called all variables are synchronized on client
void PlayDeployLoopSound ()
void RefreshState ()
void RemoveFromObject (EntityAI victim)
override void SetActions ()
void SetActive ()
void SetDisarmed (bool disarmed)
DEPRECATED.
void SetInactive (bool stop_timer=true)
void SetupTrap ()
void SetupTrapPlayer (PlayerBase player, bool set_position=true)
void SnapOnObject (EntityAI victim)
void StartActivate (PlayerBase player)
void StartDeactivate (PlayerBase player)
void StopDeployLoopSound ()
protected void Synch (EntityAI victim)
keeping "step" here for consistency only
void TrapBase ()
void ~TrapBase ()
Variables
protected const int DAMAGE_TRIGGER_MINE = 75
bool m_AddActivationDefect
bool m_AddDeactivationDefect
string m_AnimationPhaseGrounded
string m_AnimationPhaseSet
string m_AnimationPhaseTriggered
protected ref array< int > m_ClothingDmg
float m_DamageOthers
float m_DamagePlayers
float m_DefectRate
protected ref EffectSound m_DeployLoopSound
protected bool m_Disarmed = false
string m_InfoActivationTime
string m_InfoDamage
string m_InfoDamageManipulation
string m_InfoDeactivated
string m_InfoSetup
int m_InitWaitTime
protected bool m_IsActive
protected bool m_IsInProgress
bool m_NeedActivation
protected ref Timer m_Timer
protected TrapTrigger m_TrapTrigger
protected ref Timer m_UpdateTimer
bool m_WasActivatedOrDeactivated
DEPRECATED Used for explosive traps to prevent detonation after destroying through disarm action.
enum SoundTypeTrap SPAWN_FLAGS = ECE_LOCAL
protected const float UPDATE_TIMER_INTERVAL = 0.05
Enumeration Type Documentation
SoundTypeTrap
enum SoundTypeTrap
Enumerator
ACTIVATING
Definition at line 1 of file trapbase.c.
{
    ACTIVATING          = 5,
}
Function Documentation
AddDefect()
void AddDefect ()
Definition at line 455 of file trapbase.c.
    {
        if ( GetGame().IsServer() )
        {
            DecreaseHealth( "", "", m_DefectRate );
        }
    }
References DecreaseHealth(), GetGame(), and m_DefectRate.
Referenced by SetActive(), SetInactive(), and TrapSpawnBase::SpawnCatch().
CanBeClapped()
bool CanBeClapped ()
DEPRECATED Set if trap can be disarmed using ActionClapBearTrapWithThisItem.
Definition at line 629 of file trapbase.c.
    {
        return true;
    }
CanBeDisarmed()
bool CanBeDisarmed ()
Definition at line 635 of file trapbase.c.
    {
        return false;
    }
CanBePlaced()
override bool CanBePlaced (Man player, vector position)
Definition at line 618 of file trapbase.c.
    {
        return IsPlaceableAtPosition( position );
    }
References IsPlaceableAtPosition().
CanBePlacedFailMessage()
override string CanBePlacedFailMessage (Man player, vector position)
Definition at line 623 of file trapbase.c.
    {
        return "Trap can't be placed on this surface type.";
    }
CanPutInCargo()
override bool CanPutInCargo (EntityAI parent)
Definition at line 593 of file trapbase.c.
    {
        if ( !super.CanPutInCargo(parent) )
        {
            return false;
        }
        return IsTakeable();
    }
References IsTakeable().
CanPutIntoHands()
override bool CanPutIntoHands (EntityAI parent)
Definition at line 603 of file trapbase.c.
    {
        if ( !super.CanPutIntoHands( parent ) )
        {
            return false;
        }
        return IsTakeable();
    }
References IsTakeable().
CanRemoveFromHands()
override bool CanRemoveFromHands (EntityAI parent)
Definition at line 613 of file trapbase.c.
    {
        return IsTakeable();
    }
References IsTakeable().
CreateTrigger()
void CreateTrigger ()
Definition at line 530 of file trapbase.c.
    {
        if (Class.CastTo(m_TrapTrigger, GetGame().CreateObjectEx("TrapTrigger", GetPosition(), SPAWN_FLAGS)))
        {
            vector mins = "-0.01 -0.05 -0.01";
            vector maxs = "0.01 0.5 0.01";
            m_TrapTrigger.SetOrientation(GetOrientation());
            m_TrapTrigger.SetExtents(mins, maxs);
            m_TrapTrigger.SetParentObject(this);
        }
    }
References Class::CastTo(), GetGame(), GetOrientation(), GetPosition, m_TrapTrigger, Trigger::SetExtents(), TrapTrigger::SetParentObject(), and SPAWN_FLAGS.
Referenced by ContaminatedArea_Static::InitZoneServer(), ContaminatedArea_Dynamic::InitZoneServer(), and SpookyArea::InitZoneServer().
DamageClothing()
protected void DamageClothing (PlayerBase player)
Definition at line 726 of file trapbase.c.
    {
        //Array used to find all relevant information about currently equipped clothes
        array<ClothingBase> equippedClothes = new array<ClothingBase>;
        equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("LEGS")));
        equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("BACK")));
        equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("VEST")));
        equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("HeadGear")));
        equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("Mask")));
        equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("BODY")));
        equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("FEET")));
        equippedClothes.Insert(ClothingBase.Cast(player.GetItemOnSlot("GLOVES")));
        //Damage all currently equipped clothes
        for (int i = 0; i < equippedClothes.Count(); i++)
        {
            //If no item is equipped on slot, slot is ignored
            if (equippedClothes[i] == null)
            {
                continue;
            }
            equippedClothes[i].DecreaseHealth(m_ClothingDmg[i], false);
        }
    }
References m_ClothingDmg.
Referenced by OnSteppedOn().
DeleteTrigger()
void DeleteTrigger ()
Definition at line 542 of file trapbase.c.
    {
        GetGame().ObjectDelete(m_TrapTrigger);
        m_TrapTrigger = null;
    }
References GetGame(), m_TrapTrigger, and CGame::ObjectDelete().
Referenced by SetInactive(), and StartDeactivate().
Disarm()
void Disarm ()
Definition at line 228 of file trapbase.c.
    {
        SetInactive(false);
        RefreshState();
        GetGame().RPCSingleParam(this, ERPCs.RPC_TRAP_DISARM, null, true);
        OnDisarm();
    }
References GetGame(), TrapBase::OnDisarm(), RefreshState(), CGame::RPCSingleParam(), and SetInactive().
EEDelete()
override void EEDelete (EntityAI parent)
Definition at line 122 of file trapbase.c.
    {
        super.EEDelete(parent);
        //GetGame() can be sometimes NULL when turning off server
        if ( GetGame() && m_TrapTrigger )
        {
            GetGame().ObjectDelete( m_TrapTrigger );
            m_TrapTrigger = NULL;
        }
    }
References GetGame(), m_TrapTrigger, and CGame::ObjectDelete().
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name)
Definition at line 573 of file trapbase.c.
    {
        super.EEItemAttached(item, slot_name);
        if ( GetGame().IsServer() )
        {
            RefreshState();
        }
    }
References GetGame(), and RefreshState().
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name)
Definition at line 583 of file trapbase.c.
    {
        super.EEItemDetached(item, slot_name);
        if ( GetGame().IsServer() )
        {
            RefreshState();
        }
    }
References GetGame(), and RefreshState().
GetClosestCarWheel()
protected EntityAI GetClosestCarWheel (EntityAI victim)
carscript specific handling (not all traps are uses this)
ruined wheel, bail out
ignore all spare wheel
actual, healthy wheel, let it pass
Definition at line 685 of file trapbase.c.
    {
        vector trapPosXZ = GetPosition();
        trapPosXZ[1] = 0;
        GameInventory inv = victim.GetInventory();
        for (int i = 0; i < inv.AttachmentCount(); i++)
        {
            EntityAI wheelEntity = inv.GetAttachmentFromIndex(i);
            if (wheelEntity && wheelEntity.Type() == CarWheel_Ruined)
            {
                continue;
            }
            int slotId;
            string slotName;
            wheelEntity.GetInventory().GetCurrentAttachmentSlotInfo(slotId, slotName);
            slotName.ToLower();
            if (slotName.Contains("spare"))
            {
                continue
            }
            if (wheelEntity && wheelEntity.IsInherited(CarWheel))
            {
                vector entPosXZ = wheelEntity.GetPosition();
                entPosXZ[1] = 0;
                if (vector.Distance(trapPosXZ, entPosXZ) < 1)
                {
                    return wheelEntity;
                }
            }
        }
        return null;
    }
References string::Contains(), vector::Distance(), GetPosition, and string::ToLower().
Referenced by OnUpdate(), and TrapBase::OnUpdate().
GetDisarmed()
bool GetDisarmed ()
DEPRECATED.
Definition at line 647 of file trapbase.c.
    {
        return m_Disarmed;
    }
References m_Disarmed.
IsActivable()
bool IsActivable ()
Definition at line 191 of file trapbase.c.
    {
        return !IsActive() && GetHierarchyRootPlayer() == null && GetHierarchyParent() == null && m_IsInProgress == false && !IsRuined() && m_NeedActivation;
    }
References IsActive(), IsRuined(), m_IsInProgress, and m_NeedActivation.
IsActive()
bool IsActive ()
Definition at line 170 of file trapbase.c.
    {
        return m_IsActive && m_IsInProgress == false && GetHierarchyRootPlayer() == null;
    }
References m_IsActive, and m_IsInProgress.
IsInactive()
bool IsInactive ()
Definition at line 175 of file trapbase.c.
    {
        return !IsActive() && m_IsInProgress == false && GetHierarchyRootPlayer() == null;
    }
References IsActive(), and m_IsInProgress.
Referenced by RefreshState().
IsPlaceable()
bool IsPlaceable ()
Definition at line 196 of file trapbase.c.
    {
        if ( GetHierarchyRootPlayer() != null && GetHierarchyRootPlayer().GetHumanInventory().GetEntityInHands() == this )
        {
            PlayerBase player = PlayerBase.Cast( GetHierarchyRootPlayer() );
            vector player_pos = player.GetPosition();
            vector aim_pos = player.GetAimPosition();
            if ( vector.DistanceSq( player_pos, aim_pos ) <= ( Math.SqrFloat( 1.5 ) ) )
            {
                return IsPlaceableAtPosition( aim_pos );
            }
        }
        return false;
    }
References vector::DistanceSq(), IsPlaceableAtPosition(), and Math::SqrFloat().
IsPlaceableAtPosition()
bool IsPlaceableAtPosition (vector position)
Definition at line 214 of file trapbase.c.
    {
        if ( GetGame().SurfaceIsSea( position[0], position[2] ) )
        {
            return false;
        }
        else if ( GetGame().SurfaceIsPond( position[0], position[2] ) )
        {
            return false;
        }
        return true;
    }
References GetGame().
Referenced by CanBePlaced(), and IsPlaceable().
IsTakeable()
override bool IsTakeable ()
Definition at line 181 of file trapbase.c.
    {
        if ( m_IsInProgress == false && !IsActive() )
        {
            return true;
        }
        return false;
    }
References IsActive(), and m_IsInProgress.
OnActivate()
void OnActivate ()
HumanCommandScript fully scriptable command.
Warning
NON-MANAGED, will be managed by C++ once it is sent to the CommandHandler through Human.StartCommand_Script
Note
So ideally, it is best to set up the HumanCommandScript, not create any instances and start it through Human.StartCommand_ScriptInst In case an instance needs to be created, it needs manual deletion if not sent to the CommandHandler But deleting it while it is in the CommandHandler will cause crashes constructor must have 1st parameter to be Human virtual to be overridden called when command starts
Definition at line 1072 of file human.c.
{ };
References GetGame(), GetPlayer(), m_TimerLoopSound, and PlaySoundActivate().
Referenced by Activate(), AntibioticsMdfr::OnReconnect(), CharcoalMdfr::OnReconnect(), FatigueMdfr::OnReconnect(), FeverMdfr::OnReconnect(), HemolyticReactionMdfr::OnReconnect(), PoisoningMdfr::OnReconnect(), WetMdfr::OnReconnect(), DisinfectionMdfr::OnReconnect(), DrowningMdfr::OnReconnect(), EpinephrineMdfr::OnReconnect(), FliesMdfr::OnReconnect(), ImmunityBoost::OnReconnect(), MaskMdfr::OnReconnect(), MorphineMdfr::OnReconnect(), PainKillersMdfr::OnReconnect(), and SalineMdfr::OnReconnect().
OnDisarm()
void OnDisarm ()
also called from RPC on client
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
Definition at line 548 of file trapbase.c.
    {
        super.OnItemLocationChanged(old_owner, new_owner);
        if (GetGame().IsServer())
        {
            RefreshState();
            // TAKE ACTIVE TRAP FROM VICINITY
            if (old_owner == NULL && new_owner != NULL && IsActive())
            {
                // TAKE INTO HANDS
                if ( new_owner.IsPlayer() )
                {
                    SnapOnObject(new_owner);
                }
                else if (new_owner.GetHierarchyRootPlayer())
                {
                    SnapOnObject(new_owner.GetHierarchyRootPlayer());
                }
            }
        }
    }
References GetGame(), IsActive(), RefreshState(), and SnapOnObject().
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
Parameters
rpc_type user defined identification of RPC
ctx read context for params
Definition at line 324 of file trapbase.c.
    {
        super.OnRPC(sender, rpc_type, ctx);
        if ( !GetGame().IsDedicatedServer() )
        {
            switch (rpc_type)
            {
                case ERPCs.RPC_TRAP_VICTIM:
                    ref Param1<EntityAI> p_victim = new Param1<EntityAI>(NULL);
                    if (ctx.Read(p_victim))
                    {
                        if (p_victim.param1)
{
                            SnapOnObject(p_victim.param1);
                        }
                    }
                break;
                case ERPCs.RPC_TRAP_DISARM:
                    OnDisarm();
                break;
                case SoundTypeTrap.ACTIVATING:
                    ref Param1<bool> p = new Param1<bool>(false);
                    if (ctx.Read(p))
                    {
                        bool play = p.param1;
                    }
                    if ( play )
                    {
                        PlayDeployLoopSound();
                    }
                    if ( !play )
                    {
                        StopDeployLoopSound();
                    }
                break;
            }
        }
    }
References GetGame(), TrapBase::OnDisarm(), PlayDeployLoopSound(), Serializer::Read(), SnapOnObject(), and StopDeployLoopSound().
OnSteppedOn()
void OnSteppedOn (EntityAI victim)
Definition at line 298 of file trapbase.c.
    {
        SetInactive(false);
    }
References SetInactive().
OnSteppedOut()
void OnSteppedOut (EntityAI victim)
Definition at line 160 of file trap_landmine.c.
    {
        if (victim.IsInherited(CarScript))
        {
            if (m_UpdateTimer && m_UpdateTimer.IsRunning())
            {
                m_UpdateTimer.Stop();
            }
        }
    }
References m_UpdateTimer.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 144 of file trapbase.c.
    {
        if ( !super.OnStoreLoad(ctx, version) )
            return false;
        bool b_is_active = false;
        if ( !ctx.Read( b_is_active ) )
            b_is_active = false;
        bool b_is_in_progress = false;
        if ( !ctx.Read( b_is_in_progress ) )
            b_is_in_progress = false;
        if ( b_is_active )
        {
            SetActive();
        }
        if (b_is_in_progress &&  !b_is_active)
        {
            StartActivate(null);
        }
        return true;
    }
References Serializer::Read(), SetActive(), and StartActivate().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
Definition at line 134 of file trapbase.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write(m_IsActive);
        ctx.Write(m_IsInProgress);
    }
References m_IsActive, m_IsInProgress, and Serializer::Write().
OnUpdate()
void OnUpdate (EntityAI victim)
Definition at line 83 of file trap_landmine.c.
    {
        if (victim && victim.IsInherited(CarScript))
        {
            EntityAI wheel = GetClosestCarWheel(victim);
            if (wheel)
            {
                OnServerSteppedOn(wheel, "");
            }
        }
    }
References GetClosestCarWheel(), and TrapBase::OnServerSteppedOn().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
this event is called all variables are synchronized on client
Definition at line 89 of file trapbase.c.
    {
        super.OnVariablesSynchronized();
        if ( IsDeploySound() )
        {
            PlayDeploySound();
        }
        if ( CanPlayDeployLoopSound() )
        {
            PlayDeployLoopSound();
        }
        if ( m_DeployLoopSound && !CanPlayDeployLoopSound() )
        {
            StopDeployLoopSound();
        }
        if ( GetGame().IsMultiplayer() )
        {
            if (m_IsActive)
            {
                SetActive();
            }
            if (m_IsInProgress && !m_IsActive)
            {
                StartActivate(null);
            }
        }
    }
References CanPlayDeployLoopSound(), GetGame(), IsDeploySound(), m_DeployLoopSound, m_IsActive, m_IsInProgress, PlayDeployLoopSound(), PlayDeploySound(), SetActive(), StartActivate(), and StopDeployLoopSound().
PlayDeployLoopSound()
void PlayDeployLoopSound ()
Definition at line 656 of file trapbase.c.
    {
        #ifndef SERVER
        if (!m_DeployLoopSound || !m_DeployLoopSound.IsSoundPlaying())
        {
            m_DeployLoopSound = SEffectManager.PlaySound(GetLoopDeploySoundset(), GetPosition());
        }
        #endif
    }
References TrapBase::GetLoopDeploySoundset(), GetPosition, EffectSound::IsSoundPlaying(), m_DeployLoopSound, and SEffectManager::PlaySound().
Referenced by OnRPC(), ItemBase::OnVariablesSynchronized(), and OnVariablesSynchronized().
RefreshState()
void RefreshState ()
Definition at line 374 of file trapbase.c.
    {
        if ( !m_WasActivatedOrDeactivated )
        {
            return;
        }
        if ( GetGame().IsServer() )
        {
            // item is owned by player
            if ( GetHierarchyRootPlayer() != NULL && m_AnimationPhaseGrounded != "" )
            {
                SetAnimationPhase( m_AnimationPhaseSet, 1 );
                if ( m_AnimationPhaseTriggered != m_AnimationPhaseGrounded )
                {
                    SetAnimationPhase( m_AnimationPhaseTriggered, 1 );
                }
                SetAnimationPhase( m_AnimationPhaseGrounded, 0 );
            }
            // item is set active
            else if ( IsActive() )
            {
                if ( m_AnimationPhaseGrounded != "" )
                {
                    SetAnimationPhase( m_AnimationPhaseGrounded, 1 );
                }
                if ( m_AnimationPhaseSet != "" && m_AnimationPhaseTriggered != "" )
                {
                    SetAnimationPhase( m_AnimationPhaseTriggered, 1 );
                    SetAnimationPhase( m_AnimationPhaseSet, 0 );
                }
            }
            // item is inactive and not owned by player (on the ground)
            else if ( IsInactive() )
            {
                if ( m_AnimationPhaseGrounded != "" &&  m_AnimationPhaseTriggered != m_AnimationPhaseGrounded )
                {
                    SetAnimationPhase( m_AnimationPhaseGrounded, 1 );
                }
                if ( m_AnimationPhaseSet != "" && m_AnimationPhaseTriggered != "" )
                {
                    SetAnimationPhase( m_AnimationPhaseSet, 1 );
                    SetAnimationPhase( m_AnimationPhaseTriggered, 0 );
                }
            }
        }
    }
References GetGame(), IsActive(), IsInactive(), m_AnimationPhaseGrounded, m_AnimationPhaseSet, m_AnimationPhaseTriggered, and m_WasActivatedOrDeactivated.
Referenced by Disarm(), EEItemAttached(), EEItemDetached(), OnItemLocationChanged(), OnStoreLoad(), SetActive(), SetInactive(), and SnapOnObject().
RemoveFromObject()
void RemoveFromObject (EntityAI victim)
Definition at line 292 of file trapbase.c.
    {
        OnSteppedOut(victim);
        Synch(null);
    }
References TrapBase::OnSteppedOut(), and Synch().
SetActions()
override void SetActions ()
Definition at line 677 of file trapbase.c.
    {
        super.SetActions();
        AddAction(ActionActivateTrap);
    }
References AddAction().
SetActive()
void SetActive ()
Definition at line 463 of file trapbase.c.
    {
        m_WasActivatedOrDeactivated = true;
        m_IsInProgress = false;
        m_IsActive = true;
        if (m_AddActivationDefect)
        {
            AddDefect();
        }
        if (GetGame().IsServer())
        {
            CreateTrigger();
            RefreshState();
            Synch(null);
        }
        OnActivate();
    }
References AddDefect(), TrapBase::CreateTrigger(), GetGame(), m_AddActivationDefect, m_IsActive, m_IsInProgress, m_WasActivatedOrDeactivated, TrapBase::OnActivate(), RefreshState(), and Synch().
Referenced by ItemBase::EEItemAttached(), EEItemLocationChanged(), Icon::Icon(), UniversalTemperatureSourceDebug::Init(), ItemBase::OnItemLocationChanged(), ItemBase::OnPlacementComplete(), OnStoreLoad(), ItemBase::OnStoreLoad(), OnVariablesSynchronized(), HandsContainer::Refresh(), Container::Select(), LayoutHolder::SetFirstActive(), Container::SetNextActive(), AttachmentsGroupContainer::SetNextActive(), LayoutHolder::SetNextActive(), Container::SetPreviousActive(), AttachmentsGroupContainer::SetPreviousActive(), LayoutHolder::SetPreviousActive(), TrapSpawnBase::SetupTrap(), SetupTrapPlayer(), SlotsIcon::SlotsIcon(), and StartActivate().
SetDisarmed()
void SetDisarmed (bool disarmed)
DEPRECATED.
Definition at line 641 of file trapbase.c.
    {
        m_Disarmed = disarmed;
    }
References m_Disarmed.
SetInactive()
void SetInactive (bool stop_timer = true)
Definition at line 510 of file trapbase.c.
    {
        m_WasActivatedOrDeactivated = true;
        m_IsActive = false;
        if (m_Timer && stop_timer)
        {
            m_Timer.Stop();
        }
        if (m_AddDeactivationDefect)
        {
            AddDefect();
        }
        DeleteTrigger();
        RefreshState();
        Synch(null);
    }
References AddDefect(), DeleteTrigger(), m_AddDeactivationDefect, m_IsActive, m_Timer, m_WasActivatedOrDeactivated, RefreshState(), and Synch().
Referenced by Disarm(), TrapBase::EEHealthLevelChanged(), ItemBase::Fold(), ItemBase::OnItemLocationChanged(), TrapBase::OnServerSteppedOn(), OnServerSteppedOn(), and OnSteppedOn().
SetupTrap()
void SetupTrap ()
Definition at line 422 of file trapbase.c.
    {
        if ( GetGame().IsServer() )
        {
            if ( GetHierarchyRootPlayer() && GetHierarchyRootPlayer().CanDropEntity( this ) )  // kvoli desyncu
            {
                SetupTrapPlayer( PlayerBase.Cast( GetHierarchyRootPlayer() ) );
            }
        }
    }
References GetGame(), and SetupTrapPlayer().
SetupTrapPlayer()
void SetupTrapPlayer (PlayerBase player, bool set_position = true)
Definition at line 433 of file trapbase.c.
    {
        if ( GetGame().IsServer() )
        {
            if ( set_position )
            {
                Error("Mojmir: TODO");
                player.LocalDropEntity( this );
                vector trapPos = ( player.GetDirection() ) * 1.5;
                trapPos[1] = 0;
                SetPosition( player.GetPosition() + trapPos );
            }
            if ( m_NeedActivation == false )
            {
                SetActive();
            }
            //player.MessageStatus( m_InfoSetup );
        }
    }
References Error(), GetGame(), m_NeedActivation, SetActive(), and SetPosition().
Referenced by ItemBase::OnPlacementComplete(), SetupTrap(), and ItemBase::SetupTrap().
SnapOnObject()
void SnapOnObject (EntityAI victim)
Definition at line 240 of file trapbase.c.
    {
        if ( GetGame().IsServer() )
        {
            if ( m_Timer )
            {
                m_Timer.Stop();
            }
            RefreshState();
            if (m_DamagePlayers > 0)
            {
                if (victim)
                {
                    if ( victim.IsInherited(SurvivorBase))
                    {
                        victim.DecreaseHealth("", "", m_DamagePlayers);
                    }
                    else if (victim.IsInherited(DayZCreatureAI))
                    {
                        victim.DecreaseHealth("", "", m_DamageOthers);
                    }
                    else if (victim.IsInherited(ItemBase))
                    {
                        ItemBase victim_item = ItemBase.Cast(victim);
                        float damage_coef = 1;
                        if (victim_item.HasQuantity() && victim_item.GetQuantityMax() != 0 && victim_item.GetQuantity() > 0)
{
                            damage_coef = victim_item.GetQuantityMax() / victim_item.GetQuantity(); // Lower quantity increases damage exposure
                        }
                        if (damage_coef > 0)
{
                            int item_size_x = 1;
                            int item_size_y = 1;
                            GetGame().GetInventoryItemSize(victim_item, item_size_x, item_size_y);
                            float add_damage = 300 * damage_coef / Math.Clamp(item_size_x * item_size_y, 1, int.MAX);
                            victim_item.DecreaseHealth("", "", add_damage);
                        }
                    }
                }
            }
            Synch(victim);
        }
        OnSteppedOn(victim);
    }
References Math::Clamp(), GetGame(), CGame::GetInventoryItemSize(), m_DamageOthers, m_DamagePlayers, m_Timer, MAX, TrapBase::OnSteppedOn(), RefreshState(), and Synch().
Referenced by OnItemLocationChanged(), and OnRPC().
StartActivate()
void StartActivate (PlayerBase player)
Definition at line 487 of file trapbase.c.
    {
        if ( GetGame().IsServer() )
        {
            m_Timer = new Timer( CALL_CATEGORY_SYSTEM );
            HideSelection("safety_pin");
            if ( m_InitWaitTime > 0 )
            {
                m_IsInProgress = true;
                m_Timer.Run( m_InitWaitTime, this, "SetActive" );
                Synch(null);
            }
            else
            {
                SetActive();
            }
        }
    }
References CALL_CATEGORY_SYSTEM, GetGame(), m_InitWaitTime, m_IsInProgress, m_Timer, SetActive(), and Synch().
Referenced by TrapBase::OnPlacementComplete(), OnPlacementComplete(), OnStoreLoad(), ItemBase::OnStoreLoad(), and OnVariablesSynchronized().
StartDeactivate()
void StartDeactivate (PlayerBase player)
Definition at line 193 of file trap_tripwire.c.
    {
        super.StartDeactivate(player);
        DeleteTrigger();
        SetState(FOLDED);
    }
References DeleteTrigger(), FOLDED, and SetState().
Referenced by EEKilled(), and OnItemLocationChanged().
StopDeployLoopSound()
void StopDeployLoopSound ()
Definition at line 666 of file trapbase.c.
    {
        #ifndef SERVER
        if (m_DeployLoopSound)
        {
            m_DeployLoopSound.SetSoundFadeOut(0.5);
            m_DeployLoopSound.SoundStop();
        }
        #endif
    }
References m_DeployLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
Referenced by OnRPC(), ItemBase::OnVariablesSynchronized(), and OnVariablesSynchronized().
Synch()
protected void Synch (EntityAI victim)
keeping "step" here for consistency only
Definition at line 306 of file trapbase.c.
    {
        if (GetGame().IsServer())
        {
            SetSynchDirty();
            if (victim && !victim.GetAllowDamage())
            {
                return;
            }
            Param1<EntityAI> p = new Param1<EntityAI>(victim);
            GetGame().RPCSingleParam(this, ERPCs.RPC_TRAP_VICTIM, p, true);
        }
    }
References GetGame(), and CGame::RPCSingleParam().
Referenced by TrapBase::OnServerSteppedOn(), OnServerSteppedOn(), RemoveFromObject(), SetActive(), SetInactive(), SnapOnObject(), and StartActivate().
TrapBase()
void TrapBase ()
timer calling OnUpdate in configured interval
Definition at line 49 of file trapbase.c.
    {
        m_IsInProgress = false;
        m_NeedActivation = true;
        m_InitWaitTime = 5;             //After this time after deployment, the trap is activated
        m_DefectRate = 15;              //Added damage after trap activation
        m_DamagePlayers = 25;           //How much damage player gets when caught
        m_DamageOthers = 100;           //How much damage others gets when caught
        m_AddActivationDefect = false;
        m_AddDeactivationDefect = false;
        m_WasActivatedOrDeactivated = false;
        m_AnimationPhaseGrounded = "";
        m_AnimationPhaseSet = "";
        m_AnimationPhaseTriggered = "";
        m_InfoSetup =               "#STR_TrapBase0";
        m_InfoDeactivated =         "#STR_TrapBase1";
        m_InfoDamageManipulation =  "#STR_TrapBase2";
        m_InfoDamage =              "#STR_TrapBase3";
        m_InfoActivationTime =      "#STR_TrapBase4" + m_InitWaitTime.ToString() + "#STR_TrapBase5";
        m_UpdateTimer               = new ref Timer();
        RegisterNetSyncVariableBool("m_IsActive");
        RegisterNetSyncVariableBool("m_IsInProgress");
        RegisterNetSyncVariableBool("m_IsSoundSynchRemote");
        RegisterNetSyncVariableBool("m_IsDeploySound");
    }
References m_AddActivationDefect, m_AddDeactivationDefect, m_AnimationPhaseGrounded, m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DamageOthers, m_DamagePlayers, m_DefectRate, m_InfoActivationTime, m_InfoDamage, m_InfoDamageManipulation, m_InfoDeactivated, m_InfoSetup, m_InitWaitTime, m_IsInProgress, m_NeedActivation, m_UpdateTimer, and m_WasActivatedOrDeactivated.
~TrapBase()
void ~TrapBase ()
Definition at line 81 of file trapbase.c.
    {
        SEffectManager.DestroyEffect( m_DeployLoopSound );
    }
References SEffectManager::DestroyEffect(), and m_DeployLoopSound.
Variable Documentation
DAMAGE_TRIGGER_MINE
protected const int DAMAGE_TRIGGER_MINE = 75
Definition at line 14 of file trapbase.c.
Referenced by OnSteppedOn().
m_AddActivationDefect
bool m_AddActivationDefect
Definition at line 23 of file trapbase.c.
Referenced by SetActive(), and TrapBase().
m_AddDeactivationDefect
bool m_AddDeactivationDefect
Definition at line 24 of file trapbase.c.
Referenced by LandMineTrap(), SetInactive(), and TrapBase().
m_AnimationPhaseGrounded
string m_AnimationPhaseGrounded
Definition at line 32 of file trapbase.c.
Referenced by TrapBase::BearTrap(), FoldTripWire(), RefreshState(), TrapBase(), and TripwireTrap().
m_AnimationPhaseSet
string m_AnimationPhaseSet
Definition at line 33 of file trapbase.c.
Referenced by TrapBase::BearTrap(), FoldTripWire(), RefreshState(), ItemBase::SetActive(), ItemBase::SetDeployed(), ItemBase::SetUsed(), TrapSpawnBase::Trap_FishNet(), TrapSpawnBase::Trap_RabbitSnare(), TrapSpawnBase::Trap_SmallFish(), TrapBase(), ItemBase::TrapSpawnBase(), and TripwireTrap().
m_AnimationPhaseTriggered
string m_AnimationPhaseTriggered
Definition at line 34 of file trapbase.c.
Referenced by TrapBase::BearTrap(), FoldTripWire(), RefreshState(), ItemBase::SetActive(), ItemBase::SetDeployed(), ItemBase::SetUsed(), TrapSpawnBase::Trap_FishNet(), TrapSpawnBase::Trap_RabbitSnare(), TrapSpawnBase::Trap_SmallFish(), TrapBase(), ItemBase::TrapSpawnBase(), and TripwireTrap().
m_ClothingDmg
protected ref array<int> m_ClothingDmg
Definition at line 46 of file trapbase.c.
Referenced by DamageClothing(), and LandMineTrap().
m_DamageOthers
float m_DamageOthers
Definition at line 21 of file trapbase.c.
Referenced by TrapBase::BearTrap(), SnapOnObject(), and TrapBase().
m_DamagePlayers
float m_DamagePlayers
Definition at line 20 of file trapbase.c.
Referenced by TrapBase::BearTrap(), LandMineTrap(), SnapOnObject(), TrapBase(), and TripwireTrap().
m_DefectRate
float m_DefectRate
Definition at line 19 of file trapbase.c.
Referenced by AddDefect(), ItemBase::AddDefect(), TrapBase::BearTrap(), LandMineTrap(), TrapSpawnBase::Trap_FishNet(), TrapSpawnBase::Trap_RabbitSnare(), TrapSpawnBase::Trap_SmallFish(), TrapBase(), ItemBase::TrapSpawnBase(), and TripwireTrap().
m_DeployLoopSound
protected ref EffectSound m_DeployLoopSound
Definition at line 47 of file trapbase.c.
Referenced by ItemBase::OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), OnVariablesSynchronized(), ItemBase::PlayDeployLoopSound(), Inventory_Base::PlayDeployLoopSound(), PlayDeployLoopSound(), ItemBase::StopDeployLoopSound(), Inventory_Base::StopDeployLoopSound(), StopDeployLoopSound(), ItemBase::~BarbedWire(), Inventory_Base::~HescoBox(), ItemBase::~KitBase(), ItemBase::~Spotlight(), ItemBase::~TentBase(), ~TrapBase(), and ItemBase::~TrapSpawnBase().
m_Disarmed
protected bool m_Disarmed = false
Definition at line 28 of file trapbase.c.
Referenced by GetDisarmed(), and SetDisarmed().
m_InfoActivationTime
string m_InfoActivationTime
Definition at line 40 of file trapbase.c.
Referenced by LandMineTrap(), TrapBase(), and TripwireTrap().
m_InfoDamage
string m_InfoDamage
Definition at line 39 of file trapbase.c.
Referenced by TrapBase().
m_InfoDamageManipulation
string m_InfoDamageManipulation
Definition at line 38 of file trapbase.c.
Referenced by TrapBase().
m_InfoDeactivated
string m_InfoDeactivated
Definition at line 37 of file trapbase.c.
Referenced by TrapBase().
m_InfoSetup
string m_InfoSetup
Definition at line 36 of file trapbase.c.
Referenced by TrapBase().
m_InitWaitTime
int m_InitWaitTime
Definition at line 17 of file trapbase.c.
Referenced by TrapBase::BearTrap(), LandMineTrap(), ItemBase::SetActive(), StartActivate(), TrapSpawnBase::Trap_FishNet(), TrapSpawnBase::Trap_RabbitSnare(), TrapSpawnBase::Trap_SmallFish(), TrapBase(), ItemBase::TrapSpawnBase(), and TripwireTrap().
m_IsActive
protected bool m_IsActive
Definition at line 25 of file trapbase.c.
m_IsInProgress
protected bool m_IsInProgress
Definition at line 26 of file trapbase.c.
Referenced by IsActivable(), IsActive(), IsInactive(), IsTakeable(), OnStoreSave(), ItemBase::OnStoreSave(), OnVariablesSynchronized(), SetActive(), StartActivate(), and TrapBase().
m_NeedActivation
bool m_NeedActivation
Definition at line 18 of file trapbase.c.
Referenced by IsActivable(), SetupTrapPlayer(), TrapBase(), and TripwireTrap().
m_Timer
protected ref Timer m_Timer
Definition at line 42 of file trapbase.c.
Referenced by UniversalTemperatureSourceDebug::ChangeSettings(), Clothing::CheckParent(), Clothing::Headtorch_ColorBase(), UniversalTemperatureSourceDebug::Init(), Hud::Init(), UniversalTemperatureSourceDebug::IsActive(), PointLightBase::OnFrameLightSource(), PluginBase::PluginAdminLog(), ItemBase::SetActive(), UniversalTemperatureSourceDebug::SetActive(), ItemBase::SetInactive(), SetInactive(), ItemBase::SetUsed(), SnapOnObject(), ItemBase::SpawnCatch(), StartActivate(), PoweredOptic_Base::StartPeriodicMeasurement(), ItemBase::StartPeriodicMeasurement(), PoweredOptic_Base::StopPeriodicMeasurement(), ItemBase::StopPeriodicMeasurement(), and UniversalTemperatureSourceDebug::UniversalTemperatureSource().
m_TrapTrigger
protected TrapTrigger m_TrapTrigger
Definition at line 44 of file trapbase.c.
Referenced by CreateTrigger(), TrapBase::CreateTrigger(), DeleteTrigger(), EEDelete(), EEItemLocationChanged(), EEKilled(), and TrapBase::OnPlacementComplete().
m_UpdateTimer
protected ref Timer m_UpdateTimer
Definition at line 43 of file trapbase.c.
m_WasActivatedOrDeactivated
bool m_WasActivatedOrDeactivated
DEPRECATED Used for explosive traps to prevent detonation after destroying through disarm action.
Definition at line 30 of file trapbase.c.
Referenced by RefreshState(), SetActive(), SetInactive(), and TrapBase().
SPAWN_FLAGS
enum SoundTypeTrap SPAWN_FLAGS = ECE_LOCAL
Referenced by CreateTrigger().
UPDATE_TIMER_INTERVAL
protected const float UPDATE_TIMER_INTERVAL = 0.05
Definition at line 15 of file trapbase.c.
Referenced by TrapBase::OnSteppedOn(), and OnSteppedOn().