DayzKode: P:/scripts/4_world/DayZ/entities/itembase/trapbase/trap_landmine.c File Reference
trap_landmine.c File Reference
Enumerations
enum SoundTypeMine { DISARMING = 0 }
Functions
override bool CanBeDisarmed ()
override bool CanExplodeInFire ()
void DeleteThis ()
override void EEKilled (Object killer)
override void Explode (int damageType, string ammoType="")
override string GetLoopDeploySoundset ()
override bool IsDeployable ()
void LandMineTrap ()
override void OnActivate ()
HumanCommandScript fully scriptable command.
override void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
protected void OnServerSteppedOn (Object obj, string damageZone)
override void OnSteppedOn (EntityAI victim)
override void OnSteppedOut (EntityAI victim)
override void OnUpdate (EntityAI victim)
void PlayDisarmingLoopSound ()
void PlaySoundActivate ()
override void SetActions ()
override void StartActivate (PlayerBase player)
void StopDisarmingLoopSound ()
void ~LandMineTrap ()
Variables
private const int BLEED_SOURCE_PROB = 50
private const int BROKEN_LEG_PROB = 90
protected ref Timer m_DeleteTimer
protected ref EffectSound m_DisarmingLoopSound
enum SoundTypeMine m_TimerLoopSound
private const int MAX_BLEED_SOURCE = 1
Enumeration Type Documentation
SoundTypeMine
enum SoundTypeMine
Enumerator
DISARMING
Definition at line 1 of file trap_landmine.c.
{
    DISARMING = 0
}
Function Documentation
CanBeDisarmed()
override bool CanBeDisarmed ()
Definition at line 236 of file trap_landmine.c.
    {
        return true;
    }
CanExplodeInFire()
override bool CanExplodeInFire ()
Definition at line 78 of file trap_landmine.c.
    {
        return true;
    }
DeleteThis()
void DeleteThis ()
Definition at line 188 of file trap_landmine.c.
    {
        m_DeleteTimer = new Timer(CALL_CATEGORY_SYSTEM);
        m_DeleteTimer.Run(1, this, "DeleteSafe");
    }
References CALL_CATEGORY_SYSTEM, and m_DeleteTimer.
Referenced by Explode(), OnActivatedByItem(), and OnSteppedOn().
EEKilled()
override void EEKilled (Object killer)
Definition at line 199 of file trap_landmine.c.
    {
        super.EEKilled(killer);
        Explode(DamageType.EXPLOSION);
    }
References Explode().
Explode()
override void Explode (int damageType, string ammoType = "")
Definition at line 215 of file trap_landmine.c.
    {
        if (ammoType == "")
        {
            ammoType = ConfigGetString("ammoType");
        }
        if (ammoType == "")
        {
            ammoType = "Dummy_Heavy";
        }
        if ( GetGame().IsServer() )
        {
            SynchExplosion();
            vector offset = Vector(0, 0.1, 0); //Vertical offset applied to landmine explosion (in meters)
            DamageSystem.ExplosionDamage(this, NULL, ammoType, GetPosition() + offset, damageType); //Offset explosion on Y axis
            DeleteThis();
        }
    }
References ConfigGetString(), DeleteThis(), GetGame(), GetPosition, SynchExplosion(), and Vector().
GetLoopDeploySoundset()
override string GetLoopDeploySoundset ()
Definition at line 302 of file trap_landmine.c.
    {
        return "landmine_deploy_SoundSet";
    }
IsDeployable()
override bool IsDeployable ()
Definition at line 297 of file trap_landmine.c.
    {
        return true;
    }
LandMineTrap()
void LandMineTrap ()
Definition at line 16 of file trap_landmine.c.
    {
        m_DefectRate            = 15;
        m_DamagePlayers         = 0;            //How much damage player gets when caught
        m_InitWaitTime          = 10;           //After this time after deployment, the trap is activated
        m_InfoActivationTime    = string.Format("#STR_LandMineTrap0%1#STR_LandMineTrap1", m_InitWaitTime.ToString());
        m_AddDeactivationDefect = true;
        //Order is important and must match clothing array in DamageClothing method
        m_ClothingDmg = new array<int>;
        m_ClothingDmg.Insert(60);   //Trousers
        m_ClothingDmg.Insert(100);  //BackPack
        m_ClothingDmg.Insert(40);   //Vest
        m_ClothingDmg.Insert(10);   //HeadGear
        m_ClothingDmg.Insert(10);   //Mask
        m_ClothingDmg.Insert(40);   //Body
        m_ClothingDmg.Insert(50);   //Feet
        m_ClothingDmg.Insert(5);    //Gloves
    }
References string::Format(), m_AddDeactivationDefect, m_ClothingDmg, m_DamagePlayers, m_DefectRate, m_InfoActivationTime, and m_InitWaitTime.
Referenced by ActionCondition(), OnAnimationEvent(), OnEndAnimationLoop(), OnFinishProgressServer(), and OnStartAnimationLoop().
OnActivate()
override void OnActivate ()
HumanCommandScript fully scriptable command.
Warning
NON-MANAGED, will be managed by C++ once it is sent to the CommandHandler through Human.StartCommand_Script
Note
So ideally, it is best to set up the HumanCommandScript, not create any instances and start it through Human.StartCommand_ScriptInst In case an instance needs to be created, it needs manual deletion if not sent to the CommandHandler But deleting it while it is in the CommandHandler will cause crashes constructor must have 1st parameter to be Human virtual to be overridden called when command starts
Definition at line 61 of file trap_landmine.c.
    {
        if (!GetGame().IsDedicatedServer())
        {
            if (m_TimerLoopSound)
            {
                m_TimerLoopSound.SetAutodestroy(true);
                m_TimerLoopSound.SoundStop();
            }
            if (GetGame().GetPlayer())
            {
                PlaySoundActivate();
            }
        }
    }
References GetGame(), GetPlayer(), m_TimerLoopSound, and PlaySoundActivate().
OnActivatedByItem()
override void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
Definition at line 55 of file trap_landmine.c.
    {
        SetHealth("", "", 0.0);
        DeleteThis();
    }
References DeleteThis(), and SetHealth().
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
Definition at line 194 of file trap_landmine.c.
    {
        super.OnItemLocationChanged(old_owner, new_owner);
    }
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0")
Definition at line 286 of file trap_landmine.c.
    {
        super.OnPlacementComplete(player, position, orientation);
        if (GetGame().IsServer())
        {
            PlayerBase player_PB = PlayerBase.Cast(player);
            StartActivate(player_PB);
        }
    }
References GetGame(), and StartActivate().
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
Parameters
rpc_type user defined identification of RPC
ctx read context for params
Definition at line 241 of file trap_landmine.c.
    {
        super.OnRPC(sender, rpc_type, ctx);
        Param1<bool> p = new Param1<bool>(false);
        if (!ctx.Read(p))
        {
            return;
        }
        bool play = p.param1;
        switch (rpc_type)
        {
        case SoundTypeMine.DISARMING:
            if (play)
            {
                PlayDisarmingLoopSound();
            }
            else
            {
                StopDisarmingLoopSound();
            }
            break;
        }
    }
References PlayDisarmingLoopSound(), Serializer::Read(), and StopDisarmingLoopSound().
OnServerSteppedOn()
protected void OnServerSteppedOn (Object obj, string damageZone)
Definition at line 171 of file trap_landmine.c.
    {
        if (obj.IsInherited(CarWheel))
        {
            obj.ProcessDirectDamage(DT_CLOSE_COMBAT, this, "", "LandMineExplosion_CarWheel", "0 0 0", 1);
            Explode(DamageType.EXPLOSION);
            if (m_UpdateTimer.IsRunning())
            {
                m_UpdateTimer.Stop();
            }
        }
        SetInactive(false);
        Synch(EntityAI.Cast(obj));
    }
References Explode(), m_UpdateTimer, SetInactive(), and Synch().
OnSteppedOn()
override void OnSteppedOn (EntityAI victim)
CarScript specific reaction on LandMineTrap
Definition at line 95 of file trap_landmine.c.
    {
        int i;
        if (GetGame().IsServer() && victim)
        {
            if (!victim.GetAllowDamage())
            {
                return;
            }
            if (victim.IsInherited(CarScript))
            {
                Param1<EntityAI> params = new Param1<EntityAI>(victim);
                m_UpdateTimer.Run(UPDATE_TIMER_INTERVAL, this, "OnUpdate", params, true);
                return;
            }
            else
            {
                //Check if we have a player
                PlayerBase victim_PB = PlayerBase.Cast(victim);
                if (victim_PB && victim_PB.IsAlive())
                {
                    int randNum; //value used for probability evaluation
                    randNum = Math.RandomInt(0, 100);
                    if (randNum <= BROKEN_LEG_PROB)
                    {
                        float damage = victim_PB.GetMaxHealth("RightLeg", ""); //deal 100% damage to break legs
                        victim_PB.DamageAllLegs( damage );
                    }
                    randNum = Math.RandomInt(0, 100);
                    if (randNum < BLEED_SOURCE_PROB)
                    {
                        for (i = 0; i < MAX_BLEED_SOURCE; i++)
{
                            //We add two bleeding sources max to lower half
                            randNum = Math.RandomIntInclusive(0, PlayerBase.m_BleedingSourcesLow.Count() - 1);
                            victim_PB.m_BleedingManagerServer.AttemptAddBleedingSourceBySelection(PlayerBase.m_BleedingSourcesLow[randNum]);
                        }
                    }
                    DamageClothing(victim_PB);
                }
                else
                {
                    ItemBase victim_IB = ItemBase.Cast(victim);
                    if (victim_IB)
                    {
                        MiscGameplayFunctions.DealAbsoluteDmg(victim_IB, DAMAGE_TRIGGER_MINE);
                    }
                }
                Explode(DamageType.EXPLOSION);
            }
            DeleteThis();
        }
        super.OnSteppedOn(victim);
    }
References BLEED_SOURCE_PROB, BROKEN_LEG_PROB, DAMAGE_TRIGGER_MINE, DamageClothing(), DeleteThis(), Explode(), GetGame(), m_UpdateTimer, MAX_BLEED_SOURCE, Math::RandomInt(), Math::RandomIntInclusive(), and UPDATE_TIMER_INTERVAL.
OnSteppedOut()
override void OnSteppedOut (EntityAI victim)
Definition at line 160 of file trap_landmine.c.
    {
        if (victim.IsInherited(CarScript))
        {
            if (m_UpdateTimer && m_UpdateTimer.IsRunning())
            {
                m_UpdateTimer.Stop();
            }
        }
    }
References m_UpdateTimer.
OnUpdate()
override void OnUpdate (EntityAI victim)
Definition at line 83 of file trap_landmine.c.
    {
        if (victim && victim.IsInherited(CarScript))
        {
            EntityAI wheel = GetClosestCarWheel(victim);
            if (wheel)
            {
                OnServerSteppedOn(wheel, "");
            }
        }
    }
References GetClosestCarWheel(), and TrapBase::OnServerSteppedOn().
PlayDisarmingLoopSound()
void PlayDisarmingLoopSound ()
Definition at line 269 of file trap_landmine.c.
    {
        if (!m_DisarmingLoopSound || !m_DisarmingLoopSound.IsSoundPlaying())
        {
            m_DisarmingLoopSound = SEffectManager.PlaySound("landmine_deploy_SoundSet", GetPosition());
        }
    }
References GetPosition, EffectSound::IsSoundPlaying(), m_DisarmingLoopSound, and SEffectManager::PlaySound().
Referenced by OnRPC().
PlaySoundActivate()
void PlaySoundActivate ()
Definition at line 206 of file trap_landmine.c.
    {
        if (!GetGame().IsDedicatedServer())
        {
            EffectSound sound = SEffectManager.PlaySound("landmineActivate_SoundSet", GetPosition(), 0, 0, false);
            sound.SetAutodestroy(true);
        }
    }
References GetGame(), GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnActivate().
SetActions()
override void SetActions ()
Definition at line 307 of file trap_landmine.c.
    {
        super.SetActions();
        AddAction(ActionAttach);
        AddAction(ActionDetach);
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionActivateTrap);
        AddAction(ActionDeployObject);
    }
References ActionAttach(), ActionDeployObject(), ActionDetach(), and AddAction().
StartActivate()
override void StartActivate (PlayerBase player)
Definition at line 43 of file trap_landmine.c.
    {
        super.StartActivate(player);
        if (!GetGame().IsDedicatedServer())
        {
            EffectSound sound = SEffectManager.PlaySound("landmine_safetyPin_SoundSet", GetPosition(), 0, 0, false);
            sound.SetAutodestroy( true );
            m_TimerLoopSound = SEffectManager.PlaySound("landmine_timer2_SoundSet", GetPosition(), 0, 0, true);
        }
    }
References GetGame(), GetPosition, m_TimerLoopSound, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
StopDisarmingLoopSound()
void StopDisarmingLoopSound ()
Definition at line 277 of file trap_landmine.c.
    {
        m_DisarmingLoopSound.SoundStop();
    }
References m_DisarmingLoopSound, and EffectSound::SoundStop().
Referenced by OnRPC().
~LandMineTrap()
void ~LandMineTrap ()
Definition at line 37 of file trap_landmine.c.
    {
        SEffectManager.DestroyEffect(m_TimerLoopSound);
        SEffectManager.DestroyEffect(m_DisarmingLoopSound);
    }
References SEffectManager::DestroyEffect(), m_DisarmingLoopSound, and m_TimerLoopSound.
Variable Documentation
BLEED_SOURCE_PROB
private const int BLEED_SOURCE_PROB = 50
Definition at line 13 of file trap_landmine.c.
Referenced by OnSteppedOn().
BROKEN_LEG_PROB
private const int BROKEN_LEG_PROB = 90
Definition at line 12 of file trap_landmine.c.
Referenced by OnSteppedOn().
m_DeleteTimer
protected ref Timer m_DeleteTimer
Definition at line 10 of file trap_landmine.c.
m_DisarmingLoopSound
protected ref EffectSound m_DisarmingLoopSound
Definition at line 9 of file trap_landmine.c.
Referenced by PlayDisarmingLoopSound(), StopDisarmingLoopSound(), and ~LandMineTrap().
m_TimerLoopSound
enum SoundTypeMine m_TimerLoopSound
Referenced by OnActivate(), StartActivate(), and ~LandMineTrap().
MAX_BLEED_SOURCE
private const int MAX_BLEED_SOURCE = 1
Definition at line 14 of file trap_landmine.c.
Referenced by OnSteppedOn().