DayzKode: P:/scripts/3_game/DayZ/tools/uimanager.c File Reference
uimanager.c File Reference
Classes
class UIManager
Functions
string GetRandomLoadingBackground ()
Returns random loading background texture path.
Function Documentation
GetRandomLoadingBackground()
string GetRandomLoadingBackground ()
Returns random loading background texture path.
Definition at line 253 of file uimanager.c.
{
    const string images[] = {"{655A1BF79F5B291}Gui/textures/loading_screens/loading_screen_1_co.edds", "{84BE5F7442BD4B}Gui/textures/loading_screens/loading_screen_2_co.edds"};
    Math.Randomize(-1);
    int index = Math.RandomInt(0, 100) % 2;
    return images[index];
}
References Math::RandomInt(), and Math::Randomize().
Referenced by UIScriptedMenu::Init().