DayzKode: P:/scripts/4_world/DayZ/classes/undergroundhandlerclient.c File Reference
undergroundhandlerclient.c File Reference
Enumerations
enum EUndergroundPresence { NONE , OUTER , TRANSITIONING , FULL }
Functions
private void ApplyEyeAcco ()
private bool CalculateEyeAcco (float timeSlice)
private void CalculateEyeAccoTarget ()
private void EnableLights (bool enable)
private PPERUndergroundAcco GetRequester ()
void OnTriggerEnter (UndergroundTrigger trigger)
private void OnTriggerInsiderUpdate ()
void OnTriggerLeave (UndergroundTrigger trigger)
private void OnUndergroundPresenceUpdate (EUndergroundPresence newPresence, EUndergroundPresence oldPresence)
void OnUpdateTimerEnd ()
void OnUpdateTimerIn ()
void OnUpdateTimerOut ()
private void ProcessEyeAcco (float timeSlice)
private void ProcessLighting (float timeSlice)
private void ProcessSound (float timeSlice)
private void SetUndergroundPresence (UndergroundTrigger trigger)
void Tick (float timeSlice)
void UndergroundHandlerClient (PlayerBase player)
void ~UndergroundHandlerClient ()
Variables
const float ACCO_MODIFIER = 1
const float DEFAULT_INTERPOLATION_SPEED = 7
const float DISTANCE_CUTOFF = 5
enum EUndergroundPresence LIGHT_BLEND_SPEED_IN = 5
const float LIGHT_BLEND_SPEED_OUT = 1.75
private float m_AccoInterpolationSpeed
private EffectSound m_AmbientSound
private ref AnimationTimer m_AnimTimerLightBlend
private float m_EyeAcco = 1
private float m_EyeAccoTarget = 1
private ref set< UndergroundTrigger > m_InsideTriggers = new set<UndergroundTrigger>()
private float m_LightingLerp
private float m_LightingLerpTarget
private PPERequester_CameraNV m_NVRequester
private PlayerBase m_Player
private PPERUndergroundAcco m_Requester
private UndergroundTrigger m_TransitionalTrigger
const float MAX_RATIO = 0.9
const float RATIO_CUTOFF = 0
const string UNDERGROUND_LIGHTING = "dz\\data\\lighting\\lighting_underground.txt"
Enumeration Type Documentation
EUndergroundPresence
enum EUndergroundPresence
Enumerator
NONE
OUTER
TRANSITIONING
FULL
Definition at line 1 of file undergroundhandlerclient.c.
{
    NONE,//player is not interacting with underground at any level
    OUTER,//player is on the outskirts of the underdound, some effects are already in effect, while others might not be
    TRANSITIONING,//player has entered underground and is in the process of screen darkening transition
    FULL//the player is now fully entered underground
}
Function Documentation
ApplyEyeAcco()
private void ApplyEyeAcco ()
Definition at line 233 of file undergroundhandlerclient.c.
    {
        #ifdef DEVELOPER
        if (!DiagMenu.GetBool(DiagMenuIDs.DM_UNDERGROUND_DISABLE_DARKENING) )
        {
            GetRequester().SetEyeAccommodation(m_EyeAcco);
        }
        else
        {
            GetRequester().SetEyeAccommodation(1);
        }
        #else
        GetRequester().SetEyeAccommodation(m_EyeAcco);
        #endif
        float undergrounNVExposureCoef = m_EyeAcco;
        if (m_LightingLerp >= 1.0 || GetDayZGame().GetWorld().IsNight())
        {
            undergrounNVExposureCoef = 1.0;
        }
        m_NVRequester.SetUndergroundExposureCoef(undergrounNVExposureCoef);
    }
References DiagMenu::GetBool(), GetDayZGame(), GetRequester(), m_EyeAcco, m_LightingLerp, and m_NVRequester.
Referenced by ProcessEyeAcco().
CalculateEyeAcco()
private bool CalculateEyeAcco (float timeSlice)
Definition at line 256 of file undergroundhandlerclient.c.
    {
        if (m_TransitionalTrigger || !m_Player.m_UndergroundPresence || (m_EyeAccoTarget == 1))
        {
            float accoDiff = m_EyeAccoTarget - m_EyeAcco;
            float increase = accoDiff * m_AccoInterpolationSpeed * timeSlice;
            m_EyeAcco += increase;
            if (Math.AbsFloat(accoDiff) < 0.01)
            {
                m_EyeAcco = m_EyeAccoTarget;
                return true;
            }
        }
        else
        {
            m_EyeAcco = m_EyeAccoTarget;
        }
        return false;
    }
References Math::AbsFloat(), m_AccoInterpolationSpeed, m_EyeAcco, m_EyeAccoTarget, m_Player, and m_TransitionalTrigger.
Referenced by ProcessEyeAcco().
CalculateEyeAccoTarget()
private void CalculateEyeAccoTarget ()
Definition at line 81 of file undergroundhandlerclient.c.
    {
        if (m_TransitionalTrigger && m_TransitionalTrigger.m_Data.Breadcrumbs.Count() >= 2)
        {
            float closestDist = float.MAX;
            float acco;
            array<float> distances = new array<float>();
            array<float> distancesInverted = new array<float>();
            int excludeMask = 0;
            foreach (int indx, auto crumb:m_TransitionalTrigger.m_Data.Breadcrumbs)
            {
                if (indx > 32)//error handling for exceeding this limit is handled elsewhere
                    break;
                float dist = vector.Distance(m_Player.GetPosition(), crumb.GetPosition());
                float crumbRadius = m_TransitionalTrigger.m_Data.Breadcrumbs[indx].Radius;
                float maxRadiusAllowed = DISTANCE_CUTOFF;
                if (crumbRadius != -1)
                {
                    maxRadiusAllowed = crumbRadius;
                }
                if (dist > maxRadiusAllowed)
                {
                    excludeMask = (excludeMask | (1 << indx));
                }
                else if (m_TransitionalTrigger.m_Data.Breadcrumbs[indx].UseRaycast)
                {
                    int idx = m_Player.GetBoneIndexByName("Head");
                    vector rayStart = m_Player.GetBonePositionWS(idx);
                    vector rayEnd = crumb.GetPosition();
                    vector hitPos, hitNormal;
                    float hitFraction;
                    Object hitObj;
                    if (DayZPhysics.RayCastBullet(rayStart, rayEnd,PhxInteractionLayers.TERRAIN | PhxInteractionLayers.ROADWAY| PhxInteractionLayers.BUILDING, null, hitObj, hitPos, hitNormal, hitFraction))
                    {
                        excludeMask = (excludeMask | (1 << indx));
                    }
                }
                distances.Insert(dist);
                    #ifdef DEVELOPER
                if ( DiagMenu.GetBool(DiagMenuIDs.DM_UNDERGROUND_SHOW_BREADCRUMB) )
                {
                    Debug.DrawSphere(crumb.GetPosition(),0.1, COLOR_RED, ShapeFlags.ONCE);
                }
                #endif
            }
            float baseDst = distances[0];
            float sum = 0;
            //Print(excludeMask);
            foreach (float dst:distances)
            {
                if (dst == 0)
                    dst = 0.1;
                float dstInv = (baseDst / dst) * baseDst;
                sum += dstInv;
                distancesInverted.Insert(dstInv);
            }
            float sumCheck = 0;
            float eyeAcco = 0;
            foreach (int i, float dstInvert:distancesInverted)
            {
                /*
                //Print(m_TransitionalTrigger.m_Data.Breadcrumbs[i].EyeAccommodation);
                //Print(m_TransitionalTrigger.m_Data.Breadcrumbs.Count());
                */
                if ((1 << i) & excludeMask)
                    continue;
                float ratio = dstInvert / sum;
                if (ratio > MAX_RATIO)
                    ratio = MAX_RATIO;
                if (ratio > RATIO_CUTOFF)
                {
                        #ifdef DEVELOPER
                    if (DiagMenu.GetBool(DiagMenuIDs.DM_UNDERGROUND_SHOW_BREADCRUMB) )
                    {
                        float intensity = (1-ratio) * 255;
                        Debug.DrawLine(GetGame().GetPlayer().GetPosition() + "0 1 0", m_TransitionalTrigger.m_Data.Breadcrumbs[i].GetPosition(),ARGB(0,255,intensity,intensity),ShapeFlags.ONCE);
                    }
                    #endif
                    eyeAcco += ratio * m_TransitionalTrigger.m_Data.Breadcrumbs[i].EyeAccommodation;
                }
            }
            m_EyeAccoTarget = eyeAcco * ACCO_MODIFIER;
        }
    }
References ACCO_MODIFIER, ARGB(), COLOR_RED, vector::Distance(), DISTANCE_CUTOFF, Debug::DrawLine(), Debug::DrawSphere(), DiagMenu::GetBool(), GetGame(), CGame::GetPlayer(), m_EyeAccoTarget, m_Player, m_TransitionalTrigger, MAX_RATIO, RATIO_CUTOFF, and DayZPhysics::RayCastBullet().
Referenced by ProcessEyeAcco().
EnableLights()
private void EnableLights (bool enable)
Definition at line 342 of file undergroundhandlerclient.c.
    {
        foreach (ScriptedLightBase light:ScriptedLightBase.m_NightTimeOnlyLights)
        {
            light.SetVisibleDuringDaylight(enable);
        }
    }
Referenced by OnUndergroundPresenceUpdate().
GetRequester()
private PPERUndergroundAcco GetRequester ()
Definition at line 54 of file undergroundhandlerclient.c.
    {
        if (!m_Requester)
        {
            m_Requester = PPERUndergroundAcco.Cast(PPERequesterBank.GetRequester( PPERequesterBank.REQ_UNDERGROUND));
            m_Requester.Start();
        }
        return m_Requester;
    }
References m_Requester.
Referenced by ApplyEyeAcco(), ProcessEyeAcco(), and Managed::RegisterRequester().
OnTriggerEnter()
void OnTriggerEnter (UndergroundTrigger trigger)
Definition at line 64 of file undergroundhandlerclient.c.
    {
        m_InsideTriggers.Insert(trigger);
        OnTriggerInsiderUpdate();
    }
References m_InsideTriggers, and OnTriggerInsiderUpdate().
OnTriggerInsiderUpdate()
private void OnTriggerInsiderUpdate ()
Definition at line 279 of file undergroundhandlerclient.c.
    {
        EUndergroundTriggerType bestType = EUndergroundTriggerType.UNDEFINED;
        m_TransitionalTrigger = null;
        UndergroundTrigger bestTrigger;
        m_EyeAccoTarget = 1;
        m_AccoInterpolationSpeed = DEFAULT_INTERPOLATION_SPEED;
        foreach (auto t:m_InsideTriggers)
        {
            if (t.m_Type > bestType)
            {
                bestTrigger = t;
                bestType = t.m_Type;
            }
        }
        //Print(m_InsideTriggers.Count());
        //Print(bestType);
        if (bestTrigger)
        {
            if (bestTrigger.m_Type == EUndergroundTriggerType.TRANSITIONING)
            {
                m_TransitionalTrigger = bestTrigger;
            }
            m_EyeAccoTarget = bestTrigger.m_Accommodation;
            if (bestTrigger.m_InterpolationSpeed != -1 && bestTrigger.m_InterpolationSpeed != 0)
                m_AccoInterpolationSpeed = bestTrigger.m_InterpolationSpeed;
        }
        SetUndergroundPresence(bestTrigger);
    }
References DEFAULT_INTERPOLATION_SPEED, m_AccoInterpolationSpeed, m_EyeAccoTarget, m_InsideTriggers, m_TransitionalTrigger, and SetUndergroundPresence().
Referenced by OnTriggerEnter(), and OnTriggerLeave().
OnTriggerLeave()
void OnTriggerLeave (UndergroundTrigger trigger)
Definition at line 71 of file undergroundhandlerclient.c.
    {
        int index = m_InsideTriggers.Find(trigger);
        if (index != -1)
        {
            m_InsideTriggers.Remove(index);
        }
        OnTriggerInsiderUpdate();
    }
References m_InsideTriggers, and OnTriggerInsiderUpdate().
OnUndergroundPresenceUpdate()
private void OnUndergroundPresenceUpdate (EUndergroundPresence newPresence, EUndergroundPresence oldPresence)
Definition at line 372 of file undergroundhandlerclient.c.
    {
        //Print("-----> On Undeground Presence update " + EnumTools.EnumToString(EUndergroundPresence, newPresence) + " " + EnumTools.EnumToString(EUndergroundPresence, oldPresence));
        if (newPresence > EUndergroundPresence.NONE)
        {
            if (oldPresence == EUndergroundPresence.NONE)
            {
                EnableLights(true);
            }
            if (newPresence > EUndergroundPresence.OUTER && oldPresence <= EUndergroundPresence.OUTER)
            {
                GetGame().GetWeather().SuppressLightningSimulation(true);
                m_Player.PlaySoundSetLoop(m_AmbientSound, "Underground_SoundSet",3,3);
            }
            if (newPresence == EUndergroundPresence.FULL)
            {
                m_AnimTimerLightBlend = new AnimationTimer();
                m_AnimTimerLightBlend.Run(1, this, "OnUpdateTimerIn", "OnUpdateTimerEnd",0, false, LIGHT_BLEND_SPEED_IN);
            }
        }
        if (newPresence < EUndergroundPresence.FULL && oldPresence == EUndergroundPresence.FULL)
        {
            m_AnimTimerLightBlend = new AnimationTimer();
            m_AnimTimerLightBlend.Run(0, this, "OnUpdateTimerOut", "OnUpdateTimerEnd",m_LightingLerp, false, LIGHT_BLEND_SPEED_OUT);
        }
        if (newPresence <= EUndergroundPresence.OUTER && oldPresence > EUndergroundPresence.OUTER)
        {
            GetGame().GetWeather().SuppressLightningSimulation(false);
            if (m_AmbientSound)
                m_Player.StopSoundSet(m_AmbientSound);
        }
        if (newPresence == EUndergroundPresence.NONE && oldPresence >= EUndergroundPresence.OUTER)
        {
            GetGame().GetWorld().SetUserLightingLerp(0);
            EnableLights(false);
        }
    }
References EnableLights(), GetGame(), CGame::GetWeather(), CGame::GetWorld(), LIGHT_BLEND_SPEED_IN, LIGHT_BLEND_SPEED_OUT, m_AmbientSound, m_AnimTimerLightBlend, m_LightingLerp, m_Player, AnimationTimer::Run(), World::SetUserLightingLerp(), and Weather::SuppressLightningSimulation().
Referenced by SetUndergroundPresence().
OnUpdateTimerEnd()
void OnUpdateTimerEnd ()
OnUpdateTimerIn()
void OnUpdateTimerIn ()
Definition at line 352 of file undergroundhandlerclient.c.
    {
        if (!m_AnimTimerLightBlend)
            return;
        float value01 = m_AnimTimerLightBlend.GetValue();
        float result = Easing.EaseInQuint(value01);
        m_LightingLerp = result;
    }
References Easing::EaseInQuint(), AnimationTimer::GetValue(), m_AnimTimerLightBlend, and m_LightingLerp.
OnUpdateTimerOut()
void OnUpdateTimerOut ()
Definition at line 362 of file undergroundhandlerclient.c.
    {
        if (!m_AnimTimerLightBlend)
            return;
        float value01 = m_AnimTimerLightBlend.GetValue();
        float result = Easing.EaseOutCubic(value01);
        m_LightingLerp = result;
    }
References Easing::EaseOutCubic(), AnimationTimer::GetValue(), m_AnimTimerLightBlend, and m_LightingLerp.
ProcessEyeAcco()
private void ProcessEyeAcco (float timeSlice)
Definition at line 175 of file undergroundhandlerclient.c.
    {
        CalculateEyeAccoTarget();
        bool reachedTarget = CalculateEyeAcco(timeSlice);
        ApplyEyeAcco();
        if(reachedTarget && !m_Player.m_UndergroundPresence)
        {
            GetRequester().Stop();
            m_NVRequester.SetUndergroundExposureCoef(1.0);
            m_Player.KillUndergroundHandler();
        }
    }
References ApplyEyeAcco(), CalculateEyeAcco(), CalculateEyeAccoTarget(), GetRequester(), m_NVRequester, and m_Player.
Referenced by Tick().
ProcessLighting()
private void ProcessLighting (float timeSlice)
Definition at line 189 of file undergroundhandlerclient.c.
    {
        #ifdef DEVELOPER
        if (!DiagMenu.GetBool(DiagMenuIDs.DM_UNDERGROUND_DISABLE_DARKENING) )
        {
            GetGame().GetWorld().SetUserLightingLerp(m_LightingLerp);
        }
        else
        {
            GetGame().GetWorld().SetUserLightingLerp(0);
        }
        #else
        GetGame().GetWorld().SetUserLightingLerp(m_LightingLerp);
        #endif
    }
References DiagMenu::GetBool(), GetGame(), CGame::GetWorld(), m_LightingLerp, and World::SetUserLightingLerp().
Referenced by Tick().
ProcessSound()
private void ProcessSound (float timeSlice)
Definition at line 205 of file undergroundhandlerclient.c.
    {
        GetGame().GetWorld().SetExplicitVolumeFactor_EnvSounds2D(m_EyeAcco, 0);
        if (m_AmbientSound)
        {
            m_AmbientSound.SetSoundVolume(1-m_EyeAcco);
            //Print(m_AmbientSound.GetSoundVolume());
        }
    }
References GetGame(), CGame::GetWorld(), m_AmbientSound, m_EyeAcco, World::SetExplicitVolumeFactor_EnvSounds2D(), and EffectSound::SetSoundVolume().
SetUndergroundPresence()
private void SetUndergroundPresence (UndergroundTrigger trigger)
Definition at line 312 of file undergroundhandlerclient.c.
    {
        EUndergroundPresence newPresence = EUndergroundPresence.NONE;
        EUndergroundPresence oldPresence = m_Player.m_UndergroundPresence;
        if (trigger)
        {
            if (trigger.m_Type == EUndergroundTriggerType.OUTER)
            {
                newPresence = EUndergroundPresence.OUTER;
            }
            else if (trigger.m_Type == EUndergroundTriggerType.TRANSITIONING)
            {
                newPresence = EUndergroundPresence.TRANSITIONING;
            }
            else if (trigger.m_Type == EUndergroundTriggerType.INNER)
            {
                newPresence = EUndergroundPresence.FULL;
            }
        }
        if (newPresence != oldPresence)//was there a change ?
        {
            OnUndergroundPresenceUpdate(newPresence,oldPresence);
            m_Player.SetUnderground(newPresence);
        }
    }
References m_Player, and OnUndergroundPresenceUpdate().
Referenced by OnTriggerInsiderUpdate().
Tick()
void Tick (float timeSlice)
Definition at line 215 of file undergroundhandlerclient.c.
    {
        if (!m_Player.IsAlive())
            return;
        ProcessEyeAcco(timeSlice);
        ProcessLighting(timeSlice);
        ProcessSound(timeSlice);
        #ifdef DEVELOPER
        if ( DiagMenu.GetBool(DiagMenuIDs.DM_UNDERGROUND_SHOW_BREADCRUMB) )
        {
            DisplayDebugInfo(GetGame().GetWorld().GetEyeAccom(), m_LightingLerp);
        }
        #endif
    }
References DiagMenu::GetBool(), GetGame(), m_LightingLerp, m_Player, ProcessEyeAcco(), ProcessLighting(), and ProcessSound().
UndergroundHandlerClient()
void UndergroundHandlerClient (PlayerBase player)
Definition at line 35 of file undergroundhandlerclient.c.
    {
        GetGame().GetWorld().LoadUserLightingCfg(UNDERGROUND_LIGHTING, "Underground");
        m_Player = player;
        m_NVRequester = PPERequester_CameraNV.Cast(PPERequesterBank.GetRequester( PPERequesterBank.REQ_CAMERANV));
    }
References GetGame(), CGame::GetWorld(), World::LoadUserLightingCfg(), m_NVRequester, m_Player, and UNDERGROUND_LIGHTING.
Referenced by ManBase::GetUndergroundHandler(), OnEnterClientEvent(), and OnLeaveClientEvent().
~UndergroundHandlerClient()
void ~UndergroundHandlerClient ()
Definition at line 42 of file undergroundhandlerclient.c.
    {
        if (GetGame())
        {
            GetGame().GetWorld().SetExplicitVolumeFactor_EnvSounds2D(1, 0.5);
            GetGame().GetWeather().SuppressLightningSimulation(false);
            GetGame().GetWorld().SetUserLightingLerp(0);
            if (m_AmbientSound)
                m_AmbientSound.Stop();
        }
    }
References GetGame(), CGame::GetWeather(), CGame::GetWorld(), m_AmbientSound, World::SetExplicitVolumeFactor_EnvSounds2D(), World::SetUserLightingLerp(), EffectSound::Stop(), and Weather::SuppressLightningSimulation().
Variable Documentation
ACCO_MODIFIER
const float ACCO_MODIFIER = 1
Definition at line 16 of file undergroundhandlerclient.c.
Referenced by CalculateEyeAccoTarget().
DEFAULT_INTERPOLATION_SPEED
const float DEFAULT_INTERPOLATION_SPEED = 7
Definition at line 17 of file undergroundhandlerclient.c.
Referenced by OnTriggerInsiderUpdate().
DISTANCE_CUTOFF
const float DISTANCE_CUTOFF = 5
Definition at line 15 of file undergroundhandlerclient.c.
Referenced by CalculateEyeAccoTarget().
LIGHT_BLEND_SPEED_IN
enum EUndergroundPresence LIGHT_BLEND_SPEED_IN = 5
Referenced by OnUndergroundPresenceUpdate().
LIGHT_BLEND_SPEED_OUT
const float LIGHT_BLEND_SPEED_OUT = 1.75
Definition at line 12 of file undergroundhandlerclient.c.
Referenced by OnUndergroundPresenceUpdate().
m_AccoInterpolationSpeed
private float m_AccoInterpolationSpeed
Definition at line 27 of file undergroundhandlerclient.c.
Referenced by CalculateEyeAcco(), and OnTriggerInsiderUpdate().
m_AmbientSound
private EffectSound m_AmbientSound
Definition at line 31 of file undergroundhandlerclient.c.
Referenced by OnUndergroundPresenceUpdate(), ProcessSound(), and ~UndergroundHandlerClient().
m_AnimTimerLightBlend
private ref AnimationTimer m_AnimTimerLightBlend
Definition at line 19 of file undergroundhandlerclient.c.
Referenced by OnUndergroundPresenceUpdate(), OnUpdateTimerIn(), and OnUpdateTimerOut().
m_EyeAcco
private float m_EyeAcco = 1
Definition at line 28 of file undergroundhandlerclient.c.
Referenced by ApplyEyeAcco(), CalculateEyeAcco(), and ProcessSound().
m_EyeAccoTarget
private float m_EyeAccoTarget = 1
Definition at line 26 of file undergroundhandlerclient.c.
Referenced by CalculateEyeAcco(), CalculateEyeAccoTarget(), and OnTriggerInsiderUpdate().
m_InsideTriggers
private ref set<UndergroundTrigger> m_InsideTriggers = new set<UndergroundTrigger>()
Definition at line 24 of file undergroundhandlerclient.c.
Referenced by OnTriggerEnter(), OnTriggerInsiderUpdate(), and OnTriggerLeave().
m_LightingLerp
private float m_LightingLerp
Definition at line 30 of file undergroundhandlerclient.c.
Referenced by ApplyEyeAcco(), OnUndergroundPresenceUpdate(), OnUpdateTimerIn(), OnUpdateTimerOut(), ProcessLighting(), and Tick().
m_LightingLerpTarget
private float m_LightingLerpTarget
Definition at line 29 of file undergroundhandlerclient.c.
m_NVRequester
private PPERequester_CameraNV m_NVRequester
Definition at line 23 of file undergroundhandlerclient.c.
Referenced by ApplyEyeAcco(), ProcessEyeAcco(), and UndergroundHandlerClient().
m_Player
private PlayerBase m_Player
Definition at line 21 of file undergroundhandlerclient.c.
m_Requester
private PPERUndergroundAcco m_Requester
Definition at line 22 of file undergroundhandlerclient.c.
Referenced by GetRequester(), SymptomBase::OnGetDeactivatedClient(), SymptomBase::OnInit(), and SymptomBase::OnUpdateClient().
m_TransitionalTrigger
private UndergroundTrigger m_TransitionalTrigger
Definition at line 33 of file undergroundhandlerclient.c.
Referenced by CalculateEyeAcco(), CalculateEyeAccoTarget(), and OnTriggerInsiderUpdate().
MAX_RATIO
const float MAX_RATIO = 0.9
Definition at line 13 of file undergroundhandlerclient.c.
Referenced by CalculateEyeAccoTarget().
RATIO_CUTOFF
const float RATIO_CUTOFF = 0
Definition at line 14 of file undergroundhandlerclient.c.
Referenced by CalculateEyeAccoTarget().
UNDERGROUND_LIGHTING
const string UNDERGROUND_LIGHTING = "dz\\data\\lighting\\lighting_underground.txt"
Definition at line 18 of file undergroundhandlerclient.c.
Referenced by UndergroundHandlerClient().