DayzKode: P:/scripts/4_world/DayZ/entities/scriptedentities/triggers/undergroundtrigger.c File Reference
undergroundtrigger.c File Reference
Classes
class UndergroundTriggerCarrierBase
Functions
override protected bool CanAddObjectAsInsider (Object object)
override void EOnInit (IEntity other, int extra)
void Init (JsonUndergroundAreaTriggerData data)
override protected void OnEnterClientEvent (TriggerInsider insider)
override protected void OnLeaveClientEvent (TriggerInsider insider)
Variables
float m_Accommodation
class UndergroundTriggerCarrier extends UndergroundTriggerCarrierBase m_Data
float m_InterpolationSpeed
EUndergroundTriggerType m_Type
class UndergroundTriggerCarrier extends UndergroundTriggerCarrierBase OUTER
class UndergroundTriggerCarrier extends UndergroundTriggerCarrierBase TRANSITIONING
class UndergroundTriggerCarrier extends UndergroundTriggerCarrierBase UNDEFINED
Function Documentation
CanAddObjectAsInsider()
override protected bool CanAddObjectAsInsider (Object object)
Definition at line 120 of file undergroundtrigger.c.
    {
        if (!super.CanAddObjectAsInsider(object))
        {
            return false;
        }
        PlayerBase player = PlayerBase.Cast(object);
        return player.IsControlledPlayer();
    }
EOnInit()
override void EOnInit (IEntity other, int extra)
Definition at line 132 of file undergroundtrigger.c.
    {
        //disable parent behaviour
    }
Init()
void Init (JsonUndergroundAreaTriggerData data)
Definition at line 89 of file undergroundtrigger.c.
    {
        m_Data = data;
        //Print("Spawning trigger " + this + "at pos: " + GetPosition());
        vector extMax = data.GetSize() * 0.5;
        vector extMin = -extMax;
        SetExtents(extMin, extMax);
        m_Accommodation = data.EyeAccommodation;
        m_InterpolationSpeed = data.InterpolationSpeed;
        if (data.Breadcrumbs && data.Breadcrumbs.Count() > 0) //TODO: simpler check
        {
            if (data.Breadcrumbs.Count() > 32)
            {
                ErrorEx("max 'Breadcrumb' count is 32, found: " + data.Breadcrumbs.Count());
            }
            m_Type = EUndergroundTriggerType.TRANSITIONING;
        }
        else
        {
            if (m_Accommodation == 1)
            {
                m_Type = EUndergroundTriggerType.OUTER;
            }
            else
            {
                m_Type = EUndergroundTriggerType.INNER;
            }
        }
    }
References JsonUndergroundAreaTriggerData::Breadcrumbs, ErrorEx, JsonUndergroundAreaTriggerData::EyeAccommodation, JsonUndergroundAreaTriggerData::GetSize(), JsonUndergroundAreaTriggerData::InterpolationSpeed, m_Accommodation, m_Data, m_InterpolationSpeed, m_Type, and Trigger::SetExtents().
OnEnterClientEvent()
override protected void OnEnterClientEvent (TriggerInsider insider)
Definition at line 136 of file undergroundtrigger.c.
    {
        //Print("OnEnterClientEvent " + this);
        //return;
        PlayerBase player = PlayerBase.Cast(insider.GetObject());
        if (player)
        {
            UndergroundHandlerClient handler = player.GetUndergroundHandler();
            if (handler)
            {
                handler.OnTriggerEnter(this);
            }
        }
    }
References TriggerInsider::GetObject(), and UndergroundHandlerClient().
OnLeaveClientEvent()
override protected void OnLeaveClientEvent (TriggerInsider insider)
Definition at line 151 of file undergroundtrigger.c.
    {
        //Print("OnLeaveClientEvent " + this);
        //return;
        PlayerBase player = PlayerBase.Cast(insider.GetObject());
        if (player)
        {
            UndergroundHandlerClient handler = player.GetUndergroundHandler();
            if (handler)
            {
                handler.OnTriggerLeave(this);
            }
        }
    }
References TriggerInsider::GetObject(), and UndergroundHandlerClient().
Variable Documentation
m_Accommodation
float m_Accommodation
Definition at line 86 of file undergroundtrigger.c.
Referenced by Init().
m_Data
class UndergroundTriggerCarrier extends UndergroundTriggerCarrierBase m_Data
m_InterpolationSpeed
float m_InterpolationSpeed
Definition at line 87 of file undergroundtrigger.c.
Referenced by Init().
m_Type
EUndergroundTriggerType m_Type
Definition at line 85 of file undergroundtrigger.c.
OUTER
class UndergroundTriggerCarrier extends UndergroundTriggerCarrierBase OUTER
TRANSITIONING
class UndergroundTriggerCarrier extends UndergroundTriggerCarrierBase TRANSITIONING
UNDEFINED
class UndergroundTriggerCarrier extends UndergroundTriggerCarrierBase UNDEFINED