DayzKode: P:/scripts/3_game/DayZ/vonmanager.c File Reference
vonmanager.c File Reference
Classes
class VONManager
Manager class which handles Voice-over-network functionality while player is connected to a server.
class VONManagerBase
Functions
void HandleInput (Input inp)
Handles some VON related input.
void HideVoiceNotification ()
Hides the VON notification completely and immediately.
bool IsVonToggled ()
void OnEvent (EventType eventTypeId, Param params)
Handles VON-related events.
void OnVOIPThresholdChanged ()
Fires every time VOIP threshold value changes.
void ShowVoiceNotification (int level, bool fading)
Shows the voice notification.
void VONManagerBase ()
VONManagerBase Managed VONManagerImplementation ()
void ~VONManagerImplementation ()
Variables
ref ScriptInvoker m_OnPartyChatChangedEvent
ref ScriptInvoker m_OnVonStateEvent
protected bool m_VoNToggled
Function Documentation
HandleInput()
override void HandleInput (Input inp)
Handles some VON related input.
Parameters
inp input to handle
Definition at line 113 of file vonmanager.c.
    {
#ifdef PLATFORM_XBOX
        // ignore VON-related input if user is in an xbox party
        if (GetGame().IsInPartyChat())
        {
            return;
        }
#endif
        int oldLevel = GetGame().GetVoiceLevel();
        int newLevel = -1;
        if (inp.LocalPress("UAVoiceDistanceUp",false))
        {
            newLevel = ( oldLevel + 1 ) % ( VoiceLevelShout + 1 );
        }
        if (inp.LocalPress("UAVoiceDistanceDown",false))
        {
            newLevel = oldLevel - 1;
            if (newLevel < VoiceLevelWhisper) //nah...
            {
                newLevel = VoiceLevelShout;
            }
        }
        if (newLevel != -1)
        {
            if (m_VoNToggled)
            {
                if (VONManager.IsVoiceThresholdMinimum())
                {
                    ShowVoiceNotification(newLevel, false);
                }
                else
                {
                    ShowVoiceNotification(newLevel, true);
                }
            }
            else
            {
                ShowVoiceNotification(newLevel, !GetGame().GetMission().IsVoNActive());
            }
            // update general voice icon
            GetGame().SetVoiceLevel(newLevel);
        }
    }
References GetGame(), CGame::GetVoiceLevel(), VONManager::IsVoiceThresholdMinimum(), Input::LocalPress(), m_VoNToggled, CGame::SetVoiceLevel(), and VONManagerBase::ShowVoiceNotification().
HideVoiceNotification()
override void HideVoiceNotification ()
Hides the VON notification completely and immediately.
Definition at line 41 of file vonmanager.c.
    {
        if (GetGame().IsMissionMainMenu())
        {
            return;
        }
        Mission mission = GetGame().GetMission();
        mission.GetMicrophoneIcon().Show(false);
        mission.HideVoiceLevelWidgets();
    }
IsVonToggled()
bool VONManagerImplementation::IsVonToggled ()
Definition at line 42 of file vonmanager.c.
    {
        if (GetGame().IsMissionMainMenu())
        {
            return;
References GetGame(), Mission::GetMicrophoneIcon(), CGame::GetMission(), Mission::HideVoiceLevelWidgets(), and mission.
OnEvent()
void VONManagerImplementation::OnEvent (EventType eventTypeId, Param params)
Handles VON-related events.
Parameters
eventTypeId event that fired
params event-specific parameters
Definition at line 188 of file vonmanager.c.
    {
        Mission mission = GetGame().GetMission();
        switch (eventTypeId)
        {
            case VONUserStartedTransmittingAudioEventTypeID:
            {
                // only handle this if we are in Voice Activation mode, so ignore if in PTT mode
                if (m_VoNToggled)
                {
                    if (!VONManager.IsVoiceThresholdMinimum())
                    {
                        ShowVoiceNotification(GetGame().GetVoiceLevel(), false);
                    }
                }
                break;
            }
            case VONUserStoppedTransmittingAudioEventTypeID:
            {
                // only handle this if we are in Voice Activation mode, so ignore if in PTT mode
                if (m_VoNToggled)
                {
                    if (!VONManager.IsVoiceThresholdMinimum())
                    {
                        HideVoiceNotification();
                    }
                }
                break;
            }
            case VONStateEventTypeID:
            {
                if (!mission)
                {
                    break;
                }
                VONStateEventParams vonStateParams = VONStateEventParams.Cast( params );
                mission.SetVoNActive(vonStateParams.param1);
                m_VoNToggled = vonStateParams.param2;
                int rangeLevel = GetGame().GetVoiceLevel();
                if (mission.IsVoNActive())
                {
                    if (m_VoNToggled)
                    {
                        if (VONManager.IsVoiceThresholdMinimum())
{
                            ShowVoiceNotification(rangeLevel, false);
                        }
                        else
{
                            ShowVoiceNotification(rangeLevel, true);
                        }
                    }
                    else
                    {
                        ShowVoiceNotification(rangeLevel, false);
                    }
                }
                else
                {
                    HideVoiceNotification();
                }
                m_OnVonStateEvent.Invoke();
                break;
            }
            case PartyChatStatusChangedEventTypeID:
            {
                m_OnPartyChatChangedEvent.Invoke();
                break;
            }
            case VONStartSpeakingEventTypeID:
            {
                VONStartSpeakingEventParams vonStartParams;
                if (Class.CastTo(vonStartParams, params))
                {
                    GetDayZGame().AddVoiceNotification(vonStartParams);
                }
                break;
            }
            case VONStopSpeakingEventTypeID:
            {
                VONStopSpeakingEventParams vonStopParams;
                if (Class.CastTo(vonStopParams, params))
                {
                    GetDayZGame().RemoveVoiceNotification(vonStopParams);
                }
                break;
            }
            case MPSessionPlayerReadyEventTypeID:
            {
                if (m_VoNToggled)
                {
                    if (VONManager.IsVoiceThresholdMinimum())
                    {
                        ShowVoiceNotification(GetGame().GetVoiceLevel(), false);
                    }
                }
                break;
            }
        }
    }
References Class::CastTo(), GetDayZGame(), GetGame(), CGame::GetMission(), CGame::GetVoiceLevel(), VONManagerBase::HideVoiceNotification(), ScriptInvoker::Invoke(), VONManager::IsVoiceThresholdMinimum(), Mission::IsVoNActive(), m_OnPartyChatChangedEvent, m_OnVonStateEvent, m_VoNToggled, mission, Mission::SetVoNActive(), and VONManagerBase::ShowVoiceNotification().
OnVOIPThresholdChanged()
override void OnVOIPThresholdChanged ()
Fires every time VOIP threshold value changes.
Definition at line 165 of file vonmanager.c.
    {
        Mission mission = GetGame().GetMission();
        // voice activation mode
        if (m_VoNToggled)
        {
            if (VONManager.IsVoiceThresholdMinimum())
            {
                ShowVoiceNotification(GetGame().GetVoiceLevel(), false);
            }
            else
            {
                HideVoiceNotification();
            }
        }
    }
References GetGame(), CGame::GetMission(), VONManagerBase::HideVoiceNotification(), VONManager::IsVoiceThresholdMinimum(), m_VoNToggled, mission, and VONManagerBase::ShowVoiceNotification().
ShowVoiceNotification()
override void ShowVoiceNotification (int level, bool fading)
Shows the voice notification.
Parameters
level the loudness of the player voice. 0 = whisper, 1 = normal, 2 = shout
fading specifies whether icon should slowly fade to invisibility after being displayed
Definition at line 58 of file vonmanager.c.
    {
        if (GetGame().IsMissionMainMenu())
        {
            return;
        }
        Mission mission = GetGame().GetMission();
        ImageWidget micIcon = mission.GetMicrophoneIcon();
        WidgetFadeTimer micTimer = mission.GetMicWidgetFadeTimer();
        map<int,ImageWidget> voiceLeveWidgets = mission.GetVoiceLevelWidgets();
        map<int,ref WidgetFadeTimer> voiceLevelTimers = mission.GetVoiceLevelTimers();
        // microphone icon
        micTimer.Stop();
        micIcon.SetAlpha(1.0);
        micIcon.Show(true);
        if (fading)
        {
            micTimer.FadeOut(micIcon, 3.0);
        }
        // range icons
        for( int n = 0; n < voiceLeveWidgets.Count(); n++ )
        {
            int voiceKey = voiceLeveWidgets.GetKey(n);
            ImageWidget voiceWidget = voiceLeveWidgets.Get(n);
            // stop fade timer since it will be refreshed
            WidgetFadeTimer timer = voiceLevelTimers.Get(n);
            timer.Stop();
            // show widgets according to the level
            if ( voiceKey <= level )
            {
                voiceWidget.SetAlpha(1.0); // reset from possible previous fade out
                voiceWidget.Show(true);
                if (fading)
                {
                    timer.FadeOut(voiceWidget, 3.0);
                }
            }
            else
            {
                voiceWidget.Show(false);
            }
        }
    }
References GetGame(), Mission::GetMicrophoneIcon(), Mission::GetMicWidgetFadeTimer(), CGame::GetMission(), Mission::GetVoiceLevelTimers(), Mission::GetVoiceLevelWidgets(), and mission.
VONManagerBase()
void VONManagerImplementation::VONManagerBase ()
Definition at line 31 of file vonmanager.c.
    {
        m_OnVonStateEvent.Clear();
VONManagerImplementation()
VONManagerBase Managed VONManagerImplementation ()
Definition at line 1 of file vonmanager.c.
    {
        m_OnVonStateEvent = new ScriptInvoker();
        m_OnPartyChatChangedEvent = new ScriptInvoker();
    }
Referenced by VONManager::Init().
~VONManagerImplementation()
void ~VONManagerImplementation ()
Definition at line 32 of file vonmanager.c.
    {
        m_OnVonStateEvent.Clear();
        m_OnPartyChatChangedEvent.Clear();
    }
References ScriptInvoker::Clear(), m_OnPartyChatChangedEvent, and m_OnVonStateEvent.
Variable Documentation
m_OnPartyChatChangedEvent
ref ScriptInvoker m_OnPartyChatChangedEvent
Definition at line 29 of file vonmanager.c.
Referenced by OnEvent(), and ~VONManagerImplementation().
m_OnVonStateEvent
ref ScriptInvoker m_OnVonStateEvent
Definition at line 28 of file vonmanager.c.
Referenced by OnEvent(), and ~VONManagerImplementation().
m_VoNToggled
protected bool m_VoNToggled
Definition at line 27 of file vonmanager.c.
Referenced by HandleInput(), OnEvent(), and OnVOIPThresholdChanged().