DayzKode: P:/scripts/4_world/DayZ/entities/woodbase.c File Reference
woodbase.c File Reference
Enumerations
enum EHarvestType { NORMAL , BARK }
Functions
int GetAmountOfDrops (ItemBase item)
int GetAmountOfDropsEx (ItemBase item, EHarvestType type)
string GetBarkType ()
float GetCycleTimeOverride ()
float GetDamageToMiningItemEachDrop (ItemBase item)
float GetDamageToMiningItemEachDropEx (ItemBase item, EHarvestType type)
void GetMaterialAndQuantityMap (ItemBase item, out map< string, int > output_map)
void GetMaterialAndQuantityMapEx (ItemBase item, out map< string, int > output_map, EHarvestType type)
int GetPrimaryDropsAmount ()
string GetPrimaryOutput ()
int GetSecondaryDropsAmount ()
string GetSecondaryOutput ()
float GetToolDamage ()
void InitMiningValues ()
override bool IsCuttable ()
override bool IsWoodBase ()
void WoodBase ()
Variables
static string m_BarkType = ""
static float m_CycleTimeOverride = -1.0
enum EHarvestType m_IsCuttable
static int m_PrimaryDropsAmount = -1
static string m_PrimaryOutput = ""
static int m_SecondaryDropsAmount = -1
static string m_SecondaryOutput = ""
static float m_ToolDamage = -1.0
Enumeration Type Documentation
EHarvestType
enum EHarvestType
Enumerator
NORMAL
BARK
Definition at line 1 of file woodbase.c.
{
    NORMAL,
    BARK
}
Function Documentation
GetAmountOfDrops()
int GetAmountOfDrops (ItemBase item)
Definition at line 88 of file woodbase.c.
    {
        if ( GetPrimaryDropsAmount() > 0 )
        {
            if ( IsTree() && item && ( item.KindOf("Knife") || item.IsInherited(Screwdriver) ) )
            {
                return -1;
            }
            else
            {
                return GetPrimaryDropsAmount();
            }
        }
        else
        {
            if ( item && ( item.KindOf("Knife") || item.IsInherited(Screwdriver) ) )
            {
                return -1;
            }
            else if ( item && item.KindOf("Axe") )
            {
                return 3;
            }
            else
            {
                return 100;
            }
        }
    }
References GetPrimaryDropsAmount(), and IsTree().
GetAmountOfDropsEx()
int GetAmountOfDropsEx (ItemBase item, EHarvestType type)
Definition at line 118 of file woodbase.c.
    {
        if ( GetPrimaryDropsAmount() > 0 )
        {
            if ( IsTree() && item && type == EHarvestType.BARK )
            {
                return -1;
            }
            else
            {
                return GetPrimaryDropsAmount();
            }
        }
        else
        {
            if ( item && type == EHarvestType.BARK )
            {
                return -1;
            }
            else if ( item &&  type == EHarvestType.NORMAL )
            {
                return 3;
            }
            else
            {
                return 100;
            }
        }
    }
References GetPrimaryDropsAmount(), and IsTree().
GetBarkType()
string GetBarkType ()
Definition at line 81 of file woodbase.c.
    {
        return ConfigGetString("barkType");
    }
References ConfigGetString().
Referenced by GetMaterialAndQuantityMap(), and GetMaterialAndQuantityMapEx().
GetCycleTimeOverride()
float GetCycleTimeOverride ()
Definition at line 66 of file woodbase.c.
    {
        return ConfigGetFloat("cycleTimeOverride");
    }
References ConfigGetFloat().
GetDamageToMiningItemEachDrop()
float GetDamageToMiningItemEachDrop (ItemBase item)
Definition at line 172 of file woodbase.c.
    {
        if (GetToolDamage() > -1)
            return GetToolDamage();
        if ( IsTree() )
        {
            if ( item && item.KindOf("Knife") )
            {
                return 20;
            }
            else if ( item && item.KindOf("Axe") )
            {
                return 20;
            }
            else
            {
                return 0;
            }
        }
        else
        {
            if ( item && item.KindOf("Knife") )
            {
                return 30;
            }
            else if ( item && item.KindOf("Axe") )
            {
                return 30;
            }
            else
            {
                return 0;
            }
        }
    }
References GetToolDamage(), and IsTree().
GetDamageToMiningItemEachDropEx()
float GetDamageToMiningItemEachDropEx (ItemBase item, EHarvestType type)
Definition at line 209 of file woodbase.c.
    {
        if (GetToolDamage() > -1)
            return GetToolDamage();
        if ( IsTree() )
        {
            if ( item && type == EHarvestType.BARK )
            {
                return 20;
            }
            else if ( item && type == EHarvestType.NORMAL )
            {
                return 20;
            }
            else
            {
                return 0;
            }
        }
        else
        {
            if ( item && type == EHarvestType.BARK )
            {
                return 30;
            }
            else if ( item && type == EHarvestType.NORMAL )
            {
                return 30;
            }
            else
            {
                return 0;
            }
        }
    }
References GetToolDamage(), and IsTree().
GetMaterialAndQuantityMap()
void GetMaterialAndQuantityMap (ItemBase item, out map< string, int > output_map)
Definition at line 148 of file woodbase.c.
    {
        if ( IsTree() && item && ( item.KindOf("Knife") || item.IsInherited(Screwdriver) ) && GetBarkType() != "" )
        {
            output_map.Insert(GetBarkType(),1);
        }
        else
        {
            output_map.Insert(GetPrimaryOutput(),1);
        }
    }
References GetBarkType(), GetPrimaryOutput(), and IsTree().
GetMaterialAndQuantityMapEx()
void GetMaterialAndQuantityMapEx (ItemBase item, out map< string, int > output_map, EHarvestType type)
Definition at line 160 of file woodbase.c.
    {
        if ( IsTree() && item && type == EHarvestType.BARK && GetBarkType() != "" )
        {
            output_map.Insert(GetBarkType(),1);
        }
        else
        {
            output_map.Insert(GetPrimaryOutput(),1);
        }
    }
References GetBarkType(), GetPrimaryOutput(), and IsTree().
GetPrimaryDropsAmount()
int GetPrimaryDropsAmount ()
Definition at line 51 of file woodbase.c.
    {
        return ConfigGetInt("primaryDropsAmount");
    }
References ConfigGetInt().
Referenced by GetAmountOfDrops(), and GetAmountOfDropsEx().
GetPrimaryOutput()
string GetPrimaryOutput ()
Definition at line 71 of file woodbase.c.
    {
        return ConfigGetString("primaryOutput");
    }
References ConfigGetString().
Referenced by GetMaterialAndQuantityMap(), and GetMaterialAndQuantityMapEx().
GetSecondaryDropsAmount()
int GetSecondaryDropsAmount ()
Definition at line 56 of file woodbase.c.
    {
        return ConfigGetInt("secondaryDropsAmount");
    }
References ConfigGetInt().
GetSecondaryOutput()
string GetSecondaryOutput ()
Definition at line 76 of file woodbase.c.
    {
        return ConfigGetString("secondaryOutput");
    }
References ConfigGetString().
GetToolDamage()
float GetToolDamage ()
Definition at line 61 of file woodbase.c.
    {
        return ConfigGetFloat("toolDamage");
    }
References ConfigGetFloat().
Referenced by GetDamageToMiningItemEachDrop(), and GetDamageToMiningItemEachDropEx().
InitMiningValues()
void InitMiningValues ()
Definition at line 36 of file woodbase.c.
    {
        //m_IsCuttable = false;
    };
IsCuttable()
override bool IsCuttable ()
Definition at line 46 of file woodbase.c.
    {
        return ConfigGetBool("isCuttable");
    }
References ConfigGetBool().
IsWoodBase()
override bool IsWoodBase ()
Definition at line 41 of file woodbase.c.
    {
        return true;
    }
WoodBase()
void WoodBase ()
Definition at line 30 of file woodbase.c.
    {
        //InitMiningValues();
    }
Referenced by CAContinuousMineWood::Execute(), CAContinuousMineWood::GetMiningData(), and ActionMineBase::GetYieldName().
Variable Documentation
m_BarkType
string m_BarkType = "" static
Definition at line 17 of file woodbase.c.
m_CycleTimeOverride
float m_CycleTimeOverride = -1.0 static
Definition at line 14 of file woodbase.c.
m_IsCuttable
enum EHarvestType m_IsCuttable
m_PrimaryDropsAmount
int m_PrimaryDropsAmount = -1 static
Definition at line 11 of file woodbase.c.
m_PrimaryOutput
string m_PrimaryOutput = "" static
Definition at line 15 of file woodbase.c.
m_SecondaryDropsAmount
int m_SecondaryDropsAmount = -1 static
Definition at line 12 of file woodbase.c.
m_SecondaryOutput
string m_SecondaryOutput = "" static
Definition at line 16 of file woodbase.c.
m_ToolDamage
float m_ToolDamage = -1.0 static
Definition at line 13 of file woodbase.c.